### ISSUE TITLE
EpollEventLoop fails to initialize

### ISSUE THREAD

**Issue by blucas** [netty/netty#4840] opened 2016-02-04 20:30 UTC
Netty Version: 4.1 latest snapshot

I get the following exception when attempting to use Epoll.  None of my code has changed, I just grabbed the latest snapshot jars.  Could it have anything to do with 075a54af3e607c20eeaf7809a2a08602abd5d735 ??? I have not shaded my app or anything.
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.IovArray
        at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:57)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:78)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:30)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:77)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:48)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:57)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:63)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:51)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:43)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:36)
```

**Comment by blucas** [comment] 2016-02-04 20:31
@Scottmitch @normanmaurer - Any ideas guys? this is kinda worrying me, especially considering Norman tagged CR2

**Comment by blucas** [comment] 2016-02-04 20:48
On a related note, I get the following exception when attempting to start and SSL service:

```
java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSLContext.getMode(J)I
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:202)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:134)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:420)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:408)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:315)
```

**Comment by normanmaurer** [comment] 2016-02-04 21:04
@blucas the second is because you need to use netty-tcnative-1.1.33.Fork12. The other maybe @Scottmitch has an idea ?

**Comment by normanmaurer** [comment] 2016-02-05 08:30
@blucas is the same happen with CR2 ? (non snapshot)

**Comment by blucas** [comment] 2016-02-05 09:23
Same thing happens.  I just noticed another stack trace higher up that might give us a better clue:

```
Caused by: java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by /tmp/libnetty-transport-native-epoll1356421042500119665.so
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:60)
        at io.netty.channel.epoll.IovArray.<clinit>(IovArray.java:57)
        at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:57)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:78)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:30)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:77)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:48)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:57)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:63)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:51)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:43)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:36)
```

This makes me think it definitely has something to do with @Scottmitch's changes to support shading. FYI, I'm using Java 7 runtime, I don't know if that makes a difference for JNI support

**Comment by blucas** [comment] 2016-02-05 12:15
*Update:* If I revert 075a54af3e607c20eeaf7809a2a08602abd5d735 the issue is no longer present and everything works as expected

**Comment by Scottmitch** [comment] 2016-02-05 16:35
@blucas - Sorry for the snag ... let me dig in here

**Comment by blucas** [comment] 2016-02-05 17:36
@Scottmitch - sent you an email (via your gmail account) with some more info

**Comment by Scottmitch** [comment] 2016-02-05 19:19
@blucas - I was able to reproduce locally stay tuned for a PR.

**Comment by normanmaurer** [comment] 2016-02-06 18:44
Fixed by https://github.com/netty/netty/pull/4851

**Closed by normanmaurer** 2016-02-06 18:44 UTC
Labels: defect
