### ISSUE TITLE
Query parameter name is encoded while it shouldn't be

### ISSUE THREAD

**Issue by manish-panwar** [netty/netty#8151] opened 2018-07-25 16:18 UTC
### Expected behavior

Query parameter name shouldn't be encoded.

### Actual behavior

Query parameter name is encoded.

### Steps to reproduce

If we go to following code, you will notice that we are encoding the query parameter name as well. I am wondering why would query parameter name needed to be encoded.

[QueryStringEncoder.java](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/QueryStringEncoder.java#L72)

Also, if you look at unit test, it also don't test any specific use-case for **parameter name** to be encoded, although there are unit tests around parameter value to be encoded.

[QueryStringEncoderTest.java](https://github.com/netty/netty/blob/4.1/codec-http/src/test/java/io/netty/handler/codec/http/QueryStringEncoderTest.java)

We works as a proxy app, and using Vertx, which in-turn uses Netty, and when we proxy following request, it causing the query parameter **name** being encoded while (probably) it shouldn't.

**Input** 
`/server/path?jREJBBB5x2AaiSSDO0/OskoCztDZBAAAAAADV1A4`

**Output**
`/server/path?jREJBBB5x2AaiSSDO0%2FOskoCztDZBAAAAAADV1A4`

Please note that in sample above there is no value defined for the parameter. This is how we receive from a Windows device, so we are suppose to proxy it as-is.

Please See Vertx issue for reference - https://github.com/eclipse/vert.x/issues/2544

### Netty version

4.1.x

### JVM version (e.g. `java -version`)
1.8_181

**Comment by normanmaurer** [comment] 2018-08-09 12:13
@manish-panwar we love PRs... also @slandelle any thoughts ?

**Comment by slandelle** [comment] 2018-08-09 12:46
On vacation :)

@manish-panwar Actually, you're wrong, and parameter names must be encoded, just like parameter values.
The problem is that Netty's QueryStringEncoder uses URLEncoder for encoding query params, which is wrong as, as its javadoc states, is for `application/x-www-form-urlencoded` encoding!

From RFC3986:

> query       = *( pchar / "/" / "?" )

so `/` shouldn't be percent encoded.

Sadly, JDK lacks a tool for building URIs (or maybe there's one with the new HTTP client in Java 11, can't say). There's one in JAX-RS, one in Spring, there's scala-uri for Scala... Basically, each URI part has its own valid character set.

**Comment by manish-panwar** [comment] 2018-08-09 15:10
Thanks a lot for the response guys! Looks like I might need help from Vertx guys to not use QueryStringEncoder.java, or some workaround. I will look into Java 11 HTTP Client as well, in case it has anything.

**Comment by manish-panwar** [comment] 2018-08-09 15:11
@arushi315 - Can you please look into Java 11?

**Comment by normanmaurer** [comment] 2019-10-11 08:43
Closing as it seems like this is not a bug

**Closed by normanmaurer** 2019-10-11 08:43 UTC
