### ISSUE TITLE
On a system without netty-tcnative: netty 4.1.74.Final unsuccessfully tries to load netty-tcnative, while netty 4.1.70.Final detects that netty-tcnative is not in the classpath

### ISSUE THREAD

**Issue by privatestatic** [netty/netty#12101] opened 2022-02-15 12:27 UTC
As the netty seems to work correctly despite the tcnative loader problem this seems be more like a cosmetical issue.

### Expected behavior
It should be detected that netty-tcnative is not in the classpath like it was in netty 4.1.70.Final:
```
22-02-15 08:25:41,387 D [Thread-1                  InternalThreadLocalMap           86] -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
22-02-15 08:25:41,419 D [Thread-1                  OpenSsl                         137] netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
22-02-15 08:25:41,622 D [Thread-1                  JdkSslContext                    97] Default protocols (JDK): [TLSv1.3, TLSv1.2] 
```

### Actual behavior
With netty 4.1.74.Final it's tried to load netty-tcnative which gives the following exception:
```
22-02-15 09:44:10,576 D [Thread-0                  InternalThreadLocalMap           89] -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
22-02-15 09:44:10,607 D [Thread-0                  NativeLibraryLoader              78] -Dio.netty.native.workdir: C:\Windows\TEMP (io.netty.tmpdir)
22-02-15 09:44:10,607 D [Thread-0                  NativeLibraryLoader              83] -Dio.netty.native.deleteLibAfterLoading: true
22-02-15 09:44:10,607 D [Thread-0                  NativeLibraryLoader              87] -Dio.netty.native.tryPatchShadedId: true
22-02-15 09:44:10,607 D [Thread-0                  NativeLibraryLoader              91] -Dio.netty.native.detectNativeLibraryDuplicates: true
22-02-15 09:44:10,607 D [Thread-0                  OpenSsl                         149] Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705) ~[netty-handler-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146) [netty-handler-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.ssl.SslContext.defaultProvider(SslContext.java:124) [netty-handler-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.ssl.SslContext.defaultClientProvider(SslContext.java:120) [netty-handler-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:817) [netty-handler-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:611) [netty-handler-4.1.74.Final.jar:4.1.74.Final]
...
22-02-15 09:44:11,092 D [Thread-0                  JdkSslContext                    97] Default protocols (JDK): [TLSv1.3, TLSv1.2] 
```

### Netty version
4.1.74.Final without tcnative in the classpath

### JVM version (e.g. `java -version`)
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### OS version (e.g. `uname -a`)
Windows Server 2019 Datacenter
Version 1809
OS build 17763.678

**Comment by chrisvest** [comment] 2022-02-16 00:26
It does do this, though: https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L131-L143

Can you double-check that you really don't have a `io.netty.internal.tcnative.SSLContext` class anywhere on your class path?

**Comment by privatestatic** [comment] 2022-02-16 09:15
Thanks, indeed the problem seems to be that io.netty.internal.tcnative.SSLContext is in the classpath for netty 4.1.74.Final.

The maven dependency tree shows the following difference for the netty versions:

netty 4.1.70.Final:
```
[INFO]    +- io.netty:netty-common:jar:4.1.70.Final:compile
[INFO]    \- io.netty:netty-handler:jar:4.1.70.Final:compile
[INFO]       +- io.netty:netty-resolver:jar:4.1.70.Final:compile
[INFO]       +- io.netty:netty-buffer:jar:4.1.70.Final:compile
[INFO]       +- io.netty:netty-transport:jar:4.1.70.Final:compile
[INFO]       \- io.netty:netty-codec:jar:4.1.70.Final:compile
```

netty 4.1.74.Final:
```
[INFO]    +- io.netty:netty-common:jar:4.1.74.Final:compile
[INFO]    \- io.netty:netty-handler:jar:4.1.74.Final:compile
[INFO]       +- io.netty:netty-resolver:jar:4.1.74.Final:compile
[INFO]       +- io.netty:netty-buffer:jar:4.1.74.Final:compile
[INFO]       +- io.netty:netty-transport:jar:4.1.74.Final:compile
[INFO]       +- io.netty:netty-codec:jar:4.1.74.Final:compile
[INFO]       \- io.netty:netty-tcnative-classes:jar:2.0.48.Final:compile
```

With netty 4.1.74.Final io.netty.internal.tcnative.SSLContext comes to with io.netty:netty-tcnative-classes and io.netty:netty-tcnative-classes is a dependency of io.netty:netty-handler.

After looking through the latest commits, it looks like the different behaviour came with https://github.com/netty/netty/commit/81f8b1a5017a4887bdd42dd8f4c8157953b07d24.
Since this change netty-handler has a non-optional dependency on netty-tcnative-classes and so we always have the io.netty.internal.tcnative.SSLContext when we have the netty-handler.

**Comment by chrisvest** [comment] 2022-02-16 14:13
Yeah, looks like it's caused by https://github.com/netty/netty/pull/11745

@normanmaurer do you recall what prompted that one? The motivation isn't obvious to me.

**Comment by normanmaurer** [comment] 2022-03-04 16:44
I think we should better make it a runtime dependency as before. Let me fix this.

**Comment by normanmaurer** [comment] 2022-03-04 16:49
Related to https://github.com/netty/netty/issues/12132

**Comment by normanmaurer** [comment] 2022-03-04 16:49
Should be fixed by https://github.com/netty/netty/pull/12146

**Closed** 2022-03-04 19:38 UTC
