### ISSUE TITLE
If caught Throwables such as OutOfMemoryError need more handling than logging

### ISSUE THREAD

**Issue by nickreeves** [netty/netty#466] opened 2012-07-19 14:35 UTC
In some cases Throwables which are not Exceptions such as OutOfMemoryError are being caught then handled only by logging which is inadequate. For example see org.jboss.netty.channel.socket.nio.AbstractNioWorker.

Java programs are generally not intended to carry on normally after such failures. although some error handling before they exit may sometimes be appropriate when possible. Netty should either exit the Java process itself in these circumstances, or at least defer the decision to the enclosing application.

In my case the customer reported a large number of ClosedSelectorExceptions being logged by netty. Trawling back through many hours of logs in turned out that an earlier series of OutOfMemoryErrors had put Netty into a strange state, but there was no way for the enclosing application to determine or handle this. If the process had exited then existing failure detection mechanisms would have caused it be restarted.

**Comment by s1monw** [comment] 2017-04-06 09:57
> Ideally Netty shouldn't even be catching Throwables it has no adequate mechanism for handling. Arguably all the "catch (Throwable t)" should be "catch (Exception e)" and let the JVM exit with other Throwables such as OutOfMemoryError.

I couldn't agree more on this.... please don't call `System.exit` yourself rather don't catch throwable all apps can do the `System.exit` call in their code or handle it in different ways ie. log stuff or whatever

**Comment by Scottmitch** [comment] 2017-04-06 15:41
I'm going to close this issue as a duplicate of https://github.com/netty/netty/issues/6096. https://github.com/netty/netty/issues/6096#issuecomment-264574221 includes more up to date and I think more concrete discussion on a path forward.

**Closed by Scottmitch** 2017-04-06 15:41 UTC
