### ISSUE TITLE
Update Netty to Java 21

### ISSUE THREAD

**Issue by Talbot3** [netty/netty#13975] opened 2024-04-13 12:21 UTC
just want ask this, any plan to do it and fix bug...

**Comment by Talbot3** [comment] 2024-04-13 12:22
any plan to fix such as

```

java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @6767c1fc
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
	at java.base/java.lang.reflect.Method.invoke(Method.java:571)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:325)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:214)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:82)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:269)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:166)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:135)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at com.bfxy.netty.marshalling.Server.main(Server.java:17)
```

**Comment by Talbot3** [comment] 2024-04-13 12:23
because module java.base does not export jdk.internal.misc to unnamed module,
that so hated

**Comment by Talbot3** [comment] 2024-04-13 12:50
please use JEP 442 for java 21. maybe we can create a new version for this special.

**Comment by Talbot3** [comment] 2024-04-13 12:50
detail here https://openjdk.org/jeps/442

**Comment by chrisvest** [comment] 2024-04-13 18:35
Whatever Netty version you're talking about is not the latest. And the stack trace you're showing is most likely from a DEBUG log line.

**Comment by Talbot3** [comment] 2024-04-14 00:21
Whatever Netty version you're talking about is not the latest. And the stack trace you're showing is most likely from a DEBUG log line.

_Originally posted by @chrisvest in https://github.com/netty/netty/issues/13975#issuecomment-2053726747_
            
What mean?here version
```
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.1.108.Final</version>
</dependency>

```

when run on java 21, exception will be create. because  java 21 not support access java.io.base or other internal package.

**Comment by shoothzj** [comment] 2024-04-14 03:48
I think code in [PlatformDependent0](https://github.com/netty/netty/blob/e19c91f73aa9d9ae2e67c0b01847f72a882196d1/common/src/main/java/io/netty/util/internal/PlatformDependent0.java) is trying to detect. You can share the full log, it should contains information which printed in  PlatformDependent0.java

**Comment by chrisvest** [comment] 2024-04-15 02:17
> ```
> <dependency>
>     <groupId>io.netty</groupId>
>     <artifactId>netty-all</artifactId>
>     <version>4.1.108.Final</version>
> </dependency>
> ```

The mystery deepens.

According to [your stack trace](https://github.com/netty/netty/issues/13975#issuecomment-2053631733), `PlatformDependent0.java` line 334 makes a call to the `java.lang.reflect.Method.invoke()` method.
However, if we look at line 334 in the 4.1.108.Final tag, we just see a closing curly-bracket:

https://github.com/netty/netty/blob/3a3f9d13b129555802de5652667ca0af662f554e/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L332-L336

This means the version of `netty-common` you have at runtime, is _not_ the one implied by your `netty-all` dependency.

Probably you have a mix of netty versions on your classpath at runtime, and this can cause all sorts of problems.
This is most likely the root cause of your troubles, and the stack trace you see is just a symptom.
I suggest you investigate your netty versions first, and only look at how well Java 21 is supported once you've made sure all your netty versions are coordinated.

**Comment by He-Pin** [comment] 2024-04-22 16:53
Quick result,  import a netty bom in your parent pom, then fixed

**Closed** 2024-05-27 06:44 UTC
