### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:1

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [netty/netty#5070] opened 2016-04-04 11:52 UTC
Hello, I have this exception, at 4.1.0.CR6 but at 4.1.0.Beta8 works well. What I did wrong? Currently I am using custom Handshaker, with 13 version (WebSocketClientHandshaker13) .

```
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:1
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:188)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I tried to set "allowExtensions"  but then with 

```
io.netty.handler.codec.CorruptedFrameException: data frame using reserved opcode 7
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:229)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

reproduce: try to connect to lightstreamer server. via  wss

**Comment by vitaliy-kuzmich** [comment] 2016-04-05 08:15
just tried 4.1.0.CR1, it also does not works. What is the changes in frames between 4.1.0.Beta8 and  4.1.0.CR1 ?

**Comment by vitaliy-kuzmich** [comment] 2016-04-05 10:43
upd: wss does not working with proxies. But worked before.

**Comment by normanmaurer** [comment] 2016-04-05 11:17
@vitaliy-kuzmich can you give us a reproducer ?

**Comment by vitaliy-kuzmich** [comment] 2016-04-06 11:39
https://github.com/vitaliy-kuzmich/reproducer5070
to fix:
cut HttpProxyHandler handler from WSInitializer or change netty version to 4.1.0.Beta8 in pom.xml

**Comment by normanmaurer** [comment] 2016-04-07 12:44
@vitaliy-kuzmich what I'm expected to see when it works ?

**Comment by vitaliy-kuzmich** [comment] 2016-04-07 16:30
@normanmaurer "CloseWebSocketFrame Cannot continue due to an unexpected error" it is mean then WS parsed well....

**Comment by normanmaurer** [comment] 2016-04-07 16:44
@vitaliy-kuzmich did you also try to test it by have the proxy (little-proxy) and your code run in two different JVMs ? As maybe the little-proxy is prepared to take the latest CR releases in terms of changes.

**Comment by vitaliy-kuzmich** [comment] 2016-04-07 16:52
firstly I got this error at external proxy service... I found that same error occures with little-proxy also, so I used it to reproduce and exclude external services which is easier.

**Comment by vitaliy-kuzmich** [comment] 2016-04-07 16:53
no I did not test it on different JVMs.

**Comment by normanmaurer** [comment] 2016-04-07 17:04
@vitaliy-kuzmich ah ok... thanks!

**Comment by normanmaurer** [comment] 2016-04-07 17:11
@vitaliy-kuzmich just checked and I can not reproduce with latest code from 4.1 branch. Can you try with 4.1.0.Final-SNAPSHOT and check if you can not reproduce anymore as well ?

**Comment by normanmaurer** [comment] 2016-04-07 17:31
hmm something is still wrong. let me investigate

**Comment by normanmaurer** [comment] 2016-04-07 17:43
@vitaliy-kuzmich ok I know whats going on.... let me think about a way to fix it.

**Comment by vitaliy-kuzmich** [comment] 2016-04-07 17:45
@ngocdaothanh that is interesting. What is going on there?

**Comment by normanmaurer** [comment] 2016-04-07 18:53
@vitaliy-kuzmich basically the HttpClientCodec of HttpProxyHandler is removed by mistake.

**Comment by vplewis** [comment] 2016-08-31 18:27
I am having this exact issue with 4.1.5 Final

**Comment by philrykoff** [comment] 2017-05-29 10:17
RSV 4 seems to be connected to another issue: https://github.com/netty/netty/issues/5837.

**Comment by philrykoff** [comment] 2017-05-29 10:21
I can reproduce this issue (wss over proxy => CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:1) with VertX 3.3.3 which uses netty 4.1.5.Final.

From the comments, it looks like @normanmaurer has resolved the issue - but it is still open. Will this be merged or should it already be fixed?

**Comment by fenik17** [comment] 2017-05-29 10:38
> Will this be merged or should it already be fixed?

Obviously, the fix was included in a later version [than 4.1.5](http://netty.io/news/2016/08/29/4-0-41-Final-4-1-5-Final.html).

**Comment by wojciechkumon** [comment] 2017-05-29 11:07
I'm facing "io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:1" (vertx 3.4.1, wss over proxy), can I do anything or should I just wait for new version?

**Comment by philrykoff** [comment] 2017-05-29 11:15
VertX 3.4.1 (which is the latest release of VertX) uses netty 4.1.8.Final (released Jan 2017).

It actually looks like the corresponding pull request https://github.com/netty/netty/pull/5329 was never merged.

**Comment by wojciechkumon** [comment] 2017-05-29 11:25
Any chance to merge it and use in next release?

**Comment by philrykoff** [comment] 2017-10-10 14:26
@normanmaurer any chance to merge your solution to this issue - was it commit  https://github.com/netty/netty/commit/387bb09f9a97c4c2e6a3c461bed0666f5cd59277 ?

**Comment by johnou** [comment] 2017-10-10 20:38
@philrykoff he is off on holiday now, if you take that commit, rebase it, and address the comments Trustin left I think that would help a lot.

**Comment by ted-wq-x** [comment] 2017-10-13 07:08
@philrykoff i use vertx 3.4.2 also has this problem ,do you have any idea to fix this?

**Comment by philrykoff** [comment] 2017-10-13 07:27
I have never worked "in" netty, so I am a bit hesitant to rebase that PR myself. I am currently wrapping up a project and get back to this afterwards.

**Comment by ted-wq-x** [comment] 2017-10-13 10:48
The default value is http so i set the type to socks5,hahaha,but I don’t know why netty doesn’t support https?

在 2017年10月13日，下午3:28，Phil Rykoff <notifications@github.com<mailto:notifications@github.com>> 写道：

hesitant

**Comment by amotech-tm** [comment] 2018-05-02 12:57
Hi - I have the same problem with vertx 3.5.1 / netty 4.1.19.Final 
Are there any plans to fix this ? 
Best regards
Thomas

**Comment by valodzka** [comment] 2018-05-18 10:14
@normanmaurer  any particular reason why 387bb09f9a97c4c2e6a3c461bed0666f5cd59277 is not merged? Any plans to do it?

**Comment by kedarw** [comment] 2018-11-01 18:22
Hi, I am also facing same issue. Is there plan to merge fix in any of upcoming releases?

Also others who faced same issue, found way to get around? Can you please describe what you did? Thanks in advance.

Just for reference exception I saw:

```io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:1
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:188)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1336)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wojtas626** [comment] 2018-11-01 19:48
@kedarw I found a workaround: https://github.com/TakahikoKawasaki/nv-websocket-client
This is websocket client library supporting wss and proxy. I replaced vertx websocket client with this. Works in production :)

**Comment by kedarw** [comment] 2018-11-02 17:39
Thanks @wojtas626, appreciate your help. I will try nv-websocket-client.

**Comment by rgmz** [comment] 2019-04-12 16:42
> Hi - I have the same problem with vertx 3.5.1 / netty 4.1.19.Final / wss over proxy
> Are there any plans to fix this ?
> Best regards
> Thomas

I am still experiencing this issue in Vert.x 3.7.0 / Netty 4.1.30.Final :(.

**Comment by luckyyuandm** [comment] 2019-04-26 04:09
The problem is that the WebSocketClientHandshaker put ws-decoder（ws-encoder）  in the wrong place in the ChannelPipeline. The WebSocketClientHandshaker find the position where the ws-decoder（ws-encoder）was put in the ChannelPipeline by locating the first io.netty.handler.codec.http.HttpClientCodec. details ：https://github.com/netty/netty/issues/5201#issue-152789771 
workaround：rewrite HttpProxyHandler and HttpClientCodec which HttpProxyHandler referenced, change the package name.  Make sure HttpClientCodec which HttpProxyHandler referenced in the channelpipeline is different from io.netty.handler.codec.http.HttpClientCodec。

**Comment by hengyunabc** [comment] 2019-08-21 09:21
Version:  4.1.38.Final

Change 

```java
pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, true));
```

to 

```java
pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, null, true, 65536, false, true, 10000L));
```

Resolved my problem.

**Closed** 2020-04-22 10:56 UTC
Labels: defect
