### ISSUE TITLE
JVM crash on Raspberry Pi3 (cross-post from vertx-web)

### ISSUE THREAD

**Issue by pmlopes** [netty/netty#5058] opened 2016-03-30 07:21 UTC
See: vert-x3/vertx-web#346

Netty version: 4.0.33.Final

Problem:
```
Problematic frame:
     J 481 C1 io.netty.util.internal.PlatformDependent.getByte(J)B (5 bytes) @ 0x7413cf30 [0x7413cf20+0x10]
```

Result: JVM crash

**Comment by johnou** [comment] 2016-03-30 07:31
@pmlopes try 4.0.35+

https://github.com/netty/netty/pull/4845

**Comment by normanmaurer** [comment] 2016-03-30 08:58
Duplicate of #4845 closing.

**Closed by normanmaurer** 2016-03-30 08:58 UTC
