### ISSUE TITLE
http2 cleartext upgrade, server not support first POST request to upgrade protocol

### ISSUE THREAD

**Issue by zjupure** [netty/netty#7079] opened 2017-08-10 09:23 UTC
send a initial upgrade request with POST method and header content-length > 0, the server will not upgrade to HTTP/2.

### Expected behavior
upgrade the HTTP/1.1 to HTTP/2 and response the request rather than 413.
as the rfc http://httpwg.org/specs/rfc7540.html, it is not mandatory that frist upgarde request must be GET or OPTIONS method. just need to modify the header "Connection", "Upgrade", "HTTP2-Settings"

```
GET / HTTP/1.1
Host: server.example.com
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: <base64url encoding of HTTP/2 SETTINGS payload>
```
Requests that contain a payload body MUST be sent in their entirety before the client can send HTTP/2 frames. This means that a large request can block the use of the connection until it is completely sent.

If concurrency of an initial request with subsequent requests is important, an OPTIONS request can be used to perform the upgrade to HTTP/2, at the cost of an additional round trip.

It means the first request could be any method request. If the server support HTTP2, then response 101 code and the real response for this request with http frame format. If not, it still can response with HTTP/1.1 protocol.

### Actual behavior
The http2 server example will reponse 413 not 101.

### Steps to reproduce
send a request with POST method for upgrade request.
```
POST / HTTP/1.1
Host: server.example.com
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: <base64url encoding of HTTP/2 SETTINGS payload>
Content-length: 5

<http1.1 body data>
```

### Netty version
lastest, 4.1

**Comment by normanmaurer** [comment] 2017-08-10 09:51
@zjupure seems legit... want to contribute a PR to fix it ?

**Comment by normanmaurer** [comment] 2017-08-15 04:30
@zjupure can you tell me which exact example code you are talking about ? We have multiple :)

**Comment by zjupure** [comment] 2017-08-16 05:39
@normanmaurer  the http2 examples under `netty/example/src/main/java/io/netty/example/http2/helloworld`, the server examples in package `server`, `multiplex.server`, `frame.server` would response 413 code and not upgrade to HTTP/2.

I digest the source and find the default consturct function with two params of class `'io.netty.handler.codec.http.HttpServerUpgradeHandler` with set super class `HttpObjectAggregator's` filed `maxContentLength` to be zero. When `Http2ServerInitializer` configure clear text pipeline handlers, it use the default consturct method,  so then the call `isContentLengthInvalid()` in `HttpObjectAggregator's` will return `true`, so POST upgrade to HTTP/2 failed.

io.netty.handler.codec.http.HttpServerUpgradeHandler
```
public HttpServerUpgradeHandler(HttpServerUpgradeHandler.SourceCodec sourceCodec, HttpServerUpgradeHandler.UpgradeCodecFactory upgradeCodecFactory) {
        this(sourceCodec, upgradeCodecFactory, 0);
    }
```


and I modify the example code in `Http2ServerInitializer` to set a large `maxContentLength` to `HttpServerUpgradeHandler`, then it can pass my POST upgrade test. Thanks.

io.netty.example.http2.helloworld.server.Http2ServerInitializer
```
    private void configureClearText(SocketChannel ch) {
        final ChannelPipeline p = ch.pipeline();
        final HttpServerCodec sourceCodec = new HttpServerCodec();
         // change this line to use the three params construct function
        final HttpServerUpgradeHandler upgradeHandler = new HttpServerUpgradeHandler(sourceCodec, upgradeCodecFactory, maxHttpContentLength);      
        final CleartextHttp2ServerUpgradeHandler cleartextHttp2ServerUpgradeHandler =
                new CleartextHttp2ServerUpgradeHandler(sourceCodec, upgradeHandler,
                                                       new HelloWorldHttp2HandlerBuilder().build());

        p.addLast(cleartextHttp2ServerUpgradeHandler);
        p.addLast(new SimpleChannelInboundHandler<HttpMessage>() {
            @Override
            protected void channelRead0(ChannelHandlerContext ctx, HttpMessage msg) throws Exception {
                // If this handler is hit then no upgrade has been attempted and the client is just talking HTTP.
                System.err.println("Directly talking: " + msg.protocolVersion() + " (no upgrade was attempted)");
                ChannelPipeline pipeline = ctx.pipeline();
                ChannelHandlerContext thisCtx = pipeline.context(this);
                pipeline.addAfter(thisCtx.name(), null, new HelloWorldHttp1Handler("Direct. No Upgrade Attempted."));
                pipeline.replace(this, null, new HttpObjectAggregator(maxHttpContentLength));
                ctx.fireChannelRead(ReferenceCountUtil.retain(msg));
            }
        });

        p.addLast(new UserEventLogger());
    }
```

**Comment by normanmaurer** [comment] 2017-08-16 05:43
@zjupure ah makes sense... Then its not a bug. Let me close this

**Closed by normanmaurer** 2017-08-16 05:43 UTC
