### ISSUE TITLE
ReadString()

### ISSUE THREAD

**Issue by esfomeado** [netty/netty#4481] opened 2015-11-17 17:31 UTC
Is there any plans in implementing a simple readString to the ByteBuf class?

Thanks

**Comment by normanmaurer** [comment] 2015-11-21 15:58
@esfomeado why not use `ByteBuf.toString(....)` ?

**Comment by normanmaurer** [comment] 2015-11-26 21:16
Closing as we need more info

**Closed by normanmaurer** 2015-11-26 21:16 UTC

**Comment by esfomeado** [comment] 2015-12-22 11:44
ByteBuf.toString(...) works fine however you need to do the following steps in order to read a string from a ByteBuf:
1 - Read (U16) string length.
2 - Read the string itself.
3 - Move the readerIndex of the ByteBuf.

In you create a function to do this steps but it would look "ugly" when this could be integrated in Netty.
So i was thinking that would be great if was possible to encapsulate this steps in a readString() like there is a readByte(), readShort(), etc...
The readString() should support as parameter the Charset and if one wasn't passed it should use the default.

**Comment by Scottmitch** [comment] 2015-12-23 01:14
This feels like a duplicate of https://github.com/netty/netty/issues/2936? @esfomeado - Can you describe how this request differs from the previous request?

**Comment by esfomeado** [comment] 2015-12-23 11:05
@Scottmitch Is a duplicated.

In my opinion it makes some sense to have a readString(), writeString() directly in the ByteBuf because sometimes there is the need to send strings in the ByteBuf.
I can't use a decoder because i don't wanna convert all the ByteBuf to a string. I'm developing a MMO in my free time and this would be a great helper to simplify some stuff.

Regards
