### ISSUE TITLE
[Proposal] Keep information about the class/method that released the buffer

### ISSUE THREAD

**Issue by maseev** [netty/netty#6773] opened 2017-05-23 14:38 UTC
From time to time you get this notorious `IllegalReferenceCountException` which basically means that you released the same buffer twice. 

It can be a real pain in the neck to track down the method which released this particular buffer. 
It's especially painful if you have a quite large pipeline and you're juggling with `ByteBuf` instances back and forth. 

The exception itself tells only two things:

1.  The buffer was already released (i.e. its reference count is zero)
2.  The actual stack trace which shows you which method and in which class called the `ByteBuf::release` method

It would be great if Netty could keep some information about the caller in the ByteBuf instances. So when you call the `ByteBuf::release` method and see that the reference counter is zero, you could attach this information to the exception message and a user would know who released this particular buffer earlier.

I think it would simplify the debugging process a little bit. At the moment it can often be impossible to understand who released the buffer without knowing this additional information about the previous caller.
 
`Reflection.getCallerClass()` or something similar should do the trick. This feature can also be implemented as a special type of `ByteBuf` which can only be enabled with some startup option (like a memory leak detector). Because it'll definitely be very costly to use this feature all the time, I think.

WDYT?

**Comment by NiteshKant** [comment] 2017-05-23 21:36
@maseev it looks like you are looking for the feature provided by `io.netty.util.ResourceLeakDetector`? [This wiki page](http://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks) details how to use it. Or am I missing something in your proposal?

**Comment by Scottmitch** [comment] 2017-05-23 23:47
This request sounds different than `io.netty.util.ResourceLeakDetector`. Instead of detecting things that aren't released (what `io.netty.util.ResourceLeakDetector` tries to do) this is requesting tracking call stack information when a buffer is actually released to help debug "double release" scenarios.

As you indicated I think the challenge here is balancing overhead introduced by the additional tracking and potential API impacts. Do we retain a field in each object and increase the memory footprint of each object (even if we are not "tracking" would we still have an additional member variable to track)? Do we sample like we do for ref counting ... what if your object wasn't sampled do we offer a mode to track all deallocations? How common is this in practice and is it worth the additional work/overhead to track this?

**Comment by maseev** [comment] 2017-05-24 04:41
> As you indicated I think the challenge here is balancing overhead introduced by the additional tracking and potential API impacts.

This feature can be implemented the same way as the memory leak detection subsystem. You pass a `-Dio.netty.leakDetection.level` option with the desired level and instead of receiving simple `PooledSlicedBuf` you start receiving `AdvancedLeakAwareByteBuf` instances. 
But the end users won't notice any differences because they primarily work with a `ByteBuf` class. The similar approach can be used to implement this feature. But I think it would be rather problematic to allow users use the memory leak detection and 'double release' detection features at the same time.

> Do we retain a field in each object and increase the memory footprint of each object (even if we are not "tracking" would we still have an additional member variable to track)?

It's not necessary. This feature can only be enabled when the user passes a special startup option. So, when this option is present, we work with a special subtype of `ByteBuf` class which can remember who released it. But when the option is not present, we work with the good old `PooledUnsafeDirectByteBuf` (or something similar) which obviously doesn't have any overhead related to this new feature.

> Do we sample like we do for ref counting ... what if your object wasn't sampled do we offer a mode to track all deallocations?

I think you can 'sample' all deallocations. You can check the reference counter field and if it's greater than zero then you just update this field which keeps the information about the previous caller of the method. But if you see that this counter is zero, you get the information about the previous caller and attach it to the exception message.

> How common is this in practice and is it worth the additional work/overhead to track this?

The more I work with Netty and the more I use different components (TLS and other types of handlers), the more often I see this exception. The same question can be asked about the memory leak detection subsystem. Is it that common that people who use Netty simply forget to call release and end up with OOM? These two features are common in this regard. It's very simple - you receive a `ByteBuf` instance and you either release it or pass it down the pipeline.

I encountered a very weird scenario not so long ago when a device from one manufacturer had connected to the server, passed the handshake and then disconnected abruptly because the server blew up with the `IllegalReferenceCountException` exception in some of the Netty's class (it wasn't one of the server's handlers). When I tested the same case with a different device the test passed without any exceptions. For some reason switching from `PooledByteBufAllocator` to `UnpooledByteBufAllocator` did the trick. But it's basically a workaround not a solution of the problem.

**Comment by Scottmitch** [comment] 2017-05-24 17:48
> But I think it would be rather problematic to allow users use the memory leak detection and 'double release' detection features at the same time.

Hum I don't have cycles to think too deeply about this problem but it would be nice to avoid introducing another layer of object allocations/wrapping and work out how this interacts with the leak detection layer. I don't see why having both on (leak detection and double release) simultaneously would logically be a problem ... more a question of how its implemented. I wonder if enhancing the leak detection to also (optionally?) track double release too makes sense...

> the server blew up with the IllegalReferenceCountException exception in some of the Netty's class (it wasn't one of the server's handlers)

Note that this doesn't necessarily mean that there is an issue in Netty. If for example the Netty class is designed to retain reference count ownership this means the application called `release()` it shouldn't have.

> For some reason switching from PooledByteBufAllocator to UnpooledByteBufAllocator did the trick. But it's basically a workaround not a solution of the problem.

This is worrisome and agreed it would be better to understand the root cause.

**Comment by maseev** [comment] 2017-05-25 01:36
>I wonder if enhancing the leak detection to also (optionally?) track double release too makes sense...

This is probably the only way it can be implemented so that users could use this two features at the same time. At least, this is the only way I could come up with. Or it can be implemented as a separate feature (not an enhancement of the memory leak detection feature). But in this case, Netty would need to check what features are enabled and throw an exception if these two features were turned on.

>Note that this doesn't necessarily mean that there is an issue in Netty. If for example the Netty class is designed to retain reference count ownership this means the application called release() it shouldn't have.

I agree. But the funny this is at the time of testing I had the only implementation of the pipeline which handled connections from these devices. And only one type of the device was making the server throw this exception.

>This is worrisome and agreed it would be better to understand the root cause.

Again, it's quite difficult to say what went wrong without knowing who released that particular buffer before. It's interesting that this particular feature was already implemented during the investigation of this [ticket](https://github.com/netty/netty/issues/5999#issuecomment-260025202).

**Comment by maseev** [comment] 2017-05-26 05:55
Is there an extension point in Netty I could use to implement this functionality by any chance?

**Comment by Scottmitch** [comment] 2017-05-30 19:12
You may be able to create your own ByteBufAllocator and provide additional info as necessary.

**Comment by maseev** [comment] 2017-05-31 01:53
Should I submit a PR or you folks are not interested in such feature?

**Comment by normanmaurer** [comment] 2017-05-31 05:26
Yeah you can submit one.... if or if not it will be merged at the end depends of course

**Comment by maseev** [comment] 2017-06-02 17:42
I will stick with [this](https://github.com/netty/netty/issues/6773#issuecomment-304978695) approach.

**Comment by maseev** [comment] 2017-09-18 11:21
On second thought, I think it would be a good idea to share this feature. I'll create a PR soon.

**Closed** 2018-03-03 13:39 UTC
