### ISSUE TITLE
HttpContentCompressor.beginEncode

### ISSUE THREAD

**Issue by mskaric** [netty/netty#6689] opened 2017-05-01 20:45 UTC
There is a problem in condition. Please remove ! sign.

### Expected behavior

String contentEncoding = headers.headers().get(HttpHeaderNames.CONTENT_ENCODING);
        if (contentEncoding != null &&
            HttpHeaderValues.IDENTITY.contentEqualsIgnoreCase(contentEncoding)) {
            return null;
        }

### Actual behavior

String contentEncoding = headers.headers().get(HttpHeaderNames.CONTENT_ENCODING);
        if (contentEncoding != null &&
            !HttpHeaderValues.IDENTITY.contentEqualsIgnoreCase(contentEncoding)) {
            return null;
        }

**Comment by normanmaurer** [comment] 2017-05-01 20:46
Can you please open a PR and add a unit-test as well ?


On 1. May 2017 at 13:45:41, mskaric (notifications@github.com) wrote:

There is a problem in condition. Please remove ! sign.
Expected behavior

String contentEncoding =
headers.headers().get(HttpHeaderNames.CONTENT_ENCODING);
if (contentEncoding != null &&
HttpHeaderValues.IDENTITY.contentEqualsIgnoreCase(contentEncoding)) {
return null;
}
Actual behavior

String contentEncoding =
headers.headers().get(HttpHeaderNames.CONTENT_ENCODING);
if (contentEncoding != null &&
!HttpHeaderValues.IDENTITY.contentEqualsIgnoreCase(contentEncoding)) {
return null;
}
Steps to reproduce Minimal yet complete reproducer code (or URL to code) Netty
version JVM version (e.g. java -version) OS version (e.g. uname -a)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/netty/netty/issues/6689>, or mute the thread

**Comment by mskaric** [comment] 2017-05-01 20:56
Unfortunately I really have no time to delve into that :). I just wanted to
help. I made this code to go around the problem and now it works as
expected. Hopefully you don't mind.
Setting identity should turn off the compression e.g. return null.


public class WebContentCompressor extends HttpContentCompressor{

    @Override
    protected Result beginEncode(HttpResponse headers, String
acceptEncoding) throws Exception {
        String
encoding=headers.headers().get(HttpHeaderNames.CONTENT_ENCODING);
        if(encoding!=null &&
HttpHeaderValues.IDENTITY.contentEqualsIgnoreCase(encoding))
              return null;
        return super.beginEncode(headers, acceptEncoding);
    }

}


Srdačan pozdrav,

*Milan*

**Comment by normanmaurer** [comment] 2017-05-02 03:32
@mskaric PTAL https://github.com/netty/netty/pull/6690

**Comment by normanmaurer** [comment] 2017-05-03 17:55
Fixed via https://github.com/netty/netty/pull/6690

**Closed by normanmaurer** 2017-05-03 17:55 UTC
