### ISSUE TITLE
Feature request: simple HTTP proxy handler

### ISSUE THREAD

**Issue by kleinron** [netty/netty#8269] opened 2018-09-06 09:07 UTC
Currently, the class HttpProxyHandler supports only proxy-ing through a TCP tunnel, established by a `CONNECT` command.
This implementation would make it hard to cache the results, since the actual request and response are being transferred within the established TCP tunnel.
This means that well known proxy servers, such as Squid, might not function at all as proxies (they might refuse to establish the connection) or might not be able to cache the results.

I suggest that a new proxy handler would be developed, so that it won't have the `CONNECT` scenario, and would just issue the HTTP request against the proxy server, rather than the actual host of the HTTP request.

**Comment by normanmaurer** [comment] 2018-09-06 09:56
@kleinron we love contributions...

**Comment by kleinron** [comment] 2018-09-06 11:48
@normanmaurer as a newcomer, this is not a trivial task, especially when the project is quite complex. Maybe I'm wrong and it is a trivial task?

**Comment by vkostyukov** [comment] 2018-09-10 18:26
@kleinron I'm not sure I follow your reasoning. What would a proxy handler you propose do? If you don't need a CONNECT semantic (usually you want it for SSL/TLS connections), you can just omit `HttpProxyHandler` and talk directly to a proxy server, which will forward your requests based on what in the `Host` header.

**Comment by vkostyukov** [comment] 2018-09-11 16:57
@kleinron You should be able to keep the original HTTP request unchanged assuming you're adding a HOST header, [which you normally include anyway](https://tools.ietf.org/html/rfc7230#section-5.4).

**Comment by kleinron** [comment] 2018-09-11 21:00
@vkostyukov IIUC, what you say is that I can do it myself using Netty.
Even if this is true, I think that the proxy related classes are somewhat missing the "regular" and quite common proxy pattern.
This is why I suggest this new feature.
Please don't get me wrong about it, I totally respect Netty project, I just thought it would be nice to recommend on a new feature.

**Comment by SharpMan** [comment] 2018-09-13 06:33
So if I well understand you want a simple HTTPProxyHandler that adds the HOST header ?

**Comment by kleinron** [comment] 2018-09-15 05:45
@SharpMan no, that's not what I mean.
I assume that the request already has a Host header (and even if it doesn't, it can be easily extracted).
All I want is a proxy handler, which would hold an endpoint: a combination of {host|ip} + port.
So that it would execute the original http request against this endpoint, regardless of the host declared in the original http request.

**Comment by normanmaurer** [comment] 2018-11-12 13:32
Closing as we do not plan to add something like this

**Closed by normanmaurer** 2018-11-12 13:32 UTC

**Comment by alvinbush** [comment] 2019-09-10 08:36
@SharpMan are you able to resolve this issue when using netty in Spring WebClient, I have exact the same issue with our proxy, which don't allow CONNECT for http endpoints.

**Comment by jensgram** [comment] 2019-09-25 18:40
@alvinbush I ran into the same issue where a back-end system did not support the HTTP CONNECT verb (405.) The following hack appears to work:

```
WebClient.builder()
  .baseUrl("http://" + proxyHost + ":" + proxyPort)
  .defaultHeader(HttpHeaders.HOST, destinationHost + ":" destinationPort)
  .…
```

**Comment by dipengfei** [comment] 2019-11-21 12:49
@alvinbush @jensgram @kleinron 
I also met issue in my project and the proxy returned 403 Forbidden, May I know is there any progress in your side for deal with such issue? Is there any solution or workaround?  

Thank you in advance.

**Comment by alvinbush** [comment] 2019-11-21 13:08
Hi 👋 yes the trick from @jensgram helped me to resolve my issue. Thank you so much.

The following worked for me.

url: "http://<proxy:port>/<urlpath>"

 this.header(HttpHeaders.HOST, < Host and Port Part of the actual server address

Now the trick, add the proxy itself into the bypass list of URL’s so that there is no round trips.

If you’re proxy needs username and password you need add the below
httpHeader.set(HttpHeaders.AUTHORIZATION, "Basic ${Base64Utils.encodeToString(it.toByteArray())}")
 

This works lika a charm.

**Comment by dipengfei** [comment] 2019-11-21 13:32
> Hi 👋 yes the trick from @jensgram helped me to resolve my issue. Thank you so much.
> 
> The following worked for me.
> 
> url: "http://proxy:port/urlpath"
> 
> this.header(HttpHeaders.HOST, < Host and Port Part of the actual server address
> 
> Now the trick, add the proxy itself into the bypass list of URL’s so that there is no round trips.
> 
> If you’re proxy needs username and password you need add the below
> httpHeader.set(HttpHeaders.AUTHORIZATION, "Basic ${Base64Utils.encodeToString(it.toByteArray())}")
> 
> This works lika a charm.

Thank you for responding me so quickly, actually I already tried this solution, but it didn't work for me. Please see below code, sorry I can't put the real server information here as it's confidential.

Assuming I want to GET http://stg-dest.com:7105/testuri/xxxxxxx through proxy http://dev-proxy.com:9502, and I confirmed there is no authorization required, the code looks like below,

`
    @Test
    public void test3() {
        
        final String destHost = "stg-dest.com";
        final Integer destPort = 7105;
        
        final String proxyHost = "dev-proxy.com";
        final Integer proxyPort = 9502;
        
        final WebClient wc = WebClient.builder().baseUrl("http://" + proxyHost + ":" + proxyPort)
                                      .defaultHeader(HttpHeaders.HOST, destHost + ":" + destPort)
                                      .build();
        final Mono<String> response = wc.get()
                                        .uri("/testuri/xxxxxxx")
                                        .retrieve()
                                        .bodyToMono(String.class);
        
        log.info("response: {}", response.block());

    }
`
And I get the error saying, 
org.springframework.web.reactive.function.client.WebClientResponseException$NotFound: 404 Not Found from GET http://dev-proxy.com:9502/itesturi/xxxxxxx

I'm not sure if I totally understood your solution, but above URI works good if I test it by using postman and Spring RestTemplate. Please check it out.

Thank you!

**Comment by alvinbush** [comment] 2019-11-21 15:56
I think had this issue as well. Let me check your code and get back to you.

Alvin

Von meinem iPhone gesendet

**Comment by alvinbush** [comment] 2019-11-22 10:40
public void test3() {

    final String destHost = "stg-dest.com";
    final Integer destPort = 7105;
    
    final String proxyHost = "dev-proxy.com";
    final Integer proxyPort = 9502;
    
    final WebClient wc = WebClient.builder()
                                  .build();
    wc.header(HttpHeader.HOST, destHost + ":" + destPort )
    final Mono<String> response = wc.get()
                                    .uri("http://dev-proxy.com:9502/testuri/xxxxxxx")
                                    .retrieve()
                                    .bodyToMono(String.class);
    
    log.info("response: {}", response.block());
}

was working for me. And if you are sharing the web client for other services with https as well, you need to put the proxy host into the bypass of tcpCleint.proxy config

**Comment by dipengfei** [comment] 2019-11-25 01:21
> public void test3() {
> 
> ```
> final String destHost = "stg-dest.com";
> final Integer destPort = 7105;
> 
> final String proxyHost = "dev-proxy.com";
> final Integer proxyPort = 9502;
> 
> final WebClient wc = WebClient.builder()
>                               .build();
> wc.header(HttpHeader.HOST, destHost + ":" + destPort )
> final Mono<String> response = wc.get()
>                                 .uri("http://dev-proxy.com:9502/testuri/xxxxxxx")
>                                 .retrieve()
>                                 .bodyToMono(String.class);
> 
> log.info("response: {}", response.block());
> ```
> 
> }
> 
> was working for me. And if you are sharing the web client for other services with https as well, you need to put the proxy host into the bypass of tcpCleint.proxy config

Thank you a lot, let me have a try!

**Comment by sasikala1591** [comment] 2020-05-08 11:36
Hi, Tried the above solution. Please let me know if the proxy host & port and destination host & port are the same.
