### ISSUE TITLE
HexDumpProxy example does not run out of the box

### ISSUE THREAD

**Issue by uptimestar** [netty/netty#7349] opened 2017-10-29 17:33 UTC
### Expected behavior
I am able to run example and proxy google.
### Actual behavior
Error:
2017-10-29 13:31:30 [nioEventLoopGroup-3-1] io.netty.util.internal.logging.Slf4JLogger.info()
INFO: [id: 0xe63aa526, L:/0:0:0:0:0:0:0:1:8443 - R:/0:0:0:0:0:0:0:1:50264] READ COMPLETE
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
2017-10-29 13:31:30 [nioEventLoopGroup-3-1] io.netty.util.internal.logging.Slf4JLogger.info()
### Steps to reproduce
Download latest netty jar 4.1.16 and run HexDumpProxy example 

### JVM version (e.g. `java -version`)
Latest 1.8.x
### OS version (e.g. `uname -a`)
OSX

**Comment by madgnome** [comment] 2017-12-21 22:34
Can't reproduce on OSX, Java 1.8 and netty 4.1.20

**Comment by normanmaurer** [comment] 2017-12-22 06:19
same... let me close this for now... Please reopen if you still see issues

**Closed by normanmaurer** 2017-12-22 06:19 UTC
