### ISSUE TITLE
channelInactive events with no previous channelActive

### ISSUE THREAD

**Issue by cconroy** [netty/netty#5639] opened 2016-08-04 22:23 UTC
I believe there may be a race condition in `AbstractChannel` that allows for multiple `channelInactive` events to fire.

While there are checks for `wasActive` before firing `channelInactive` events, the actual firing of `channelInactive` is done asynchronously. So, two back-to-back (or concurrent) calls to close the channel may result in duplicate `channelInactive` events firing.

I can gather more data on the precise call stacks that are triggering this if we need. However, we definitely think we see this in a simple metrics handler that increments a counter on `channelActive` and decrements it on `channelInactive`. It should never be possible for this to result in negative values, but that is what we are observing.

Perhaps the `AbstractChannelHandlerContext` should be responsible for enforcing valid state transitions? This could simplify some of the calling code in `AbstractChannel`, and at the time of actually invoking a state change inside the event loop, the context could record the updated state in order to de-dupe any concurrent attempts at changing state?

**Comment by Scottmitch** [comment] 2016-08-04 23:14
@cconroy - can you provide stack traces ... this would be helpful to be sure we understand the root cause.

**Comment by normanmaurer** [comment] 2016-08-05 04:35
+1

**Comment by cconroy** [comment] 2016-08-11 19:39
I added some code to try to gather a pair of the offending stacktraces, but this may be a bit of a Heisenbug: the issue has not happened after I added the instrumentation! This isn't terribly surprising as grabbing a stack trace requires a jvm safepoint. I'll try a different approach where I only grab the second stack trace...

**Comment by normanmaurer** [comment] 2016-08-11 19:40
@cconroy thanks! Keep us posted.

**Comment by cconroy** [comment] 2016-08-12 17:47
No dice with the alternate approach, but I did still observe the strange mismatch. New theory is that we're potentially getting `inactive` events without a prior corresponding `active` event. I'm adding instrumentation to capture stack traces for any such events now.

**Comment by normanmaurer** [comment] 2016-08-12 18:31
@cconroy ok :)

**Comment by normanmaurer** [comment] 2016-08-15 12:32
@cconroy stay tuned I may have an idea what the problem is.

**Comment by cconroy** [comment] 2016-08-17 20:47
My latest instrumentation captured the offending stacktrace:


```
java.lang.Throwable
	at <my channel metrics handler>
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:234)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:234)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
```

I added some code to track firing of active/inactive events in my metrics handler

```
    if (activeFired == 1 && inactiveFired == 0) {
      currentConnections.dec();
    } else {
      logger.warn("Out of order inactive fired activeFired=%d, inactiveFired=%d, channel=%s",
          new Throwable(), activeFired, inactiveFired, ctx.channel());
    }
    inactiveFired++;
    super.channelInactive(ctx);
```

We are getting inactive events before any active events via the IdleStateHandler:

` Out of order inactive fired activeFired=0, inactiveFired=0`

**Comment by cconroy** [comment] 2016-08-17 20:49
I've updated the title of the issue to reflect these new findings.

**Comment by Scottmitch** [comment] 2016-08-17 20:55
@cconroy - thanks for the additional info!

**Comment by normanmaurer** [comment] 2016-08-17 20:58
@cconroy thanks... stay tuned

**Comment by normanmaurer** [comment] 2016-08-18 14:14
@cconroy is it possible that you close a channel directly in a `ChannelFutureListener` that is attached to a ChannelFuture that is returned by `connect(...)` ?

**Comment by cconroy** [comment] 2016-08-18 16:26
I only see this occur on the client side of my reverse proxy. There, in a `ChannelFutureListener` in the event of an error setting up the channel I do call `.addListener(ChannelFutureListener.CLOSE);` on the future.

On the incoming server side, I do call `close` directly and do not see this issue. Though that may not be related as there are different pipelines, latency characteristics, etc..

**Comment by normanmaurer** [comment] 2016-08-18 17:03
Ok thx... Will have a fix shortly

**Comment by normanmaurer** [comment] 2016-08-22 05:43
@cconroy hey... I think this should fix it : https://github.com/netty/netty/pull/5724

**Comment by cconroy** [comment] 2016-08-22 18:53
Thanks!

**Comment by normanmaurer** [comment] 2016-08-24 06:48
Fixed by https://github.com/netty/netty/pull/5724

**Closed by normanmaurer** 2016-08-24 06:48 UTC
Labels: defect
