### ISSUE TITLE
Possibly incorrect changes with Expect/Continue handling in 4.1.14

### ISSUE THREAD

**Issue by omarkilani** [netty/netty#7170] opened 2017-08-31 20:22 UTC
Hi Norman,

I'm one of the developers on unfiltered (https://github.com/unfiltered/unfiltered)

I'm not an expert on Expect/Continue, but this commit:
https://github.com/netty/netty/commit/52e19d5c631d9cbe6cc41b5ea34d7493160f26ee

Introduces a regression to one of our tests:

https://github.com/unfiltered/unfiltered/blob/374eaa908cff4bac51c83f68a2ba5880edbc02c0/library/src/test/scala/HeadersSpec.scala#L72

Which started failing after updating our dependency from 4.1.13 to 4.1.15.

netty used to return a 200 status code in this case, due to a "MAY" in the RFC:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3

Specifically this:

```
      - An origin server MAY omit a 100 (Continue) response if it has
        already received some or all of the request body for the
        corresponding request.
      - An origin server that sends a 100 (Continue) response MUST
        ultimately send a final status code, once the request body is
        received and processed, unless it terminates the transport
        connection prematurely.
```

Netty now returns a 100 status code even though the entire request body has been consumed by the server.

Our test suite runs the same tests against both jetty (v9.2 through to v9.4 -- it returns a 200 status code in this case) as well as netty.

Is this a regression in netty or should we adjust our tests?

Thanks!

**Comment by normanmaurer** [comment] 2017-09-01 06:36
@dschobel thoughts ? 

@omarkilani I will check in detail over the next days, sorry I am super busy atm.

**Comment by dschobel** [comment] 2017-09-01 23:36
Since the spec allows either behavior I don't think it's a regression. I defer to @normanmaurer if netty cares about behaving the same way as jetty.

**Comment by normanmaurer** [comment] 2018-04-24 13:01
I agree with @dschobel I think both are fine... Let me close this issue and please adjust your test.

**Closed by normanmaurer** 2018-04-24 13:01 UTC
