### ISSUE TITLE
Weird websocket client behaviour with pooled allocator

### ISSUE THREAD

**Issue by lexek** [netty/netty#4635] opened 2015-12-29 13:26 UTC
A few days ago I noticed that my websocket clients are being disconnected in weird way. I found that, when upgrade is complete, exception below is being thrown from HttpResponseDecoder and WebSocketClientProtocolHandler just closes connection on exception. And this happens only if i use pooled allocator for channels.

```
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:391)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1190)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1176)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:672)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:390)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
	... 12 more
```

System info
```
Linux Atplaychannel 3.5.0-17-generic #28-Ubuntu SMP Tue Oct 9 19:31:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```
Java version
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

This happens only when first websocket frame is being received in same packet as upgrade response.
Netty version is 4.0.33.Final and it looks like that previous versions don't have this issue.

Code that reproduces the issue https://gist.github.com/lexek/b61d0980f029f47b353b

**Comment by normanmaurer** [comment] 2015-12-29 13:32
@lexek will have a look

**Comment by normanmaurer** [comment] 2015-12-29 13:33
@lexek what websockets version ?

**Comment by lexek** [comment] 2015-12-29 13:37
@normanmaurer v13

**Comment by normanmaurer** [comment] 2015-12-29 18:58
@lexek so far not luck reproduce it with your code on linux and OS X :(

**Comment by lexek** [comment] 2015-12-29 19:18
@normanmaurer is channel getting closed right with first websocket frame? I had to put logging handler before websocket handler to see the exception itself, because webscocket handler closes channel silently on any exception, sorry I din't mention that. Updated gist too.

**Comment by normanmaurer** [comment] 2015-12-29 19:29
@lexek was able to reproduce it one time now. I think I know what the issue is... let me try to write a unit test and a fix.

**Comment by normanmaurer** [comment] 2016-01-04 19:38
@lexek please test https://github.com/netty/netty/pull/4651

**Comment by lexek** [comment] 2016-01-04 21:45
@normanmaurer tested and looks like it is fixed

**Comment by normanmaurer** [comment] 2016-01-04 21:47
@lexek thanks for verify!

**Comment by normanmaurer** [comment] 2016-01-05 10:09
Fixed by https://github.com/netty/netty/pull/4651

**Closed by normanmaurer** 2016-01-05 10:09 UTC
Labels: defect
