### ISSUE TITLE
JsonObjectDecoder Race Condition(s)

### ISSUE THREAD

**Issue by gtomassi** [netty/netty#3657] opened 2015-04-17 21:56 UTC
Netty version: 4.1.0.Beta1 (All I think)

Context: 
The JsonObjectDecoder started improperly grouping frames together in our pipeline when a lot of data was being quickly piped through it. Normally, it should spit out a frame at a time, but it was chunking them together and piping out multiple at once in the same stream. The number of frames was arbitrary, and it would occur at random times throughout a stream of an identical chunk of JSON data - which immediately threw up a race condition flag to me.

My Notes from 2015-04-08:
"After investigating for a while, it seems there may be some sort of race condition in the netty decoder. The way the slice is removed from the ByteBuf seems very dangerous to me and does not decouple it from other processes either later or down the pipeline - this is probably what's causing the race condition but I can't be certain. Either way, it's quick and easy for me to write my own so I'm just going to do that instead..."

Steps to reproduce:
Going to be difficult considering the nature of it, even I didn't want to try. I think it would be wiser for an experienced Nettyian to look at the "extractObject" section of the decoder first and verify that it is valid. 

Suggestion:
Here is a temporary workaround (currently used in production at https://www.sensemetrics.com/) for anyone interested in a simple decoder without the "array stream" mechanism (which I feel is sort of a bad idea anyways since it produces and ambiguous and poor implementation option that fails slowly in production):

```java
public class JsonObjectDecoder extends ByteToMessageDecoder {

	private final int maxObjectLength;
	
	private int openBracesCount = 0;
	private final ByteBuf frame = Unpooled.buffer(1024);
	
	public JsonObjectDecoder(int maxObjectLength) {
		this.maxObjectLength = maxObjectLength;
	}
	
	public JsonObjectDecoder() {
		this(1024 * 1024);
	}
	
	@Override
	protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
		
		// Process frames like a boss
		while (in.isReadable()) {
			byte next = in.readByte();
			if (next == 0x7B) { // "{"
				openBracesCount++;
			} else if (next == 0x7D) { // "}"
				openBracesCount--;
			} 
			frame.writeByte(next);
			if (openBracesCount == 0) {
				out.add(frame.toString(Charset.defaultCharset()));
				frame.clear();
			}			
		}
		
		// Check for corrupt frame
		if (frame.readableBytes() > maxObjectLength) {
			throw new TooLongFrameException("object length of " + frame.readableBytes() + " exceeds "
					+ maxObjectLength + "bytes");
		}
		
	}

}
```

**Comment by buchgr** [comment] 2015-04-18 07:51
@gtomassi 

thanks for reporting! I don't understand the reasoning on how there is a race condition. This is all happening within an `EventLoop`. Would it be possible for you to share some of the JSON data where the errors occurred? 

Regarding the array streaming, it's optional and you can disable it in the constructor. Also your "fix" doesn't work for JSON objects containing `{` or `}` in a string i.e.

```
{
   key : "{value}"
}
```

**Comment by normanmaurer** [comment] 2015-09-09 12:29
Closing for now... Please re-open with more details if still an issue

**Closed by normanmaurer** 2015-09-09 12:29 UTC

**Comment by gtomassi** [comment] 2015-09-09 17:03
@normanmaurer @buchgr 
I'm fairly sure this code is broke and you want to reopen this issue..

I took a brief look at the JsonObjectDecoder. Am I incorrect that lines 172-176 make the state of the "idx" variable used for reading indeterminable since the input buffer (in) is at an unknown writer index determined somewhere upstream in the incoming pipeline? As I said I'm not 100% clear on the workings of the netty pipeline/buffers so can't say with certainty. Maybe the issue is somewhere else, the only thing I feel sure on is that rewriting this class would be a better idea than trying to fix this code!

I have absolutely no time to look at this and rewrite it. Not sure how I can contribute, but I am more than happy to have sensemetrics pay $200/hr for anyone **experienced in Netty** to rewrite this module. If this module doesn't have any issues and someone can explain to me why it's all good and definitely has no RC's, then that person has an implicit job offer from us! 

Thanks!

**Comment by ninja-** [comment] 2015-09-09 19:22
@gtomassi regarding part about slices and idx, it's safe because ByteToMessageDecoder makes sure not to "move" the buffer IF a slice has been created. so you would need to look deeper for the problem. If your custom decoder works with the protocol and you just consider it slow it's fairly easy to optimize from this point so I can have a look tomorrow.

**Comment by gtomassi** [comment] 2015-09-09 19:55
@ninja- 
I'm sure we could dive in and figure it out but not worth the effort, the whole thing needs to be replaced. 

A few comments:
 - No I don't consider it slow, and even if I did I wouldn't really care about that. I care that it doesn't fail!
 - It would need the additional support of all possible string characters as buchgr mentioned above. 
 - It would also need the "streamArrayElements" option to be backward compatible -- although as I said above I don't really care about that mode and think it poor design and should probably be removed unless that's a common JSON practice. 
 - For backwards compatibility you also have to consider people overriding the "extractObject" if "you want to filter the json objects/arrays that get passed through the pipeline". This should be removed completely! It goes against the design of Netty -- one should just add a filter to the pipeline immediately downstream from the decoder. 

Thanks..

**Comment by buchgr** [comment] 2015-09-09 20:21
@gtomassi  

I am happy to write you the JSON decoder of your dreams and explain to you why there is no race condition in the current implementation. I am not saying there might not be a bug. My best guess would be that it could be a character encoding issue, since we are operating on bytes and the JSON Spec actually requires Unicode, with different allowed encodings i.e. UTF-8, UTF-16, ...

Feel free to contact me at bucjac@gmail.com.

**Comment by buchgr** [comment] 2015-09-10 02:15
I strongly advise against anyone working with @gtomassi on a professional basis. After talking with him for ~10 minutes over the phone about how Netty works and how the code works, I told him that I am happy to set up a contract (as he claimed in his previous comment) and provide him with support. He then immediately changed tone and told me that "I clearly don't understand how Netty works" and that "if anything he is doing me a favor to even talk to me and that I can learn from him, because he is co-founder of sensemetrics and runs large software engineering teams ...".

**Comment by humzaazam** [comment] 2017-07-31 22:52
Hi,
I'm experiencing the same issue using netty-all 4.1.5.Final, where, when multiple messages are received simultaneously or in quick succession, some or all of the json objects/frames sent will be chunked together and piped to next handler in the pipeline, instead of one at a time. The first time it happened, this was the json I received (I changed the values/properties because some of the data is sensitive):

{"string1":"value1","obj1":{"obj11":{"string2":"value2","string3":"value3","obj111":{"bool1":true,"string4":"value4","obj1111":{"string5":"value5","string6":"value6"},"string7":"value7","string8":"value8","number1":1,"number2":2}},"string9":"value9"},"number3":3}{"string1":"value2","obj1":{"string2":"value2"},"number1":1}

All the characters used, I believe, are sent in UTF_8 encoding, if that helps.

**Comment by normanmaurer** [comment] 2017-08-01 04:37
Please upgrade to latest 4.1 release and see if it still happens

**Comment by javastu** [comment] 2017-09-18 17:16
I am using the latest 4.1.15.Final and I am experiencing the same thing. I have a server process that is sending me lots of small json objects in rapid succession. I imagine that some of them are being lumped together in one TcpIP packet. Some might be split across two packets. I don't know for sure because I haven't looked that closely at what is happening.

But I do know this. If I have the JsonObjectDecoder in my pipline, My downstream reader gets about the first 9 Json objects that are sent but no more. I know that the JsonObjectDecoder is the culprit because when I remove it from the pipeline I get all bytes that are sent to me. The only thing is that they are sometimes not separated into individual Json objects. I get fragments. This leaves all the framing to me to code which is what I wanted the JsonObjectDecoder for in the first place.

Can you provide a fix. This is high priority.

**Comment by alokhan** [comment] 2018-02-09 09:13
Hi,

I have the same issue and I wonder if it is not caused by characters "[" and "]" in my Json objects.

Reading this code:

``  

> // JSON object/array detected. Accumulate bytes until all braces/brackets are closed.
>             } else if (c == '{' || c == '[') {
>                 initDecoding(c);
>                 if (state == ST_DECODING_ARRAY_STREAM) {
>                     // Discard the array bracket
>                     in.skipBytes(1);
>                 }
> }

> 

>

**Comment by johnou** [comment] 2018-02-09 10:09
@alokhan what would help is creating a unit test which demonstrates what payload fails when being decoded by JsonObjectDecoder.
