### ISSUE TITLE
ClassCastException while accessing PooledHeapByteBuf array

### ISSUE THREAD

**Issue by ppersad** [netty/netty#6133] opened 2016-12-14 21:28 UTC
### Context

After our server has been running for a few weeks, we notice that some TCP connections are broken in one direction (we can receive messages, but not send them).  From looking at the stack traces, it seems like the "memory" byte[] field of the PooledHeapByteBuf has been replaced by something else.  After this exception appears on a particular worker thread, that thread then remains broken and we cannot send any messages to channels associated with that thread.  The exceptions we get are (note that application specific portions of this stack trace have been removed or re-named in order to comply with IT security requirements):

```
15:57:33,328  WARN            TcpSender [ tcpWorkerThreadPoolExecutor-11] Failed to send message to channelId: [69551bb9] io.netty.handler.codec.EncoderException: java.lang.ArrayStoreException
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:826) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:733) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at com.example.jmx.MessageTracker.write(MessageTracker.java:19) ~[****-*.*.*.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:826) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:733) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:811) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:824) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:804) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:841) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at com.example.transport.TcpSender.sendMessage(TcpSender.java:158) [****-*.*.*.jar:?]
        <Application code which generates message to send>
Caused by: java.lang.ArrayStoreException
        at java.lang.System.arraycopy(Native Method) ~[?:1.8.0_66]
        at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:238) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1037) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1044) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.compression.JdkZlibEncoder.encode(JdkZlibEncoder.java:219) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.compression.JdkZlibEncoder.encode(JdkZlibEncoder.java:33) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        ... 64 more

15:57:47,932  WARN            TcpSender [ tcpWorkerThreadPoolExecutor-11] Failed to send message to channelId: [69551bb9] io.netty.handler.codec.EncoderException: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to [B
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:826) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:733) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at com.example.jmx.MessageTracker.write(MessageTracker.java:19) ~[****-*.*.*.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:826) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:733) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1101) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1148) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1090) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-all-4.1.5.Final.jar:4.1.5.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to [B
        at io.netty.buffer.PooledHeapByteBuf.array(PooledHeapByteBuf.java:319) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.compression.JdkZlibEncoder.deflate(JdkZlibEncoder.java:315) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.compression.JdkZlibEncoder.encode(JdkZlibEncoder.java:229) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.compression.JdkZlibEncoder.encode(JdkZlibEncoder.java:33) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        ... 23 more
```

The cause of the first exception is pretty clear from looking at the second exception.  Somehow the byte[] in the "memory" field has been replaced by a HashMap$Node.  On other broken threads I've seen ClassCastExceptions for other strange things like a AbstractQueuedSynchronizer$Node or for a anonymous Runnable instance from half way across the system (that never gets anywhere near the netty code).  I'm somewhat at a loss for how it is possible for this to happen.  My best guess at this point is that an unsafe memory copy somewhere in netty is incorrectly calculating addresses (or the GC is moving things between address calculation and performing the copy).  However this is relatively unsatisfying as an explanation given that this is a Heap buffer not a Direct buffer.

### Steps to reproduce

Unfortunately this issue only seems to be reproducible on a system which has been running for a couple weeks under load (at least that's the only time we've been able to encounter it).

### Netty version

4.1.5

### JVM version (e.g. `java -version`)

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

### OS version (e.g. `uname -a`)

CentOS release 6.7 (Final)
$ uname -a
Linux 2.6.32-573.18.1.el6.x86_64 GNU/Linux

**Comment by Scottmitch** [comment] 2016-12-14 23:17
Hum this is strange. Can you update your JDK and Netty to the latest released versions?

If this issue persists it would be nice to put a check that the memory must be of type `byte[]` or `ByteBuffer` when it is initialized [1][2] and dump the stack if not.

[1] https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBuf.java#L50
[2] https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBuf.java#L63

**Comment by ppersad** [comment] 2016-12-15 00:16
Unfortunately, due to how long a system must be running to reproduce the issue, we currently only see it with any reliability on a production server.  As a result, our ability to upgrade is limited.  We're currently trying to reproduce in a performance testing environment where we have more freedom to make arbitrary changes.  However, again due to soak time required to reproduce, I can't promise a quick answer on whether a JDK or netty 4.1.5 -> 4.1.6 upgrade fixes anything.  We're also going to experiment with the `-Dio.netty.noUnsafe=true` flag to see if that fixes the issue.

**Comment by Scottmitch** [comment] 2016-12-16 20:01
@ppersad - Can you instrument the code as I request above in the test environment (also in the prod environment if possible)? It would be helpful to know the condition which causes the unexpected type to be put into the pool.

**Comment by ppersad** [comment] 2016-12-16 22:24
@Scottmitch If we are able to reproduce the issue in our perf testing environment, then I can try with a forked version of netty that has the changes you mentioned.  Unfortunately our prod environment is too tightly controlled to allow that kind of change there.

**Comment by Scottmitch** [comment] 2016-12-16 23:16
@ppersad - I'll defer to your judgment as you are more aware of your setup but if it takes weeks to reproduce maybe its best to instrument now. When/if it does occur you will have information to report as opposed to having to wait and hope you are able to reproduce again.

Keep us posted if you get any more info!

**Comment by YuvalItzchakov** [comment] 2017-01-08 13:58
I am seeing the same exception occur in Spark Streaming with an uptime of 3 days.

The stacktrace seems similar, only I see that `PooledHeapByteBuf._setLong` is trying to can an `Object[]` to a `byte[]` and failing:

```
2017-01-08 09:31:48 ERROR TransportClient - Failed to send RPC 6931123135404301494 to /172.30.14.41:44400: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [B
io.netty.handler.codec.EncoderException: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [B
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [B
	at io.netty.buffer.PooledHeapByteBuf._setLong(PooledHeapByteBuf.java:185)
	at io.netty.buffer.AbstractByteBuf.writeLong(AbstractByteBuf.java:791)
	at org.apache.spark.network.protocol.MessageEncoder.encode(MessageEncoder.java:79)
	at org.apache.spark.network.protocol.MessageEncoder.encode(MessageEncoder.java:33)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 13 more
```

Environment details:

## Java:
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

## OS:
```
(Amazon Linux)
Linux XXX.amzn1.x86_64 #1 x86_64 x86_64 x86_64 GNU/Linux
```

## Netty:
```
io.netty % netty-all % v4.0.29.Final
io.netty % netty % 3.8.0.Final
```

**Comment by normanmaurer** [comment] 2017-01-08 14:00
@ppersad can you try upgrading java and report back if you still see it ?

**Comment by YuvalItzchakov** [comment] 2017-01-09 08:49
@normanmaurer We've updated from 8u66 to 8u112 in production, I'll update in the following days if the issue was resolved.

**Comment by normanmaurer** [comment] 2017-01-09 08:51
@YuvalItzchakov thanks! Also please let me know if there is any "easy" way for me to reproduce.

**Comment by YuvalItzchakov** [comment] 2017-01-09 08:53
@normanmaurer I'm trying to create a minimal reproduce. If anything comes up, I'll be sure to update.

**Comment by ppersad** [comment] 2017-01-09 19:47
Currently where I'm at on my side is that we've found that we cannot reproduce the issue if we set the `-Dio.netty.noUnsafe=true` flag.  Next up is to get a build to our perf testing environment without that flag, with the latest version of the JDK and with a forked version of netty containing additional logging.  I'll update again once I have more information.

**Comment by YuvalItzchakov** [comment] 2017-01-11 06:47
@normanmaurer After running for two days, the issue has reproduced. I still haven't had the time to try and work on a reproduce, so I'm just dropping this here so you'll know updating to 8u112 doesn't help.

**Comment by normanmaurer** [comment] 2017-01-11 07:00
@ppersad @YuvalItzchakov thanks a lot for the comments... I will start digging in the meantime.

**Comment by normanmaurer** [comment] 2017-01-17 08:36
@ppersad any news ?

@YuvalItzchakov can you also try using `-Dio.netty.noUnsafe=true` and see if this fixes the problem for you ?

**Comment by YuvalItzchakov** [comment] 2017-01-17 09:05
@normanmaurer I'm currently running with `-Dio.netty.noUnsafe=true` and the problem hasn't reproduced since.

**Comment by normanmaurer** [comment] 2017-01-17 09:19
@YuvalItzchakov thx! If I would provide you with a custom jar could you run with it and see if the problem still shows ? I am just trying to get a better idea where exactly I need to debug.

**Comment by YuvalItzchakov** [comment] 2017-01-17 09:40
@normanmaurer I can't really run custom JARs in production like that :) Perhaps I can enable some debug flags?

**Comment by normanmaurer** [comment] 2017-01-17 11:02
@YuvalItzchakov basically I would like you to run a build that not use PooledUnsafeHeapByteBuf and see if this fixed it. I can even push it in a branch so you can build it by yourself if this would help. WDYT ?

**Comment by YuvalItzchakov** [comment] 2017-01-17 12:48
@normanmaurer But doesn't the flag `noUnsafe` cause it *not* to use the unsafe heapbyteubf?

**Comment by normanmaurer** [comment] 2017-01-17 12:49
@YuvalItzchakov yes put also in other areas of the code-base. I would like to validate that it is only related to `PooledUnsafeHeapBytBuf`. Also another thing I would like to know is if it also happens if you use `UnpooledByteBufAllocator`.

**Comment by YuvalItzchakov** [comment] 2017-01-17 12:51
@normanmaurer The problem is that I'm not using Netty directly, but rather indirectly through Spark. Getting netty with the custom build will require to jump some hoops to get working with all the dependencies.

**Comment by normanmaurer** [comment] 2017-01-17 12:53
@YuvalItzchakov I see... what spark version is this ?

**Comment by YuvalItzchakov** [comment] 2017-01-17 12:55
2.0.1. It uses:
```
io.netty % netty-all % v4.0.29.Final
io.netty % netty % 3.8.0.Final
```

**Comment by YuvalItzchakov** [comment] 2017-01-17 12:59
@normanmaurer [`MessageEncoder`](https://github.com/apache/spark/blob/39e2bad6a866d27c3ca594d15e574a1da3ee84cc/common/network-common/src/main/java/org/apache/spark/network/protocol/MessageEncoder.java) is the class that handles writing to the underlying message.

**Comment by normanmaurer** [comment] 2017-01-17 12:59
@YuvalItzchakov thats super interesting as 4.0.29.Final does not even contain `*UnsafeHeapByteBuf`.  So the search goes on :/

**Comment by normanmaurer** [comment] 2017-01-17 14:20
@ppersad also just to double check... you are not using spark correct ?

**Comment by ppersad** [comment] 2017-01-17 15:06
@normanmaurer Correct, I am not using spark.  We are directly using netty-all 4.1.5

**Comment by normanmaurer** [comment] 2017-01-17 15:07
@ppersad thanks... Any way you could provide a reproducer ?

**Comment by ppersad** [comment] 2017-01-17 15:09
@normanmaurer Unfortunately I've got some competing priorities keeping me out of our performance environment at the moment.  Dedicating time to reproducing is planned, however I'm not sure when I'll get the chance to do it.

**Comment by normanmaurer** [comment] 2017-01-17 15:11
@ppersad I see... just not sure how to continue here without a reproducer :(

**Comment by normanmaurer** [comment] 2018-11-09 19:10
I will close this as we did not receive any reports like this for a long time, so I assume we fixed it.

**Closed by normanmaurer** 2018-11-09 19:10 UTC
