### ISSUE TITLE
 HttpPostRequestDecoder boundary split bug

### ISSUE THREAD

**Issue by semoro** [netty/netty#3416] opened 2015-02-10 20:23 UTC
Netty  4.1.0.Beta3
When i trying to send multipart forms by Qt to Netty

I found that this bug is based on wrong use of StringUtil.split

String[] boundary = StringUtil.split(headerContentType[mrank], '=');
            if (boundary.length != 2) {
                throw new ErrorDataDecoderException("Needs a boundary value");
            }

Here a check for count of split result not equal to 2
but, when qt sends boundary
For example 
multipart/form-data; boundary="boundary_.oOo._MTM2Mjc3NzU1OQ==MTYyMDIwNDkzMA==NTAyNTc2MTI0" 

it splits up to 6 elements, and i think that it wrong, or may be more strict protocol in netty?

**Comment by keteracel** [comment] 2015-02-19 01:37
This is a dupe of https://github.com/netty/netty/issues/3004 and has already been addressed in https://github.com/netty/netty/commit/d6e7997f8dfd0a9b7dfa7c2b9ab0bdbf17e46712

**Closed** 2015-02-19 05:28 UTC

**Comment by fredericBregier** [comment] 2015-02-19 09:27
@semoro I confirm this should be fixed already. It is already in the 4.1.0 repository (but not release yet since the 4.1.0 Beta 4 is not already out).
Could you check ?

**Comment by semoro** [comment] 2015-02-21 19:55
I had updated to 4.1.0 Beta 4, Now all works fine) Thank you!

**Comment by fredericBregier** [comment] 2015-02-21 19:58
Thanks to report this works now !
