### ISSUE TITLE
Netty 4.0.38 with openssl causes application hang

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#5487] opened 2016-07-01 21:05 UTC
Netty 4.0.38 with openssl causes application hang. If i revert commit https://github.com/netty/netty/commit/8ed9953f361639d910141b4a839cb4c07c0bed68 then it works again.

**Comment by Scottmitch** [comment] 2016-07-02 01:28
@floragunncom - What version of tcnative? Can you provide a reproducer? If not can you provide some debug information like a few jstack captures while in this condition? Is an EventLoop thread spinning or is it dead locked? If the thread is spinning can you describe the state of variables, and provide other useful information?

Maybe add some debug statements would be useful too (maybe not safe in a production critical scenario):

```java
if (pendingNetResult.getStatus() != OK) {
  logger.info("Result NOT OK! {}", pendingNetResult);
  return pendingNetResult;
}
logger.info("Result OK bytesProduced{} {}", bytesProduced, pendingNetResult);
bytesProduced = pendingNetResult.bytesProduced();
```

**Comment by floragunncom** [comment] 2016-07-02 10:03
tcnative is 1.1.33.Fork18 (all other are not compatible with netty 4.0.38 IMHO). Logs are here: https://gist.github.com/floragunncom/3e3d7adede4737d5fc15672b16290a4a
The code which produced this logs is here: https://gist.github.com/floragunncom/f1844eb46d49a90e1eaca12a795dc7fb

**Comment by johnou** [comment] 2016-07-04 08:24
@floragunncom I don't see any thread dumps in your logs?

**Comment by floragunncom** [comment] 2016-07-04 09:35
dumps are here https://github.com/floragunncom/files/tree/jstacks-netty

**Comment by johnou** [comment] 2016-07-04 10:40
@floragunncom just to confirm the application which is hanging is an openssl client, not server?

**Comment by floragunncom** [comment] 2016-07-04 12:46
Not sure what you mean. The application has a server and a client side and therefore uses:
* ``SslContextBuilder.forServer(...)`` and
* ``SslContextBuilder.forClient()``

**Comment by johnou** [comment] 2016-07-04 14:25
The thread dumps you provided have the org.jboss.netty package.. which would indicate Netty 3.x?

**Comment by floragunncom** [comment] 2016-07-04 14:37
yes, i use netty3 code, but the SSLEngine is created with netty4:

```
SSLEngine engine = createNetty4SSLEngine(...); # netty4
SslHandler sslHandler = new SslHandler(engine); # SSLHandler is netty3
ctx.getPipeline().replace(this, "ssl_client", sslHandler); # netty3
```

*(Pls. dont ask why. Cannot change completely to netty4 yet)*

With netty 3.10.5 and netty 4.0.37/Fork17 it works like a charm!

**Comment by johnou** [comment] 2016-07-04 14:45
@Scottmitch I'll leave this one to you!

**Comment by Scottmitch** [comment] 2016-07-05 18:09
@floragunncom - Thanks for providing the additional info! Unfortunately using Netty 3 and Netty 4 together in this way is not a supported use case. Netty 3 has been [EOL](http://netty.io/news/2016/06/29/3-10-6-Final.html) and it is difficult to determine if this issue is due to a Netty 3 bug (perhaps SslHander) or is in Netty 4. The change set you reverted from Netty 4 (8ed9953) is relatively isolated and seems correct (let me know if you disagree). Please let me know once you are able to completely upgrade to Netty 4 if this issue still persists and I can dig in more.

**Comment by normanmaurer** [comment] 2017-02-28 14:03
Let me close this. Please reopen if you see the same problem using netty 4.x only

**Closed by normanmaurer** 2017-02-28 14:03 UTC
