### ISSUE TITLE
HTTP/2 Http2MultiplexCodec/Http2FrameCodec push promise support

### ISSUE THREAD

**Issue by cy6erGn0m** [netty/netty#7603] opened 2018-01-22 13:20 UTC
Currently it looks like there is no way to start a new stream via push promise. So for now I do the following:

```kotlin
        // reserve outgoing stream id
        val promisedStreamId = connection.local().incrementAndGetNextStreamId()

        // create a new channel and context (with strean id = -1)
        val bs = Http2StreamChannelBootstrap(channel.parent()).handler(this)
        val child = bs.open().get() 

        // HACK: set stream.id to promisedStreamId via reflection!
        child.setId(promisedStreamId)

        val promise = rootContext.newPromise()
        // write push promise frame to the origin stream
        codec.encoder().writePushPromise(rootContext, streamId, 
                                    promisedStreamId, headers, 0, promise)

        if (promise.isSuccess) {
            startHttp2(child.pipeline().firstContext(), headers)
        } else {
            promise.addListener { t ->
                t.get()
                startHttp2(child.pipeline().firstContext(), headers)
            }
        }
```

**Comment by normanmaurer** [comment] 2018-01-27 08:02
Will have a look....

**Comment by normanmaurer** [comment] 2018-01-29 13:10
@cy6erGn0m I wonder if you have a good solution in mind in terms of API... Maybe we should add a method to `HttpStreamChannel` that allows to create a new `HttpStreamChannel` by sending a `PUSH_PROMISE` with is "tied" to the `HttpStreamChannel` itself. For the `HttpFrameCodec` it should be not too hard to do as we just need to expose a new Frame type and allow to write it.

also @ejona86 @trustin @Scottmitch @carl-mastrangelo ....

**Comment by normanmaurer** [comment] 2018-01-29 13:11
Another thing we could do is change `Http2StreamChannelBootstrap ` to detect if the `Channel` that is used to construct is of type `Http2StreamChannel` and if so write a `PUSH_PROMISE` when calling `open(...)`.

**Comment by ejona86** [comment] 2018-01-31 14:35
This seems like a duplicate of #4527.

**Comment by normanmaurer** [comment] 2018-01-31 14:36
You are right @ejona86 let me close this one.

**Closed by normanmaurer** 2018-01-31 14:36 UTC
Labels: feature
