### ISSUE TITLE
io.netty.channel.epoll.Native.epollWait0 high cpu usage

### ISSUE THREAD

**Issue by FurmigaHumana** [netty/netty#5896] opened 2016-10-06 10:18 UTC
I'm experiencing very high cpu load while using the native transport, the epollWait method is taking as much cpu as a while (true) { } loop

This is not much of an issue if you only have one netty server in the box, but while running multiple instances the cpu load can go as high as 100.0 while without using native transport it never reaches 10.0

Thread dump with native transport:
`
"Netty IO Thread #0" - Thread t@41
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:117)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:231)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
	- None
`

Profiler with native transport, 100% cpu time (just like an infinite loop, which increases cpu usage, this is just with 1 connection)
![image](https://cloud.githubusercontent.com/assets/1264257/19148445/1dac6c54-8b93-11e6-85c0-a9c3a9076dca.png)

--
## Server specs
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
CentOS Linux release 7.2.1511 (Core)
Netty 4.1.5.final
CPU Xeon 1245v2 4/8c

Now the profiler without native transport, notice there's basically no cpu time with 1 connection
![image](https://cloud.githubusercontent.com/assets/1264257/19148734/735a4a58-8b94-11e6-86a5-d32d5dec2e46.png)

Thread dump without native transport
"Netty IO Thread #0" - Thread t@46
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(Unknown Source)
	at sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	- locked <111a62cd> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <5846f671> (a java.util.Collections$UnmodifiableSet)
	- locked <6480e209> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:731)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
	- None

This can be reproduced with the message test server on my linux box, just send something like 10 messages per second, 5 bytes each message.

**Comment by Scottmitch** [comment] 2016-10-06 20:53
@normanmaurer - wasn't there an issue reported that may be a duplicate of this? IIRC the tools aren't able to detect the CPU yield in native code or something like this?

**Comment by FurmigaHumana** [comment] 2016-10-06 21:04
@Scottmitch yes, very old one and currently closed, but there was a jdk bug with the sun.nio.ch.EPollArrayWrapper.epollWait, the issue here is with io.netty.channel.epoll.Native.epollWait, dont know if they are the same tho.

#327 here

**Comment by normanmaurer** [comment] 2016-10-10 06:09
@FurmigaHumana what does `top` show ? Is it really using so much cpu or is it just the `profiler` ? Profilers often miss-intepret native code, which may happen here.

**Comment by FurmigaHumana** [comment] 2016-10-10 15:58
@normanmaurer I couldn't test on my busy boxes for obvious reasons, but I tested on some with around 30 connections each.

I collected this data by watching the top output for about 5 minutes.

This is with **epoll disabled** cpu usage goes all the way down to 7% and maximum of 27% with 35 connections, print represent the most average value.
![image](https://cloud.githubusercontent.com/assets/1264257/19241751/78ec624e-8ee6-11e6-9dd0-44f263452ef4.png)

This is with **epoll enabled** minimum cpu usage i noticed was 35% and maximum 96% with 32 connections. it stays around 50-70 most of the time but it vary a lot and its not stable as the other one.
![image](https://cloud.githubusercontent.com/assets/1264257/19241864/f60bc97c-8ee6-11e6-9db4-108758fc46f0.png)

With epoll disabled I can handle 2500 connections, a few drops due to gc but nothing serious, latency could be better but its all in the acceptable zone.

With epoll enabled I can barely handle 500 connections, drops start due to cpu overload. with 300 connections the latency is much better and better throughput but at this point cpu load is already at 100%

**Comment by FurmigaHumana** [comment] 2016-10-10 16:00
By the way... if any issue confirmed, i'm available for testing :)

**Comment by normanmaurer** [comment] 2016-10-10 17:19
@FurmigaHumana can you share a reproducer ? Also what linux dist and what kernel version ? 
Also even 2500 connections sounds super low.

**Comment by Scottmitch** [comment] 2016-10-11 01:42
+1 .. reproducer would be very helpful

**Comment by FurmigaHumana** [comment] 2016-10-13 16:35
I am leaving this ticket as the issue is not as big as I first diagnosticated. I left epoll running for 24 hours and then I disabled it for another 24 hours, this is the cpu graphic.

![image](https://cloud.githubusercontent.com/assets/1264257/19357566/9f8e68de-9148-11e6-8c62-b95cfa2c0ad9.png)

The first curve shows a little higher cpu usage with epoll enabled, but it also has higher throughput and less latency which might be the reason.. maybe it just runs faster so it consumes more resources.

I tried to create a reproducer but a single computer can't caused enough trouble to the server.

@normanmaurer 2500 connections is just the amount i currently have, i dont know if it can handle more, thats just the amount of clients I have today.

**Comment by Scottmitch** [comment] 2016-10-13 16:39
> but it also has higher throughput and less latency which might be the reason.. maybe it just runs faster so it consumes more resources.

Before you indicated that the concurrent connection count was much lower. Do you still have issues with lower concurrent connection count? Was the throughput/latency also lower before or did something change?

**Comment by FurmigaHumana** [comment] 2016-10-16 21:27
@Scottmitch thats probably because I ran out of cpu faster so I cant handle as many connections.

--

I did a lot of testing in the last days and I found my peace with netty 4.0.40 with epoll for external connections and nio for local (same network, not same machine), something feels very wrong with epoll, specially with netty 4.1.5 which gives me around 25ms of latecy with local connections versus 1ms of 4.0.40, I set back to 4.0.40 and disabled epoll and things feel to run much better, no weird cpu spikes, no weird connection drops, just nice and smooth.

For illustration.. this is the connection count with netty 4.1.5
![image](https://cloud.githubusercontent.com/assets/1264257/19420942/ff2793f4-93d4-11e6-9055-d46bfa3f5622.png)

And here with 4.0.40
![image](https://cloud.githubusercontent.com/assets/1264257/19420944/10f20aba-93d5-11e6-98be-3550ddb6e3da.png)

But, Sadly I have not managed to track down the source of the issues much less its causes and I dont want to lose members because of instability, as things are good with 4.0.40 I will keep with that for the time being.

Thank you for the help and I am sorry if I wasted everyone's time :(

**Closed** 2016-10-16 21:28 UTC

**Comment by UmarJarushi** [comment] 2019-07-17 13:08
> @Scottmitch thats probably because I ran out of cpu faster so I cant handle as many connections.
> 
> I did a lot of testing in the last days and I found my peace with netty 4.0.40 with epoll for external connections and nio for local (same network, not same machine), something feels very wrong with epoll, specially with netty 4.1.5 which gives me around 25ms of latecy with local connections versus 1ms of 4.0.40, I set back to 4.0.40 and disabled epoll and things feel to run much better, no weird cpu spikes, no weird connection drops, just nice and smooth.
> 
> For illustration.. this is the connection count with netty 4.1.5
> ![image](https://cloud.githubusercontent.com/assets/1264257/19420942/ff2793f4-93d4-11e6-9055-d46bfa3f5622.png)
> 
> And here with 4.0.40, both on a friday and 24 hours period
> ![image](https://cloud.githubusercontent.com/assets/1264257/19420944/10f20aba-93d5-11e6-98be-3550ddb6e3da.png)
> 
> But, Sadly I have not managed to track down the source of the issues much less its causes and I dont want to lose members because of instability, as things are good with 4.0.40 I will keep with that for the time being.
> 
> Thank you for the help and I am sorry if I wasted everyone's time :(

hi @FurmigaHumana ,
We are facing the same issue of high CPU with Netty version 4.1.31.Final
Do you know if there exists a higher netty version since 4.0.40 that does not have this issue ? 
thanks,

**Comment by normanmaurer** [comment] 2019-07-17 13:20
@FurmigaHumana that is very strange.. please open a new issue with more details (after upgrading to latest 4.1.x version)

**Comment by UmarJarushi** [comment] 2019-07-17 14:41
@normanmaurer have you treated this issue in one of the latest minor versions [4.1.32.Final - 4.1.37.Final] ?

**Comment by FurmigaHumana** [comment] 2019-07-17 16:25
This thread is very old, I've been keeping my netty version updated ever since but never managed to save some resources, so I accepted it is a cpu intensive thing and adapted my budged to fit it.

Netty handling only connections eats more cpu than the entire logic of the software which is kind of a little game so nothing cheap to run.. but still.

Some time ago I changed most of my netty dependant code for a in-house built one based on AIO.2, saved me a whopping 80% on cpu usage keeping the exact same functionality we needed.

**Comment by normanmaurer** [comment] 2019-07-17 17:00
@FurmigaHumana this does not sound right... there must be something wrong with either how you use Netty or something else. Please also note that have something shown up as used CPU may be misleading as many profilers get confused when something is waiting in native code (as epollWait0(...)) does.

You may need to profile with async-profiler or something similar.
