### ISSUE TITLE
BouncyCastle ALPN seems to break native image builds

### ISSUE THREAD

**Issue by pmlopes** [netty/netty#11369] opened 2021-06-07 07:30 UTC
See: https://github.com/eclipse-vertx/vert.x/issues/3960

Apparently the newly added feature: https://github.com/netty/netty/commit/56ef371676ed48262a46ce827d5462cd6f218a6d

Introduced support to BC, however, it relies on reflection to detect the presence of BC. This will fail native image builds. My assumption is that extra graalvm metadata should be added to ensure that the class is explicitly allowed and not discarded during the dead code removal phase.

**Comment by normanmaurer** [comment] 2021-06-07 13:15
I would be happy to review a PR... I don'T have a lot of knowledge with Graal. Not sure if @chrisvest can help

**Comment by pmlopes** [comment] 2021-06-07 17:50
This one is a tricky (at least for me), if you just go wild and "make it compile" you may end up removing important classes out of the analysis that could compromise the overall security of BC. :man_shrugging:

**Comment by normanmaurer** [comment] 2021-09-02 18:41
@pmlopes I wonder why we don't have the problem with conscrypt where we also use reflection for that.... Any idea ? I am far from being a Graal guru :)

**Comment by martin-g** [comment] 2021-09-03 07:05
You need to whitelist the classes (+ methods) which use reflection [here](https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/transport/src/main/resources/META-INF/native-image/io.netty/transport/reflection-config.json) or similar file if it is for another Maven module.

**Comment by perezd** [comment] 2021-09-03 16:36
workaround, if I add io.netty.handler.ssl.BouncyCastleAlpnSslUtils to the --initialize-at-run-time flag, this goes away.

I'm not sure if that's actually better for end users, or if they should use reflect-config approach.

**Comment by linghengqian** [comment] 2022-11-03 04:22
- Considering that the 4.1 branch already has quite a few submodules actively maintaining GraalVM reachability metadata, what should we do for this issue?

**Comment by normanmaurer** [comment] 2022-11-03 07:35
@gradinac any idea ?

**Comment by gradinac** [comment] 2022-11-04 19:14
I can take a look into this :)
@linghengqian, do you by any chance have a minimal example where BouncyCastle ALPN breaks an image build but works on Java? If yes, that would greatly help trying this out and seeing where the problem is

**Comment by linghengqian** [comment] 2022-11-14 13:12
> I can take a look into this :)
> @linghengqian, do you by any chance have a minimal example where BouncyCastle ALPN breaks an image build but works on Java? If yes, that would greatly help trying this out and seeing where the problem is

- Sorry for the late reply, as I have been plagued by some issues that are happening on my device for a long time.  

- I can't seem to build a simple unit test to get the GraalVM Trace Agent to capture the GraalVM reachability metadata that is needed.  I'm trying to capture GraalVM reachability metadata for the vertx component covered by this issue.

**Comment by panlw** [comment] 2022-11-20 02:13
My solution is:

```properties
# src/main/resources/META-INF/native-image/io.netty/netty-handler/native-image.properties
Args = --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils
```

> https://www.graalvm.org/22.0/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file

**Comment by linghengqian** [comment] 2022-11-20 04:52
@panlw Hi, can you build a unit test for netty or vertx ? I can verify the runtime reflection problem directly here.

**Comment by linghengqian** [comment] 2022-11-20 19:00
- I saw this issue while preparing a PR for https://github.com/oracle/graalvm-reachability-metadata/issues/117 . I tweaked `user-code-filter.json` unexpectedly can not solve this problem.
- ![image](https://user-images.githubusercontent.com/20187731/202919438-55df149c-22e0-4645-9899-561377d5e6ab.png)
- The unit tests for vertx-core are too big, and I am still thinking about how to build the smallest reproducible unit tests.

**Comment by linghengqian** [comment] 2022-11-20 20:42
- For non-public internal classes, I really don't know how to make unit tests outside. I will try to submit a PR for netty to supplement the unit tests of BouncyCastleAlpnSslUtils.🫠

**Comment by linghengqian** [comment] 2022-11-20 20:58
- For non-public internal classes, I really don't know how to make unit tests outside. 
- But I noticed an even weirder problem. 
- `io.netty.handler.ssl.BouncyCastleAlpnSslUtils` is only used by `io.netty.handler.ssl.BouncyCastleAlpnSslEngine`. 
- `io.netty.handler.ssl.BouncyCastleAlpnSslEngine` is only used by `io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator`.
- `io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator` is deprecated.
- @chrisvest Is there any issue pointing out why this class is deprecated? Can we just remove these three classes?

**Comment by linghengqian** [comment] 2022-11-21 10:03
- @pmlopes When I turned on central repository support for GraalVM reachability metadata, `./gradlew -Pagent nativeTest` worked fine. This means that the metadata has reached the central warehouse. 
- @normanmaurer  Shouldn't this issue be marked as resolved? **And closed?**
```groovy
plugins {
    id 'org.graalvm.buildtools.native' version '0.9.17'
}
graalvmNative {
        metadataRepository {
            enabled = true
            version = "0.2.5"
        }
    }
}
```
- ![image](https://user-images.githubusercontent.com/20187731/203022167-3600a591-0093-432f-ba12-e2c72141c8e7.png)

**Comment by chrisvest** [comment] 2022-11-28 23:53
> Is there any issue pointing out why this class is deprecated? Can we just remove these three classes?

@linghengqian, the class is deprecated to steer people toward using `ApplicationProtocolConfig`. We can't remove them because they are public API in 4.1.

**Comment by chrisvest** [comment] 2022-11-28 23:57
@pmlopes @panlw Ling says recent versions of Netty include correct Graal metadata so this should just work (which matches my expectation from @gradinac's recent work in that area) – can you confirm?

**Comment by pmlopes** [comment] 2022-11-29 12:02
@chrisvest I believe we can close this issue, I've updated vert.x how to the latest versions (netty, vertx and graal):

https://github.com/vertx-howtos/graal-native-image-howto/commit/21b898f9069f7c38222b9ed2a917cb65eabfbd8a

And the build works fine!

**Closed** 2022-11-29 16:54 UTC

**Comment by panlw** [comment] 2022-12-02 03:11
> My solution is:
> 
> ```ini
> # src/main/resources/META-INF/native-image/io.netty/netty-handler/native-image.properties
> Args = --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils
> ```
> 
> > https://www.graalvm.org/22.0/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file

Upgrade Spring Boot from 2.7.5 to 3.0 GA, then everything is OK :-)
