### ISSUE TITLE
netty-all-4.0.21.Final Error while read(...): Connection reset by peer

### ISSUE THREAD

**Issue by KBCode** [netty/netty#6630] opened 2017-04-17 03:05 UTC
### Expected behavior
service throw exception
09:55:29.907 [epollEventLoopGroup-5-3] INFO com.*.**.PrintServerHandler - 719724627--/49.66.21.64:15264==>open
09:56:41.584 [epollEventLoopGroup-5-3] ERROR com.*.**.PrintServerHandler - /49.66.21.64:15264
java.io.IOException: Error while read(...): Connection reset by peer
	at io.netty.channel.epoll.Native.readAddress(Native Method) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:523) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:562) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
### Actual behavior
    When a client has connected ,send to service Heartbeat Message, service receive the message.
### Netty version
4.0.21.Final
EventLoopGroup use EpollServerSocketChannel
### JVM version (e.g. `java -version`)
JDK 1.8.66
### OS version (e.g. `uname -a`)
CentOS release 6.5 (Final)  2.6.32-431.23.3.el6.x86_64

**Comment by maseev** [comment] 2017-04-17 11:17
An exception like this `java.io.IOException: Connection reset by peer` means that a client closed the connection abruptly. 
Very often it means that the server sent something to the client which caused the client to close the connection (a message protocol error, for example). 

It would be great to have some code that reproduces this problem. You can also try to upgrade to the latest stable version of Netty (`4.1.9.Final`, if I'm not mistaken) and try to reproduce this problem again. Just to make sure it hasn't been fixed already (if it was really a bug in Netty).

**Comment by KBCode** [comment] 2017-04-18 11:43
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: No route to host
at io.netty.channel.unix.Errors.newIOException(Errors.java:117) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.channel.unix.Errors.ioResult(Errors.java:138) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:175) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:268) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1007) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.1.9.Final.jar:4.1.9.Final]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by maseev** [comment] 2017-04-18 12:23
I might be wrong, but are you sure that your client is able to parse the message which your server is trying to send? It looks like you lose your connection in the middle of the protocol interaction. It also looks like you decided to use Unix sockets instead.

Is it possible to get a minimal reproducer for your problem? Or at least can you provide some information about the server and the client? From your description, it looks like that the server sends a heartbeat message when the client connects, right? 

Is there anything else we should know about this protocol implementation?
Does the server send the heartbeat message only once or it sends it on schedule? Can you describe what your application is supposed to do?

**Comment by KBCode** [comment] 2017-04-18 12:38
of course, client is able to parse the message. 
 when the client connects the server, sends a heartbeat message to server,  when  the server read the message throw exception. but Not necessarily appear.

**Comment by maseev** [comment] 2017-04-18 14:46
Here, have a look:

Server:
```java
package io.github.maseev.echo;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.epoll.EpollEventLoopGroup;
import io.netty.channel.epoll.EpollServerSocketChannel;
import io.netty.channel.socket.SocketChannel;
import io.netty.handler.codec.FixedLengthFrameDecoder;

public class Server {

  public static void main(String[] args) throws Exception {
    final int FRAME_LENGTH = 2;
    final int PORT = Integer.parseInt(System.getProperty("port", "8080"));
    final int workerThreads = Integer.parseInt(System.getProperty("workers", "1"));

    final EventLoopGroup bossGroup = new EpollEventLoopGroup(1);
    final EventLoopGroup workerGroup = new EpollEventLoopGroup(workerThreads);
    try {
      ServerBootstrap b = new ServerBootstrap();

      b.group(bossGroup, workerGroup)
        .channel(EpollServerSocketChannel.class)
        .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
        .childOption(ChannelOption.TCP_NODELAY, true)
        .childHandler(new ChannelInitializer<SocketChannel>() {
          @Override
          public void initChannel(SocketChannel ch) throws Exception {
            ch.pipeline().addLast(
              new FixedLengthFrameDecoder(FRAME_LENGTH),
              new MessageHandler());
          }
        });

      ChannelFuture f = b.bind(PORT).sync();

      f.channel().closeFuture().sync();
    } finally {
      bossGroup.shutdownGracefully();
      workerGroup.shutdownGracefully();
    }
  }
}

class MessageHandler extends ChannelInboundHandlerAdapter {

  @Override
  public void channelActive(ChannelHandlerContext ctx) throws Exception {
    System.out.println("Client connected");
  }

  @Override
  public void channelInactive(ChannelHandlerContext ctx) throws Exception {
    System.out.println("Client disconnected");
  }

  @Override
  public void channelRead(ChannelHandlerContext ctx, Object obj) throws Exception {
    final ByteBuf msg = (ByteBuf) obj;
    try {
      final short year = msg.readShort();

      System.out.println("year: " + year);
    } finally {
      msg.release();
    }
  }

  @Override
  public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
    cause.printStackTrace();
    ctx.close();
  }
}
```

Client:
```java
package io.github.maseev.echo;

import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;

public class Client {

  public static void main(String[] args) throws InterruptedException {
    final int FRAME_LENGTH = 2;
    final String HOST = System.getProperty("host", "127.0.0.1");
    final int PORT = Integer.parseInt(System.getProperty("port", "8080"));
    EventLoopGroup group = new NioEventLoopGroup();

    try {
      Bootstrap b = new Bootstrap();
      b.group(group)
        .channel(NioSocketChannel.class)
        .option(ChannelOption.TCP_NODELAY, true)
        .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
        .handler(new ChannelInitializer<SocketChannel>() {
          @Override
          public void initChannel(SocketChannel ch) throws Exception {
            ch.pipeline().addLast(new ClientHandler(FRAME_LENGTH));
          }
        });

      ChannelFuture f = b.connect(HOST, PORT).sync();
      f.channel().closeFuture().sync();
    } finally {
      group.shutdownGracefully();
    }
  }
}

class ClientHandler extends ChannelInboundHandlerAdapter {

  private final int frameLength;

  public ClientHandler(int frameLength) {
    this.frameLength = frameLength;
  }

  @Override
  public void channelActive(ChannelHandlerContext ctx) throws Exception {
    System.out.println("Client has successfully connected to the server");
    final ByteBuf msg = ctx.alloc().directBuffer(frameLength, frameLength);

    msg.writeShort(2017);

    ctx.writeAndFlush(msg, ctx.voidPromise());
  }

  @Override
  public void channelInactive(ChannelHandlerContext ctx) throws Exception {
    System.out.println("Closed the connection");
    super.channelInactive(ctx);
  }

  @Override
  public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
    cause.printStackTrace();
    ctx.close();
  }
}
```

So, when the client sends a message when it connects to the server. The server reads the message and prints it out. This is pretty much what your application is doing (at least that's what your description tells us).

**Comment by KBCode** [comment] 2017-04-19 01:07
Thank you so much for your assistance.
Because the program is a problem in the production environment, the situation is somewhat complicated, I carefully analyze.

**Comment by maseev** [comment] 2017-04-19 06:57
It's very hard to say what went wrong. Server code looks OK to me. I would check any logs on the client side, just in case.

**Comment by maseev** [comment] 2017-04-21 11:15
@KBCode any news?

**Comment by Scottmitch** [comment] 2017-04-27 03:12
Please update to the latest version of Netty (a lot of bugs have been fixed in the EPOLL transport). If the issue still persists please re-open and provide a complete/minimal reproducer.

**Closed by Scottmitch** 2017-04-27 03:12 UTC

**Comment by johnou** [comment] 2017-04-27 08:26
@maseev your case might be related to https://github.com/netty/netty/issues/6419
