### ISSUE TITLE
about InternalLogger test case problems.

### ISSUE THREAD

**Issue by takeseem** [netty/netty#7192] opened 2017-09-07 12:52 UTC
## InternalLoggerFactoryTest - I think these test cases is invalid, it can not really test effective.

* [@Before InternalLoggerFactoryTest.init()](https://github.com/netty/netty/blob/4.1/common/src/test/java/io/netty/util/internal/logging/InternalLoggerFactoryTest.java#L33) **the "mock" InternalLogger always the same mockLogger instance.**
```
    @Before
    public void init() {
        oldLoggerFactory = InternalLoggerFactory.getDefaultFactory();

        final InternalLoggerFactory mockFactory = mock(InternalLoggerFactory.class);
        mockLogger = mock(InternalLogger.class);
        when(mockFactory.newInstance("mock")).thenReturn(mockLogger);  //<=== the "mock" InternalLogger always the same mockLogger instance.
        InternalLoggerFactory.setDefaultFactory(mockFactory);
    }
```
* so in any test case the **logger** must be === "mockLogger", so test any the method of them must be same effective, becasue of **logger** and "mockLogger" is the same instance. e.g. [InternalLoggerFactoryTest.testIsTraceEnabled()](https://github.com/netty/netty/blob/4.1/common/src/test/java/io/netty/util/internal/logging/InternalLoggerFactoryTest.java#L68)
```
    @Test
    public void testIsTraceEnabled() {
        when(mockLogger.isTraceEnabled()).thenReturn(true);

        InternalLogger logger = InternalLoggerFactory.getInstance("mock");
        assertTrue(logger.isTraceEnabled());
        verify(mockLogger).isTraceEnabled();
    }
```
## InternalLogger's junit I think it's must be depend Level
* we know any isXX or log method in the Logger, It must be depend logger's Level. so I think the test must be setLevel then test the isXX or log method, not for a mock(isTraceEnable())=true then test trace(msg).
* Because not all Logger implements are first to determine isTraceEnable(), may be called other methods, such as logger4j2's AbstractLogger.trace(String), it is direct determine the logger's leve with Level.TRACE
```
    @Override
    public void trace(final String message) {
        logIfEnabled(FQCN, Level.TRACE, null, message, (Throwable) null);
    }
```

**Comment by normanmaurer** [comment] 2018-04-12 19:33
@takeseem can you provide a pr ? I am not sure what exactly the problem is

**Comment by normanmaurer** [comment] 2018-05-18 20:26
Let me close this ... please re-open with more infos if you think there is an issue

**Closed by normanmaurer** 2018-05-18 20:26 UTC
