### ISSUE TITLE
netty 4.0.37 causes hangs in Apache Cassandra

### ISSUE THREAD

**Issue by JeremiahDJordan** [netty/netty#5486] opened 2016-07-01 19:12 UTC
Ever since we updated Apache Cassandra to using netty 4.0.37 from netty 4.0.36 we have been seeing random hangs on our OSS test suite where a response from the server to the client seemingly is getting lost or something (the client just hangs) until the test times out.  With the OSS test suite it only happens sometimes, it isn't super easy to reproduce (right now I can only reproduce it using a 1.5 hour test suite we have for DataStax Enterprise) but I bisected it to f984870ccca133d6056e8b0df0b2352f8f90b0fe.  I then reverted f984870ccca133d6056e8b0df0b2352f8f90b0fe from 4.0.37 and I can run my tests with 4.0.37+f984870ccca133d6056e8b0df0b2352f8f90b0fe reverted and everything seems good.

**Comment by normanmaurer** [comment] 2016-07-01 19:24
Hmm ... Can you also try 4.0.38.Final?

Also is it using nio or epoll? Can I run the testsuite locally somehow?

**Comment by JeremiahDJordan** [comment] 2016-07-01 19:26
I tried 4.0.38.Final and it still has the problem.  I tried both nio and epoll show the problem.

**Comment by JeremiahDJordan** [comment] 2016-07-01 19:30
Sadly you can't run the "reliably fails" test suit locally.  The straight cassandra-testall tests show it sometimes.  These runs of our OSS all hung:
http://cassci.datastax.com/job/trunk_testall/975/
http://cassci.datastax.com/job/trunk_testall/982/
http://cassci.datastax.com/job/trunk_testall/985/

@jkni may have something that you can use to reproduce it, he is checking right now if the hang he is seeing is fixed by going back to 4.0.36 as I type.

**Comment by tjake** [comment] 2016-07-01 19:32
Looking at that patch....  Is the issue handlerState isn't volatile?

**Comment by JeremiahDJordan** [comment] 2016-07-01 19:37
Good idea @tjake I'll try that and see if it does the trick.

**Comment by normanmaurer** [comment] 2016-07-01 19:41
@tjake @JeremiahDJordan as far as I remember this is only ever accessed / modified from the same thread. Do I miss something ?

**Comment by normanmaurer** [comment] 2016-07-01 19:57
@JeremiahDJordan also do you modify the pipeline from outside the EventLoop at all ?

**Comment by tjake** [comment] 2016-07-01 19:58
Not the pipeline but the ChannelHandlerContext can be called from outside the event loop I think.

**Comment by normanmaurer** [comment] 2016-07-01 20:00
@tjake ok... can you tell me why you think the handlerState should be volatile ?

**Comment by tjake** [comment] 2016-07-01 20:23
I'm not sure tbh. Just looked like a racy condition.

**Comment by JeremiahDJordan** [comment] 2016-07-01 20:25
4.0.38 with that changed to volatile still has the problem, so that isn't it.

**Comment by tjake** [comment] 2016-07-01 20:35
@normanmaurer 

If the pipeline isn't called from inside the eventloop you hit this

https://github.com/netty/netty/commit/f984870ccca133d6056e8b0df0b2352f8f90b0fe#diff-6b8633f415085302023f47004357891aR192

That calls callHandlerAdded0() from a random thread which calls ctx.setAdded()

**Comment by tjake** [comment] 2016-07-01 20:41
Also the fact that that section used to waitOnFuture and now it doesn't is different.

**Comment by tjake** [comment] 2016-07-01 20:47
Also, callHandlerAdded0 is no longer being called under a synchronized block in that scenario whereas before it was calling synchronized (DefaultChannelPipeline.this) in the Runnable

**Comment by jkni** [comment] 2016-07-01 20:56
At the moment, we think we're seeing this fairly regularly on [cassandra-dtest](https://github.com/riptano/cassandra-dtest) runs against [trunk](http://cassci.datastax.com/job/trunk_dtest), which is running 4.0.37. The same dtests do not reproduce against 4.0.36 (yet). It's a little bit tedious, but it might give you an option to reproduce.

Any test from this [run](http://cassci.datastax.com/job/trunk_dtest/1295/) with a "Timed out creating connection" error is an option. 

On my local Linux box, the best reproduction I have is

```
while nosetests -vvv -s json_test.py:FromJsonSelectTests.select_using_secondary_index_test; do :; done  
```

On my machine, this takes 15 seconds to run and I typically have to loop for 15-20 minutes to reproduce. On 4.0.36, I've run the test for over an hour with no failures.

If you'd rather not get cassandra-dtests running or cannot reproduce on your machine, I'm available to help debug. jkni on cassandra-dev IRC.

**Comment by normanmaurer** [comment] 2016-07-02 06:23
Thanks!

I will investigate and ping you guys...

**Comment by normanmaurer** [comment] 2016-07-02 06:34
@tjake it will not call `callHandlerAdded0(...)` from a random thread as it schedule it on the EventLoop and then return.

 See https://github.com/netty/netty/commit/f984870ccca133d6056e8b0df0b2352f8f90b0fe#diff-6b8633f415085302023f47004357891aR192 .

Or is there anything Im missing ? All the `callHandlerAdded0(...)` /  `callHandlerRemoved0(...)` should always happen in the EventLoop. That was one of the points of the PR ;)

**Comment by normanmaurer** [comment] 2016-07-02 06:37
@JeremiahDJordan @tjake @jkni one thing I would be interested in is if you ever see a condition in your `AbstractChannelHandlerContext` methods where `isAdded()` returns false. Could you test this and if so print the stacktrace ? Basically for all methods in there, like for example:
https://github.com/netty/netty/commit/f984870ccca133d6056e8b0df0b2352f8f90b0fe#diff-5d5eb2c10e26184226a4f493481bcf87R189

**Comment by snazy** [comment] 2016-07-02 08:14
@normanmaurer, based on @tjake and @JeremiahDJordan findings, I *think* I found a way to reproduce this in a utest - pushed to gh in [this branch](https://github.com/apache/cassandra/compare/trunk...snazy:12072-utest-trunk?expand=1). Hope this helps.

Wondering whether it makes a difference that the [old version](https://github.com/netty/netty/commit/f984870ccca133d6056e8b0df0b2352f8f90b0fe#diff-6b8633f415085302023f47004357891aL210) used `waitOnFuture` but the new one doesn't:

**Comment by johnou** [comment] 2016-07-02 08:58
@snazy did you manage to get a thread dump?

**Comment by normanmaurer** [comment] 2016-07-02 09:32
So just running the unit test ?

**Comment by snazy** [comment] 2016-07-02 09:43
Yup, seems like just the new utest helps to reproduce it.

**Comment by normanmaurer** [comment] 2016-07-02 09:50
@snazy do I need to somehow install / configure cassandra first or is it self-containing ?

**Comment by snazy** [comment] 2016-07-02 09:56
self-containing - just execute the utest with `ant test -Dtest.name=NativeTransportStressTest` or in an IDE. It complains with `com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:53043 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Operation timed out))` with 4.0.37

**Comment by normanmaurer** [comment] 2016-07-02 09:56
@snazy awesome! Will look into it later today.

**Comment by snazy** [comment] 2016-07-02 09:58
Or use `generate-idea-files` and run the utest in IDEA - similar for Eclipse.

**Comment by normanmaurer** [comment] 2016-07-02 12:23
@snazy @JeremiahDJordan @tjake ok I took the time to debug the issue and thanks to @snazy it was quite easy to understand whats going on :) I would have taken me a lot longer without the unit test.

To make it short, its a cassandra bug IMHO and you was just "lucky" that it never broke before. 

So here is the problem.... In Cassandra you are using your own `EventExecutor` implementation which break the `EventExecutor` contract.  The contract is that `execute(...)` calls must be executed in a serial fashion which is not the case here as you just return `false` from the `inEventLoop()` method and then delegate the `execute` call to an underlying Executor, which gives no such guarantees. Because of this a race can happen where an "event" may be handed over to an `AbstractChannelHandlerContext` before `setAdded()` is called, which will then have the effect that the handler is skipped.

This was previous no problem as we synchronized which had other problems, thus we removed it. 

So to make it short your `EventExecutor` implementation must guarantee ordering. That said you can have an `EventExecutorGroup` that holds multiple `EventExecutor` implementations and each of them only needs to guarantee ordering by itself, not for the whole group. 

Hope this makes sense.... Let me know if you have more questions.

@snazy when doing this patch it never fails for me with your branch:

```
iff --git a/src/java/org/apache/cassandra/service/NativeTransportService.java b/src/java/org/apache/cassandra/service/NativeTransportService.java
index 48839f1..e46b895 100644
--- a/src/java/org/apache/cassandra/service/NativeTransportService.java
+++ b/src/java/org/apache/cassandra/service/NativeTransportService.java
@@ -81,7 +81,7 @@ public class NativeTransportService

         org.apache.cassandra.transport.Server.Builder builder = new org.apache.cassandra.transport.Server.Builder()
                                                                 .withEventExecutor(eventExecutorGroup)
-                                                                .withEventLoopGroup(workerGroup)
+                                                                //.withEventLoopGroup(workerGroup)
                                                                 .withHost(nativeAddr);

         if (!DatabaseDescriptor.getClientEncryptionOptions().enabled)
diff --git a/test/unit/org/apache/cassandra/cql3/CQLTester.java b/test/unit/org/apache/cassandra/cql3/CQLTester.java
index 30ddf2c..f1fedce 100644
--- a/test/unit/org/apache/cassandra/cql3/CQLTester.java
+++ b/test/unit/org/apache/cassandra/cql3/CQLTester.java
@@ -344,7 +344,7 @@ public abstract class CQLTester
         server = new Server.Builder().
                             withHost(nativeAddr).
                             withPort(nativePort).
-                            withEventExecutor(new RequestThreadPoolExecutor()).
+                            //withEventExecutor(new RequestThreadPoolExecutor()).
                             build();
         server.start();
```

**Comment by normanmaurer** [comment] 2016-07-02 12:58
If you guys like I can fix it in cassandra... I think I have an idea how to fix it there while still give you the same behaviour as before. Just let me know

**Comment by JeremiahDJordan** [comment] 2016-07-02 15:18
If you have an idea of how to fix it that would be great.

**Comment by normanmaurer** [comment] 2016-07-02 15:19
Alright stay tuned :)

**Comment by normanmaurer** [comment] 2016-07-03 06:19
@JeremiahDJordan @tjake @snazy so @belliottsmith made a good point on twitter that if the requirement of serial execution is not documented in the `EventExecutor` interface the change I made could be considered as a breaking API change in a bug-fix release. So I checked our docs and it seems like we never documented this 😭 . 

I am currently looking into a way to change netty to work again with your code. I also have a patch with needed cassandra changes here to let it work with any netty version, but I wonder if I should not just fix it in netty after @belliottsmith made the point here... @JeremiahDJordan @tjake @snazy WDYT ?

**Comment by johnou** [comment] 2016-07-03 07:43
http://netty.io/4.1/api/io/netty/util/concurrent/DefaultEventExecutor.html "execute all submitted task in a serial fashion"

**Comment by johnou** [comment] 2016-07-03 07:46
@normanmaurer would you mind sharing the Cassandra patch anyway?

**Comment by normanmaurer** [comment] 2016-07-03 07:50
This is on the implementation but not on the interface...

**Comment by normanmaurer** [comment] 2016-07-03 07:50
Once its complete yes

**Comment by belliottsmith** [comment] 2016-07-03 08:26
I would suggest revisiting the decision to impose this constraint.

In a system where requests have differing costs (and time to serve), forbidding out-of-order execution is debilitating, as it forbids QoS (long tasks block all short tasks to all clients being served by the same thread).  It also ensures a higher memory watermark that is harder to manage.

In Cassandra this would also pretty much bring down the entire cluster (to clients' perspective), at least temporarily, because of one node failure, as requests waiting for a failed node will prevent all healthy responses from responding to clients.

Further, limiting to sequential execution only at best permits CPU on the box to be utilised (assuming an even distribution of client connections, which is far from guaranteed - C* benchmarks generally do not saturate this); it prevents saturating the system when any other resource is the bottleneck (network, disk, other nodes).  You could of course pretend to execute sequentially by delaying the final step if you somehow can separate the completion task from the execution step, but that only fixes one of your problems.

**Comment by normanmaurer** [comment] 2016-07-03 08:34
@belliotsmith thanks for chiming in :) Like I said I think you have a point here and after investigate a bit I think I can remove this constraint easily while still preserve the fix that the original patch did. So let me do this:

Write a netty patch and a cassandra patch and then let us check both of them to see which one is preferable. Cassandra will still work the same with my cassandra patch btw.

That said I'm currently leaning to adjust netty and not cassandra. As this also makes netty more flexible in general

**Comment by belliottsmith** [comment] 2016-07-03 09:08
Sure - just giving my 2c (that, as you say, a more flexible netty is a good thing)

**Comment by JeremiahDJordan** [comment] 2016-07-03 14:59
I think the netty patch is preferable if possible. There may be other projects out there which will have mysterious bugs after updating netty otherwise.

For Cassandra a netty patch would mean that users of older versions of Cassandra could update netty if they hit some problem without having to update to a newer version of Cassandra itself.

**Comment by normanmaurer** [comment] 2016-07-06 04:40
@JeremiahDJordan @tjake @jkni @snazy @belliottsmith PTAL https://github.com/netty/netty/pull/5506 . This fixes the issue for me without any cassandra changes.

**Comment by normanmaurer** [comment] 2016-07-07 13:03
Fixed by https://github.com/netty/netty/pull/5506

**Closed by normanmaurer** 2016-07-07 13:03 UTC
Labels: defect
