### ISSUE TITLE
Last Stable BungeeCord Build {issue]

### ISSUE THREAD

**Issue by KiritoKun90** [netty/netty#7219] opened 2017-09-17 08:47 UTC
I tried to update my BungeeCord with the last stable build, but when I run the server I get this error in the console now, and I can't join my server:

`06:59:34 [SEVERE] Sep 16, 2017 6:59:34 AM io.netty.util.internal.MacAddressUtil defaultMachineId WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 03:7d:bc:0c:de:a9:fd:23`

I read it was a common bug with older versions and that it wasn't a big issue, but actually I can't join my server so I dunno what to do. I've also tried by deleting all my BungeeCord server and reinstall it again from the beginning with the command wget and without any plugins... but nothing changed and the problem persists.

What's that?

**Comment by johnou** [comment] 2017-09-17 11:11
Netty does not provide BungeeCord support. The message you pasted is a warning, not something that would prevent Netty itself from working. There were some recent improvements to MacAddressUtil in the latest releases so you could try pushing Netty updates upstream. That said you might want to try BungeeCord forums / mailing lists for support.

**Comment by KiritoKun90** [comment] 2017-09-17 11:36
Actually I first wrote into Bungee Hub and they told me that it isn't a Bungee issue and that I was suppose to write here, look the post I made:

https://github.com/SpigotMC/BungeeCord/issues/2257

Second of all it's not only a warning, it says [SEVERE] and I'm still not understanding what it is asking. How I said before, I looked around a lot and I've found some older posts that talks about it and they were al solved. To fix the issues they only had to upgrade nitty and they said that with new version this error shouldn't come again. First time I hear nitty and I honestly dunno what we are talking about.

Plz help

**Comment by johnou** [comment] 2017-09-17 13:54
@KiritoKun90 it's a warning, https://github.com/netty/netty/blob/01eb428b39156e61624dae303ae9772ba3424b36/common/src/main/java/io/netty/util/internal/MacAddressUtil.java#L143 and as stated here https://github.com/netty/netty/pull/6308#issuecomment-292053749 harmless.

I recommend checking your server firewall rules / port forwarding and if problems persist reopen your https://github.com/SpigotMC/BungeeCord/issues/2257 issue with further information about your deployment.

**Comment by Scottmitch** [comment] 2017-09-17 19:16
As stated above I wouldn't expect a failure to detect a default network interface as the root cause to an issue. Are you using a SecurityManager, and is the server able to bind to the anticipated load address/port?

You will have to provide us with more information and details as to why you think this is a Netty issue that is preventing you from connecting to your server. I would suggest you troubleshoot with the BungeeCord folks more to diagnose a root cause, and if you determine it is attributed to Netty report back with more details.

**Comment by KiritoKun90** [comment] 2017-09-24 09:09
I think is about a Netty issue for two reasons:
1) because I found a lot of old threads that discuss about it like:
https://github.com/netty/netty/issues/6406
2) I've already wrote to Bungee section, but they told me is probably an issue more on your side rather than his.

**Comment by KiritoKun90** [comment] 2017-09-24 09:10
You say is not really important and that I can ignore it, but is it possible to hide/delete it in a certain way?

**Comment by johnou** [comment] 2017-09-24 13:11
@KiritoKun90 what version of Netty are you using? It should be fixed with 4.1.9 or above but I recommend using the latest version available. 

Scott and I are still waiting for you to reply to our previous comments / questions.

**Comment by normanmaurer** [comment] 2017-09-26 12:26
You could adjust the logging configuration to not log for this class. How this is done really depends on the logging framework you use.

**Comment by johnou** [comment] 2017-10-03 21:47
@KiritoKun90 ping.

**Comment by normanmaurer** [comment] 2018-04-24 13:00
Closing as no further details provided

**Closed by normanmaurer** 2018-04-24 13:00 UTC
