### ISSUE TITLE
WeakOrderQueue.transfer is 1st Hot Method

### ISSUE THREAD

**Issue by louxiu** [netty/netty#10251] opened 2020-05-06 08:32 UTC
### Expected behavior
4.1.44.Final should work same as 4.0.49.Final(WeakOrderQueue#transfer)
Hot threads and methods in 4.0.49
![WeChatWorkScreenshot_d5769c74-31b4-42a2-abe5-2f288a4ec14f](https://user-images.githubusercontent.com/925154/81154179-3ee16480-8fb6-11ea-95cc-f6ca842fd9c0.png)

### Actual behavior
4.0.49.Final works better than 4.1.44.Final
Hot threads and methods in 4.1.44
![WeChatWorkScreenshot_b83f2206-b243-4bfd-b004-4ba223f7ee78](https://user-images.githubusercontent.com/925154/81154370-6a644f00-8fb6-11ea-9309-5d8de6fc0e21.png)

### Steps to reproduce
Be part of a service, it is hard to strip a demo code.

### Netty version
4.1.44.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux  3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment] 2020-05-06 08:36
@louxiu please update to latest 4.1.x release first and report back if you still think there is a problem.

**Comment by louxiu** [comment] 2020-05-06 08:37
This commit(71860e5b94dbc665fdb8d279d3780d6fe1c618ea) in 4.1.x will reduce the effective of recycle object. After disable drop in WeakOrderQueue. The problem seems disappear.

![WeChatWorkScreenshot_159e5dbf-6f96-496e-aa12-016bc84eec6a](https://user-images.githubusercontent.com/925154/81155433-83b9cb00-8fb7-11ea-96d5-6cb32ef8433a.png)

![WeChatWorkScreenshot_e92cc6c2-52a7-486d-92ff-b4e0cd4956a7](https://user-images.githubusercontent.com/925154/81155746-dabfa000-8fb7-11ea-8c91-d5c55e99f0be.png)

Would add an option to disable drop in WeakOrderQueue is an acceptable solution?

**Comment by normanmaurer** [comment] 2020-05-06 08:42
@louxiu I happy to review a PR... that said I think you could just adjust the `ratioMask` ?

**Comment by louxiu** [comment] 2020-05-06 08:50
I also tried `-Dio.netty.recycler.ratio=1` or `-Dio.netty.recycler.ratio=2`, but without luck.

Hot method with `-Dio.netty.recycler.ratio=1`
![WeChatWorkScreenshot_30a3fd88-af79-4f8f-b9ec-fa62a7f5410a](https://user-images.githubusercontent.com/925154/81157129-3f2f2f00-8fb9-11ea-9b02-67ed18f89b6d.png)

Hot method with `-Dio.netty.recycler.ratio=2` or 4
![WeChatWorkScreenshot_bcf9e8cc-5f94-4b98-9205-f60aceefbebc](https://user-images.githubusercontent.com/925154/81157520-a2b95c80-8fb9-11ea-98a6-43abb4d2ef6f.png)


I also noticed the `DEFAULT_INITIAL_MAX_CAPACITY` is changed from 32768 to 4096. The stress test above are all `DEFAULT_INITIAL_MAX_CAPACITY=32768`.

**Comment by louxiu** [comment] 2020-05-06 08:51
> @louxiu I happy to review a PR... that said I think you could just adjust the `ratioMask` ?

Tried that, but without luck. It's quite weird.

**Comment by louxiu** [comment] 2020-05-06 08:54
> @louxiu I happy to review a PR... that said I think you could just adjust the `ratioMask` ?

After spent a lot time, add an option to disable drop in `WeakOrderQueue` is the only solution I could do. I am glad to create a PR. Do you think it is an acceptable change? @normanmaurer

**Comment by louxiu** [comment] 2020-05-06 11:37
Stress test with latest version(4.1.49.Final), the problem still exists.
![WeChatWorkScreenshot_f3f700b3-73a8-474f-9ce9-ea06957dd5f9](https://user-images.githubusercontent.com/925154/81172487-e7042700-8fd0-11ea-88f5-f39751a96e11.png)

**Comment by franz1981** [comment] 2020-05-06 12:09
@louxiu Just to be 100% that's the problem (as it seems) can you profile it by using https://github.com/jvm-profiling-tools/async-profiler and adding `-XX:UnlockDiagnosticVMOptions -XX:DebugNonSafepoints` to the jvm configuration? JFR is ok as well as long as you add the same JVM args

**Comment by louxiu** [comment] 2020-05-07 05:49
> @louxiu Just to be 100% that's the problem (as it seems) can you profile it by using https://github.com/jvm-profiling-tools/async-profiler and adding `-XX:UnlockDiagnosticVMOptions -XX:DebugNonSafepoints` to the jvm configuration? JFR is ok as well as long as you add the same JVM args

Ok, I will try it later

**Comment by normanmaurer** [comment] 2020-05-07 08:31
@louxiu even now that your PR is merged I would be interested in this...

**Comment by louxiu** [comment] 2020-05-07 08:53
> @louxiu even now that your PR is merged I would be interested in this...

I will try @franz1981 's suggest. 

PS: We upgrade to 4.1.x to use `recvmmsg` feature(Context switch decreased), `FixedRecvByteBufAllocator` set as 5 * MTU as previous's test. I should set it as 1 MTU to avoid its affect.

**Comment by normanmaurer** [comment] 2020-05-07 08:58
@louxiu I dont understand your statement for `MTU`. If you think there should be something changed please open a PR.

**Comment by normanmaurer** [comment] 2020-05-11 13:24
@louxiu ping... any update ?

**Comment by louxiu** [comment] 2020-05-12 13:14
@normanmaurer Sorry for late reply. Busy doing other work before and will get time on this tomorrow.

**Comment by normanmaurer** [comment] 2020-05-12 16:19
@louxiu don't worry... just wanted to ensure we dont forget :)

**Closed** 2020-05-13 07:15 UTC

**Comment by louxiu** [comment] 2020-05-13 13:12
Jvm args

    nohup java -Xmx8g -Xms8g -Xloggc:/home/shared/log/gc.log.`date +%Y-%m-%d-%H-%M` \
    -XX:+PreserveFramePointer \
    -XX:+PrintGCDateStamps -XX:+UseG1GC -XX:MaxGCPauseMillis=200 \
    -XX:MetaspaceSize=128m -XX:-OmitStackTraceInFastThrow -XX:+PrintGCDetails -verbose:gc \
    -jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=1098 -Dio.netty.allocator.smallCacheSize=2560 \
    -Dio.netty.recycler.maxCapacity=32768 -Dio.netty.recycler.ratio=x -Dio.netty.recycler.delayedQueue.ratio=y \
    -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:FlightRecorderOptions=defaultrecording=true,disk=true,repository=/home/shared/jfr,maxage=1m,settings=default \
    target/${JAR_NAME}


[flame graph with ratio=8](https://gist.github.com/louxiu/342715c6ffd1b3f76952a7e863c3d95a#file-flamegraph-ratio-8-svg)
![WeChatWorkScreenshot_e6c060c4-2868-43d7-91ce-5ed0bb7cffcc](https://user-images.githubusercontent.com/925154/81816500-fac60500-955d-11ea-8301-d0bb37162bd9.png)

[flame graph with ratio=4 and delayedQueue.ratio=2](https://gist.github.com/louxiu/342715c6ffd1b3f76952a7e863c3d95a#file-flamegraph-ratio-4-delayedqueue-ratio-2-svg)
![WeChatWorkScreenshot_9830effb-3c10-4343-bffc-3737f6634810](https://user-images.githubusercontent.com/925154/81816357-cd795700-955d-11ea-8574-46d480076ea1.png)

@franz1981 @normanmaurer

**Comment by franz1981** [comment] 2020-05-13 13:20
@louxiu Beware JFR need -XX:UnlockDiagnosticVMOptions -XX:DebugNonSafepoints

**Comment by louxiu** [comment] 2020-05-13 13:36
Two jfrs: es.with.ratio=4.delayedQueue=2.2020-05-13-20_50_07.jfr and  es.with.ratio=8.2020-05-13-20_40_36.jfr
[jfrs.zip](https://github.com/netty/netty/files/4622216/Archive.zip)

**Comment by louxiu** [comment] 2020-05-13 13:37
> @louxiu Beware JFR need -XX:UnlockDiagnosticVMOptions -XX:DebugNonSafepoints while -XX:+PreserveFramePointer isn't needed

Restress with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`, but didn't notice much difference in jfr

**Comment by franz1981** [comment] 2020-05-13 14:09
@louxiu using `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` is useful when inlined methods are the most costy ones: if it won't make any difference "maybe" is that they are not the most costy one, but the flags should be there to make sure it's the case

**Comment by louxiu** [comment] 2020-05-20 08:07
@normanmaurer @franz1981 The problem is `Stack#scavengeSome` loop `WeakOrderQueue`  list to collect recyclable object. It needs to iterate all `WeakOrderQueue`  even there is no recyclable object available(In our case, one thread has 64 delayed queue).

Option "-Dio.netty.recycler.ratio=8 -Dio.netty.recycler.delayedQueue.ratio=0" and "-Dio.netty.recycler.ratio=4 -Dio.netty.recycler.delayedQueue.ratio=2" behaves different, "-Dio.netty.recycler.delayedQueue.ratio=2" lead to more empty `WeakOrderQueue`.

**Comment by normanmaurer** [comment] 2020-05-20 09:38
@louxiu so just so I understand correct... There are a lot of "empty" `WeakOrderQueue` and the problem is the iteration of 64 links ?

**Comment by louxiu** [comment] 2020-05-20 09:52
> @louxiu so just so I understand correct... There are a lot of "empty" `WeakOrderQueue` and the problem is the iteration of 64 links ?

Yes. Currently we disable drop ratio. It's seems that only drop ratio above some threshold, it will be a problem. Not sure wether there is an easy way(or worth to optimize) to avoid loop "empty" `WeakOrderQueue` list.
