### ISSUE TITLE
NPE in Native#address() @ line 411

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#3328] opened 2015-01-14 17:28 UTC
```
2015-01-14 17:20:38:579 GMT [Client-To-Proxy-80-AcceptorThread-0,] WARN DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: null
	at io.netty.channel.epoll.Native.address(Native.java:411) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.epoll.Native.remoteAddress(Native.java:402) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.epoll.EpollSocketChannel.<init>(EpollSocketChannel.java:76) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.epoll.EpollServerSocketChannel$EpollServerSocketUnsafe.epollInReady(EpollServerSocketChannel.java:109) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
```

**Comment by normanmaurer** [comment] 2015-01-14 20:20
@rkapsi thanks will check

**Comment by normanmaurer** [comment] 2015-01-14 20:31
@rkapsi is there an easy way to reproduce ?

**Comment by rkapsi** [comment] 2015-01-14 20:39
@normanmaurer I don't have a repro. The stacktrace is straight from production. It's rare but happens once in a while.

**Comment by hepin1989** [comment] 2015-01-17 15:11
I encounter this problem too.
using netty4.1.beta3

my stack trace is useless ,cause I am using it as akka's remote transport
```
java.lang.NullPointerException
	at qgame.akka.remote.transport.netty4.tcp.Netty4TcpTransport$.inetAddressToActorAddress(Netty4TcpTransport.scala:77)
	at qgame.akka.remote.transport.netty4.tcp.Netty4TcpTransportServerActor$$anonfun$qgame$akka$remote$transport$netty4$tcp$Netty4TcpTransportServerActor$$associationEventListenerRegistered$1.applyOrElse(Netty4TcpTransportServerActor.scala:127)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at qgame.akka.remote.transport.netty4.tcp.Netty4TcpTransportServerActor.aroundReceive(Netty4TcpTransportServerActor.scala:24)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

as you can see,the channel is connected ：

```java
case ChannelActive(channel) =>
      val remoteAddress = Netty4TcpTransport.inetAddressToActorAddress(channel.remoteAddress().asInstanceOf[InetSocketAddress])
```
this call going to call
```java
  def inetAddressToActorAddress(addr: InetSocketAddress): Address = {
    Address(schemeRef.get(), systemRef.get(), hostnameRef.get(), addr.getPort)
  }
```
the last call ```addr.getPort``` throw the NPE,I have looked into the native code a little.
```
JNIEXPORT jbyteArray JNICALL Java_io_netty_channel_epoll_Native_remoteAddress0(JNIEnv* env, jclass clazz, jint fd) {
    socklen_t len;
    struct sockaddr_storage addr;

    len = sizeof addr;
    if (getpeername(fd, (struct sockaddr*) &addr, &len) == -1) {
        return NULL;
    }
    return createInetSocketAddressArray(env, addr);
}
```
as @rkapsi just said,just happens once a while.I can't produce it too.maybe there is a race condition.
where the channel is connected ,but the peername is not been set .

**Comment by hepin1989** [comment] 2015-01-17 15:30
@normanmaurer @rkapsi 
I just come to an idea about that:
could it be some virus or port scanner ,which send a corrupted package?!

**Comment by rkapsi** [comment] 2015-01-17 18:40
I can't say much about it but in our case it's basically a server socket listening on port 80 that is sitting behind a HW load balancer and a layer of network scrubbers to mitigate continuous DDoS attacks. Normal operation is in the multiple Gbit/s range and "bad data" is a pretty common problem.

**Comment by normanmaurer** [comment] 2015-01-17 19:07
For what ever reason the peer name can not be retrieved. This may be as the connection is already closed. Will fix it

**Comment by hepin1989** [comment] 2015-01-18 05:26
@normanmaurer thanks,let's tracking it down,and beat it hardly.

**Comment by normanmaurer** [comment] 2015-01-26 09:44
@rkapsi @hepin1989 fixed by #3347

**Closed by normanmaurer** 2015-01-26 09:44 UTC
Labels: defect

**Comment by hepin1989** [comment] 2015-01-26 09:48
@normanmaurer thanks will there be a new netty-native-trasnport-epoll release?

**Comment by normanmaurer** [comment] 2015-01-26 09:50
@hepin1989 yeah sure... not sure when though

**Comment by hepin1989** [comment] 2015-01-26 09:58
@normanmaurer thanks ,I have worked around this~:P

**Comment by hepin1989** [comment] 2015-03-04 08:44
@normanmaurer 
after I try netty4.1.0-beta4 with native transport epoll netty4.1.0-beta4 at centos with 
```
[root@ST-M15-03-xxjh-gw05 bin]# uname -a
Linux ST-M15-03-xxjh-gw05 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```
can not get the localAddress and remoteAddress ,witch just return null.
but it's OK on my desktop.
with ```
Linux kerr 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

```
after downgrade to netty4.1.0-beta3. it works again.

**Comment by normanmaurer** [comment] 2015-03-04 08:50
@hepin1989 that's strange... can you tell me more about the centos host.. like exact centos version, java version, ipv4 or ipvv6 etc.

**Comment by normanmaurer** [comment] 2015-03-04 11:49
@hepin1989 also a simple reproducer which works on one and fails on the other would help a lot :)

**Comment by hepin1989** [comment] 2015-03-04 12:06
It's CentOS release 6.3 (Final), java version "1.8.0_25",IPv4.
I am tracking it.

**Comment by hepin1989** [comment] 2015-03-04 13:12
@normanmaurer 
the problem is that
```
          clientBootstrap.connect(remoteSocketAddress).onComplete {
            case Success(channel) =>
              //when the channel is connected to the remote,
              //we need to associate it
              log.debug("client channel :{}", channel)
              log.debug("remote address:{}", channel.remoteAddress())
              log.debug("local address :{}", channel.localAddress())
```
when call ```channel.localAddress()``` after the channel is connected to the remote port.which just return null.we could read the ```channel.remoteAddress()```.but not the ```localAddress()```

**Comment by normanmaurer** [comment] 2015-03-04 13:13
@hepin1989 so remote works but local sometimes not. right ?

**Comment by hepin1989** [comment] 2015-03-04 13:22
@normanmaurer yes,that's it.

**Comment by normanmaurer** [comment] 2015-03-04 13:23
@hepin1989 will check. Thanks!
