### ISSUE TITLE
StackOverflowError when create NioEventLoopGroup

### ISSUE THREAD

**Issue by builder79** [netty/netty#7244] opened 2017-09-22 05:46 UTC
when jvm options  -Xss128k then stackoverflow
remove jvm option then ok

### Netty version
  4.1.15.Final

### JVM version (e.g. `java -version`)
 jdk1.8.0_144

### OS version (e.g. `uname -a`)
  windows server 2012 r2

** server env
2017-09-22 14:36:44.390 [R0] - -Dio.netty.eventLoopThreads: 24 
2017-09-22 14:36:44.406 [R0] - Platform: Windows 
2017-09-22 14:36:44.406 [R0] - -Dio.netty.noUnsafe: false 
2017-09-22 14:36:44.406 [R0] - Java version: 8 
2017-09-22 14:36:44.406 [R0] - sun.misc.Unsafe.theUnsafe: available 
2017-09-22 14:36:44.406 [R0] - sun.misc.Unsafe.copyMemory: available 
2017-09-22 14:36:44.406 [R0] - java.nio.Buffer.address: available 
2017-09-22 14:36:44.406 [R0] - direct buffer constructor: available 
2017-09-22 14:36:44.406 [R0] - java.nio.Bits.unaligned: available, true 
2017-09-22 14:36:44.421 [R0] - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9 
2017-09-22 14:36:44.421 [R0] - java.nio.DirectByteBuffer.<init>(long, int): available 
2017-09-22 14:36:44.421 [R0] - sun.misc.Unsafe: available 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.tmpdir: C:\Users\ADMINI~1\AppData\Local\Temp\2 (java.io.tmpdir) 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.bitMode: 64 (sun.arch.data.model) 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.noPreferDirect: false 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.maxDirectMemory: 1073741824 bytes 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.uninitializedArrayAllocationThreshold: -1 
2017-09-22 14:36:44.421 [R0] - java.nio.ByteBuffer.cleaner(): available 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.noKeySetOptimization: false 
2017-09-22 14:36:44.421 [R0] - -Dio.netty.selectorAutoRebuildThreshold: 512 
2017-09-22 14:36:44.437 [R0] - org.jctools-core.MpscChunkedArrayQueue: available 

**** trace
Exception in thread "R0" java.lang.StackOverflowError
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
       at io.netty.util.Signal$1.<init>(Signal.java:27)
       at io.netty.util.Signal.<clinit>(Signal.java:27)
       at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:43)
       at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36)
       at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
       at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
       at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
       at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
       at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
       at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
       at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
       at com.test.Main$ClientBootstrap.run(Main.java:376)

**Comment by johnou** [comment] 2017-09-23 18:44
Not sure what you are asking for but by setting the thread stack size so low that exception is expected if the stack size exceeds the configured value. Our jvms usually run with -Xss256k without any problems.

**Comment by carl-mastrangelo** [comment] 2017-09-23 21:26
@builder79 does the problem go away if you spawn a new thread to run ClientBootstrap?   IIRC, the JVM  uses a ton of stack at start up.

Also I agree with @johnou, 128K stack is too little.

**Comment by normanmaurer** [comment] 2017-09-26 12:08
Let me close this as like @johnou and @carl-mastrangelo said this is not a bug.

**Closed by normanmaurer** 2017-09-26 12:08 UTC

**Comment by wbuilder282** [comment] 2020-09-18 06:53
thanks! @johnou @carl-mastrangelo
