### ISSUE TITLE
Netty cannot build SSL Context on Android

### ISSUE THREAD

**Issue by WonderfulWorlds** [netty/netty#5366] opened 2016-06-07 20:55 UTC
Using: netty-all:4.1.0.Final, Android 4.4.2.

Running the following code

```
public void connect() {
    // Configure SSL.
    SslContext sslCtx = null;
    try {
        sslCtx = SslContextBuilder.forClient()
            .trustManager(InsecureTrustManagerFactory.INSTANCE).build();
    } catch (SSLException e) {
        System.out.println(e.getMessage());
    }
}
```

produces the following rather long printouts in logcat (dates and package names omitted from beginning for clarity). Note that the code works perfectly when run from a Windows environment.

```
I/dalvikvm: Could not find method org.slf4j.LoggerFactory.getILoggerFactory, referenced from method io.netty.util.internal.logging.Slf4JLoggerFactory.<init>
W/dalvikvm: VFY: unable to resolve static method 61515: Lorg/slf4j/LoggerFactory;.getILoggerFactory ()Lorg/slf4j/ILoggerFactory;
I/dalvikvm: Could not find method org.slf4j.LoggerFactory.getLogger, referenced from method io.netty.util.internal.logging.Slf4JLoggerFactory.newInstance
W/dalvikvm: VFY: unable to resolve static method 61516: Lorg/slf4j/LoggerFactory;.getLogger (Ljava/lang/String;)Lorg/slf4j/Logger;
I/dalvikvm: Could not find method org.apache.log4j.Logger.getLogger, referenced from method io.netty.util.internal.logging.Log4JLoggerFactory.newInstance
W/dalvikvm: VFY: unable to resolve static method 60939: Lorg/apache/log4j/Logger;.getLogger (Ljava/lang/String;)Lorg/apache/log4j/Logger;
W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/apache/log4j/Logger;)
I/dalvikvm: Could not find method org.apache.log4j.Logger.getName, referenced from method io.netty.util.internal.logging.Log4JLogger.<init>
W/dalvikvm: VFY: unable to resolve virtual method 60940: Lorg/apache/log4j/Logger;.getName ()Ljava/lang/String;
I/dalvikvm: Could not find method org.apache.log4j.Logger.isTraceEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.isTraceCapable
W/dalvikvm: VFY: unable to resolve virtual method 60944: Lorg/apache/log4j/Logger;.isTraceEnabled ()Z
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
I/dalvikvm: Could not find method org.apache.log4j.Logger.isDebugEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.debug
W/dalvikvm: VFY: unable to resolve virtual method 60941: Lorg/apache/log4j/Logger;.isDebugEnabled ()Z
I/dalvikvm: Could not find method org.apache.log4j.Logger.isDebugEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.debug
W/dalvikvm: VFY: unable to resolve virtual method 60941: Lorg/apache/log4j/Logger;.isDebugEnabled ()Z
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
I/dalvikvm: Could not find method org.apache.log4j.Logger.isDebugEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.debug
W/dalvikvm: VFY: unable to resolve virtual method 60941: Lorg/apache/log4j/Logger;.isDebugEnabled ()Z
W/dalvikvm: VFY: unable to resolve static field 22387 (ERROR) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22387 (ERROR) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22387 (ERROR) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22387 (ERROR) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22387 (ERROR) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22388 (INFO) in Lorg/apache/log4j/Level;
I/dalvikvm: Could not find method org.apache.log4j.Logger.isInfoEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.info
W/dalvikvm: VFY: unable to resolve virtual method 60943: Lorg/apache/log4j/Logger;.isInfoEnabled ()Z
I/dalvikvm: Could not find method org.apache.log4j.Logger.isInfoEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.info
W/dalvikvm: VFY: unable to resolve virtual method 60943: Lorg/apache/log4j/Logger;.isInfoEnabled ()Z
W/dalvikvm: VFY: unable to resolve static field 22388 (INFO) in Lorg/apache/log4j/Level;
I/dalvikvm: Could not find method org.apache.log4j.Logger.isInfoEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.info
W/dalvikvm: VFY: unable to resolve virtual method 60943: Lorg/apache/log4j/Logger;.isInfoEnabled ()Z
I/dalvikvm: Could not find method org.apache.log4j.Logger.isDebugEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.isDebugEnabled
W/dalvikvm: VFY: unable to resolve virtual method 60941: Lorg/apache/log4j/Logger;.isDebugEnabled ()Z
W/dalvikvm: VFY: unable to resolve static field 22387 (ERROR) in Lorg/apache/log4j/Level;
I/dalvikvm: Could not find method org.apache.log4j.Logger.isInfoEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.isInfoEnabled
W/dalvikvm: VFY: unable to resolve virtual method 60943: Lorg/apache/log4j/Logger;.isInfoEnabled ()Z
I/dalvikvm: Could not find method org.apache.log4j.Logger.isTraceEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.isTraceEnabled
W/dalvikvm: VFY: unable to resolve virtual method 60944: Lorg/apache/log4j/Logger;.isTraceEnabled ()Z
I/dalvikvm: Could not find method org.apache.log4j.Logger.isDebugEnabled, referenced from method io.netty.util.internal.logging.Log4JLogger.isTraceEnabled
W/dalvikvm: VFY: unable to resolve virtual method 60941: Lorg/apache/log4j/Logger;.isDebugEnabled ()Z
W/dalvikvm: VFY: unable to resolve static field 22390 (WARN) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22389 (TRACE) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22389 (TRACE) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22389 (TRACE) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22389 (TRACE) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22389 (TRACE) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22386 (DEBUG) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22390 (WARN) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22390 (WARN) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22390 (WARN) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22390 (WARN) in Lorg/apache/log4j/Level;
W/dalvikvm: VFY: unable to resolve static field 22390 (WARN) in Lorg/apache/log4j/Level;
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5772 at 0x10 in Lio/netty/util/internal/logging/Log4JLogger;.debug
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5772 at 0x10 in Lio/netty/util/internal/logging/Log4JLogger;.debug
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5772 at 0x10 in Lio/netty/util/internal/logging/Log4JLogger;.debug
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5773 at 0x12 in Lio/netty/util/internal/logging/Log4JLogger;.error
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5773 at 0x12 in Lio/netty/util/internal/logging/Log4JLogger;.error
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5773 at 0x12 in Lio/netty/util/internal/logging/Log4JLogger;.error
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5774 at 0x10 in Lio/netty/util/internal/logging/Log4JLogger;.info
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5774 at 0x10 in Lio/netty/util/internal/logging/Log4JLogger;.info
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5774 at 0x10 in Lio/netty/util/internal/logging/Log4JLogger;.info
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5776 at 0x12 in Lio/netty/util/internal/logging/Log4JLogger;.warn
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5776 at 0x12 in Lio/netty/util/internal/logging/Log4JLogger;.warn
I/dalvikvm: DexOpt: unable to optimize static field ref 0x5776 at 0x12 in Lio/netty/util/internal/logging/Log4JLogger;.warn
I/dalvikvm: Could not find method org.apache.tomcat.jni.Pool.create, referenced from method io.netty.handler.ssl.OpenSsl.<clinit>
W/dalvikvm: VFY: unable to resolve static method 60970: Lorg/apache/tomcat/jni/Pool;.create (J)J
I/dalvikvm: Could not find method org.apache.tomcat.jni.Library.initialize, referenced from method io.netty.handler.ssl.OpenSsl.initializeTcNative
W/dalvikvm: VFY: unable to resolve static method 60969: Lorg/apache/tomcat/jni/Library;.initialize (Ljava/lang/String;)Z
E/dalvikvm: Could not find class 'org.apache.tomcat.jni.SSL', referenced from method io.netty.handler.ssl.OpenSsl.loadTcNative
W/dalvikvm: VFY: unable to resolve const-class 6540 (Lorg/apache/tomcat/jni/SSL;) in Lio/netty/handler/ssl/OpenSsl;
I/dalvikvm: Could not find method org.apache.tomcat.jni.Buffer.address, referenced from method io.netty.handler.ssl.OpenSsl.memoryAddress
W/dalvikvm: VFY: unable to resolve static method 60968: Lorg/apache/tomcat/jni/Buffer;.address (Ljava/nio/ByteBuffer;)J
I/dalvikvm: Could not find method org.apache.tomcat.jni.SSL.version, referenced from method io.netty.handler.ssl.OpenSsl.version
W/dalvikvm: VFY: unable to resolve static method 61010: Lorg/apache/tomcat/jni/SSL;.version ()I
I/dalvikvm: Could not find method org.apache.tomcat.jni.SSL.versionString, referenced from method io.netty.handler.ssl.OpenSsl.versionString
W/dalvikvm: VFY: unable to resolve static method 61011: Lorg/apache/tomcat/jni/SSL;.versionString ()Ljava/lang/String;
I/dalvikvm: Could not find method sun.misc.Unsafe.addressSize, referenced from method io.netty.util.internal.PlatformDependent0.addressSize
W/dalvikvm: VFY: unable to resolve virtual method 61528: Lsun/misc/Unsafe;.addressSize ()I
I/dalvikvm: Could not find method sun.misc.Unsafe.allocateMemory, referenced from method io.netty.util.internal.PlatformDependent0.allocateMemory
W/dalvikvm: VFY: unable to resolve virtual method 61529: Lsun/misc/Unsafe;.allocateMemory (J)J
I/dalvikvm: Could not find method sun.misc.Unsafe.copyMemory, referenced from method io.netty.util.internal.PlatformDependent0.copyMemory
W/dalvikvm: VFY: unable to resolve virtual method 61535: Lsun/misc/Unsafe;.copyMemory (JJJ)V
I/dalvikvm: Could not find method sun.misc.Unsafe.copyMemory, referenced from method io.netty.util.internal.PlatformDependent0.copyMemory
W/dalvikvm: VFY: unable to resolve virtual method 61536: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
I/dalvikvm: Could not find method sun.misc.Unsafe.getChar, referenced from method io.netty.util.internal.PlatformDependent0.equals
W/dalvikvm: VFY: unable to resolve virtual method 61540: Lsun/misc/Unsafe;.getChar (Ljava/lang/Object;J)C
I/dalvikvm: Could not find method sun.misc.Unsafe.getChar, referenced from method io.netty.util.internal.PlatformDependent0.equals
W/dalvikvm: VFY: unable to resolve virtual method 61540: Lsun/misc/Unsafe;.getChar (Ljava/lang/Object;J)C
I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.equals
W/dalvikvm: VFY: unable to resolve virtual method 61539: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
I/dalvikvm: Could not find method sun.misc.Unsafe.getChar, referenced from method io.netty.util.internal.PlatformDependent0.equals
W/dalvikvm: VFY: unable to resolve virtual method 61540: Lsun/misc/Unsafe;.getChar (Ljava/lang/Object;J)C
I/dalvikvm: Could not find method sun.misc.Unsafe.getChar, referenced from method io.netty.util.internal.PlatformDependent0.equals
W/dalvikvm: VFY: unable to resolve virtual method 61540: Lsun/misc/Unsafe;.getChar (Ljava/lang/Object;J)C
I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.equals
W/dalvikvm: VFY: unable to resolve virtual method 61539: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
I/dalvikvm: Could not find method sun.misc.Unsafe.freeMemory, referenced from method io.netty.util.internal.PlatformDependent0.freeMemory
W/dalvikvm: VFY: unable to resolve virtual method 61537: Lsun/misc/Unsafe;.freeMemory (J)V
I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.getByte
W/dalvikvm: VFY: unable to resolve virtual method 61538: Lsun/misc/Unsafe;.getByte (J)B
I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.getByte
W/dalvikvm: VFY: unable to resolve virtual method 61539: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
I/dalvikvm: Could not find method sun.misc.Unsafe.getInt, referenced from method io.netty.util.internal.PlatformDependent0.getInt
W/dalvikvm: VFY: unable to resolve virtual method 61541: Lsun/misc/Unsafe;.getInt (J)I
I/dalvikvm: Could not find method sun.misc.Unsafe.getLong, referenced from method io.netty.util.internal.PlatformDependent0.getLong
W/dalvikvm: VFY: unable to resolve virtual method 61544: Lsun/misc/Unsafe;.getLong (J)J
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.getShort
W/dalvikvm: VFY: unable to resolve virtual method 61549: Lsun/misc/Unsafe;.getShort (J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.getShort
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61539: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61539: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.hashCodeAscii
W/dalvikvm: VFY: unable to resolve virtual method 61550: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
I/dalvikvm: Could not find method sun.misc.Unsafe.putByte, referenced from method io.netty.util.internal.PlatformDependent0.putByte
W/dalvikvm: VFY: unable to resolve virtual method 61554: Lsun/misc/Unsafe;.putByte (JB)V
I/dalvikvm: Could not find method sun.misc.Unsafe.putByte, referenced from method io.netty.util.internal.PlatformDependent0.putByte
W/dalvikvm: VFY: unable to resolve virtual method 61555: Lsun/misc/Unsafe;.putByte (Ljava/lang/Object;JB)V
I/dalvikvm: Could not find method sun.misc.Unsafe.putInt, referenced from method io.netty.util.internal.PlatformDependent0.putInt
W/dalvikvm: VFY: unable to resolve virtual method 61556: Lsun/misc/Unsafe;.putInt (JI)V
I/dalvikvm: Could not find method sun.misc.Unsafe.putLong, referenced from method io.netty.util.internal.PlatformDependent0.putLong
W/dalvikvm: VFY: unable to resolve virtual method 61559: Lsun/misc/Unsafe;.putLong (JJ)V
I/dalvikvm: Could not find method sun.misc.Unsafe.putShort, referenced from method io.netty.util.internal.PlatformDependent0.putShort
W/dalvikvm: VFY: unable to resolve virtual method 61567: Lsun/misc/Unsafe;.putShort (JS)V
I/dalvikvm: Could not find method sun.misc.Unsafe.putShort, referenced from method io.netty.util.internal.PlatformDependent0.putShort
W/dalvikvm: VFY: unable to resolve virtual method 61568: Lsun/misc/Unsafe;.putShort (Ljava/lang/Object;JS)V
I/dalvikvm: Could not find method sun.misc.Unsafe.throwException, referenced from method io.netty.util.internal.PlatformDependent0.throwException
W/dalvikvm: VFY: unable to resolve virtual method 61569: Lsun/misc/Unsafe;.throwException (Ljava/lang/Throwable;)V
```

**Comment by Scottmitch** [comment] 2016-06-07 21:03
This may be a duplicate of https://github.com/netty/netty/issues/4824

Can you try to run with `-Dio.netty.noUnsafe=true`?

**Comment by WonderfulWorlds** [comment] 2016-06-07 21:20
How?

**Comment by Scottmitch** [comment] 2016-06-07 21:38
This should be defined as a java system property. What I specified above is how you can define the system property on the command line.

**Comment by WonderfulWorlds** [comment] 2016-06-07 22:06
Tried it, did the exact same thing. No exception caught.

**Comment by WonderfulWorlds** [comment] 2016-06-08 11:25
For everyone who wants to reproduce this, simply run [netty's secure chat example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/securechat)'s client on Android. No server needed. After further investigation it seems that netty's documentation is incorrect, neglecting to mention a dependency on log4j (and perhaps others), causing the errors.

**Comment by NoiZeR355** [comment] 2017-03-03 10:27
How did you fixed it then for android?

**Comment by normanmaurer** [comment] 2017-10-25 12:58
Closing it as it seems to just work

**Closed by normanmaurer** 2017-10-25 12:58 UTC
