### ISSUE TITLE
Unable to initialize PlatformDependent0 (Netty 4.1.8.Final)

### ISSUE THREAD

**Issue by shumy** [netty/netty#6548] opened 2017-03-16 16:17 UTC
### Expected behavior
No errors

### Actual behavior
java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
io.netty.common[io.netty.channel.DefaultChannelId] : Could not invoke Process.myPid(); not Android?
java.lang.ClassNotFoundException: android/os/Process

### Steps to reproduce
On Ubuntu 16:
git clone https://github.com/shumy/leffe-wg
cd leffe-wg
gradle
./run.sh

### Minimal yet complete reproducer code (or URL to code)
https://github.com/shumy/leffe-wg

### Netty version
4.1.8.Final

### JVM version (e.g. `java -version`)
Java 8 on Apache Felix OSGi 

### OS version (e.g. `uname -a`)
Linux micael 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### OSGi bundles
    0|Active     |    0|System Bundle (5.4.0)|5.4.0
    1|Active     |    1|Guava: Google Core Libraries for Java (18.0.0)|18.0.0
    2|Active     |    1|Jackson-annotations (2.7.0)|2.7.0
    3|Active     |    1|Jackson-core (2.7.4)|2.7.4
    4|Active     |    1|jackson-databind (2.7.4)|2.7.4
    5|Active     |    1|com.github.shumy.leffe-wg (1.0.0)|1.0.0
    6|Active     |    1|Netty/Buffer (4.1.8.Final)|4.1.8.Final
    7|Active     |    1|Netty/Codec (4.1.8.Final)|4.1.8.Final
    8|Active     |    1|Netty/Codec/DNS (4.1.8.Final)|4.1.8.Final
    9|Active     |    1|Netty/Codec/HTTP (4.1.8.Final)|4.1.8.Final
   10|Active     |    1|Netty/Codec/HTTP2 (4.1.8.Final)|4.1.8.Final
   11|Active     |    1|Netty/Codec/Socks (4.1.8.Final)|4.1.8.Final
   12|Active     |    1|Netty/Common (4.1.8.Final)|4.1.8.Final
   13|Active     |    1|Netty/Handler (4.1.8.Final)|4.1.8.Final
   14|Active     |    1|Netty/Handler/Proxy (4.1.8.Final)|4.1.8.Final
   15|Active     |    1|Netty/Resolver (4.1.8.Final)|4.1.8.Final
   16|Active     |    1|Netty/Resolver/DNS (4.1.8.Final)|4.1.8.Final
   17|Active     |    1|Netty/Transport (4.1.8.Final)|4.1.8.Final
   18|Active     |    1|Apache Felix Configuration Admin Service (1.8.14)|1.8.14
   19|Active     |    1|Apache Felix Gogo Command (0.16.0)|0.16.0
   20|Active     |    1|Apache Felix Gogo Runtime (0.16.2)|0.16.2
   21|Active     |    1|Apache Felix Gogo Shell (0.12.0)|0.12.0
   22|Active     |    1|Apache Felix Declarative Services (2.0.8)|2.0.8
   23|Active     |    1|Xtend Runtime Library (2.11.0.v20170124-1424)|2.11.0.v20170124-1424
   24|Active     |    1|Xtend Macro Interfaces (2.11.0.v20170124-1424)|2.11.0.v20170124-1424
   25|Active     |    1|Xbase Runtime Library (2.11.0.v20170124-1424)|2.11.0.v20170124-1424
   26|Active     |    1|OPS4J Pax Logging - API (1.9.1)|1.9.1
   27|Active     |    1|Vert.x Core (3.4.1)|3.4.1

### Logs and stack trace
Welcome to Apache Felix Gogo

g! Activate leffe-wg...
[io.netty.util.internal.logging.InternalLoggerFactory] : Using SLF4J as the default logging framework
[io.netty.util.ResourceLeakDetector] : -Dio.netty.leakDetection.level: simple
[io.netty.util.ResourceLeakDetector] : -Dio.netty.leakDetection.maxRecords: 4
[io.netty.channel.MultithreadEventLoopGroup] : -Dio.netty.eventLoopThreads: 16
[io.netty.util.internal.PlatformDependent] : -Dio.netty.noUnsafe: false
[io.netty.util.internal.PlatformDependent0] : java.nio.Buffer.address: available
[io.netty.util.internal.PlatformDependent] : Java version: 8
[io.netty.util.internal.PlatformDependent] : maxDirectMemory: 1832910848 bytes (maybe)
[io.netty.util.internal.PlatformDependent] : -Dio.netty.noJavassist: false
[io.netty.util.internal.PlatformDependent] : Javassist: unavailable
[io.netty.util.internal.PlatformDependent] : You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
[io.netty.util.internal.PlatformDependent] : -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[io.netty.util.internal.PlatformDependent] : -Dio.netty.bitMode: 64 (sun.arch.data.model)
[io.netty.util.internal.PlatformDependent] : -Dio.netty.noPreferDirect: true
[io.netty.util.internal.PlatformDependent] : Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[io.netty.util.internal.PlatformDependent] : io.netty.maxDirectMemory: -1 bytes
[io.netty.channel.nio.NioEventLoop] : -Dio.netty.noKeySetOptimization: false
[io.netty.channel.nio.NioEventLoop] : -Dio.netty.selectorAutoRebuildThreshold: 512
[io.netty.util.internal.PlatformDependent] : org.jctools-core.MpscChunkedArrayQueue: unavailable
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling JULI Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J v2 API support. Ignored FQCN: org.apache.logging.log4j.spi.AbstractLogger
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.numHeapArenas: 16
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.numDirectArenas: 16
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.pageSize: 8192
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.maxOrder: 11
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.chunkSize: 16777216
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.tinyCacheSize: 512
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.smallCacheSize: 256
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.normalCacheSize: 64
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.maxCachedBufferCapacity: 32768
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.cacheTrimInterval: 8192
io.netty.common[io.netty.buffer.PooledByteBufAllocator] : -Dio.netty.allocator.useCacheForAllThreads: true
io.netty.common[io.netty.channel.DefaultChannelId] : Could not invoke ManagementFactory.getRuntimeMXBean().getName(); Android?
java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
	at io.netty.util.internal.PlatformDependent.getClassLoader(PlatformDependent.java:874)
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:113)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:78)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:86)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$doBind$2(AsyncResolveConnectHelper.java:78)
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:89)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
io.netty.common[io.netty.channel.DefaultChannelId] : Could not invoke Process.myPid(); not Android?
java.lang.ClassNotFoundException: android/os/Process
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:126)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:78)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:86)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$doBind$2(AsyncResolveConnectHelper.java:78)
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:89)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
io.netty.common[io.netty.util.internal.ThreadLocalRandom] : -Dio.netty.initialSeedUniquifier: 0x153a5d61a8da2108
io.netty.common[io.netty.channel.DefaultChannelId] : Failed to find the current process ID from ''; using a random value: -885700473
io.netty.common[io.netty.channel.DefaultChannelId] : -Dio.netty.processId: -885700473 (auto-detected)
io.netty.common[io.netty.util.NetUtil] : -Djava.net.preferIPv4Stack: false
io.netty.common[io.netty.util.NetUtil] : -Djava.net.preferIPv6Addresses: false
io.netty.common[io.netty.util.NetUtil] : Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
io.netty.common[io.netty.util.NetUtil] : /proc/sys/net/core/somaxconn: 128
io.netty.common[io.netty.channel.DefaultChannelId] : -Dio.netty.machineId: 68:5d:43:ff:fe:ee:bb:64 (auto-detected)
io.netty.common[io.netty.buffer.ByteBufUtil] : -Dio.netty.allocator.type: pooled
io.netty.common[io.netty.buffer.ByteBufUtil] : -Dio.netty.threadLocalDirectBufferSize: 65536
io.netty.common[io.netty.buffer.ByteBufUtil] : -Dio.netty.maxThreadLocalCharBufferSize: 16384
org.ops4j.pax.logging.pax-logging-api[com.github.shumy.leffewg.LeffeVerticle] : Server is now listening on port 9191.

**Comment by johnou** [comment] 2017-03-16 16:34
@shumy those exceptions are debug level logger statements, changing your log level to info or warn should do the trick.

**Comment by johnou** [comment] 2017-03-16 16:36
you could optionally set ```-Dio.netty.processId=$$``` when starting the JVM if you want to prevent Netty from trying to determine the process pid.

**Comment by shumy** [comment] 2017-03-16 16:40
I thought this was affecting vertx behavior, because I'm unable to receive a response from port 9191.

**Comment by shumy** [comment] 2017-03-17 11:03
Also, from the Netty logs I'm receiving requests, but nothing comes out:

```
io.netty.common[io.netty.handler.logging.LoggingHandler] : [id: 0x1f5489d4, L:/127.0.0.1:9191 - R:/127.0.0.1:49494] RECEIVED: 141B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
|00000010| 55 73 65 72 2d 41 67 65 6e 74 3a 20 57 67 65 74 |User-Agent: Wget|
|00000020| 2f 31 2e 31 37 2e 31 20 28 6c 69 6e 75 78 2d 67 |/1.17.1 (linux-g|
|00000030| 6e 75 29 0d 0a 41 63 63 65 70 74 3a 20 2a 2f 2a |nu)..Accept: */*|
|00000040| 0d 0a 41 63 63 65 70 74 2d 45 6e 63 6f 64 69 6e |..Accept-Encodin|
|00000050| 67 3a 20 69 64 65 6e 74 69 74 79 0d 0a 48 6f 73 |g: identity..Hos|
|00000060| 74 3a 20 6c 6f 63 61 6c 68 6f 73 74 3a 39 31 39 |t: localhost:919|
|00000070| 31 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 4b |1..Connection: K|
|00000080| 65 65 70 2d 41 6c 69 76 65 0d 0a 0d 0a          |eep-Alive....   |
+--------+-------------------------------------------------+----------------+
io.netty.common[io.netty.handler.logging.LoggingHandler] : [id: 0x1f5489d4, L:/127.0.0.1:9191 - R:/127.0.0.1:49494] CLOSE
io.netty.common[io.netty.handler.logging.LoggingHandler] : [id: 0x1f5489d4, L:/127.0.0.1:9191 ! R:/127.0.0.1:49494] INACTIVE
io.netty.common[io.netty.handler.logging.LoggingHandler] : [id: 0x1f5489d4, L:/127.0.0.1:9191 ! R:/127.0.0.1:49494] CLOSE
io.netty.common[io.netty.handler.logging.LoggingHandler] : [id: 0x1f5489d4, L:/127.0.0.1:9191 ! R:/127.0.0.1:49494] UNREGISTERED
```

**Comment by shumy** [comment] 2017-03-17 13:26
OK, I found the solution myself, and this will probably be a problem on Java 9.
Seems that "sun.misc.Unsafe" is not optional in OSGi, Apache Felix!!

Just added the dependency "com.diffplug.osgi:com.diffplug.osgi.extension.sun.misc:0.0.0", this will provide the "sun.misc.Unsafe".

**Comment by johnou** [comment] 2017-03-17 14:48
@shumy at least it should be marked optional https://github.com/netty/netty/blob/4.1/pom.xml#L857 is there a problem with the Import-Package?

**Comment by shumy** [comment] 2017-03-17 15:01
I mean... optional or not in the manifest, if I do not expose the "sun.misc" in the OSGi container it will not work. Vert.x responses don't get out. No errors thrown!

**Comment by Scottmitch** [comment] 2017-03-30 23:13
We (the Netty project maintainers) don't have much experience with OSGi and rely upon the community to drive these changes. So PRs are welcome if there are issue with OSGi. Please update to Netty 4.1.9 and submit a PR if its still broken.

**Comment by normanmaurer** [comment] 2017-04-19 10:28
@shumy ^^ . Could you provide a PR ?

**Comment by ashkanpaya88** [comment] 2017-06-13 22:04
I get the same stack trace error on 4.1.11.Final

D 06-13 21:44:57.355 pool-1-thread-1 i.n.u.i.l.InternalLoggerFactory:71 |::] Using SLF4J as the default logging framework
D 06-13 21:44:57.363 pool-1-thread-1 i.n.u.i.PlatformDependent0:76 |::] -Dio.netty.noUnsafe: false
D 06-13 21:44:57.366 pool-1-thread-1 i.n.u.i.PlatformDependent0:71 |::] sun.misc.Unsafe.theUnsafe: available
D 06-13 21:44:57.366 pool-1-thread-1 i.n.u.i.PlatformDependent0:71 |::] sun.misc.Unsafe.copyMemory: available
D 06-13 21:44:57.367 pool-1-thread-1 i.n.u.i.PlatformDependent0:71 |::] java.nio.Buffer.address: available
D 06-13 21:44:57.368 pool-1-thread-1 i.n.u.i.PlatformDependent0:71 |::] direct buffer constructor: available
D 06-13 21:44:57.369 pool-1-thread-1 i.n.u.i.PlatformDependent0:76 |::] java.nio.Bits.unaligned: available, true
D 06-13 21:44:57.372 pool-1-thread-1 i.n.u.i.PlatformDependent0:91 |::] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:288)
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:895)
	at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:919)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:70)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
	at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
	at com.maginatics.raptor.RaptorConfiguration.<clinit>(RaptorConfiguration.java:486)
	....

**Comment by Scottmitch** [comment] 2017-06-13 23:12
@ashkanpaya88 - this doesn't look like the same stack trace to me. Please file a new issue with the relevant information (platform type / OS, etc..)

**Comment by ashkanpaya88** [comment] 2017-06-13 23:43
Sure, filed it here: https://github.com/netty/netty/issues/6855

**Comment by shumy** [comment] 2017-06-14 09:45
@normanmaurer PR? I didn't change anything on the Netty project, I just exposed the sun.misc package to the OSGi container.

**Comment by timothyjward** [comment] 2017-11-22 19:05
I also have a similar problem running in OSGi - it happens because there's no protection covering the case where Unsafe is totally unloadable. It should be an easy fix...

    Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at io.netty.util.internal.PlatformDependent0$1.run(PlatformDependent0.java:86)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:82)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:97)
	at com.paremus.dosgi.net.activator.Activator.<clinit>(Activator.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:763)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:716)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:956)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:308)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)

**Comment by normanmaurer** [comment] 2017-11-22 19:06
@timothyjward if its easy for you to fix please provide a PR... I have more or less zero experience with OSGI and so not even know how to test this .

**Comment by normanmaurer** [comment] 2017-11-22 20:01
@timboudreau actually let me fix it ... I see now what you mean

**Comment by johnou** [comment] 2017-11-22 20:02
@normanmaurer just missing a catch NoClassDefFoundError in the static init block right?

**Comment by normanmaurer** [comment] 2017-11-22 20:05
@timothyjward PTAL https://github.com/netty/netty/pull/7432... 

@johnou yep

**Comment by timothyjward** [comment] 2017-11-22 20:05
I went with a single `catch(Throwable t)` which will cover any nonsense that might occur

**Comment by normanmaurer** [comment] 2017-11-22 20:06
@timothyjward we actually removed the catch `Throwable` to not catch everything... I think it was @jasontedor who did the change to not catch everything.

**Comment by normanmaurer** [comment] 2017-11-22 20:07
I would prefer to not use `catch Throwable` again if possible.

**Comment by johnou** [comment] 2017-11-22 20:07
@timothyjward we have been trying to steer clear of catching throwable to avoid swallowing out of memory exceptions.

**Comment by timothyjward** [comment] 2017-11-22 20:10
Fair enough - then feel free to do something different from PR #7433 - I have confirmed that this PR fixes the problem for me in my environment, but there's definitely more than one way to fix it. 

Checking the throwable and rethrowing OutOfMemoryError would be one way out, but I accept that your experience with OOM is greater than mine 👍

**Comment by timothyjward** [comment] 2017-11-22 20:13
If you do choose to avoid catching throwable can I recommend adding a general `catch(Exception e)` block? The code really doesn't care what the type of the exception is, and currently there are lots of RuntimeExceptions that can escape.

**Comment by normanmaurer** [comment] 2017-11-22 20:18
Maybe we should catch `RuntimeException` and `LinkageError`.

**Comment by jasontedor** [comment] 2017-11-22 20:31
If unsafe is available, why not set the system property `io.netty.noUnsafe` to `true` and then no changes are needed in Netty for an environment the maintainers have no experience with, no tests for, etc.?

**Comment by timothyjward** [comment] 2017-11-22 20:58
> If unsafe is unavailable, why not set the system property io.netty.noUnsafe to true and then no changes are needed in Netty for an environment the maintainers have no experience with, no tests for, etc.?

So this isn't an OSGi problem per se, it's just that OSGi is an easy way to create the conditions for this method to fail. Netty takes pride in being able to work with or without access to `Unsafe` - in this case Netty is running in an environment where there is no `sun.misc.Unsafe` at all (rather than an environment where `Unsafe` is protected by the VM). This scenario can easily happen on any VM that doesn't have `Unsafe`, and appears to be the main reason for `PlatformDependent0` to exist.

In addition - the person who is deploying the bundle may have no idea that netty is inside it (somewhat like shading inside a jar), and may not have access to set System properties at a suitable time.

I agree that tests are a good thing. [Netty appears to have some OSGi tests already (well one)](https://github.com/netty/netty/blob/4.1/testsuite-osgi/src/test/java/io/netty/osgitests/OsgiBundleTest.java). This regression could be tested for by attempting to instantiate one of the platform dependent netty types, e.g. a direct `ByteBuf`.

**Comment by jasontedor** [comment] 2017-11-22 21:28
> So this isn't an OSGi problem per se, it's just that OSGi is an easy way to create the conditions for this method to fail.

You've convinced me.

**Comment by normanmaurer** [comment] 2017-12-13 13:23
I think this is fixed now.

**Closed by normanmaurer** 2017-12-13 13:23 UTC

**Comment by liyouxina** [comment] 2022-08-31 03:18
I fix it by adding this to JVM args
--add-opens java.base/jdk.internal.misc=ALL-UNNAMED
