### ISSUE TITLE
NPE in AbstractNioChannel.doBeginRead

### ISSUE THREAD

**Issue by richdougherty** [netty/netty#4571] opened 2015-12-14 23:18 UTC
I occasionally see an NPEs in Netty 4.0.33.Final when running a [Play Framework](https://github.com/playframework/playframework) performance test. The error appears to be random. It happens about once every two minutes under load of 50,000 requests/second.

```
java.lang.NullPointerException: null
        at io.netty.channel.nio.AbstractNioChannel.doBeginRead(AbstractNioChannel.java:366) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:683) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1117) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:614) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:595) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:614) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:595) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:614) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:595) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at com.typesafe.netty.HandlerPublisher.requestDemand(HandlerPublisher.java:86) ~[com.typesafe.netty.netty-reactive-streams-1.0.1.jar:na]
        at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:263) ~[com.typesafe.netty.netty-reactive-streams-1.0.1.jar:na]
        at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41) ~[com.typesafe.netty.netty-reactive-streams-1.0.1.jar:na]
        at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:444) ~[com.typesafe.netty.netty-reactive-streams-1.0.1.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) ~[io.netty.netty-common-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[io.netty.netty-transport-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[io.netty.netty-common-4.0.33.Final.jar:4.0.33.Final]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]
```

Machine info:
```
Linux <servername> 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Java info:
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by normanmaurer** [comment] 2015-12-15 06:29
Let me have a look

**Comment by richdougherty** [comment] 2015-12-15 06:42
Thanks. In case it helps, here's the class that's calling Netty: https://github.com/typesafehub/netty-reactive-streams/blob/master/netty-reactive-streams/src/main/java/com/typesafe/netty/HandlerPublisher.java

**Comment by dzagorovsky** [comment] 2015-12-16 12:16
Currently we migrated our product to Play 2.5.0-M1 and notices the same behaviour with a regular requests (no load).

**Comment by normanmaurer** [comment] 2015-12-16 12:17
@dzagorovsky could you provide a reproducer somehow ? Using play would be good enough

**Comment by richdougherty** [comment] 2015-12-16 19:14
Here is a ZIP file that can be used to reproduce the problem.

https://drive.google.com/file/d/0B0SP9EBGIOe5aUFWYzNOZFBKX0k/view?usp=sharing

Once you've unzipped the file, the command to start the application is:

```
JAVA_HOME=<path to Java 1.8.0_45> JAVA_OPTS="-Xms1g -Xmx1g" bin/scala-di-bench
```

The command to test the application is:

```
wrk -c32 -t16 -d<duration in seconds>s http://localhost:9000/simple
```

I can reproduce this on a Linux test machine but not on my Mac OS laptop. I usually see 1-3 errors every 5 minutes of load testing. When there is an exception it will be reported by wrk as an error. The exception details will be logged to the application's `logs/application.log` file.

The ZIP already contains a `logs/application.log` file from a previous test run. The logs in the ZIP file show an example of NPE. In addition to showing an NPE, the logs in the ZIP file also show an `IllegalStateException`. This exception doesn't usually appear in the logs, so I think it's unrelated to the NPE, but you might notice something interesting, so take a look. I think the `IllegalStateException` is a bug with Play's usage of Netty, rather than with Netty itself.

I've already included details of OS and Java versions. Here's the version of wrk that is used:

```
wrk 3.1.1 [epoll] Copyright (C) 2012 Will Glozer
```

**Comment by normanmaurer** [comment] 2015-12-16 19:26
@richdougherty thanks will have a look tomorrow :)

**Comment by normanmaurer** [comment] 2015-12-16 19:34
@richdougherty awesome ... I was able to reproduce after giving it a quick try :+1: Will look into it

**Comment by richdougherty** [comment] 2015-12-16 21:08
Thanks @normanmaurer!

**Comment by normanmaurer** [comment] 2015-12-16 21:22
@richdougherty but to make it short yes it is kind of bad usage of netty... You should only call `read()` once `isRegistered()` returns true or the `ChannelFuture` of `register(...)` is notified. That said we should never throw a NPE, so I will fix this

**Comment by richdougherty** [comment] 2015-12-16 21:29
OK, I'll fix Play, thanks a lot for tracking down the problem. Are you going to change Netty to throw an `IllegalStateException` instead?

**Comment by jroper** [comment] 2015-12-17 23:58
@normanmaurer Is it similarly invalid to invoke `Channel.close()` before `isRegistered()` returns true?  Because that's another call that it's possible that we will invoke after `handlerAdded()` is received but before `channelActive()` is received.

**Comment by richdougherty** [comment] 2016-01-31 21:35
@jroper, this should be fixed now, right?

**Comment by jroper** [comment] 2016-01-31 23:45
Yep.

**Comment by Scottmitch** [comment] 2016-02-01 20:24
@richdougherty @jroper - I'll close this then ... feel free to re-open or file another issue if it still exists.

**Comment by normanmaurer** [comment] 2016-02-01 20:25
@Scottmitch this is only "fixed" in play not in need yet.

**Comment by Scottmitch** [comment] 2016-02-01 20:27
@normanmaurer - Woops sry about that

**Comment by jroper** [comment] 2016-02-02 18:53
Sorry, the bad behaviour in Play that triggered this issue is fixed, the better error reporting is not.

**Comment by normanmaurer** [comment] 2016-05-18 12:02
Not happens in 4.0.37.final anymore :)

**Closed by normanmaurer** 2016-05-18 12:02 UTC
Labels: defect
