### ISSUE TITLE
All tests for channel re-registering stop working after migration 4.0.33 -> 4.0.34

### ISSUE THREAD

**Issue by doom369** [netty/netty#4805] opened 2016-02-01 11:35 UTC
Hello. I have a lot of different tests for testing channel re-register. After update to latest version all of them started failing. The scenario is pretty simple.

Client1 logins. Cleint2 logins. 
```
if (client2.eventLoop != client1.eventLoop) {
    client2.reregister()
}
```
Client1 send message, Client2 checks it get message.

My findings so far - after channel is re-registered it stops receive messages (no handlers within pipeline is invoked). I have a feeling all incoming messages are still processed with old EventLoop or something like that.

[Client2 pipeline.](https://github.com/blynkkk/blynk-server/blob/master/server/tcp-hardware-server/src/main/java/cc/blynk/server/hardware/HardwareServer.java#L38)
[Reregister logic](https://github.com/blynkkk/blynk-server/blob/master/server/tcp-hardware-server/src/main/java/cc/blynk/server/hardware/handlers/hardware/auth/HardwareLoginHandler.java#L98)
and [here](https://github.com/blynkkk/blynk-server/blob/master/server/core/src/main/java/cc/blynk/server/handlers/DefaultReregisterHandler.java#L15)

Let me know if you need more info.

**Comment by normanmaurer** [comment] 2016-02-01 15:01
@doom369 thanks will have a look. I have kind of the feeling that it may be related to:
https://github.com/netty/netty/commit/ba381f1a27c3251fa13725f09dd0cb771326f113

**Comment by normanmaurer** [comment] 2016-02-01 15:22
@doom369 tried to reproduce with a unit test but no luck :( Could you try to write a small unit test for it ? Maybe have a look at `DefaultChannelPipelineTest` and add something in there which shows the problem with netty only ?

**Comment by doom369** [comment] 2016-02-01 16:56
@normanmaurer here you go :

```
import io.netty.bootstrap.Bootstrap;
import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;

import java.net.InetSocketAddress;
import java.nio.ByteBuffer;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * The Blynk Project.
 * Created by Dmitriy Dumanskiy.
 * Created on 01.02.16.
 */
public class Reregister {


    private static final AtomicInteger i = new AtomicInteger();
    private static final Map<Integer, EventLoop> users = new ConcurrentHashMap<>();

    public static void main(String[] args) throws Exception {
        EventLoopGroup boss = new NioEventLoopGroup(1);
        EventLoopGroup worker = new NioEventLoopGroup(100);

        new Reregister().buildServerAndRun(boss, worker, NioServerSocketChannel.class);
        new Client().connect();
        try {
            Thread.sleep(100);
        } catch (Exception e) {

        }
        new Client().connect().send();
    }

    private void buildServerAndRun(EventLoopGroup bossGroup, EventLoopGroup workerGroup,
                                   Class<? extends ServerChannel> channelClass) throws Exception {

        ServerBootstrap b = new ServerBootstrap();
        try {
            b.group(bossGroup, workerGroup)
                    .channel(channelClass)
                    .childOption(ChannelOption.SO_KEEPALIVE, true)
                    .childHandler(getChannelInitializer());

            b.bind(8080).sync();
        } catch (Exception e) {
            throw e;
        }
    }

    protected ChannelInitializer<SocketChannel> getChannelInitializer() {
        return new ChannelInitializer<SocketChannel>() {
            @Override
            protected void initChannel(SocketChannel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();
                pipeline.addLast(
                        new SimpleChannelInboundHandler<ByteBuf>() {
                            @Override
                            protected void channelRead0(ChannelHandlerContext ctx, ByteBuf byteBuf) throws Exception {
                                System.out.println("Retrieved message from " + ctx.channel());
                            }

                            @Override
                            public void channelActive(ChannelHandlerContext ctx) throws Exception {
                                System.out.println("Server: channel active. Channel : " + ctx.channel());

                                EventLoop eventLoop = users.get(i.get());
                                if (eventLoop == null) {
                                    System.out.println("Server: Creating new user " + ctx.channel().eventLoop());
                                    users.put(i.incrementAndGet(), ctx.channel().eventLoop());
                                } else {
                                    System.out.println("Server: Re register from " + ctx.channel().eventLoop() + " to " + eventLoop);
                                    reRegisterChannel(ctx, eventLoop, channelFuture -> completeLogin());
                                }
                            }
                        }
                );
            }
        };
    }

    private static void completeLogin() {
        System.out.println("Complete re register.");
    }

    private static void reRegisterChannel(ChannelHandlerContext ctx, EventLoop eventLoop, ChannelFutureListener completeHandler) {
        ChannelFuture cf = ctx.deregister();
        cf.addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture channelFuture) throws Exception {
                eventLoop.register(channelFuture.channel()).addListener(completeHandler);
            }
        });
    }

    private static class Client {

        private Channel channel;

        public Client connect() {
            EventLoopGroup group = new NioEventLoopGroup();

            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(group).channel(NioSocketChannel.class);
            ChannelFuture future = bootstrap
                    .handler(new SimpleChannelInboundHandler<ByteBuf>() {
                        @Override
                        protected void channelRead0(ChannelHandlerContext ctx, ByteBuf byteBuf) throws Exception {
                            System.out.println("read");
                        }
                    })
                    .connect(new InetSocketAddress("localhost", 8080));
            future.addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture channelFuture) throws Exception {
                    if (channelFuture.isSuccess()) {
                        System.out.println("Client : Connection established");
                    } else {
                        System.err.println("Connection attempt failed");
                        channelFuture.cause().printStackTrace();
                    }
                }
            });

            try {
                this.channel = future.sync().channel();
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(0);
            }

            return this;
        }

        public Client send() {
            channel.writeAndFlush(Unpooled.wrappedBuffer(ByteBuffer.allocate(1).array()));
            return this;
        }
    }

}
```

This code will print for 4.0.33
`Retrieved message from `

But you'll get nothing for 4.0.34

**Comment by normanmaurer** [comment] 2016-02-01 17:58
@doom369 awesome! I know where the problem is and work on a fix. For a workaround just call `ctx.read()` or `channel.read()` in the ChannelFuture that is added to `eventLoop.register`.

**Comment by doom369** [comment] 2016-02-01 18:14
@normanmaurer good.

> For a workaround just call ctx.read() or channel.read() in the ChannelFuture that is added to eventLoop.register.

Hm, doesn't help, tried to add in few places. Maybe I didn't understood you correctly.

**Comment by normanmaurer** [comment] 2016-02-02 17:53
@doom369 please check https://github.com/netty/netty/pull/4814. This fixes the problem here.

**Comment by doom369** [comment] 2016-02-02 18:37
@normanmaurer Above example works. Most of tests fine also. But still there are few that doesn't work. I'm using tcp, http, websockets and SSL versions of them. And all of them has pipelines with reregister logic. Http reregister tests not work anymore. I'll try to make a reproducer for HTTP, but a bit later. Maybe tomorrow.

**Comment by normanmaurer** [comment] 2016-02-02 19:14
@doom369 thanks!

**Comment by doom369** [comment] 2016-02-03 14:16
@normanmaurer started this morning with coffee and reproducer for you =). Here you go (hope I didn't make any mistake) :

```
import io.netty.bootstrap.Bootstrap;
import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.*;
import io.netty.util.ReferenceCountUtil;

import java.net.InetSocketAddress;
import java.nio.ByteBuffer;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

import static io.netty.handler.codec.http.HttpResponseStatus.OK;
import static io.netty.handler.codec.http.HttpVersion.HTTP_1_1;

/**
 * The Blynk Project.
 * Created by Dmitriy Dumanskiy.
 * Created on 01.02.16.
 */
public class Reregister {


    private static final AtomicInteger i = new AtomicInteger();
    private static final Map<Integer, EventLoop> users = new ConcurrentHashMap<>();

    public static void main(String[] args) throws Exception {
        EventLoopGroup boss = new NioEventLoopGroup(1);
        EventLoopGroup worker = new NioEventLoopGroup(100);

        Reregister reregister = new Reregister();
        reregister.buildServerAndRun(boss, worker, NioServerSocketChannel.class, 8080, reregister.getTCPChannelInitializer());
        reregister.buildServerAndRun(boss, worker, NioServerSocketChannel.class, 8181, reregister.getHTTPChannelInitializer());
        new TCPClient(8080).connect();
        Thread.sleep(100);
        new TCPClient(8080).connect().send();
        Thread.sleep(100);
        new HTTPClient(8181).connect().send();
    }

    private void buildServerAndRun(EventLoopGroup bossGroup, EventLoopGroup workerGroup,
                                   Class<? extends ServerChannel> channelClass, int port, ChannelHandler channelHandler) throws Exception {
        ServerBootstrap b = new ServerBootstrap();
        b.group(bossGroup, workerGroup)
                .channel(channelClass)
                .childOption(ChannelOption.SO_KEEPALIVE, true)
                .childHandler(channelHandler);

        b.bind(port).sync();
    }

    public ChannelInitializer<SocketChannel> getTCPChannelInitializer() {
        return new ChannelInitializer<SocketChannel>() {
            @Override
            protected void initChannel(SocketChannel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();
                pipeline.addLast(
                        new SimpleChannelInboundHandler<ByteBuf>() {
                            @Override
                            protected void channelRead0(ChannelHandlerContext ctx, ByteBuf byteBuf) throws Exception {
                                System.out.println("Retrieved message from " + ctx.channel());
                            }

                            @Override
                            public void channelActive(ChannelHandlerContext ctx) throws Exception {
                                System.out.println("Server: channel active. Channel : " + ctx.channel());

                                EventLoop eventLoop = users.get(i.get());
                                if (eventLoop == null) {
                                    System.out.println("Server: Creating new user " + ctx.channel().eventLoop());
                                    users.put(i.incrementAndGet(), ctx.channel().eventLoop());
                                } else {
                                    System.out.println("Server: Re register from " + ctx.channel().eventLoop() + " to " + eventLoop);
                                    reRegisterChannel(ctx, eventLoop, channelFuture -> completeLoginTCP(channelFuture.channel()));
                                }
                            }
                        }
                );
            }
        };
    }

    public ChannelInitializer<SocketChannel> getHTTPChannelInitializer() {
        return new ChannelInitializer<SocketChannel>() {
            @Override
            protected void initChannel(SocketChannel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();
                pipeline.addLast(
                        new HttpServerCodec(200, 200, 1024),
                        new HttpObjectAggregator(1024, true),
                        new ChannelInboundHandlerAdapter() {
                            @Override
                            public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
                                if (!(msg instanceof HttpRequest)) {
                                    return;
                                }

                                HttpRequest req = (HttpRequest) msg;

                                try {
                                    System.out.println("HTTP Server: got request. Channel : " + ctx.channel());

                                    EventLoop eventLoop = users.get(i.get());
                                    if (eventLoop == null) {
                                        System.out.println("HTTP Server: Creating new user " + ctx.channel().eventLoop());
                                        users.put(i.incrementAndGet(), ctx.channel().eventLoop());
                                    } else {
                                        System.out.println("HTTP Server: Re register from " + ctx.channel().eventLoop() + " to " + eventLoop);
                                        reRegisterChannel(ctx, eventLoop, channelFuture -> completeLoginHTTP(channelFuture.channel()));
                                    }

                                } finally {
                                    ReferenceCountUtil.release(msg);
                                }
                            }
                        }
                );

            }
        };
    }


    private void completeLoginTCP(Channel channel) {
        channel.writeAndFlush(Unpooled.wrappedBuffer(ByteBuffer.allocate(1).array()));
        System.out.println("Complete TCP re register.");
    }

    private void completeLoginHTTP(Channel channel) {
        channel.writeAndFlush(new DefaultFullHttpResponse(HTTP_1_1, OK));
        System.out.println("Complete HTTP re register.");
    }

    private static void reRegisterChannel(ChannelHandlerContext ctx, EventLoop eventLoop, ChannelFutureListener completeHandler) {
        ChannelFuture cf = ctx.deregister();
        cf.addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture channelFuture) throws Exception {
                eventLoop.register(channelFuture.channel()).addListener(completeHandler);
            }
        });
    }

    private static class TCPClient {

        private Channel channel;
        private int port;

        public TCPClient(int port) {
            this.port = port;
        }

        public TCPClient connect() throws Exception {
            EventLoopGroup group = new NioEventLoopGroup();

            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(group).channel(NioSocketChannel.class);
            ChannelFuture future = bootstrap
                    .handler(new SimpleChannelInboundHandler<ByteBuf>() {
                        @Override
                        protected void channelRead0(ChannelHandlerContext ctx, ByteBuf byteBuf) throws Exception {
                            System.out.println("TCP HERE");
                        }
                    })
                    .connect(new InetSocketAddress("localhost", port));

            this.channel = future.sync().channel();
            return this;
        }

        public TCPClient send() {
            channel.writeAndFlush(Unpooled.wrappedBuffer(ByteBuffer.allocate(1).array()));
            return this;
        }
    }

    private static class HTTPClient {

        private Channel channel;
        private int port;

        public HTTPClient(int port) {
            this.port = port;
        }

        public HTTPClient connect() throws Exception {
            EventLoopGroup group = new NioEventLoopGroup();

            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(group).channel(NioSocketChannel.class);
            ChannelFuture future = bootstrap
                    .handler(getHttpPipeline())
                    .connect(new InetSocketAddress("localhost", port));

            this.channel = future.sync().channel();
            return this;
        }

        private  ChannelInitializer<SocketChannel> getHttpPipeline() {
            return new ChannelInitializer<SocketChannel>() {
                @Override
                protected void initChannel(SocketChannel ch) throws Exception {
                    ChannelPipeline p = ch.pipeline();
                    p.addLast(new HttpClientCodec());
                    p.addLast(new SimpleChannelInboundHandler<HttpObject>() {
                        @Override
                        protected void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
                            System.out.println("HTTP HERE");
                        }
                    });
                }
            };
        }

        public HTTPClient send() {
            HttpRequest request = new DefaultFullHttpRequest(
                    HttpVersion.HTTP_1_1, HttpMethod.GET, "http://localhost:" + port + "/aaa");
            channel.writeAndFlush(request);
            return this;
        }
    }
}
```

**Comment by normanmaurer** [comment] 2016-02-04 14:24
@doom369 thanks again. This is actually another bug :( https://github.com/netty/netty/pull/4839 . With this pulled in all works now.

**Comment by normanmaurer** [comment] 2016-02-04 14:40
Fixed by #4814 and #4839

**Closed by normanmaurer** 2016-02-04 14:40 UTC
Labels: defect

**Comment by doom369** [comment] 2016-02-04 16:48
@normanmaurer Now situation is much better. But I still have failing tests and seems this is related with your fix.

**Comment by normanmaurer** [comment] 2016-02-04 16:56
Any more reproducers?

**Comment by doom369** [comment] 2016-02-04 16:57
@normanmaurer Will do tomorrow. Have to go now.

**Comment by johnou** [comment] 2016-02-05 10:09
@doom369 you rock!

**Comment by doom369** [comment] 2016-02-05 12:54
@johnou =). Thank you!
@normanmaurer Look like everything fine. Those tests that failed were wrong. Now I'm confused as do not understand how did they work with 4.0.33 =). But anyway thank you for quick fixes!

**Comment by normanmaurer** [comment] 2016-02-05 13:22
Yay thx!
