### ISSUE TITLE
Netty 4.0.26 - java.io.IOException: syscall:read(...)() failed: Connection reset by peer

### ISSUE THREAD

**Issue by kyankovski** [netty/netty#3539] opened 2015-03-26 12:35 UTC
We use netty as a high-load http-server with native linux epoll transport. I tried to update version from 4.0.23 to 4.0.26, but have got a lot of exceptions like this one (IP is hidden by me):

[2015-03-25 09:10:24,448] ERROR - .n.ChannelInboundHandler2ExchangeAdapter - exception when handling request from /54.xxx.xxx.xxx:63512 
java.io.IOException: syscall:read(...)() failed: Connection reset by peer

This exception was reproduced only with high loading, but not locally. After rolling back to 4.0.23 the server works as well with no exceptions.

Server configuration:

java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

$ uname -a
Linux domain.foo.com 2.6.32-358.18.1.el6.x86_64 #1 SMP Wed Aug 28 17:19:38 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment] 2015-03-26 12:38
Do you have a full stacktrace? Also do you have a reproducer which you can share?

**Comment by normanmaurer** [comment] 2015-03-26 12:40
Also could you try 4.0.24 and 4.0.25 so we can get a better idea when this was introduced

**Comment by kyankovski** [comment] 2015-03-26 12:55
We tried to investigate this exception on prod servers, caught it in debug mode in ChannelInboundHandler2ExchangeAdapter#exceptionCaught. The exception had no cause, exc.getStackTrace() returned an empty array, and line 151 of this class (logger.error(messageBuilder.toString(), throwable);) simple printed an exception above.

As I previously said, I can reproduce this exception locally (at least for now, will try to reproduce it a bit later - really busy for now) - we caught it in production environment. And this is a reason why I can't try versions 4.0.24 and 4.0.25 - we are currently frozen with 4.0.23 and can't risk on prod.

**Comment by normanmaurer** [comment] 2015-03-30 16:54
@kyankovski hmm... this is strange... I'm just not sure how to start trying to track this down atm without more infos :/

**Comment by kyankovski** [comment] 2015-04-01 15:36
Hi! Sorry for delay...
Just checked the server with different netty versions:
4.0.25 - no errors
4.0.26 - a lot of errors as described above

**Comment by normanmaurer** [comment] 2015-04-01 15:41
@kyankovski thanks... let me try to find the root cause.

**Comment by doom369** [comment] 2015-04-01 15:58
Same for me. 4.0.26.Final. Java 1.8_40, Ubuntu 14.04.
I'm able to reproduce issue every time during performance tests when generating load ~5k req/sec. Usually this happens right after I interrupt tests without closing sockets correctly.

Also periodically I'm getting
```
java.io.IOException: readAddress() failed: Connection timed out
        at io.netty.channel.epoll.Native.newIOException(Native.java:124)
        at io.netty.channel.epoll.Native.ioResult(Native.java:140)
        at io.netty.channel.epoll.Native.readAddress(Native.java:242)
        at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:232)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:610)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollRdHupReady(AbstractEpollStreamChannel.java:573)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:315)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:250)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

Hope this info helps.

**Comment by normanmaurer** [comment] 2015-04-01 16:37
@doom369 you see this with 4.0.25.Final as well ?

**Comment by doom369** [comment] 2015-04-01 17:31
"Connection reset by peer" - yes. I see this in 4.0.25.Final also. But I'm not sure that this is bug... The only problem I see here is that exception doesn't have cause and stacktrace.

**Comment by normanmaurer** [comment] 2015-04-01 18:39
@doom369 this is expected as this will be "thrown" when the remote peer just "crashes".

**Comment by normanmaurer** [comment] 2015-04-02 07:43
@kyankovski can you give us more details like show the pipeline etc ? Even better would be to share the code that reproduce it. I'm currently feeling a bit helpless in terms of reproduce it here :/

**Comment by trustin** [comment] 2015-04-02 08:10
@doom369 It does not have stack trace or cause because we create an exception for 'connection reset' and reuse it over and over, to remove the instantiation cost.

**Comment by kyankovski** [comment] 2015-04-10 09:55
Hi, sorry for so big delay. I've looked through the changes 4.0.25->4.0.26 and found a lot of changes in io.netty.channel.epoll package. So I tried to switch the server from 'epoll' to 'nio' mode and all errors disappeared. (But we still want to work in 'epoll' mode.) So I believe is somewhere around epoll changes in 4.0.26.

There is a simplified part of our code where pipeline is initialized:
```java
private EventLoopGroup bossGroup;
		private EventLoopGroup workerGroup;
		private Channel serverChannel;
		
		if (epoolEnabled) {
			try {
				logger.info("epool initialization");
				bossGroup = new EpollEventLoopGroup(1);
				workerGroup = new EpollEventLoopGroup(threadsCount);
			} catch (Throwable e) {
				logger.error("epool initialization failed. using nio instead.", e);
			}
		}
		if (bossGroup == null) {
			bossGroup = new NioEventLoopGroup(1);
			workerGroup = new NioEventLoopGroup(threadsCount);
		}


		// Configure the server.
		final ServerBootstrap bootstrap = new ServerBootstrap();
		final String serverId = ServerId.get();
		final AtomicBoolean recordStatus = new AtomicBoolean(false);
		bootstrap.group(bossGroup, workerGroup)
				.channel(bossGroup instanceof EpollEventLoopGroup ? EpollServerSocketChannel.class : NioServerSocketChannel.class)
				.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, (int) ACTIVITY_TIMEOUT)
				.option(ChannelOption.SO_BACKLOG, backlog)
				.option(ChannelOption.SO_REUSEADDR, true)
				.childHandler(new ChannelInitializer<SocketChannel>() {
					@Override
					protected void initChannel(SocketChannel ch) throws Exception {
						ChannelPipeline pipeline = ch.pipeline();

						pipeline.addLast("codec-http", new HttpServerCodec(8192, 16384, 16384, true));
						pipeline.addLast("aggregator", new HttpObjectAggregator(65536));

						pipeline.addLast("handler", new ChannelInboundHandler2ExchangeAdapter(contexts, keepAlive, timer, serverName));

					}
				});

		// Bind and start to accept incoming connections.
		try {
			serverChannel = bootstrap.bind(address).sync().channel();
		} catch (InterruptedException e) {
			throw new RuntimeException("Interrupted", e);
		}
```

**Comment by normanmaurer** [comment] 2015-04-10 10:16
@kyankovski thanks will check in detail

**Comment by kyankovski** [comment] 2015-04-10 14:30
Unfortunately I still can't reproduce this bug locally, but if you have any ideas I can try some patched jar  on prod. So if it will help please provide a patch or a jar.

**Comment by normanmaurer** [comment] 2015-04-10 14:34
Working on it. Should have a jar soon :)

**Comment by normanmaurer** [comment] 2015-04-10 19:45
@kyankovski could you try to build a jar from the PR #3611 and use it ? This should hopefully fix your problem. Please let me know

**Comment by normanmaurer** [comment] 2015-04-13 13:34
@kyankovski ping :)

**Comment by kyankovski** [comment] 2015-04-13 13:48
Could you please send me a netty-all jar file? It will be much easier for me not to set up and build the project...

**Comment by normanmaurer** [comment] 2015-04-13 18:26
@kyankovski send me an email to norman dot maurer at googlemail dot com and I will respond with the jars :)

**Comment by kyankovski** [comment] 2015-04-15 14:45
@normanmaurer The bug is not reproduced with the provided jar.

**Comment by normanmaurer** [comment] 2015-04-15 16:43
Awesome thanks... closing :+1:

**Closed by normanmaurer** 2015-04-15 16:43 UTC
Labels: defect

**Comment by weijietong** [comment] 2017-08-31 03:42
@normanmaurer @trustin apache Drill use the 4.0.27.Final version , got the similar fail error infos :  "Caused by: java.io.IOException: syscall:write(...)() failed: Broken pipe"  、 " syscall:read(...)() failed: Connection reset by peer" when the system was suffering high concurrency query. And we substiuted epoll by nio ,the errors disappeared. 

So I want to know which version this bug is finally fixed? and what is the reason to cause this bug?

**Comment by weijietong** [comment] 2017-09-01 12:22
@normanmaurer I read the related fixed parts codes .It seems to solve the EPOLLRDUP problem which will cause the syscall:read() to fail by your descripted uncorrectly handling. Does this can protect the syscall::write() from throw exception ?At our scenario ,the syscall::write() failed more times than the syscall::read()

**Comment by kevin70** [comment] 2019-02-27 08:06
I had the same problem at `netty-4.1.31.Final`.

```
java.lang.RuntimeException: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.zhudy.duic.web.config.WebConfig$1.accept(WebConfig.kt:57)
	at io.zhudy.duic.web.config.WebConfig$1.accept(WebConfig.kt:47)
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:514)
	at reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:343)
	at reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:398)
	at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:185)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:426)
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
	at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
	at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1401)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:953)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:736)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:825)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:183)
	reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:289)
```

**Comment by tonyskulk** [comment] 2019-03-29 11:08
I have the same problem with **netty-4.1.33.Final**:

io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

**Comment by sunfriendli** [comment] 2019-08-30 08:46
I have the same problem with netty-4.1.34.Final:

io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[***.jar:?]

**Comment by xuanyimo** [comment] 2019-10-09 03:34
I have the same problem with netty-4.1.34.Final:

```java
io.netty.channel.unix.Errors$NativeIoException: syscall:write(..) failed: Broken pipe
	at io.netty.channel.unix.FileDescriptor.writeAddress(..)(Unknown Source))
```

**Comment by webdemon1** [comment] 2019-12-04 06:07
I have the same problem with netty-4.1.28.Final:

2019-12-04 at 02:08:16.005 UTC [NettyServerWorkThread_7] ERROR   - @WebSocketHandshakeHandler.exceptionCaught io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]

**Comment by Liesport758** [comment] 2020-01-08 06:56
I have the same problem with netty-4.1.31.Final:
