### ISSUE TITLE
Using an X509TrustManager with OPEN_SSL engine bypass hostname verification

### ISSUE THREAD

**Issue by vietj** [netty/netty#6664] opened 2017-04-24 16:29 UTC
### Expected behavior

Using an `X509TrustManager` with `OPEN_SSL` engine should perform hostname verification. 

### Actual behavior

With JDK engine, when an X509TrustManager is passed in the `SslContextBuilder`, the returned `X509TrustManager` is wrapped by an `X509ExtendedTrustManager` that performs hostname verification, for instance here is a verification failure trace:

```
Caused by: java.security.cert.CertificateException: No name matching localhost_ found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:221)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:95)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:998)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:937)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
```

When using the `OPEN_SSL` engine, the `checkServerTrusted(X509Certificate[] x509Certificates, String s)` of `X509TrustManager ` is called for verification purpose but it cannot perform the hostname validation as it does not have access to the engine that contains the parameters.

### Steps to reproduce

https://github.com/vietj/netty-openssl-custom-trustmanager-verification-error

- change JDK engine to OPEN_SSL in the `SslContextBuilder`
- run the test : the hostname verification should fail

### Netty version

4.1.8.Final is used in the reproducer but it fails too with 4.1.9.Final

### JVM version (e.g. `java -version`)

java version "1.8.0_92"

### OS version (e.g. `uname -a`)

Darwin julien 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
o

**Comment by normanmaurer** [comment] 2017-04-24 17:05
@vietj would have been nice if it would be a netty only unit test :)

**Comment by vietj** [comment] 2017-04-24 20:32
ah, I can convert it to pure Netty, I used Vert.x for setting up the server faster, but the important part is in Netty. I'll update it of course Norman, I just focused on providing something quickly :-)

**Comment by vietj** [comment] 2017-04-24 20:46
updated with only netty code in the reproducer

**Comment by normanmaurer** [comment] 2017-04-25 06:09
@vietj there is still vert.x code for the server. Can you change this as well ?

**Comment by vietj** [comment] 2017-04-25 06:16
ah just look at the unit test `TheTest`, not the "Main" class, sorry for confusion.

**Comment by vietj** [comment] 2017-04-25 06:17
I had open ssl classloading issues when running the main in Intellij so I moved all to a unit test with tcnative as scope test and it worked

**Comment by normanmaurer** [comment] 2017-04-25 06:18
@vietj ah ok... thx will check

**Comment by Scottmitch** [comment] 2017-04-27 18:37
> 4.1.8.Final is used in the reproducer but it fails too with 4.1.9.Final

The OpenSSL engine didn't support hostname verification before 4.1.9.Final [1]

[1] https://github.com/netty/netty/commit/d8e6fbb9c3656663f41797a15f38bb25fdcab834

**Comment by Scottmitch** [comment] 2017-04-27 18:41
You must also use netty-tcnative 2.0.0.Final [1] and OpenSSL 1.0.2+ (or boring ssl)

Since we build against 1.0.1 the dynamically linked netty-tcnative in maven central will not support this feature ... but it looks like you are want to use the statically linked BoringSSL so you should be fine.

[1] https://github.com/netty/netty-tcnative/commit/df8f3b1ffb40da35fdbdb818c4e63335939c19d5

**Comment by normanmaurer** [comment] 2017-04-27 18:44
I will investigate soon... Just need to find some time

**Comment by vietj** [comment] 2017-04-27 18:47
@Scottmitch can you explain why it works with file Key/Cert and OpenSSL ?

**Comment by Scottmitch** [comment] 2017-04-27 22:36
> can you explain why it works with file Key/Cert and OpenSSL in 4.1.8 ?

You have a `Main.java` and a `TheTest.java` in your reproducer. I only looked at `TheTest.java`.
Prior to Netty 4.1.9.Final and netty-tcnative 2.0.0 while using the OpenSSL there was no association between calling `SSLParamaters#setEndpointIdentificationAlgorithm` and Netty instructing OpenSSL of the expected hostname to validate. However the JDK's SSLEngineImpl would validate the hostname. So that is why `TheTest#doTest` "works" (handshake is setup) when you use Netty's OpenSSL engine (no validation of the host name is done) but when you use JDK's SSLEngineImpl the test "does not work" (hostname validation is done, and `localhost_ != localhost`.

If there is another scenario with 4.1.9 which isn't working as expected please update the reproducer and I can take another look.

**Comment by vietj** [comment] 2017-04-28 06:46
here is the validation with OpenSSL and Key/Cert:

```
Caused by: java.security.cert.CertificateException: No name matching localhost_ found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:221)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:95)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:223)
```

**Comment by Scottmitch** [comment] 2017-04-28 07:23
`TheTest.java` while using `SslProvider.OPENSSL` on the client successfully completes the handshake, but while using `SslProvider.JDK` the handshake fails. It is still not clear to me what the issue is. Are you suggesting we should change how things are done for OpenSSL to mimic the way things are done in the JDK? Is host name verification not working correctly when using SslProvider.OPENSSL with Netty 4.1.9+ and netty-tcnative 2.0.0+ (assuming `SSLParamaters#setEndpointIdentificationAlgorithm` is called)?

Let me describe how Netty currently works which is a bit different from how the JDK does things internally, and maybe this will help. Netty currently doesn't wrap the provided trust manager to provide any additional verification like the JDK does [1][2]. Instead we call methods directly on OpenSSL to configure these types of things directly [3], call the trust manager provided [4], and translate any exceptions to values recognized by OpenSSL [5] (which will generate corresponding TLS alerts).

[1] http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/5534221c23fc/src/share/classes/sun/security/ssl/SSLContextImpl.java#l986
[2] http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/5534221c23fc/src/share/classes/sun/security/ssl/X509TrustManagerImpl.java#l200
[3] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L1639
[4] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java#L645
[5] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslContext.java#L657

**Comment by normanmaurer** [comment] 2018-05-18 21:31
@vietj I will close this for now as there was no more activity. Please re-open if you still think there is an issue and provide more infos.

**Comment by normanmaurer** [comment] 2018-09-10 13:16
Ok I think I know what the problem is as I spotted it while doing some other work... Let me re-open

**Comment by normanmaurer** [comment] 2018-09-11 07:57
Alright... I did some more checking but unfortunally it will be kind of impossible for us to do the same here easily as the wrapping is done in the `SSLContextImpl` (which is package-private) and there is no way for us to easily access the wrapper itself (and also the hostname checking that is used here). So with this in mind this is more an implementation detail then anything else. I will close this now.

**Comment by normanmaurer** [comment] 2018-09-11 10:33
Asked on the openjdk mailinglist if there is any plan to expose it in the future:

http://mail.openjdk.java.net/pipermail/security-dev/2018-September/018160.html

**Closed** 2018-09-28 07:19 UTC
Labels: needs info
