### ISSUE TITLE
Netty HTTP/2 OutOfDirectMemoryError

### ISSUE THREAD

**Issue by ldclakmal** [netty/netty#8345] opened 2018-10-09 09:30 UTC
### Description
It is observed that following OOM error get occurred when testing with a load test with HTTP/2 connection. Load test is done with the following setup.

_Jmeter HTTP1 Client -> HTTP2 passthrough service -> HTTP2 service._

This issue get occurred after 30 mins of run with 100 concurrency in average throughput of 3000/sec.

```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 939524390, max: 954728448)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce
Original issue is reported at https://github.com/ballerina-platform/ballerina-lang/issues/9290

### Netty version
4.1.19.Final

### JVM version (e.g. `java -version`)
1.8.0_181

### OS version (e.g. `uname -a`)
Ubuntu 16.04 LTS

**Comment by normanmaurer** [comment] 2018-10-11 10:50
@ldclakmal you will need to provide more informations... This may be the result of not correctly implementing back-pressure (a.k.a writing too fast). Also please note that 4.1.19.Final is really old so you should upgrade as well.

**Comment by ldclakmal** [comment] 2018-10-11 11:43
@normanmaurer Thanks for your response.

This is the setup of the load test scenario.
**Jmeter HTTP1 Client  ->  HTTP2 passthrough service  ->  HTTP2 service.**

In this case, there is a HTTP/1.1 connection between the _'Jmeter HTTP1 Client'_  and _'HTTP2 passthrough service'_. There is a HTTP/2 connection between the _'HTTP2 passthrough service'_ and _'HTTP2 service'_.

_'HTTP2 servic'e_ doesn't consume the payload of the request, which is '8KB'. And it responds with a small payload of '15 bytes'.

The OOM issue get occured after _30 mins_ of run with _100 concurrency_ in average throughput of _3000/sec_.

The following are few observations:
- I upgraded netty version into _4.1.30.Final_ and checked with that also. But the issue is still there.
- If I maintain a constant throughput of ~1700/sec, the OOM error will not get occured.
- If I check the same setup by changing HTTP/2 connection into a HTTP/1.1 connection, the OOM error will not get occured.

With those observations, will that be due to the writing too fast (which is writing ~3000 requests per second) ?

**Comment by normanmaurer** [comment] 2018-11-26 19:44
its impossible to test what exactly the issue is without looking at the code / profiler / heap dump.

**Comment by arukshani** [comment] 2018-12-02 01:43
A heap dump is not getting created since it goes OutOfDirectMemoryError. But as you suggested in https://github.com/netty/netty/issues/8488 we disabled the direct memory usage as well as the pooled buffer usage and got a heap dump. Please find the attached heap dump.
[heap-dump.hprof.zip](https://github.com/netty/netty/files/2636498/heap-dump.hprof.zip)

We suspect this is due to not handling backpressure because right now we have just one thread handling all the streams (MAX_INT_VALUE is set as the max streams allowed per connection; this is a custom logic and not related to the max concurrent streams value in HTTP/2). Our workload is not properly distributed among I/O threads and only a single thread handles all the streams. When we reduce the max concurrent stream to a value like 20000 this issue goes away and throughput increases since the workload is distributed among multiple I/O threads. (This is an HTTP/2 client directly sending incoming payload to the backend without first reading it)

In here https://github.com/wso2/transport-http/blob/07a7423667d6e3a4d2f3c87e147c006d31d4c86c/components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2ConnectionManager.java#L161

since maxActiveStreams is MAX_INT_VALUE it always fetches the first channel and only that channel handles all the streams even though there can be multiple channels in the pool and it goes OOM. 

We really appreciate your thoughts on this @normanmaurer . 

Please find the [doc](https://docs.google.com/document/d/1drL2SDARmD13EMMNRzRZQltD_51EvSXqIQkLU5eO_OE/edit?usp=sharing) which shows the memory usage during OOM.

**Comment by normanmaurer** [comment] 2019-11-07 20:28
This can be closed as the OOM was fixed as said in https://github.com/ballerina-platform/ballerina-lang/issues/11368

**Closed by normanmaurer** 2019-11-07 20:28 UTC
