### ISSUE TITLE
SegFault Epoll

### ISSUE THREAD

**Issue by onesimpledot** [netty/netty#6686] opened 2017-04-29 22:38 UTC
### Expected behavior
no segfault on EpollEventLoopGroup#shutdownGracefully()
### Actual behavior
segfault on EpollEventLoopGroup#shutdownGracefully()
https://pastebin.com/hcSc6f5N
### Steps to reproduce
EpollEventLoopGroup#shutdownGracefully()
### Minimal yet complete reproducer code (or URL to code)
https://pastebin.com/nS6dsbK3
### Netty version
4.1.8.Final
### JVM version (e.g. `java -version`)
root@pixel:~# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
### OS version (e.g. `uname -a`)
root@pixel:~# uname -a
Linux pixel.bizzi.tv 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ninja-** [comment] 2017-04-30 13:04
This is not a segfault in epoll but in libzip as you can see. It's probably caused by you replacing the jar without shutting down the app first.

**Comment by Scottmitch** [comment] 2017-05-03 21:01
@onesimpledot - can you please create a simple git repo with a maven/gradle file which reproduces? There are some dependencies on unknown code `me.onesimpledot.` the easier it is to reproduce the more likely we will be able to diagnose the issue.

**Comment by normanmaurer** [comment] 2017-05-30 09:26
@onesimpledot please provide a reproducer if you still think this is a netty bug. Closing for now

**Closed by normanmaurer** 2017-05-30 09:26 UTC
