### ISSUE TITLE
Errors in using netty 4.0.33.Final about sun.misc.Unsafe methods

### ISSUE THREAD

**Issue by nmnhero** [netty/netty#4824] opened 2016-02-03 10:22 UTC
Hi, when I use io.netty-codec and io.netty-buffer I get this errors:

```
Could not find method sun.misc.Unsafe.addressSize, referenced from method io.netty.util.internal.PlatformDependent0.addressSize
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54886: Lsun/misc/Unsafe;.addressSize ()I
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.allocateMemory, referenced from method io.netty.util.internal.PlatformDependent0.allocateMemory
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54887: Lsun/misc/Unsafe;.allocateMemory (J)J
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.copyMemory, referenced from method io.netty.util.internal.PlatformDependent0.copyMemory
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54893: Lsun/misc/Unsafe;.copyMemory (JJJ)V
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x74 at 0x0011
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.copyMemory, referenced from method io.netty.util.internal.PlatformDependent0.copyMemory
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54894: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x74 at 0x0016
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.freeMemory, referenced from method io.netty.util.internal.PlatformDependent0.freeMemory
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54895: Lsun/misc/Unsafe;.freeMemory (J)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.getByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54896: Lsun/misc/Unsafe;.getByte (J)B
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.getByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54897: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getInt, referenced from method io.netty.util.internal.PlatformDependent0.getInt
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54898: Lsun/misc/Unsafe;.getInt (J)I
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getLong, referenced from method io.netty.util.internal.PlatformDependent0.getLong
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54901: Lsun/misc/Unsafe;.getLong (J)J
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.getShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54906: Lsun/misc/Unsafe;.getShort (J)S
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.getShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54907: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putByte, referenced from method io.netty.util.internal.PlatformDependent0.putByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54911: Lsun/misc/Unsafe;.putByte (JB)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putByte, referenced from method io.netty.util.internal.PlatformDependent0.putByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54912: Lsun/misc/Unsafe;.putByte (Ljava/lang/Object;JB)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putInt, referenced from method io.netty.util.internal.PlatformDependent0.putInt
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54913: Lsun/misc/Unsafe;.putInt (JI)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putLong, referenced from method io.netty.util.internal.PlatformDependent0.putLong
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54916: Lsun/misc/Unsafe;.putLong (JJ)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putShort, referenced from method io.netty.util.internal.PlatformDependent0.putShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54924: Lsun/misc/Unsafe;.putShort (JS)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putShort, referenced from method io.netty.util.internal.PlatformDependent0.putShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54925: Lsun/misc/Unsafe;.putShort (Ljava/lang/Object;JS)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.throwException, referenced from method io.netty.util.internal.PlatformDependent0.throwException
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54926: Lsun/misc/Unsafe;.throwException (Ljava/lang/Throwable;)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x000a
```

**Comment by Scottmitch** [comment] 2016-02-03 16:15
What version of JDK and what OS are you running on?

**Comment by nmnhero** [comment] 2016-02-04 00:59
I'm using JDK 8 and Windows 7 Pro

**Comment by johnou** [comment] 2016-02-04 14:33
@nmnhero what JRE / OS is running the application code? Looks like Android..?

**Comment by nmnhero** [comment] 2016-02-05 00:58
Yes I'm running it on Android

**Comment by Scottmitch** [comment] 2016-02-05 22:57
Can you provide a reproducer? Are you directly using `netty-buffer` when you experience this error, or is it the error triggered some where else in Netty?

**Comment by nmnhero** [comment] 2016-02-09 03:20
Yes I am directly using netty-buffer since I put its dependency on my gradle file. 
` compile 'io.netty:netty-buffer:4.0.33.Final'`
Here is a sample code:
` public static MessageRouterResponse decode(ByteBuf buffer) {
        int serviceCode = buffer.readUnsignedByte();
        buffer.skipBytes(1); // reserved
        int generalStatus = buffer.readUnsignedByte();

        int count = buffer.readUnsignedByte();
        int[] additionalStatus = new int[count];
        for (int i = 0; i < count; i++) {
            additionalStatus[i] = buffer.readShort();
        }

        ByteBuf data = buffer.isReadable() ?
                buffer.readSlice(buffer.readableBytes()).retain() : Unpooled.EMPTY_BUFFER;

        return new MessageRouterResponse(serviceCode, generalStatus, additionalStatus, data);
    }`
` MessageRouterResponse response = MessageRouterResponse.decode(buffer);`
` ByteBuf data = response.getData();`
`data.getShort(data.readerIndex())`

**Comment by Scottmitch** [comment] 2016-02-11 16:38
What version of android? if you turn on debug logging for Netty what does the log line that a starts with `sun.misc.Unsafe.theUnsafe:` look like?

**Comment by nmnhero** [comment] 2016-02-12 01:26
I'm running it on a Samsung Note10.1-IT with Android version 4.4.2

**Comment by Scottmitch** [comment] 2016-02-13 07:13
@nmnhero -  Thanks. What about the debug log statements I asked about?

**Comment by albertvaka** [comment] 2016-03-03 21:35
Same problem here. What JDK is Netty targetting? Android support for Java>6 is limited.

**Comment by Scottmitch** [comment] 2016-03-04 02:28
@nmnhero - Ping.

**Comment by normanmaurer** [comment] 2016-08-02 18:41
I will close this for now. If you still think there is an issue please reopen with more infos

**Closed by normanmaurer** 2016-08-02 18:41 UTC
Labels: android
