### ISSUE TITLE
Only single channel for netty on udp

### ISSUE THREAD

**Issue by trondarild-lode-tobiassen-heidelberg** [netty/netty#7557] opened 2018-01-02 15:44 UTC
### Steps to reproduce
		EventLoopGroup group = new OioEventLoopGroup(5, Executors.defaultThreadFactory());
		Bootstrap b = new Bootstrap();
		b.group(group).option(ChannelOption.SO_RCVBUF, 8192)
				.option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator(8192))
				.channel(OioDatagramChannel.class).handler(new ChannelInitializer<OioDatagramChannel>() {

					@Override
					protected void initChannel(OioDatagramChannel ch) throws Exception {
						ChannelPipeline cp = ch.pipeline();
						cp.addFirst("logger", new LoggingHandler());
						cp.addLast("decoder", new SipDatagramDecoder());
						cp.addLast("business", new SipInboundHandler());
						cp.addLast("outbound", new SipEncoder());

					}
				});
		ChannelFuture futureBindUDP = b.bind(PORT_UNSECURED);
		futureBindUDP.addListener(new ChannelFutureListener() {

			@Override
			public void operationComplete(ChannelFuture channelFuture) throws Exception {
				if (channelFuture.isSuccess()) {
					SipservLogger.getConsoleLogger().debug("UDP Channel bound");
				} else {
					SipservLogger.getConsoleLogger().debug("UDP bind attempt failed");

				}

			}
		});

ref: https://github.com/netty/netty/issues/1706

### Netty version
4.1.18

### JVM version (e.g. `java -version`)
C:\Users\trond>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
win 7

**Comment by Scottmitch** [comment] 2018-01-02 18:53
Note your reproducer is not self contained, and does not demonstrate the reported issue. All of the `Sip*` related classes are unknown.

However have you tried `.option(ChannelOption.SO_REUSEADDR, true)`?

**Comment by trondarild-lode-tobiassen-heidelberg** [comment] 2018-01-02 19:25
It helps. But now the second client takes over. I see no more of the 
first client. (The protocol is based on renewals of a session and the 
first client stops renewing when the second attempts to register/log 
on). Can it be that the server now drops the existing udp channel?

**Comment by Scottmitch** [comment] 2018-01-02 20:55
IIUC this is now a duplicate of https://github.com/netty/netty/issues/1706. Netty doesn't support any multiplexing/demultiplexing per channel and generally assumes a single thread per channel.

**Comment by nicktrav** [comment] 2018-01-02 21:44
I've run into the exact issue recently. Fwiw - it is obviated if you happen to use the epoll transport with SO_REUSEPORT set to true on Linux.

However, utilisation of all the threads is provisional on you sending datagrams from clients with different (source IP, source port) combinations which can be a gotchya when testing / benchmarking. 

NIO and OIO are limited to a single thread. Not sure if that's a JDK limitation or exists elsewhere. I haven't confirmed with Kqueue on BSD/macOS but assume it's the same as epoll.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment] 2018-01-02 21:55
OK. So I need to set option so_reuseport (even though the primary use 
case for this is multicasting) AND use linux. I use win7 ...

I got to save up for a new machine I guess.


Thanks for your effort in this.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment] 2018-01-03 10:23
I realise SO_REUSEPORT is not an "ChannelOption" in netty. How do you 
set it?

**Comment by nicktrav** [comment] 2018-01-03 19:26
@trondarild-lode-tobiassen-heidelberg - that option is available to the Epoll and Kqueue transports.

For example, epoll on Linux:
```java
EventLoopGroup eventLoopGroup = new EpollEventLoopGroup();
Bootstrap b = new Bootstrap();
b.group(eventLoopGroup)
  .channel(EpollDatagramChannel.class)
  .option(EpollChannelOption.SO_REUSEPORT, true)
...
```

or KQueue on BSD / macOS:
```java
EventLoopGroup eventLoopGroup = new KQueueEventLoopGroup();
Bootstrap b = new Bootstrap();
b.group(eventLoopGroup)
  .channel(KQueueDatagramChannel.class)
  .option(KQueueChannelOption.SO_REUSEPORT, true)
...
```

**Comment by trondarild-lode-tobiassen-heidelberg** [comment] 2018-01-03 19:44
Thanks a lot!

**Comment by trondarild-lode-tobiassen-heidelberg** [comment] 2018-01-03 20:32
I guess Epoll applies to Android as well?

**Comment by DATuan91** [comment] 2018-12-08 04:43
@trondarild-lode-tobiassen-heidelberg This issue is the same as [Multi threaded behavior with UDP server does not seem to work (4.0.6.Final)](https://github.com/netty/netty/issues/1706)

**Comment by huqingkang** [comment] 2019-01-28 07:51
I also had a problem with netty multicast mode not being able to communicate between hosts

**Comment by trondarild-lode-tobiassen-heidelberg** [comment] 2019-01-28 08:33
I still have not had a chance to test EPOLL on a linux box but I am sure the advice is correct. Thus I want to close this issue. But the new comment stops me. hukinqang: Are you trying on windows? If so your answer may lie in testing with a linux host and Epoll SO_TIMEOUT.

**Comment by huqingkang** [comment] 2019-01-29 07:10
Hello, my question is about the multicast mode communication of the multi-host unit. I have submitted the details of the corresponding question. It doesn't conflict with your problem. You can end this problem.

**Closed** 2019-01-29 07:11 UTC
