### ISSUE TITLE
TLS handshake succeeds before custom trust manager factory checks the certificate

### ISSUE THREAD

**Issue by ancwrd1** [netty/netty#10502] opened 2020-08-25 18:39 UTC
### Expected behavior
It worked fine in Netty 4.1.19. We have a Netty server which creates a TCP channel with a custom SslContext and a custom trust manager factory (derived from SimpleTrustManagerFactory).
This trust manager factory makes a decision on whether to trust a certificate of the connecting peer or not.
If the certificate is not trusted the CertificateException is thrown and handshake procedure should be aborted.

### Actual behavior
In Netty 4.1.51 what happens is that handshake is accepted by the remote client before the trust manager factory checks for the certificate. So the remote peer gets an OK handshake. And then immediately the connection is broken due to handshake error after the certificate is rejected on the server side.

### Minimal yet complete reproducer code (or URL to code)
Unfortunately I cannot share a complete code but it's a standard code based on examples and it's been working fine for years.

Scala code snippet to create SSL context:
```scala
    SslContextBuilder
      .forServer(keyFactory)
      .protocols("TLSv1.2")
      .trustManager(new MyTrustManagerFactory)
      .clientAuth(ClientAuth.REQUIRE)
      .build()
```

The `MyTrustManagerFactory` class just checks for the peer certificate and throws `CertificateException` if it's wrong.
Somehow this now happens after the handshake status is negotiated.

Scala code snippet to build a server channel:

```scala
new ServerBootstrap()
    .group(eventGroup, workerGroup)
    .channel(getChannelClass)
    .option(ChannelOption.SO_BACKLOG, 100: java.lang.Integer)
    .childHandler(new ChannelInitializer[SocketChannel] {
      override def initChannel(ch: SocketChannel): Unit = {
        ch.pipeline.addLast(
          newSslContext.newHandler(ch.alloc()),
          new ByteArrayDecoder,
          new ChunkedWriteHandler,
          peer)
      }
    })
```

May be I am missing something in the newer Netty?

### Netty version
4.1.51

### JVM version (e.g. `java -version`)
OpenJDK 64-Bit Server VM (build 11.0.8+10-suse-1.2-x8664, mixed mode)

### OS version (e.g. `uname -a`)
openSUSE Tumbleweed Linux 5.8.0

**Comment by normanmaurer** [comment] 2020-08-25 19:14
This will be hard to debug without a reproducer :( You have tcnative on the class path ?

**Comment by hyperxpro** [comment] 2020-08-25 19:27
Also, try upgrading to `Netty 4.1.51.Final` version and give it a shot and see because `Netty 4.1.19.Final` is way too old (December 2017 release).

**Comment by ancwrd1** [comment] 2020-08-25 20:28
This actually happens in 4.1.51.Final.
In the older version 4.1.19.Final it works fine as expected.
I will try to make a minimal reproduction case.

**Comment by ancwrd1** [comment] 2020-08-25 21:36
Ok, I have managed to reproduce it using a "securechat" example from netty sources.
The conclusion is that this issue happens when using a newer TLS v1.3.

Here is a modified "securechat" sources attached. It waits for 10 sec in the trust manager factory and then throws an exception.
When attempting to connect to this app using openssl there are different outputs depending on the TLS protocol version.

For TLS v1.2:

```text
openssl s_client -tls1_2 -cert /path/to/server.pem -connect localhost:8992
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1

< here we wait for 10 sec >

139694394160384:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1543:SSL alert number 46

<dumped some certificate and handshake info>
```

And here is TLS v1.3 log:

```text
openssl s_client -cert $vdms/old/easy3/easy-core/cfg/certs/server.pem -connect localhost:8992 
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1

<dumped some certificate and handshake info>

< wait 10 sec >

140702760461568:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1543:SSL alert number 46
```

So there is clearly a difference how they are handled. Now the question is whether this is a JDK issue (or perhaps a TLS "feature") or it is something that Netty does behind the scene.

P.S. version 4.1.19 does not seem to support TLS 1.3 at all, it's not negotiated.

[netty-tls3.zip](https://github.com/netty/netty/files/5126370/netty-tls3.zip)

**Comment by ancwrd1** [comment] 2020-08-25 21:44
Some additional information:

We have a Netty client application which registers a handshake listener like this:

```scala
    override def channelActive(ctx: ChannelHandlerContext): Unit = {
      ctx.pipeline().get(classOf[SslHandler]).handshakeFuture.addListener((future: Future[Channel]) => {
        if (future.isSuccess) {
            // do something after handshake is ok
        }
      }
    }
```

So what happens is that this future always succeeds even though the handshake is not technically done yet.

**Comment by hyperxpro** [comment] 2020-08-26 12:08
I tried reproducing with `io.netty:netty-all:4.1.51.Final` with the source code you attached. Unfortunately, it works as expected. Netty closed the connection after the `Bad Certificate` exception.

```
C:\Users\Hyper\AppData\Local\Temp\keyutil_localhost_16123888239874321424.crt
C:\Users\Hyper\AppData\Local\Temp\keyutil_localhost_7262145737571135611.key
Aug 26, 2020 5:36:04 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFO: [id: 0x3c4c3b37] REGISTERED
Aug 26, 2020 5:36:04 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0x3c4c3b37] BIND: 0.0.0.0/0.0.0.0:8992
Aug 26, 2020 5:36:04 PM io.netty.handler.logging.LoggingHandler channelActive
INFO: [id: 0x3c4c3b37, L:/0:0:0:0:0:0:0:0:8992] ACTIVE
Aug 26, 2020 5:36:21 PM io.netty.handler.logging.LoggingHandler channelRead
INFO: [id: 0x3c4c3b37, L:/0:0:0:0:0:0:0:0:8992] READ: [id: 0xe1ff1931, L:/0:0:0:0:0:0:0:1:8992 - R:/0:0:0:0:0:0:0:1:1978]
Aug 26, 2020 5:36:21 PM io.netty.handler.logging.LoggingHandler channelReadComplete
INFO: [id: 0x3c4c3b37, L:/0:0:0:0:0:0:0:0:8992] READ COMPLETE
Got Connection, Waiting for 10 seconds...
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Bad certificate
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Bad certificate
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:687)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:398)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:366)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1048)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:995)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1550)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1564)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1448)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 17 more
Caused by: java.security.cert.CertificateException: Bad certificate
	at io.netty.example.securechat.MyTrustManagerFactory$1.checkClientTrusted(MyTrustManagerFactory.java:33)
	at io.netty.handler.ssl.util.X509TrustManagerWrapper.checkClientTrusted(X509TrustManagerWrapper.java:52)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:669)
	... 32 more

```

**Comment by hyperxpro** [comment] 2020-08-26 12:18
Reproduced finally.

```
C:\Users\Hyper\AppData\Local\Temp\keyutil_localhost_8235761893751940897.crt
C:\Users\Hyper\AppData\Local\Temp\keyutil_localhost_15089618585300072117.key
Aug 26, 2020 5:45:21 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFO: [id: 0x801fbf01] REGISTERED
Aug 26, 2020 5:45:21 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0x801fbf01] BIND: 0.0.0.0/0.0.0.0:8992
Aug 26, 2020 5:45:21 PM io.netty.handler.logging.LoggingHandler channelActive
INFO: [id: 0x801fbf01, L:/0:0:0:0:0:0:0:0:8992] ACTIVE
Aug 26, 2020 5:45:34 PM io.netty.handler.logging.LoggingHandler channelRead
INFO: [id: 0x801fbf01, L:/0:0:0:0:0:0:0:0:8992] READ: [id: 0xd9329a19, L:/127.0.0.1:8992 - R:/127.0.0.1:2288]
Aug 26, 2020 5:45:34 PM io.netty.handler.logging.LoggingHandler channelReadComplete
INFO: [id: 0x801fbf01, L:/0:0:0:0:0:0:0:0:8992] READ COMPLETE
Got Connection, Waiting for 10 seconds...
Connected, TLS Protocol:NONE, Cipher: SSL_NULL_WITH_NULL_NULL
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Bad certificate
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Bad certificate
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:687)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:398)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:366)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1048)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:995)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1550)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1564)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1448)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 17 more
Caused by: java.security.cert.CertificateException: Bad certificate
	at io.netty.example.securechat.MyTrustManagerFactory$1.checkClientTrusted(MyTrustManagerFactory.java:33)
	at io.netty.handler.ssl.util.X509TrustManagerWrapper.checkClientTrusted(X509TrustManagerWrapper.java:52)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:669)
	... 32 more

```

My observation: Netty is waiting 10 seconds for `MyTrustManagerFactory`. When `MyTrustManagerFactory` throws an error, Netty marks the channel active somehow and closes the connection. I tried fetching TLS protocol and cipher suite just to know if TLS handshake was negotiated but `Connected, TLS Protocol: NONE, Cipher: SSL_NULL_WITH_NULL_NULL`. So the TLS handshake was not successful because Netty closed connection as soon as it received an exception from `MyTrustManagerFactory`.

The problem here, Netty is calling `channelActive` after closing connection.

**Comment by ancwrd1** [comment] 2020-08-26 12:20
Yes but the problem is that the client receives OK handshake before it times out with 10 seconds and throws an exception.
I have provided a code fragment from netty client.
The handshake future succeeds even though the server throws CertificateException

**Comment by ancwrd1** [comment] 2020-08-26 12:41
Also worth noting that this only happens with TLS 1.3

**Comment by normanmaurer** [comment] 2020-09-21 13:27
Sorry for the late response... I missed this one. This is just how TLS1.3 works. In TLS1.3 the handshake is already considered complete when the trust manager is consulted. 

See also:

https://stackoverflow.com/questions/62459802/tls-1-3-client-does-not-report-failed-handshake-when-client-certificate-verifica/62465859#62465859

**Closed by normanmaurer** 2020-09-21 13:27 UTC
