### ISSUE TITLE
HttpPostMultipartRequestDecoder performance regression

### ISSUE THREAD

**Issue by zentol** [netty/netty#10508] opened 2020-08-27 08:53 UTC
### Expected behavior

#10226 improves performance.

### Actual behavior

The decoder is now at least 100x slower than before iff it is offered a direct buffer.

If the decoder is offered a direct buffer it now creates a bunch of 64b direct buffers during parsing, where before it always used heap buffers.
Using a `PooledByteBufAllocator` that prefers direct buffers did not solve the issue.
Using a `(Un)PooledByteBufAllocator` that prefers heap buffers normalizes performance again.

Given that this issue was not listed in the announcement under important, I would think that this was not intentional.

### Steps to reproduce

Create a HttpPostMultipartRequestDecoder and offer around a 1000 chunks (64k); in 4.1.49 this runs in seconds, whereas in 4.1.50 it takes minutes.

### Minimal yet complete reproducer code (or URL to code)

We have [this](https://github.com/apache/flink/blob/e991de19337591cde444fbede010cb8bdc7f118f/flink-runtime/src/test/java/org/apache/flink/runtime/rest/FileUploadHandlerTest.java) test in Apache Flink that exhibits the problem.
I can try to write a minimal reproducer if requested; may take some time to figure out how to correctly create the requests :/

### Netty version

4.1.50

### JVM version (e.g. `java -version`)

8

### OS version (e.g. `uname -a`)

Windows 10, but we also saw it on ubuntu linux

**Comment by fredericBregier** [comment] 2020-08-27 13:51
My 2 cents:
First change:
- Before, it was a `copy` which limits the max, 
- now is a `buf.alloc.buffer(...).writeByte(buf)`  => Pooled buffer using the original ByteBufAllocator from the `buf`

Second change, which is probably the one you point out:
- Before (2 places): `Unpooled.buffer(64)` (Unpooled implicit)
- After (same): `undecodedChunk.alloc().heapBuffer(64)`

This should use the ByteBufAllocator used for undecoded, which in turns should be (if I understand) the same allocator than original `buf` (so the one from IO) since either it is the same, or a new allocated one using the same allocator.

I could suggest to replace `undecodedChunk.alloc().heapBuffer(64)` by `undecodedChunk.alloc().buffer(64, 64)` (here there should not be any more than 64), but as you noticed that putting a `PooledByteBufAllocator` to direct is not correct, but heap seems ok, then I finally could suggest: `undecodedChunk.alloc().heapBuffer(64, 64)`, which is almost what we have there...

@normanmaurer Any suggestion since I do not have a clear mind on this... ?

**Comment by fredericBregier** [comment] 2020-08-28 22:37
@zentol I tried to reproduce using only Netty, but I can't get the numbers you've got.

Could you have a reproducer code with Netty only (almost a Junit or simple example)?
What kind of data are you sending (which forms and numbers)?
And to be sure, your tests shows that Direct buffers are not ok, while Heap buffers are ?
Thanks

**Comment by fredericBregier** [comment] 2020-09-02 06:33
@zentol Note that I used 4.1.51 and I can't reproduce the issue you raised...

**Comment by fredericBregier** [comment] 2020-09-03 07:07
@zentol I tried another time, but the numbers I've got are almost the same whatever the allocation:
- PooledHeap, PooledDirect, PooledBuffer (from undecodedChunked
- UnpooledHeap, UnpooledDirect, UnpooledBuffer

I've tried both 1000 chunks for big data (64KB each) so 1000 decoded vars or 1000 chunks for small data (4KB each but 16 times so still chunks of 64KB each) so 16000 decoded vars, and the results are the same : 
- 4KB data size: roughly 230ms each test (16000 data) (highest - lowest = 5ms)
- 64KB data size: roughly 2900ms each test (1000 data), the difference being the data written on disk due to large size (> 16KB)  (highest - lowest = 310ms, but not so relevant since disk access is most of the issue as without disk access, there is no issue)
- 64KB data size: roughly 190ms each test (1000 data), the difference being the data not written on disk (memory only) (highest - lowest = 8ms)

So my conclusion until further information from you is that there is no issue there... Either I'm missing something, either it was fixed in 4.1.51...

**Comment by zentol** [comment] 2020-09-14 09:07
@fredericBregier I did not test it with 4.1.51 due to #10425. I will check whether the issue persists in 4.1.52, and if so try to create a reproducer.

**Comment by zentol** [comment] 2020-09-14 13:03
Ok, I think I got closer to the problem.

I wrote a reproducing test, which ran fast in 4.1.49 and slow in 4.1.50, but when I moved it into a separate project it suddenly ran fast either way.
I then noticed that the test we used so far also uses a `ResourceLeakDetector` set to `PARANOID`. If I set the level to `ADVANCED` it runs quickly with both versions, but `PARANOID` appears to slow things down way more in 4.1.50+.

Here's the test in question:

```
public class RegressionTest {

	@Rule
	public final TemporaryFolder temporaryFolder = new TemporaryFolder();

	static {
		ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.PARANOID);
	}

	@Test
	public void testRegression() throws Exception {
		File file = temporaryFolder.newFile();
		try (RandomAccessFile rw = new RandomAccessFile(file, "rw")) {
			rw.setLength(1024 * 1024 * 5);
		}
		DefaultHttpDataFactory httpDataFactory = new DefaultHttpDataFactory(true);

		HttpRequest httpRequest = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "");
		HttpPostRequestEncoder bodyRequestEncoder = new HttpPostRequestEncoder(httpDataFactory, httpRequest, true);
		bodyRequestEncoder.addBodyFileUpload("file", file, "application/octet-stream", false);

		HttpRequest firstHttpRequest = bodyRequestEncoder.finalizeRequest();
		HttpPostRequestDecoder httpPostRequestDecoder = new HttpPostRequestDecoder(httpDataFactory, firstHttpRequest);

		ByteBufAllocator allocator = PooledByteBufAllocator.DEFAULT;
		for (HttpContent httpContent = bodyRequestEncoder.readChunk(allocator); httpContent != null; httpContent = bodyRequestEncoder.readChunk(allocator)) {
			httpPostRequestDecoder.offer(httpContent);
		}
	}
}
```

**Comment by fredericBregier** [comment] 2020-09-14 13:59
@zentol Effctively, with PARANOID level set, chunks are quite high consuming time, while other levels are quite quickier. On my tests (same than before, based on 4.1.52):  whatever the pooled/unpooled heap/direct buffers
- No detector: 225 to 230ms
- Simple: 229 to 233ms
- Advanced; 228 to 245ms
- Paranoid:  147.000ms
So yes, there is a hug gap using Paranoid (almost x600). Maybe you can stay in at most Advanced mode ?

**Comment by fredericBregier** [comment] 2020-09-14 14:02
@normanmaurer However I have a question for you, do you think this kind of gap is normal ?
I do know that Paranoid is not for Production, but maybe it is so huge that it could not be usable. Note however that I used Paranoid level for a long time is all my tests and did not found any issue about on my side.

**Comment by zentol** [comment] 2020-09-15 09:42
Using Advanced would be workaround we would go for, but this runtime increase on Paranoid does not seem normal. It was perfectly fine to use Paranoid in earlier versions, and it would be unfortunate to weaken our tests now with never versions. :/

**Comment by normanmaurer** [comment] 2020-09-21 13:25
sorry for the late reply... The problem with "paranoid" is that it basically creates one stack trace per `ByteBuf` access which can be very expensive. So these kind of performance drops can happen.

**Comment by fredericBregier** [comment] 2020-09-21 18:47
@normanmaurer Thanks!
For me, it's fine as is.
If I'm correct, changing the number of items tracked through `io.netty.leakDetection.targetRecords` will not change every access to be checked but just limit the number of retained items ?

I believe that one could set specific values for `io.netty.leakDetection.samplingInterval` (default being 128 to a small value (still power of 2, such as 16 to reduce the PARANOID effect to a smaller part (If I'm correct, the main difference between ADVANCED and PARANOID is that this samplingInterval is ignored within PARANOID ?).

I checked using level = `ADVANCED` and `io.netty.leakDetection.samplingInterval` to: (using Pooled one)
- compared to `PARANOID`: 140.000ms whatever Direct or Heap
- 8 : 140.000ms Direct vs 4.000ms Heap, so almost the same as PARANOID, except using Heap
- 16 : 210ms whatever
- 128 (default) : 200ms whatever Direct or Heap
- 12 (*I know that the code said it should be a power of 2): 590ms Direct 420ms Heap
So maybe 12 could be a good tradeof ? (more trace but not as many as in PARANOID).

Again, on my side, I use PARANOID everywhere in my tests and I'm fine with it. It is more for the question of @zentol .

Note: I used this in my test bench code

    @BeforeClass
    public static void setDefaultAdvancedLevel() {
      System.setProperty("io.netty.leakDetection.samplingInterval", "12");
      ResourceLeakDetector.setLevel(Level.ADVANCED);
    }

**Comment by zentol** [comment] 2020-09-22 08:30
Our problem isn't that PARANOID is slower than other modes, that's fine and expected, but that due to _some change that impacts leak detection_ our test is 100x slower in 4.1.50 than before.

I would just like to understand what has changed; if the leak detection was made slower in general, then that's fine, but I'm worried that something else has changed that indirectly causes leak detection to be slower in our specific case.

**Comment by chrisvest** [comment] 2021-02-26 13:36
After merging #11001 I'm getting ~360-400ms for ADVANCED and ~460-770ms for PARANOID when running the test in https://github.com/netty/netty/issues/10508#issuecomment-692037524

So I think we can close this issue?

**Comment by fredericBregier** [comment] 2021-02-26 14:30
I hope so ;-)

**Closed** 2021-02-26 18:22 UTC
