### ISSUE TITLE
ByteBuf slice duplicates are not slices

### ISSUE THREAD

**Issue by vietj** [netty/netty#12919] opened 2022-10-21 07:55 UTC
### Expected behavior

A `ByteBuf` duplicated slice remains a slice.

### Actual behavior

A `ByteBuf` duplicated slice is a duplicate and not a slice anymore.

### Steps to reproduce

Duplicating a sliced `ByteBuf` is enough.

### Minimal yet complete reproducer code (or URL to code)

```java
ByteBuf helloWorld = Unpooled.copiedBuffer("Hello World", StandardCharsets.UTF_8);
ByteBuf hello = helloWorld.slice(0, 5);
try {
  hello.writeByte('_');
  fail();
} catch (Exception ignore) {
}
try {
  hello.duplicate().writeByte('_');
  fail(); // Fails here
} catch (Exception ignore) {
}
```

### Netty version

Most I'd say

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by franz1981** [comment] 2022-10-21 07:59
I would expect as well that It won't be expanded too

**Comment by chrisvest** [comment] 2022-10-21 20:00
It might be illogical or unexpected, but it is specified to behave this way. The javadocs for `duplicate()` say that it returns…

```
A buffer whose readable content is equivalent to the buffer returned by {@link #slice()}.
However this buffer will share the capacity of the underlying buffer, and therefore allows access to all of the
underlying content if necessary.
```

So `duplicate()` always gives you duplicates, and `slice()` always gives you slices.

**Comment by vietj** [comment] 2022-10-24 07:45
@chrisvest I hear that, however it is not possible from the user code perspective to determine whether the ByteBuf is a duplicate or a slice, if it needs to gets a duplicate of a slice with the same semantic.

**Comment by lhotari** [comment] 2024-06-03 05:50
I made #14093 with the title "Duplicate of slice should have the same capacity as the original slice so that it's not writable" to address this issue.

**Closed** 2024-06-03 22:56 UTC

**Comment by sergiitk** [comment] 2024-06-14 18:50
For posterity: looks like this behavioral change caused grpc/grpc-java#11284, as we relied on "`duplicate()` always gives you duplicates, and `slice()` always gives you slices." behavior (https://github.com/netty/netty/issues/12919#issuecomment-1287381943) to get around the issue with `component()` of a double-wrapped `CompositeByteBuf` returning a slice with incorrect indexes,  #12844.
