### ISSUE TITLE
Netty buffer options/childOptions speed impact 

### ISSUE THREAD

**Issue by QazPolma** [netty/netty#6832] opened 2017-06-08 13:51 UTC
Choosing option/childOption "incorrectly" for send/receive buffer in ServerBootstrap has a huge impact on speed. This is best seen when there is a significant latency(~300ms).
If I choose ServerBootstrap.childOption(ChannelOption.SO_SNDBUF,...) and/or ServerBootstrap.option(ChannelOption.SO_RCVBUF,...) it cuts the speed significantly for respective transfer direction.
If I reverse the option/childOption, then the speed recovers. 
I also get "Unknown channel option 'SO_SNDBUF' for channel" warning, so I guess send buffer is not even explicitly set at all and goes with implicit default values when using 'option'.

More details and example code - https://stackoverflow.com/questions/41463493/netty-serverbootstrap-option-or-childoption-and-its-buffer-size-impact-on-speed

Have not re-tested all results after the library has been updated, but setting default values explicitly triggers the issue.

Netty version 4.1.11
JVM 1.8.0_131
Windows 8.1 for server
MacOS Sierra(10.12.5) for agent
Increasing DNS latency with "Network Link Conditioner" on MacOS

**Comment by Scottmitch** [comment] 2017-06-08 18:23
> I also get "Unknown channel option 'SO_SNDBUF' for channel" warning, so I guess send buffer is not even explicitly set at all and goes with implicit default values when using 'option'.

Can you please provide a reproducer?
What transport type are you using (NIO, EPOLL, KQUEUE)?
What network transport type are you using (TCP, UDP, etc..)?

**Comment by QazPolma** [comment] 2017-06-09 08:48
Can I point to stackoverflow for reproducer? Code from the orginal [post](https://stackoverflow.com/questions/41463493/netty-serverbootstrap-option-or-childoption-and-its-buffer-size-impact-on-speed)
1. Take "ObjectEchoServerHandler.java" and "ObjectEchoServer.java"
2. Use the following 'args' parameters: {"sendToClient", "option", "1"}

Transport type NIO
Network transport type TCP

**Comment by Scottmitch** [comment] 2017-06-13 00:50
- `ObjectEchoServerHandler` writes a message in channelRead, and then adds a new listener which will send the same message again. There are a few instances with this:
  - the future will not be notified until the OS accepts all of the bytes ... it is expected that the time will increase as the OS buffers are reduced
  - if `msg` is reference counted (e.g. `ByteBuf`) then you will end up using a released object when it is used multiple times. This may happen on subsequent writes, or if you get multiple channelRead events.
- `ObjectEchoServerHandler` does a write and flush for each operation so you will not be able to take advantage of gathering writes. Try using `write` for multiple writes and `flush` when done.
- `ObjectEchoClientHandler` doesn't release `msg` in `channelRead` this may leak to memory leaks.

I'm not sure why you think the values are not applied and what `If I reverse the option/childOption, then the speed recovers.` means. Please be more specific as to how you came to these conclusions (e.g. include output from `lsof -T fq).

**Comment by QazPolma** [comment] 2017-06-15 11:28
Thank you for pointers on the implementation. I only fiddled with the methods until it started exibiting the same weird behaviour as the personal project, so did not put more effort.

The only reason I think that send buffer values are not applied is because when I set `ServerBootstrap.option(ChannelOption.SO_SNDBUF, 64 * 1024)` in `ObjectEchoServer` I get the following warning: 
> PM io.netty.bootstrap.AbstractBootstrap setChannelOption
> WARNING: Unknown channel option 'SO_SNDBUF' for channel '[id: 0x3b9be615]'

This warning does not show up in an older release, e.g. 4.1.6. Other than the warning itself, I did not notice any other difference.


About the `option/childOption` issue:
When setting parameters in `ObjectEchoServer`, if I use `ServerBootstrap.childOption(ChannelOption.SO_SNDBUF, 64 * 1024)`, the transfer speed server to agent will be `x`. If I use `ServerBootstrap.option(ChannelOption.SO_SNDBUF, 64 * 1024)`, then the speed in the same direction is `2x`. If I artificially increase latency(~300ms), then the speed difference between 
`option` and `childOption` becomes even more significant. 
In case of `ChannelOption.SO_RCVBUF` during setup in `ObjectEchoServer` class, the `ServerBootstrap.option(ChannelOption.SO_RCVBUF, 64 * 1024)` gives slower speeds than `ServerBootstrap.childOption(ChannelOption.SO_RCVBUF, 64 * 1024)`.
So, I have to use `option` for `SO_SNDBUF` and `childOption` for `SO_RCVBUF` to get highest speed in both directions. 
Should it be this way?

Can I use a different command to provide some output, since `lsof -T fq` doesn't have all the options available under Ubuntu virtual machine?

**Comment by normanmaurer** [comment] 2017-07-05 06:40
@QazPolma this log did not show up in earlier releases as that was a bug that was fixed. You want to set it on the child Channel via `childOption(...)`

**Comment by normanmaurer** [comment] 2017-12-13 13:20
I will close this for now ... please reopen if you still think there is an issue and provide more details

**Closed by normanmaurer** 2017-12-13 13:20 UTC
Labels: needs info

**Comment by hyperxpro** [comment] 2020-09-12 18:38
@normanmaurer I think we should support `SO_SNDBUF` in `ServerBootstrap`. Setting it like this `ctx.channel().config().setOption(ChannelOption.SO_SNDBUF, 2147483647);` works but might not be the best solution.

**Comment by yaauie** [comment] 2023-02-24 19:16
Note for posterity:

`SO_SNDBUF` _is_ supported in `ServerBootstrap#childOption`.

It does not make sense to apply send buffer sizing to the `ServerSocketChannel` since it is only _listening_ for inbound connections and not sending data; when new connections are received, they get their own `SocketChannel` which is configured with the `childOption`.
