### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by grgvineet** [netty/netty#3904] opened 2015-06-20 09:24 UTC
Netty version: 4.0.23.Final

I am using Netty in an Android application KDE connect. KDE Connect is a project that aims to communicate all your devices. It has both server and client implementation and it depends how it will behave. When a new device enter in a network it broadcasts an identity package and other other device can can connect to it on receiving that identity package.
The application runs fine on certain devices and Android versions but as of now in testing on Android 4.2 I am getting Out of Memory Exception. An NioEventLoopGroup thread is causing this trouble, some times there are two or more with similar situation.

The stack for the exception : 
06-20 09:01:21.064    4779-4834/? I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:856)
06-20 09:01:21.064    4779-4834/? I/dalvikvm﹕ [ 06-20 09:01:21.064  4779: 4834 W/System.err ]
    java.lang.OutOfMemoryError
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:45)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:43)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:136)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:127)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:109)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
06-20 09:01:21.064    4779-4834/? W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
06-20 09:01:21.164    4779-4834/? I/dalvikvm-heap﹕ Clamp target GC heap from 102.743MB to 96.000MB
06-20 09:01:21.164    4779-4834/? I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 16396-byte allocation
06-20 09:01:21.276    4779-4834/? I/dalvikvm-heap﹕ Clamp target GC heap from 102.743MB to 96.000MB
06-20 09:01:21.276    4779-4834/? E/dalvikvm-heap﹕ Out of memory on a 16396-byte allocation.
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ "nioEventLoopGroup-5-1" prio=10 tid=18 RUNNABLE
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0xa65c2530 self=0xb7be1188
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ | sysTid=4834 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1212055384
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ | state=R schedstat=( 204198344270 6670218661 51050 ) utm=19965 stm=455 core=0
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:~45)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:43)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:136)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:127)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:109)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
06-20 09:01:21.276    4779-4834/? I/dalvikvm﹕ at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
 
The source code for the class where server and client is implemented is available at : https://github.com/grgvineet/kdeconnect-android/blob/netty/src/org/kde/kdeconnect/Backends/LanBackend/LanLinkProvider.java

**Comment by normanmaurer** [comment] 2015-06-25 08:25
What about taking a heap dump ?

**Comment by grgvineet** [comment] 2015-06-25 12:18
Not getting an exception, but still a thread goes wild with too much cpu usage and garbage collection. Here is the link for heap dump https://drive.google.com/file/d/0B7UrqqDErPX4djZ2Mzl3NGNnLTA/view?usp=sharing.
Here are the images showing threads in Android Device Manager
![thread1](https://cloud.githubusercontent.com/assets/6297036/8354028/39dc2010-1b62-11e5-9f42-e9ce00b770a5.png)
![thread2](https://cloud.githubusercontent.com/assets/6297036/8354031/46c98f60-1b62-11e5-9baa-2f4df921c6fe.png)

**Comment by normanmaurer** [comment] 2015-06-27 20:00
@grgvineet could you try to move to PooledByteBufAllocator ?

**Comment by grgvineet** [comment] 2015-06-27 20:49
Still getting this.
Could be somehow related to Security Provider ?
![thread3](https://cloud.githubusercontent.com/assets/6297036/8393766/ff56423c-1d3b-11e5-94e2-1d5bb2c793a5.png)

**Comment by grgvineet** [comment] 2015-06-28 21:58
Seems like something within Android, from its security provider is creating problem for Netty. Updated security provider and everything is working fine. Android does not use java's security provider, instead it uses conscrypt[1], an open ssl based java provider. Can you look into the matter and provide support for it, means for an older version of it. Netty is fine for new version.

[1]https://conscrypt.org

**Comment by grgvineet** [comment] 2015-08-04 00:24
As mentioned earlier, the problem only occurs on Android 4.2 and less. By hacking into netty code with some print statements I found out that the problem is similar to a problem[1] in restlet framework. Can we fix it within netty?

[1] https://github.com/restlet/restlet-framework-java/issues/852

**Comment by Scottmitch** [comment] 2015-08-04 01:30
@grgvineet - This seems like a duplicate of https://github.com/netty/netty/issues/3692. WDYT?

**Comment by grgvineet** [comment] 2015-08-04 20:32
I think so, but is this solvable like restlet people solved it, if it does not impact non-android usage ?

**Comment by Scottmitch** [comment] 2015-08-04 20:52
@grgvineet - There may be a work around, but I think the root cause was identified as a defect in android. I think when @alexzk1 tried a work around he just ran into more issues. If you would like to submit a PR we could review it and see if the impact is low enough for cases which don't require the work around.

**Comment by grgvineet** [comment] 2015-08-16 14:49
There is a method named "setHandshakeSuccessIfStillHandshaking" in SslHandler to fix this issue tha SSLEngine is directly going to NOT_HANDSHAKING instead of FINISHED. But it is not working since the loop in wrapNonAppData cannot break because on calling wrap, even though bytesConsumed is zero, bytesProduced is 21. So it is encrypting empty buffer. The loop only breaks when bytesProduces is zero which is not the case here.
I added following code there, that bytesConsumed should not be zero when the hand shake status is not NOT_HANDSHAKING.
if (result.bytesConsumed() == 0 && result.getHandshakeStatus() == HandshakeStatus.NOT_HANDSHAKING) {
                    result = new SSLEngineResult(result.getStatus(), HandshakeStatus.FINISHED, 0, 0);
}
And I am able to get a sucessful SSL Server on my Android device which getting high CPU and memory usage now :) 
So the main issue is that if byteConsumed is zero after going into NOT_HANDSHAKING, bytes are produces and loop can't break.

**Comment by Scottmitch** [comment] 2015-08-17 15:48
@grgvineet - Cool. Do you feel as though this is a generic fix, and if so would you mind submitting a PR?

**Comment by normanmaurer** [comment] 2015-08-19 20:20
Fixed by https://github.com/netty/netty/pull/4101

**Closed by normanmaurer** 2015-08-19 20:20 UTC

**Comment by Scottmitch** [comment] 2015-08-19 20:27
Thanks @grgvineet !
