### ISSUE TITLE
java.util.zip.DataFormatException: invalid block type in JdkZlibDecoder for large gzip stream

### ISSUE THREAD

**Issue by shemminga** [netty/netty#11479] opened 2021-07-11 10:27 UTC
When downloading a large gzip stream, Inflater throws a DataFormatException when using HttpContentDecompressor, but not when using a GZIPInputStream.

### Expected behavior

No exception.

### Actual behavior

```
Exception in thread "main" io.netty.handler.codec.compression.DecompressionException: decompression failure
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:273)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:264)
	at io.netty.handler.codec.http.HttpContentDecoder.decodeContent(HttpContentDecoder.java:171)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:160)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:47)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.nextlisten.commoncreeper.Temp3$1.channelRead(Temp3.java:27)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1280)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at com.nextlisten.commoncreeper.Temp3.main(Temp3.java:38)
Caused by: java.util.zip.DataFormatException: invalid block type
	at java.base/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:378)
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:240)
	... 56 more
```

Full logs: [logs.txt](https://github.com/netty/netty/files/6796744/logs.txt)

### Steps to reproduce

* Install a handler that overrides the `Content-encoding` header to `gzip`, and the `Content-type` header to `text/plain`
* Install `HttpContentDecompressor` as a handler after that
* Go download a small gzip file (e.g. 845 bytes compressed: https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-25/cc-index.paths.gz ). That will work.
* Go download a large/huge gzip file (e.g. 740 MB compressed, 5.2 GB uncompressed: https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-25/indexes/cdx-00000.gz) and it will throw a DataFormatException.

To verify that the stream itself isn't corrupt, we can do the following:
* Get body as an inputStream and wrap it in a GZIPInputStream
* Reading the entire stream from the GZIPInputStream is successful.

### Minimal yet complete reproducer code (or URL to code)

This code fails:
```java
public class Temp3 {
    public static final void main(final String... args) {
        final HttpClient httpClient = HttpClient.create()
                .doOnConnected(c -> {
                    c.addHandlerFirst(new HttpContentDecompressor());
                    c.addHandlerFirst(new ChannelInboundHandlerAdapter() {
                        @Override
                        public void channelRead(final ChannelHandlerContext ctx, final Object msg) {
                            if (msg instanceof HttpResponse response && response.status().code() >= 200) {
                                response.headers()
                                        .set(HttpHeaderNames.CONTENT_ENCODING, HttpHeaderValues.GZIP)
                                        .set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);
                            }

                            ctx.fireChannelRead(msg);
                        }
                    });
                })
                .compress(true);

        httpClient
                .get()
                .uri("https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-25/indexes/cdx-00000.gz")
                .responseSingle((httpClientResponse, byteBufMono) -> byteBufMono.asString(StandardCharsets.UTF_8))
                .doOnNext(s -> System.out.println(s.substring(0, 1000)))
                .block();
    }
}
```

This code succeeds:
```java
public class Temp4 {
    public static final void main(final String... args) throws IOException {
        final HttpClient httpClient = HttpClient.create();
        final InputStream is = httpClient.get()
                .uri("https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-25/indexes/cdx-00000.gz")
                .responseSingle((httpClientResponse, byteBufMono) -> byteBufMono.asInputStream())
                .block();

        try (final GZIPInputStream gis = new GZIPInputStream(is);
                final CountingOutputStream cos = new CountingOutputStream()) {
            gis.transferTo(cos);
            System.out.println(cos.size);
        } finally {
            is.close();
        }
    }

    private static class CountingOutputStream extends OutputStream {
        private long size = 0;

        @Override
        public void write(final int b) throws IOException {
            size++;
        }
    }
}
```

### Netty version
* netty-codec-http: 4.1.65.Final
* netty-transport: 4.1.65.Final
* reactor-netty-http: 1.0.8

### JVM version (e.g. `java -version`)
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Windows 10 Pro 21H1 (build 19043.1083)

**Comment by NiteshKant** [comment] 2021-07-12 17:50
@shemminga looks like your reproducer uses reactor. In order to make sure that the issue is with netty code and not possibly some configuration in reactor, can you provide a netty only reproducer?

**Comment by shemminga** [comment] 2021-07-13 23:32
Sure.

I'm not entirely confident that I got the details right on the following, but it shows the same behaviour as the version with reactor-netty.

```java
import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.DefaultHttpRequest;
import io.netty.handler.codec.http.HttpContent;
import io.netty.handler.codec.http.HttpContentDecompressor;
import io.netty.handler.codec.http.HttpHeaderNames;
import io.netty.handler.codec.http.HttpHeaderValues;
import io.netty.handler.codec.http.HttpMethod;
import io.netty.handler.codec.http.HttpRequest;
import io.netty.handler.codec.http.HttpRequestEncoder;
import io.netty.handler.codec.http.HttpResponse;
import io.netty.handler.codec.http.HttpResponseDecoder;
import io.netty.handler.codec.http.HttpVersion;

public class Temp5 {
    public static final void main(final String... args) {
        final EventLoopGroup workerGroup = new NioEventLoopGroup();

        try {
            final Bootstrap b = new Bootstrap();
            b.group(workerGroup);
            b.channel(NioSocketChannel.class);
            b.handler(new ChannelInitializer<SocketChannel>() {
                @Override
                protected void initChannel(final SocketChannel ch) {
                    ch.pipeline()
                            .addLast(new HttpRequestEncoder())
                            .addLast(new HttpResponseDecoder())
                            .addLast(new ForceDecompressHandler())
                            .addLast(new HttpContentDecompressor())
                            .addLast(new ResultHandler());
                }
            });

            final String host = "commoncrawl.s3.amazonaws.com";
            final int port = 80;
            //final String path = "/crawl-data/CC-MAIN-2021-25/cc-index.paths.gz";
            final String path = "/cc-index/collections/CC-MAIN-2021-25/indexes/cdx-00000.gz";

            final HttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.GET, path);
            request.headers().add("Host", host);
            request.headers().add("Connection", "close");

            final ChannelFuture future = b.connect(host, port).syncUninterruptibly();
            future.channel().writeAndFlush(request).syncUninterruptibly();
            future.channel().closeFuture().syncUninterruptibly();

            System.out.println(ResultHandler.byteCounter);
        } finally {
            workerGroup.shutdownGracefully();
        }
    }

    private static class ResultHandler extends ChannelInboundHandlerAdapter {
        private static long byteCounter = 0;

        @Override
        public void channelRead(final ChannelHandlerContext ctx, final Object msg) {
            if (msg instanceof HttpContent content) {
                final ByteBuf byteBuf = content.content();
                if (byteBuf.readableBytes() > 0) {
                    //System.out.println(byteBuf.getCharSequence(byteBuf.readerIndex(), byteBuf.readableBytes(),
                    //        StandardCharsets.UTF_8));
                    byteCounter += byteBuf.readableBytes();
                }
                byteBuf.release();
            }
        }

        @Override
        public void exceptionCaught(final ChannelHandlerContext ctx, final Throwable cause) {
            cause.printStackTrace();
            ctx.close().syncUninterruptibly();
        }
    }

    private static class ForceDecompressHandler extends ChannelInboundHandlerAdapter {
        @Override
        public void channelRead(final ChannelHandlerContext ctx, final Object msg) {
            if (msg instanceof HttpResponse response && response.status().code() >= 200) {
                response.headers()
                        .set(HttpHeaderNames.CONTENT_ENCODING, HttpHeaderValues.GZIP)
                        .set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);
            }

            ctx.fireChannelRead(msg);
        }
    }
}
```

Stacktrace:
```io.netty.handler.codec.compression.DecompressionException: decompression failure
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:273)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:264)
	at io.netty.handler.codec.http.HttpContentDecoder.decodeContent(HttpContentDecoder.java:171)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:160)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:47)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.nextlisten.commoncreeper.Temp5$ForceDecompressHandler.channelRead(Temp5.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.util.zip.DataFormatException: invalid block type
	at java.base/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:378)
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:240)
	... 41 more
io.netty.handler.codec.compression.DecompressionException: decompression failure
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:273)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
	at io.netty.channel.embedded.EmbeddedEventLoop.runTasks(EmbeddedEventLoop.java:58)
	at io.netty.channel.embedded.EmbeddedChannel.runPendingTasks(EmbeddedChannel.java:596)
	at io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.close(EmbeddedChannel.java:816)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:280)
	at io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:568)
	at io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:555)
	at io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:503)
	at io.netty.channel.embedded.EmbeddedChannel.finishAndReleaseAll(EmbeddedChannel.java:493)
	at io.netty.handler.codec.http.HttpContentDecoder.cleanup(HttpContentDecoder.java:247)
	at io.netty.handler.codec.http.HttpContentDecoder.cleanupSafely(HttpContentDecoder.java:254)
	at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:234)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.util.zip.DataFormatException: invalid block type
	at java.base/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:378)
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:240)
	... 48 more
```

**Comment by NiteshKant** [comment] 2021-07-14 20:46
This does look like a bug, the provided reproducer, reproduces for me locally too. It seems to always happen after we finish reading a footer but not every time we finish reading a footer 😭 

@idelpivnitskiy any idea?

Not related to this issue, but it seems like `JdkZlibDecoder` does not clear state when it itself throws an `Exception` and hence tries to keep decoding even though a previous decode failed.

**Comment by normanmaurer** [comment] 2021-07-15 13:32
@NiteshKant imho the only sane thing todo in case of an exception would be to close the channel. WDYT ?

**Comment by NiteshKant** [comment] 2021-07-15 17:21
@normanmaurer yes and set the internal state to `finished` such that we just discard all subsequent bytes.

**Comment by normanmaurer** [comment] 2021-07-15 17:23
@NiteshKant sounds like a plan

**Comment by NiteshKant** [comment] 2021-07-15 17:24
Just to be clear, that isn't the cause of this issue, I just noticed it during debugging as it threw multiple times due to the same issue.

**Comment by idelpivnitskiy** [comment] 2021-07-22 23:57
After a quick look my guess is that we mess with indexes when we set more input for inflator. There is a risk that we push the same bytes twice if indexes are moved incorrectly between multiple `decode` invocations.

I did check that `JZlibDecoder` works fine with this input. So, the workaround will be to use `-Dio.netty.noJdkZlibDecoder=true` system property. `JdkZlibDecoder` requires deeper debugging.

**Comment by normanmaurer** [comment] 2021-07-26 09:51
Let me have a look.

**Comment by normanmaurer** [comment] 2021-07-27 14:21
This is fixed by https://github.com/netty/netty/pull/11521 ... I am currently looking into writing a test-case for it.

**Comment by normanmaurer** [comment] 2021-07-27 14:39
Ok testcase was added as well

**Closed** 2021-07-28 07:21 UTC
