### ISSUE TITLE
how to avoid direct memory peak up and channel isWritable =false

### ISSUE THREAD

**Issue by jiangguilong2000** [netty/netty#3511] opened 2015-03-18 18:00 UTC
I find the  direct memory peak up whenthe channel's isWritable attribute is false, and I continue to send message using this channel.and the message can't sent at once.
I send message using as follows:channel.writeAndFlush(msg);
my question is how to avoid that the channel change to isWritable =false status,
whether I need to use write some messages and at last use flush to send message  at regular intervals?

PS :i use PooledByteBufAllocator

**Comment by Scottmitch** [comment] 2015-03-18 18:29
What transport protocol are you using?  If the channel is not writable for TCP this can mean you are writing faster than your peer is consuming the data.  If this is the case then you may not be able to avoid the change in channel writability because it is not directly under your control, but instead is a function of your peer (and maybe networking/environment conditions).  You instead may want to decide how your application can react when these situations occur.  You may want to look into back pressure references.

**Comment by jiangguilong2000** [comment] 2015-03-18 18:41
@Scottmitch  TCP   transport protocol

**Comment by Scottmitch** [comment] 2015-03-18 18:55
Does my previous comment make sense?  Do you think that you are sending faster than the peer can consume, and then as a result allocating more buffers because they are not being sent immediately, and eventually you get backed up and start running out of memory (aka back pressure).

**Comment by kenro** [comment] 2015-03-19 13:25
@Scottmitch, I also meet the same problem.  I need send a lot of message . and wait some time .  when I send too much, its memory will become larger and larger . when the client closed, the memory is still large.

**Comment by kenro** [comment] 2015-03-19 13:26
@Scottmitch, I also meet the same problem.  I need send a lot of message . and wait some time .  when I send too much, its memory will become larger and larger . when the client closed, the memory is still large.

**Comment by kenro** [comment] 2015-03-20 01:56
@Scottmitch, I also meet the same problem.  I need send a lot of message . and wait some time .  when I send too much, its memory will become larger and larger . when the client closed, the memory is still large.

**Comment by kenro** [comment] 2015-03-20 01:57
@Scottmitch, I also meet the same problem.  I need send a lot of message . and wait some time .  when I send too much, its memory will become larger and larger . when the client closed, the memory is still large.

**Comment by Scottmitch** [comment] 2015-03-20 07:41
You can use the `WRITE_BUFFER_HIGH_WATER_MARK` and `WRITE_BUFFER_LOW_WATER_MARK` to control when `isWritable()` and `channelWritabilityChanged(..)` change.  If the data being sent to these peers is being generated off a socket (or something read on a netty event loop) you can also use `setAutoRead(false)` to stop reading automatically so you put the queueing on the transport instead of the application.

@kenro - Do you have a responsibly small reproducer?

**Comment by jiangguilong2000** [comment] 2015-03-20 17:00
@scottmitch,sorry,I cant understand, can you show me a example code? thank you!

**Comment by Scottmitch** [comment] 2015-03-22 01:13
@jiangguilong2000 - Check out http://stackoverflow.com/questions/19720956/get-oom-exception-when-sending-message-with-a-high-speed-with-netty/19721250#19721250 and http://stackoverflow.com/questions/25281124/netty-4-high-and-low-write-watermarks.

**Comment by normanmaurer** [comment] 2015-09-09 12:30
Let us close this ...

**Closed by normanmaurer** 2015-09-09 12:30 UTC
