### ISSUE TITLE
UnsatisfiedLinkError after upgrade to 4.1.69.Final

### ISSUE THREAD

**Issue by bxqgit** [netty/netty#11768] opened 2021-10-17 21:35 UTC
### Expected behavior

Everything works as it worked.

### Actual behavior

```
java.lang.UnsatisfiedLinkError: failed to load the required native library
java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_x86_64
java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: /u    sr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
```

### Steps to reproduce

0. Use `netty-all`
1. Upgrade to 4.1.69.Final
2. Build on Windows
3. Run on Ubuntu

### Minimal yet complete reproducer code (or URL to code)

Any hello world that uses `epoll`.

### Netty version

4.1.69.Final

### JVM version (e.g. `java -version`)

```
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7-67)
OpenJDK 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

`Linux 5.13.4-x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux`

**Comment by chrisvest** [comment] 2021-10-18 07:13
@bxqgit You need to add a dependency on `netty-transport-native-epoll` with the correct classifier for your target platform: `<classifier>linux-x86_64</classifier>`

This may be easier to control if instead of depending on `netty-all`, you depend on just the modules you need.

**Comment by bxqgit** [comment] 2021-10-19 09:08
@chrisvest Thanks, now it works!

To Whom It May Concern:
```
implementation "io.netty:netty-all:$version_netty"
implementation "io.netty:netty-transport-native-epoll:$version_netty:linux-x86_64"
```

**Comment by bxqgit** [comment] 2021-10-19 09:10
@hyperxpro 

I'm building a project on Windows and running on Linux.
If you add `epoll` dependency without a classifier, it will compile on Windows, but won't work on Linux.

**Comment by MrEasy** [comment] 2021-11-05 12:32
Had the same issue, when both jars:
- netty-transport-native-epoll
- netty-transport-native-epoll-linux-x86_64
were present, since they export the same classes and then it may happen, that EPoll class is loaded from non-linux and then does not find the native library in its bundle.

The changes made to #11791 should resolve this from my point of view.

**Comment by normanmaurer** [comment] 2021-12-09 08:45
Closing as we can not reproduce anymore

**Closed by normanmaurer** 2021-12-09 08:45 UTC
