### ISSUE TITLE
SSL fails on example in 4.0.27.Final

### ISSUE THREAD

**Issue by odbuser2** [netty/netty#3632] opened 2015-04-15 04:28 UTC
io.netty:netty-all:4.0.27.Final
io.netty:netty-example:4.0.27.Final
Example: io.netty.example.http.file.HttpStaticFileServer
JavaSE: Oracle 8u40 on OSX

This example fails to serve a file when you use SSL (-Dssl=true).  Directory listing works fine.

**Comment by trustin** [comment] 2015-04-15 05:37
Duplicate of #3592

**Closed by trustin** 2015-04-15 05:37 UTC
