### ISSUE TITLE
HttpObjectEncoder can not encode chunked response

### ISSUE THREAD

**Issue by cpf624** [netty/netty#4677] opened 2016-01-08 15:04 UTC
I'm tring HttpStaticFileServer with netty `5.0.0.Alpha2`, but not work, and I find that has two issues.

1. the `DefaultFullHttpResponse` implements `LastHttpContent`, after encode any of `DefaultFullHttpResponse` msg, `HttpObjectEncoder#encodeChunkedContent` will reset `state` to `ST_INIT`, then rest msg can not be encoded.
 ```java
private void encodeChunkedContent(ChannelHandlerContext ctx, Object msg, long contentLength, List<Object> out) {
        ...
        if (msg instanceof LastHttpContent) {
            ...
            state = ST_INIT; // Line 171
        } else {
            ...
        }
        ...
}
```

2. the sample code not set `transfer-encoding` header to `chunked`. in HttpObjectEncoder will process as `chunked` response only the response msg has `chunked` header. 
 ```java
protected void encode(ChannelHandlerContext ctx, Object msg, List<Object> out) throws Exception {
        if (msg instanceof HttpMessage) {
            ...
            state = HttpHeaderUtil.isTransferEncodingChunked(m) ? ST_CONTENT_CHUNK : ST_CONTENT_NON_CHUNK; // Line 75
            ...
        }
}
```

**Comment by windie** [comment] 2016-01-09 07:32
> the DefaultFullHttpResponse implements LastHttpContent, after encode any of DefaultFullHttpResponse msg, HttpObjectEncoder#encodeChunkedContent will reset state to ST_INIT, then rest msg can not be encoded.

I think this is the expected behaviour since it's a completed http message.

**Comment by cpf624** [comment] 2016-01-09 07:54
in `HttpStaticFileServer` only the response header was encoded, but the `chunked` file content can not be encoded.
And I think this will also cause `Keep-Alive` not work.

**Comment by windie** [comment] 2016-01-09 07:57
> the sample code not set transfer-encoding header to chunked. in HttpObjectEncoder will process as chunked response only the response msg has chunked header.

Just sent #4683 to fix it.

**Comment by windie** [comment] 2016-01-09 08:00
> in HttpStaticFileServer only the response header was encoded, but the chunked file content can not be encoded.
> And I think this will also cause Keep-Alive not work.

HttpStaticFileServerHandler uses DefaultHttpResponse to send the file:
https://github.com/netty/netty/blob/b6a4f5de9d213cdbe32ff7772be4bcf6a1ba9094/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java#L177

`DefaultFullHttpResponse` is used to send the file list and doesn't use HttpChunkedInput.

**Comment by cpf624** [comment] 2016-01-10 06:41
HttpStaticFileServerHandler uses `DefaultHttpResponse` to send the `header`:
https://github.com/netty/netty/blob/b6a4f5de9d213cdbe32ff7772be4bcf6a1ba9094/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java#L186

and uses `HttpChunkedInput` to send the `content`:
https://github.com/netty/netty/blob/b6a4f5de9d213cdbe32ff7772be4bcf6a1ba9094/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java#L198

but only the `header` was encoded by `HttpObjectEncoder`, the `content` can not be encoded.

**Comment by windie** [comment] 2016-01-10 07:11
When I ran `HttpStaticFileServer` with ssl and downloaded a file, I did see `HttpObjectEncoder` processes `DefaultHttpResponse` and the following `DefaultHttpContent`s. Did you see any unexpected behaviour?

**Comment by cpf624** [comment] 2016-01-10 09:48
`IllegalStateException` will be throwed in `HttpObjectEncoder`  both http and https:
https://github.com/netty/netty/blob/netty-5.0.0.Alpha2/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L92

because after the `DefaultHttpResponse  header` was encoded, the `state` has been reset to `ST_INIT `:
https://github.com/netty/netty/blob/netty-5.0.0.Alpha2/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L171

**Comment by windie** [comment] 2016-01-10 22:15
Sorry, I was testing the branch 4.1. Yes, `HttpStaticFileServer` is broken in `5.0.0.Alpha2`. However, since 5.0 has been dropped (#4466), could you test branch 4.1 and see if it still doesn't work?

**Comment by cpf624** [comment] 2016-01-11 03:17
I tried `4.1` and got the same error.

**Comment by normanmaurer** [comment] 2016-01-11 08:51
@cpf624 can you please tell us the exact steps you did. Tried with 4.1 branch with and without ssl and it "just works".

**Comment by cpf624** [comment] 2016-01-11 09:33
Sorry, it's my fault, I write wrong `HttpResponse` as `FullHttpResponse`:
```java
FullHttpResponse response = new DefaultFullHttpResponse(HTTP_1_1, OK);
```
it should be:
https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java#L177

**Comment by normanmaurer** [comment] 2016-01-11 09:37
Ok closing...

**Closed by normanmaurer** 2016-01-11 09:37 UTC
