### ISSUE TITLE
JNI classloader deadlock with latest JDK version

### ISSUE THREAD

**Issue by njhill** [netty/netty#11209] opened 2021-04-28 18:30 UTC
### Expected behavior

No classloader deadlocks

### Actual behavior

I am still investigating but there appears to be a possible class loading concurrency deadlock when using the epoll transport - it started when upgrading from OpenJDK 11.0.10 to 11.0.11.

It looks to be related to JNI reentrancy where the `netty_epoll_native_JNI_OnLoad` func, which happens in the context of static initialization of the `Epoll`/`Native` classes, calls back into java to initialize additional classes. The deadlock happens between this and another (non-native) thread in the process of loading other classes.

See stacks of deadlocked threads below.

Seems likely it's a new JDK bug. I noticed this other recent netty issue/fix which is kind of related, but this appears to be more problematic because the second thread is loading an unrelated class: https://github.com/netty/netty/issues/10187

I was able to workaround by forcing the native classes to load upfront.

### Steps to reproduce

Load `Epoll` at the same time as other classes are loading in another thread (I guess it might similarly apply to the other native modules e.g. `OpenSsl`).

### Minimal yet complete reproducer code (or URL to code)

Don't have reproducer but it happens pretty reliably (my testsuite failed every time).

### Netty version

`4.1.63.Final`

### JVM version (e.g. `java -version`)
```
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9-LTS, mixed mode, sharing)
```
### OS version (e.g. `uname -a`)
```
Linux b7992f1e6991 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Stacktraces

```
[INFO] "main":
[INFO]  at java.util.zip.ZipFile.getEntry(java.base@11.0.11/ZipFile.java:346)
[INFO]  - waiting to lock <0x00000000e119d0a8> (a java.util.jar.JarFile)
[INFO]  at java.util.zip.ZipFile$1.getEntry(java.base@11.0.11/ZipFile.java:1126)
[INFO]  at java.util.jar.JarFile.getEntry0(java.base@11.0.11/JarFile.java:578)
[INFO]  at java.util.jar.JarFile.getEntry(java.base@11.0.11/JarFile.java:508)
[INFO]  at java.util.jar.JarFile.getJarEntry(java.base@11.0.11/JarFile.java:470)
[INFO]  at jdk.internal.loader.URLClassPath$JarLoader.getResource(java.base@11.0.11/URLClassPath.java:929)
[INFO]  at jdk.internal.loader.URLClassPath.getResource(java.base@11.0.11/URLClassPath.java:314)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11.0.11/BuiltinClassLoader.java:695)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11.0.11/BuiltinClassLoader.java:621)
[INFO]  - locked <0x00000000e2006a18> (a java.lang.Object)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.11/BuiltinClassLoader.java:579)
[INFO]  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.11/ClassLoaders.java:178)
[INFO]  at java.lang.ClassLoader.loadClass(java.base@11.0.11/ClassLoader.java:522)
[INFO]  at java.lang.ClassLoader$NativeLibrary.load0(java.base@11.0.11/Native Method)
[INFO]  at java.lang.ClassLoader$NativeLibrary.load(java.base@11.0.11/ClassLoader.java:2442)
[INFO]  at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.11/ClassLoader.java:2498)
[INFO]  - locked <0x00000000e11d6ad0> (a java.util.HashSet)
[INFO]  at java.lang.ClassLoader.loadLibrary0(java.base@11.0.11/ClassLoader.java:2694)
[INFO]  at java.lang.ClassLoader.loadLibrary(java.base@11.0.11/ClassLoader.java:2627)
[INFO]  at java.lang.Runtime.load0(java.base@11.0.11/Runtime.java:768)
[INFO]  at java.lang.System.load(java.base@11.0.11/System.java:1837)
[INFO]  at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
[INFO]  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.11/Native Method)
[INFO]  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.11/NativeMethodAccessorImpl.java:62)
[INFO]  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.11/DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(java.base@11.0.11/Method.java:566)
[INFO]  at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:378)
[INFO]  at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
[INFO]  at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:370)
[INFO]  at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:336)
[INFO]  at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:200)
[INFO]  at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:290)
[INFO]  at io.netty.channel.epoll.Native.<clinit>(Native.java:70)
[INFO]  at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
[INFO]  at java.lang.Class.forName0(java.base@11.0.11/Native Method)
[INFO]  at java.lang.Class.forName(java.base@11.0.11/Class.java:315)
[INFO]  at io.grpc.netty.Utils.isEpollAvailable(Utils.java:291)
[INFO]  at io.grpc.netty.Utils.<clinit>(Utils.java:109)
[INFO]  at io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:83)
[INFO]  at c.i.w.m.e.ApplicationCode.applicationMethod(ApplicationCode.java:112)
[INFO]  at c.i.w.m.e.ApplicationCode.<init>(ApplicationCode.java:108)
[INFO]  at c.i.w.m.e.ApplicationCode.<init>(ApplicationCode.java:101)
[INFO]  at c.i.w.m.AppUnitTest.initialize(AppUnitTest.java:90)
[INFO]  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.11/Native Method)
[INFO]  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.11/NativeMethodAccessorImpl.java:62)
[INFO]  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.11/DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(java.base@11.0.11/Method.java:566)
[INFO]  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[INFO]  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[INFO]  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[INFO]  at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
[INFO]  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[INFO]  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[INFO]  at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[INFO]  at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[INFO]  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
[INFO]  at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
[INFO]  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
[INFO]  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

```
[INFO] "other-thread":
[INFO]  at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.11/ClassLoader.java:2462)
[INFO]  - waiting to lock <0x00000000e11d6ad0> (a java.util.HashSet)
[INFO]  at java.lang.ClassLoader.loadLibrary0(java.base@11.0.11/ClassLoader.java:2694)
[INFO]  at java.lang.ClassLoader.loadLibrary(java.base@11.0.11/ClassLoader.java:2648)
[INFO]  at java.lang.Runtime.loadLibrary0(java.base@11.0.11/Runtime.java:830)
[INFO]  at java.lang.System.loadLibrary(java.base@11.0.11/System.java:1873)
[INFO]  at sun.security.ec.SunEC$1.run(jdk.crypto.ec@11.0.11/SunEC.java:63)
[INFO]  at sun.security.ec.SunEC$1.run(jdk.crypto.ec@11.0.11/SunEC.java:61)
[INFO]  at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
[INFO]  at sun.security.ec.SunEC.<clinit>(jdk.crypto.ec@11.0.11/SunEC.java:61)
[INFO]  at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@11.0.11/Native Method)
[INFO]  at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@11.0.11/NativeConstructorAccessorImpl.java:62)
[INFO]  at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@11.0.11/DelegatingConstructorAccessorImpl.java:45)
[INFO]  at java.lang.reflect.Constructor.newInstance(java.base@11.0.11/Constructor.java:490)
[INFO]  at java.util.ServiceLoader$ProviderImpl.newInstance(java.base@11.0.11/ServiceLoader.java:780)
[INFO]  at java.util.ServiceLoader$ProviderImpl.get(java.base@11.0.11/ServiceLoader.java:722)
[INFO]  at java.util.ServiceLoader$3.next(java.base@11.0.11/ServiceLoader.java:1395)
[INFO]  at sun.security.jca.ProviderConfig$ProviderLoader.load(java.base@11.0.11/ProviderConfig.java:340)
[INFO]  at sun.security.jca.ProviderConfig$3.run(java.base@11.0.11/ProviderConfig.java:248)
[INFO]  at sun.security.jca.ProviderConfig$3.run(java.base@11.0.11/ProviderConfig.java:242)
[INFO]  at java.security.AccessController.doPrivileged(java.base@11.0.11/Native Method)
[INFO]  at sun.security.jca.ProviderConfig.doLoadProvider(java.base@11.0.11/ProviderConfig.java:242)
[INFO]  at sun.security.jca.ProviderConfig.getProvider(java.base@11.0.11/ProviderConfig.java:222)
[INFO]  - locked <0x00000000e20c9f58> (a sun.security.jca.ProviderConfig)
[INFO]  at sun.security.jca.ProviderList.loadAll(java.base@11.0.11/ProviderList.java:315)
[INFO]  at sun.security.jca.ProviderList.removeInvalid(java.base@11.0.11/ProviderList.java:332)
[INFO]  at sun.security.jca.Providers.getFullProviderList(java.base@11.0.11/Providers.java:165)
[INFO]  - locked <0x00000000e20bc668> (a java.lang.Class for sun.security.jca.Providers)
[INFO]  at java.security.Security.getProviders(java.base@11.0.11/Security.java:483)
[INFO]  at sun.security.x509.AlgorithmId.computeOidTable(java.base@11.0.11/AlgorithmId.java:637)
[INFO]  at sun.security.x509.AlgorithmId.oidTable(java.base@11.0.11/AlgorithmId.java:627)
[INFO]  - locked <0x00000000e2bdd3d0> (a java.lang.Class for sun.security.x509.AlgorithmId)
[INFO]  at sun.security.x509.AlgorithmId.algOID(java.base@11.0.11/AlgorithmId.java:609)
[INFO]  at sun.security.x509.AlgorithmId.get(java.base@11.0.11/AlgorithmId.java:441)
[INFO]  at sun.security.pkcs.SignerInfo.verify(java.base@11.0.11/SignerInfo.java:380)
[INFO]  at sun.security.pkcs.PKCS7.verify(java.base@11.0.11/PKCS7.java:578)
[INFO]  at sun.security.pkcs.PKCS7.verify(java.base@11.0.11/PKCS7.java:595)
[INFO]  at sun.security.pkcs.SignerInfo.getTimestamp(java.base@11.0.11/SignerInfo.java:545)
[INFO]  at sun.security.pkcs.SignerInfo.verify(java.base@11.0.11/SignerInfo.java:318)
[INFO]  at sun.security.pkcs.PKCS7.verify(java.base@11.0.11/PKCS7.java:578)
[INFO]  at sun.security.pkcs.PKCS7.verify(java.base@11.0.11/PKCS7.java:595)
[INFO]  at sun.security.util.SignatureFileVerifier.processImpl(java.base@11.0.11/SignatureFileVerifier.java:283)
[INFO]  at sun.security.util.SignatureFileVerifier.process(java.base@11.0.11/SignatureFileVerifier.java:259)
[INFO]  at java.util.jar.JarVerifier.processEntry(java.base@11.0.11/JarVerifier.java:316)
[INFO]  at java.util.jar.JarVerifier.update(java.base@11.0.11/JarVerifier.java:230)
[INFO]  at java.util.jar.JarFile.initializeVerifier(java.base@11.0.11/JarFile.java:759)
[INFO]  at java.util.jar.JarFile.ensureInitialization(java.base@11.0.11/JarFile.java:1038)
[INFO]  - locked <0x00000000e119d0a8> (a java.util.jar.JarFile)
[INFO]  at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(java.base@11.0.11/JavaUtilJarAccessImpl.java:69)
[INFO]  at jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(java.base@11.0.11/URLClassPath.java:870)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@11.0.11/BuiltinClassLoader.java:786)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11.0.11/BuiltinClassLoader.java:698)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11.0.11/BuiltinClassLoader.java:621)
[INFO]  - locked <0x00000000e204d228> (a java.lang.Object)
[INFO]  at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.11/BuiltinClassLoader.java:579)
[INFO]  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.11/ClassLoaders.java:178)
[INFO]  at java.lang.ClassLoader.loadClass(java.base@11.0.11/ClassLoader.java:522)
[INFO]  at c.i.w.m.OtherAppCode.<init>(OtherAppCode.java:371)
[INFO]  at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@11.0.11/Native Method)
[INFO]  at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@11.0.11/NativeConstructorAccessorImpl.java:62)
[INFO]  at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@11.0.11/DelegatingConstructorAccessorImpl.java:45)
[INFO]  at java.lang.reflect.Constructor.newInstance(java.base@11.0.11/Constructor.java:490)
[INFO]  at java.lang.Class.newInstance(java.base@11.0.11/Class.java:584)
[INFO]  at c.i.w.l.server.DefaultServer.lambda$doStart$0(DefaultServer.java:347)
[INFO]  at c.i.w.l.server.DefaultServer/0x00000008401c4840.run(Unknown Source)
[INFO]  at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
[INFO]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
[INFO]  at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
[INFO]  at c.i.w.l.ThreadPoolHelper$3$1.run(ThreadPoolHelper.java:94)
```

**Comment by njhill** [comment] 2021-04-28 18:52
Looking closer, the other thread is verifying jar signature and attempting to load a native JCE-related lib as part of that. Maybe some changes in this area in the 11.0.11 update.

**Comment by normanmaurer** [comment] 2021-04-29 06:24
thats interesting... Would be interesting to know if you can also reproduce it with `4.1.58.Final`

**Comment by normanmaurer** [comment] 2021-04-29 06:25
I somehow wonder if this is caused by https://github.com/netty/netty/commit/5b41f3d25b9709b9f4c779938aa7a4b6550b727f#diff-ca59b0de3820f9d6d65289825225cc0fafbe7560a11675ac84b6025e7e1004f5

**Comment by normanmaurer** [comment] 2021-04-29 07:07
Also talking with @nitsanw a bit about this it appears to be more of a openjdk bug then a netty bug. Maybe I am wrong tho...

**Comment by normanmaurer** [comment] 2021-04-29 07:20
I started a discussion on the openjdk mailinglist:

https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2021-April/006011.html

**Comment by chrisvest** [comment] 2021-04-29 08:18
@njhill What class is being loaded from `c.i.w.m.OtherAppCode.<init>(OtherAppCode.java:371)`? I only see Netty showing up in the first stack trace.

**Comment by theRealAph** [comment] 2021-04-29 08:22
You say you don't have a reproducer, but "my testsuite failed every time". If it failed every time, then you have a reproducer.

**Comment by normanmaurer** [comment] 2021-04-29 09:24
FYI... I also tried to reproduce this by running the netty-testsuite and so far I wasn't able to :/

**Comment by ChrisHegarty** [comment] 2021-04-29 09:46
Can you please say what algorithm is used to sign the jar file here, e.g.
   jdk-11.0.11.jdk/Contents/Home/bin/jarsigner -verbose -certs -verify  XXX.jar

If it is not using an algo from the SunEC provider, it may be possible to temporarily workaround this issue by removing the SunEC provider from the list of providers in conf/java.security.   While this is not a permanent solution, it will at least confirm that the issue is with the loading of the native library used by the SunEC provider.

**Comment by njhill** [comment] 2021-04-29 17:54
Thanks @normanmaurer and co

> You say you don't have a reproducer, but "my testsuite failed every time". If it failed every time, then you have a reproducer.

@theRealAph sorry I should have been clearer. The tests are internal so I can't share readily, but I will try to put together a sharable reproducer.

> What class is being loaded from c.i.w.m.OtherAppCode.<init>(OtherAppCode.java:371)? I only see Netty showing up in the first stack trace.

@chrisvest it's a random app class (I replaced the name) and unremarkable. It does not use netty itself or even have a static initializer. It does reference some classes from the eclipse-collections lib, which I guess must be what triggers the Jar verification code path since the class itself is just a .class file.

@ChrisHegarty I attempted to remove the SunEC provider in java.security, but it does not seem to have made a difference, the test still deadlocks in the same place (with `SunEC` in the stack). I'm pretty sure this is the only `java.security` present and also tried pointing to it explicitly with `-Djava.security.properties`

Checking the eclipse collections jar, here is the algorithm with no mention of SunEC in the output:
```
Digest algorithm: SHA-256
Signature algorithm: SHA256withRSA, 2048-bit key
```

**Comment by ChrisHegarty** [comment] 2021-04-29 18:31
This issue has intrigued me :-)  I think I understand the source of the deadlock, but I'm making a few assumptions about how things work on your end. If I'm right, then this has always been quite fragile (both on the Netty side and on the JDK side). See https://github.com/ChrisHegarty/deadlock

The biggest assumption I'm making (as gleaned from the stacktrace) is that the Netty native epoll library is calling back into  Java from its JNI_OnLoad. More specifically, it is triggering the loading of a class from the same signed jar file or a jar file further down on the class path than that of jar that contains the classes for the epoll library. If this is the case, then the above `deadlock` reproducer should be representative of the issue. If not, then I'm missing something, and the stacktrace is not sufficient; we will need more information about the deployment (which classes are in which jar files, and in which order on the class path).

One thing that you could try, assuming that the epoll library is loaded from a single location, is to move code out of the JNI_OnLoad and into a separate `init` function, which can be called directly after the library is loaded. That way, the initialisation code will be run *after* releasing the lock (that is currently held when loading a native library). Assuming that the initialisation code has no requirement to hold such a lock (which would surprise me if it did), and other potentially racing callers will not observe the difference.

Alternatively, trace which classes are loaded by the JNI_OnLoad and ensure that they are contained in a jar file that is present on the class path *before* the epoll classes.

**Comment by njhill** [comment] 2021-04-29 21:33
Thanks @ChrisHegarty, I think your assumptions are correct. The JNI_OnLoad function is calling `FindClass` which I assume is what's triggering the java reentrance seen in the stacktrace. That class resides in a netty jar, different to the jar containing the class being loaded by the other thread, but I assume their relative classpath position matches your criteria. So it seems very likely that you've managed to reproduce the same deadlock (thanks!). But I noticed that in my case the locked objects are a `JarFile` and a `HashSet` rather than a `JarFile` and a `Runtime` in your case.

> this has always been quite fragile 
> One thing that you could try, assuming that the epoll library is loaded from a single location, is to move code out of the JNI_OnLoad and into a separate init function, which can be called directly after the library is loaded. 

Actually I saw that variants of this _were_ encountered  in the past with netty, where @normanmaurer implemented a workaround along the lines of your suggestion: https://github.com/netty/netty/pull/7480/files
Another workaround involved forcing load of the class in question prior to loading the JNI lib: https://github.com/netty/netty/pull/10190/files

What's interesting to me is how the 11.0.11 update seemed to have exposed this case of it. As you probably saw too it's very easy to hit, presumably because the lock is held for a nontrival period of time?

> Alternatively, trace which classes are loaded by the JNI_OnLoad and ensure that they are contained in a jar file that is present on the class path _before_ the epoll classes.

Unfortunately I don't think this is a solution for netty being a library. As mentioned I was able to easily work around myself by forcing the native classes/libraries to load up front prior to other threads starting.

Is it something that could be fixed in the JDK?

**Comment by njhill** [comment] 2021-04-29 21:40
I see there's now a JDK bug ticket for this: https://bugs.openjdk.java.net/browse/JDK-8266310

**Comment by ChrisHegarty** [comment] 2021-04-29 22:42
FYI - This kind of issue is not unique to Netty, e.g.  https://github.com/openjdk/jdk/commit/991f7c13

I suspect that the race (potential issue) is possible with prior versions of 11u. Maybe Netty is just getting lucky! 😉

**Comment by njhill** [comment] 2021-04-30 00:06
@ChrisHegarty does that mean that it's in general just not safe to reenter java from `JNI_OnLoad`? I'd be interested in whether your reproducer exhibits the deadlock with 11.0.10

**Comment by ChrisHegarty** [comment] 2021-04-30 05:59
My reproducer deadlocks fairly regularly with 11.0.10, as well as 11.0.11 (and other releases). In general, referring to not already loaded classes from JNI_OnLoad is problematic, and best avoided if possible.

**Comment by normanmaurer** [comment] 2021-04-30 06:03
@ChrisHegarty so just to double check ... what you are saying is that if we call FindClass for example in the OnLoad method we need also to ensure that we load this class first from java land ?

**Comment by normanmaurer** [comment] 2021-04-30 07:38
@ChrisHegarty if I understood you correctly we can "workaround" this issue by pre-loading all the classes. Please check https://github.com/netty/netty/pull/11215 which does exactly that. 

That said I think this needs to be addressed somehow on the JDK level in general. If it can't you should at least make it clear that you should never load any classes in `OnLoad` functions. I couldn't find any documentations about this.

**Comment by theRealAph** [comment] 2021-04-30 07:55
> That said I think this needs to be addressed somehow on the JDK level in general. If it can't you should at least make it clear that you should never load any classes in `OnLoad` functions. I couldn't find any documentations about this.

Perhaps the bug can be addressed in recent JDKs, but the kind of reorganization which would be required to class loading would not be free of risk. I doubt that it would be appropriate for 11u, which is a stable release. Sometimes we have to admit it's better to leave a known bug than to try fiing things.

**Comment by ChrisHegarty** [comment] 2021-04-30 07:57
> @ChrisHegarty so just to double check ... what you are saying is that if we call FindClass for example in the OnLoad method we need also to ensure that we load this class first from java land ?

Yes.  I accept that it is not ideal and that recent changes in the JDK seem to have tickled this deadlock into reproducing more regularly, but it is a pragmatic "workaround" to limitations of the existing loading mechanism. I believe that the Netty code is potentially susceptible to this in prior releases too, just that it reproduces more readily now. So ensuring that the classes referred to from FindClass (in JNI_OnLoad) are loaded before JNI_OnLoad is called is a good idea.

I am observing a few small anomalies between the stacktraces posted above in this issue and what I see in my own reproducer. If I find anything substantial or interesting, I'll post it here.

**Comment by normanmaurer** [comment] 2021-04-30 08:00
@ChrisHegarty yeah seems like it is at least "easier" to reproduce with more recent JDKs.  Thanks for "confirm" my workaround idea! 👍

**Comment by normanmaurer** [comment] 2021-04-30 08:08
> Perhaps the bug can be addressed in recent JDKs, but the kind of reorganization which would be required to class loading would not be free of risk. I doubt that it would be appropriate for 11u, which is a stable release. Sometimes we have to admit it's better to leave a known bug than to try fiing things.

@theRealAph true enough... I just think it should be "documented" somehow then that is easy to discover.

**Comment by ChrisHegarty** [comment] 2021-04-30 08:24
> .... So it seems very likely that you've managed to reproduce the same deadlock (thanks!). But I noticed that in my case the locked objects are a `JarFile` and a `HashSet` rather than a `JarFile` and a `Runtime` in your case.

@njhill The difference we are observing here (`HashSet` versus `Runtime`) does not materially affect how to proceed with this issue from a Netty perspective (Norman's workaround is the best solution we have for now). The difference is easily understood if you look at 8231584 [1], which has been backported to OpenJDK 11u, but not Oracle JDK 11u.

[1] https://bugs.openjdk.java.net/browse/JDK-8231584

**Comment by ChrisHegarty** [comment] 2021-04-30 08:40
FTR, my reproducer shows the issue with JDK 16. The following JDK issue has been filed to investigate further if there is something that can be done to improve this situation, see https://bugs.openjdk.java.net/browse/JDK-8266350. Or at the very least, if there is no clear technical solution to this issue, then it should be documented clearly somewhere and advise given about how to avoid it.

**Comment by njhill** [comment] 2021-04-30 21:01
Thanks @ChrisHegarty @normanmaurer

I guess just pre-loading classes used in the JNI_OnLoad method may not be enough in general though, since (possibly private) class loads could still be triggered indirectly via other java methods called from JNI_OnLoad, right?

**Comment by normanmaurer** [comment] 2021-05-01 05:36
@njhill we don't call any methods from ONLoad

**Comment by njhill** [comment] 2021-05-01 14:31
@normanmaurer sorry I didn't mean we do this currently, just that _in general_ it also needs to be considered in addition to explicitly reference classes. e.g. if JNI doc was going to be improved to warn about this and how to avoid it.

**Comment by normanmaurer** [comment] 2021-05-03 08:23
Workaround was pulled in... Thanks a lot all for your help :)

**Closed** 2021-05-04 07:12 UTC
