### ISSUE TITLE
QueryStringDecoder does not decode correctly path part with '+' (plus) sign in it

### ISSUE THREAD

**Issue by croudet** [netty/netty#6745] opened 2017-05-15 18:43 UTC
### Expected behavior
'+' is a valid char for path part of URI, it should not be replaced by space.

### Actual behavior

'+' is replaced with space.

### Minimal yet complete reproducer code (or URL to code)
```
public void testURIPathDecoding() throws URISyntaxException {
    String path = "/a/path/with/a+in.it";
    URI uri = new URI("http", "www.bbbb.com", path, null);
    System.out.println(path.equals(uri.getPath()));
    System.out.println(path.equals(uri.getRawPath()));
    QueryStringDecoder dec = new QueryStringDecoder(uri.getRawPath());
    System.out.println(dec.path());
    System.out.println(path.equals(dec.path()));
    System.out.println(path.equals(dec.uri()));
  }

true
true
/a/path/with/a in.it
false
true
```
### Netty version
 4.1.11
### OS version (e.g. `uname -a`)
Any

**Comment by fenik17** [comment] 2017-05-15 19:10
See https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1
> **application/x-www-form-urlencoded**  
> This is the default content type. 
> ... Space characters are replaced by `+`...

And [Javadoc for QueryStringDecoder](https://github.com/netty/netty/blob/d675febf07d14d4dff82471829f974369705655a/codec-http/src/main/java/io/netty/handler/codec/http/QueryStringDecoder.java#L44) says that:

> This decoder can also decode the content of an HTTP POST request whose content type is **application/x-www-form-urlencoded**

**Comment by croudet** [comment] 2017-05-15 19:21
I am talking about the path part of an URL.
See grammar in  https://www.w3.org/Addressing/URL/url-spec.txt

```
httpaddress             h t t p :   / / hostport [  / path ] [ ? search ]   
path                    void |  segment  [  / path ] 
segment                 xpalphas
xpalpha                 xalpha | +   
xpalphas                xpalpha [ xpalphas ]   
```

**Comment by fenik17** [comment] 2017-05-15 19:39
@croudet yes, you are right. It's a bug..

**Comment by fenik17** [comment] 2017-05-19 19:47
A `QueryStringDecoder` also  doesn't cut a `fragment` from query string (as prescribed by [RFC 3986](http://www.faqs.org/rfcs/rfc3986.html))
```java
System.out.println(new QueryStringDecoder(new URI("p?a=b#anchor")).parameters().get("a").get(0));
System.out.println(new QueryStringDecoder("p?a=b#anchor").parameters().get("a").get(0));
```
in output
```
b
b#anchor
```
@normanmaurer @Scottmitch @trustin WDYT? I can provide a PR to fixing both issues.

**Comment by Scottmitch** [comment] 2017-05-19 22:10
@fenik17 +1 for a PR ... thanks!

**Comment by normanmaurer** [comment] 2017-05-20 06:59
@fenik yes please 👍

**Comment by fenik17** [comment] 2017-05-22 20:32
Found one more problem: a charset does not work as intended...
Code
```java
System.out.println(new URI("случайный%20праздник").getPath());
System.out.println(QueryStringDecoder.decodeComponent("случайный%20праздник"));
System.out.println(QueryStringDecoder.decodeComponent("случайный праздник"));
```
return
```
случайный праздник
A;CG09=K9 ?@074=8:
случайный праздник
```
I'll try to fix this too.

**Comment by normanmaurer** [comment] 2017-05-23 18:01
Cool thx

**Comment by fenik17** [comment] 2017-05-25 23:45
Check please #6781.

**Comment by fenik17** [comment] 2017-05-28 12:37
There is one more question.. Why QueryStringDecoder treat double percent `%%` as escaping of the percent character? I could not find it in the RFC.. An URLDecoder from JDK throw an exception on a string containing `%%`.
Commit 1f1b8d83259398f236bc4bb99676243192f6dedd.
@tsuna can you clarify this, please?

**Comment by tsuna** [comment] 2017-05-28 18:04
I don't remember why I added this.  Seems like it was intentional since there is a test case that specifically verifies this behavior, but it does look weird to me too now.

**Comment by fenik17** [comment] 2017-05-28 21:37
@tsuna thanks. I think we need to fix this too, for a more accurate match of [javadoc](http://netty.io/4.1/api/io/netty/handler/codec/http/QueryStringDecoder.html#decodeComponent-java.lang.String-java.nio.charset.Charset-):

> This is essentially equivalent to calling URLDecoder.decode(s, charset.name()) 

I'm updated a PR.

**Comment by fenik17** [comment] 2017-05-28 21:55
related https://issues.apache.org/jira/browse/HDFS-7816 ...

**Comment by fenik17** [comment] 2017-06-11 12:32
@normanmaurer close this?

**Comment by Scottmitch** [comment] 2017-06-13 01:12
fixed by https://github.com/netty/netty/pull/6781

**Closed by Scottmitch** 2017-06-13 01:12 UTC
