### ISSUE TITLE
A http post protobuf netty request problem

### ISSUE THREAD

**Issue by gileth** [netty/netty#9859] opened 2019-12-08 01:31 UTC
I have a netty server already, and now I want to send a protobuf request to this server, the request data type is byte[], the front 4 byte is the real data length, but there is a problem when the server decode the request. Can anyone help me? This is the related server code: 
ChannelInitializer code

`channelPipLine.addLast(new LengthFieldBasedFrameDecoder(Integer.MAX_VALUE, 0, 4, 0, 4));
channelPipLine.addLast(new LengthFieldPrepender(4));
channelPipLine.addLast(new TestProtobufDecoder());
channelPipLine.addLast(new TestProtobufEncoder());`

httppost client:

`byte[] dataLength = intToByteArray(4,  body.toByteArray().length);  
byte[] requestMessage = combineByteArray(dataLength, body.toByteArray());  
HttpUtils.postProtobuf("http://192.168.1.2:10002", requestMessage, "application/x-protobuf");

private static byte[] intToByteArray(int byteLength, int intValue) {  
	return ByteBuffer.allocate(byteLength).putInt(intValue).array();  
}  

private static byte[] combineByteArray(byte[] array1, byte[] array2) {  
	byte[] combined = new byte[array1.length + array2.length];  
	System.arraycopy(array1, 0, combined, 0, array1.length);  
	System.arraycopy(array2, 0, combined, array1.length, array2.length);  
	return combined;  
}`

**Comment by normanmaurer** [comment] 2019-12-10 10:37
You will at least tell use what exactly the problem is that you see.

**Comment by gileth** [comment] 2019-12-26 01:36
The data received by the server is HTTP header information and content together. Do I have to parse the content into header information and content by myself? Why isn't netty automatic?

**Comment by hyperxpro** [comment] 2020-01-27 09:19
> The data received by the server is HTTP header information and content together. Do I have to parse the content into header information and content by myself? Why isn't netty automatic?

Without having a look at code, it's hard to tell anything.

**Comment by normanmaurer** [comment] 2020-03-13 10:06
Sorry but without more details we can't help... Closing

**Closed by normanmaurer** 2020-03-13 10:06 UTC
