### ISSUE TITLE
Netty DNS Answer Section not correctly decoded

### ISSUE THREAD

**Issue by MLeipziger** [netty/netty#5760] opened 2016-08-29 07:53 UTC
I am working on a DNS-Client with netty. To test it, I wrote a simple DNS-Server with netty, that returns DnsRecords which I am expecting.

Here is my client code:

```java
final NioEventLoopGroup nioEventLoopGroup = new NioEventLoopGroup();
final EventLoop next = nioEventLoopGroup.next();
final DnsNameResolverBuilder dnsNameResolverBuilder = new 
DnsNameResolverBuilder(next).channelFactory(new ChannelFactory<DatagramChannel>() {
        @Override
        public DatagramChannel newChannel() {
            return new NioDatagramChannel();
        }
    }).queryTimeoutMillis(100000).nameServerAddresses(new 
        DnsServerAddresses() {
        @Override
        public DnsServerAddressStream stream() {
            return new DnsServerAddressStream() {
                @Override
                public InetSocketAddress next() {
                    return new InetSocketAddress("127.0.0.1", 
                    TEST_DNS_SD_SERVER_PORT);
                }
            };
        }
    });
    final DnsNameResolver build = dnsNameResolverBuilder.build();
    final DefaultDnsQuestion defaultDnsQuestion = new 
    DefaultDnsQuestion(TEST_BASE_RECORD_NAME, DnsRecordType.PTR);
    build.query(defaultDnsQuestion).addListener(new GenericFutureListener<Future<? super AddressedEnvelope<DnsResponse, InetSocketAddress>>>() {
        @Override
        public void operationComplete(final Future<? super AddressedEnvelope<DnsResponse, InetSocketAddress>> future) throws Exception {
            final AddressedEnvelope<DnsResponse, InetSocketAddress> answer = (AddressedEnvelope<DnsResponse, InetSocketAddress>) future.get();
            final DnsResponse content = answer.content();
            final int count = content.count(DnsSection.ANSWER);
            for (int i = 0; i < count; i++) {
                final DnsRecord recordAt = content.recordAt(DnsSection.ANSWER, i);
                System.out.println(recordAt);
            }
        }
    }).await();
    Thread.sleep(Long.MAX_VALUE);
```

```TEST_BASE_RECORD_NAME``` is a record containing 3 DnsPtrRecords in the answer section.

Behind the ```TEST_DNS_SD_SERVER_PORT``` I am running a DNS-Server in a seperate thread, that handles requests in the following way: (Part of LocalDNSSDHandler:)
```java
public void channelRead(final ChannelHandlerContext ctx, final Object msg) { 
        final DatagramDnsQuery query = (DatagramDnsQuery) msg;
        DatagramDnsResponse defaultDnsResponse = null;
        try {
            final DnsRecord recordAt = query.recordAt(DnsSection.QUESTION);
            final Name name = Name.fromString(recordAt.name(), Name.root);
            final DnsEntryKey dnsEntryKey = 
            new DnsEntryKey(name, recordAt.type().intValue());
            final List<Record> list = 
            LocalTestServer.this.getDnsEntries().get(dnsEntryKey);
            defaultDnsResponse = 
            new DatagramDnsResponse(query.recipient(),
            query.sender(), query.id());
            defaultDnsResponse.addRecord(DnsSection.QUESTION, recordAt);
            for (final Record record : list) {
                final ByteBuf buffer = ctx.alloc().buffer();
                buffer.writeBytes(record.toWireCanonical());
                defaultDnsResponse.addRecord(DnsSection.ANSWER, new 
                DefaultDnsRawRecord(record.getName().toString(), 
                this.fromRecord(record), Long.MAX_VALUE, buffer));
            }
        } catch (final Exception e) {
        }
        ctx.writeAndFlush(defaultDnsResponse);
    }
```

The Server definies following ChannelHandler:
```java
public void initChannel(final DatagramChannel ch) throws Exception {
                ch.pipeline().addLast(new DatagramDnsResponseEncoder());
                ch.pipeline().addLast(new DatagramDnsQueryDecoder());
                ch.pipeline().addLast(new LocalDNSSDHandler());
            }
```

What I am expecting in the client is to see 3 System.out.println for the 3 DnsPtrRecords I am expecting. But what I get is only 1.

When I debug it, I can see, that encoding/decoding on Server-side works fine. But when the Client decodes the correspondending ByteBuf (which contains the Data I am expecting), it simply returns only 1 Record and skips the other 2 at this point in code:

(DatagramDnsResponseDecoder)
```java
@Override
protected void decode(ChannelHandlerContext ctx, DatagramPacket packet, 
List<Object> out) throws Exception {
    final ByteBuf buf = packet.content();
    final DnsResponse response = newResponse(packet, buf);
    boolean success = false;
    try {
        final int questionCount = buf.readUnsignedShort();
        final int answerCount = buf.readUnsignedShort();
        final int authorityRecordCount = buf.readUnsignedShort();
        final int additionalRecordCount = buf.readUnsignedShort();
        decodeQuestions(response, buf, questionCount);
        decodeRecords(response, DnsSection.ANSWER, buf, answerCount);
        decodeRecords(response, DnsSection.AUTHORITY, buf,
        authorityRecordCount);
        decodeRecords(response, DnsSection.ADDITIONAL, buf, 
        additionalRecordCount);
        ...//source code of netty 4.1, trimmed
```

The ```answerCount``` is 3 as I am expecting. But when

 ```decodeRecords(response, DnsSection.ANSWER, buf, answerCount);```

is called, it will call

(DefaultDnsRecordDecoder)
```java
protected DnsRecord decodeRecord(
        String name, DnsRecordType type, int dnsClass, long timeToLive,
        ByteBuf in, int offset, int length) throws Exception {
    if (type == DnsRecordType.PTR) {
        in.setIndex(offset, offset + length);
        return 
        new DefaultDnsPtrRecord(name, dnsClass, timeToLive, decodeName0(in));
    }
    return new DefaultDnsRawRecord(
            name, type, dnsClass, timeToLive, 
            in.retainedDuplicate().setIndex(offset, offset + length));
}
```

I don't understand the

```in.setIndex(offset, offset + length);```

since this sets the read AND write Index of the ByteBuf (in), and this will skip the other DnsRecords in the Answer section and makes it returing only one DnsRecord.

I am using Netty 4.1.4.Final

**Comment by normanmaurer** [comment] 2016-08-29 08:00
@MLeipziger currently we only support DNS for client side... To make it work for the server-side I think you would need to modify it. Si this is expected.

**Comment by MLeipziger** [comment] 2016-08-29 08:10
The "Bug" (it may be my fault as well) occurs on the client side, when it comes to decode the dns-Answer section, as described above.

The Server is sending things, as I am expecting.

Where the problem is in my understanding is on the client side:

```java
@Override
protected void decode(ChannelHandlerContext ctx, DatagramPacket packet, 
List<Object> out) throws Exception {
    final ByteBuf buf = packet.content();
    final DnsResponse response = newResponse(packet, buf);
    boolean success = false;
    try {
        final int questionCount = buf.readUnsignedShort();
        final int answerCount = buf.readUnsignedShort();
        final int authorityRecordCount = buf.readUnsignedShort();
        final int additionalRecordCount = buf.readUnsignedShort();
        decodeQuestions(response, buf, questionCount);
        decodeRecords(response, DnsSection.ANSWER, buf, answerCount);
        decodeRecords(response, DnsSection.AUTHORITY, buf,
        authorityRecordCount);
        decodeRecords(response, DnsSection.ADDITIONAL, buf, 
        additionalRecordCount);
        ...//source code of netty 4.1, trimmed
```

This is running on the client.

**Comment by normanmaurer** [comment] 2016-08-29 08:14
@MLeipziger it not set the index in `in` but on the duplicate of `in`. So the writerIndex and readerIndex of `in` are not affected. Can you provide a testcase a.k.a unit test that fails ?

**Comment by MLeipziger** [comment] 2016-08-29 09:36
Hard to write a Unittest for that. Here is a little integration Test for it:

Here a simple DNS Test Server 
```java

import java.util.List;
import java.util.Map;

import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.DatagramChannel;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.codec.dns.DatagramDnsQuery;
import io.netty.handler.codec.dns.DatagramDnsQueryDecoder;
import io.netty.handler.codec.dns.DatagramDnsResponse;
import io.netty.handler.codec.dns.DatagramDnsResponseEncoder;
import io.netty.handler.codec.dns.DefaultDnsRawRecord;
import io.netty.handler.codec.dns.DnsRecord;
import io.netty.handler.codec.dns.DnsRecordType;
import io.netty.handler.codec.dns.DnsSection;

public class LocalDNSTestServer implements Runnable {

    private final Map<String, List<DNSTestClient.Record>> dnsEntries;
    private volatile boolean isStarted = false;
    private final int port;
    private ChannelFuture f;

    public LocalDNSTestServer(final int port, final Map<String, List<DNSTestClient.Record>> map) {

        this.dnsEntries = map;
        this.port = port;
    }

    public void startServer() throws InterruptedException {
        final EventLoopGroup bossGroup = new NioEventLoopGroup();
        try {
            final Bootstrap b = new Bootstrap();
            b.group(bossGroup).channel(NioDatagramChannel.class).handler(new ChannelInitializer<DatagramChannel>() {
                @Override
                public void initChannel(final DatagramChannel ch) throws Exception {
                    ch.pipeline().addLast(new DatagramDnsResponseEncoder());
                    ch.pipeline().addLast(new DatagramDnsQueryDecoder());
                    ch.pipeline().addLast(new LocalDNSSDHandler());
                }
            });
            this.f = b.bind(this.port).sync();
            this.isStarted = true;
            this.f.channel().closeFuture().sync();
        } finally {
            bossGroup.shutdownGracefully();
        }
    }

    public void stopServer() {
        this.f.channel().close();
    }

    public class LocalDNSSDHandler extends ChannelInboundHandlerAdapter {
        @Override
        public void channelRead(final ChannelHandlerContext ctx, final Object msg) {
            final DatagramDnsQuery query = (DatagramDnsQuery) msg;
            DatagramDnsResponse defaultDnsResponse = null;
            try {
                final DnsRecord recordAt = query.recordAt(DnsSection.QUESTION);
                final List<DNSTestClient.Record> list = LocalDNSTestServer.this.getDnsEntries().get(recordAt.name());
                defaultDnsResponse = new DatagramDnsResponse(query.recipient(), query.sender(), query.id());
                defaultDnsResponse.addRecord(DnsSection.QUESTION, recordAt);
                for (final DNSTestClient.Record record : list) {
                    final ByteBuf buffer = ctx.alloc().buffer();
                    defaultDnsResponse.addRecord(DnsSection.ANSWER, new DefaultDnsRawRecord(record.getName().toString(), DnsRecordType.PTR, Long.MAX_VALUE, buffer));
                }
            } catch (final Exception e) {
            }
            ctx.writeAndFlush(defaultDnsResponse);
        }

        @Override
        public void exceptionCaught(final ChannelHandlerContext ctx, final Throwable cause) {
            cause.printStackTrace();
            ctx.close();
        }
    }

    @Override
    public void run() {
        try {
            this.startServer();
        } catch (final InterruptedException e) {
            e.printStackTrace();
        }
    }

    public boolean isStarted() {
        return this.isStarted;
    }

    public Map<String, List<DNSTestClient.Record>> getDnsEntries() {
        return this.dnsEntries;
    }

}
```

And here a simple DNS Client:

```java

import static org.junit.Assert.assertTrue;

import java.net.InetSocketAddress;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.BeforeClass;
import org.junit.Test;

import io.netty.channel.AddressedEnvelope;
import io.netty.channel.ChannelFactory;
import io.netty.channel.EventLoop;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.DatagramChannel;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.codec.dns.DefaultDnsQuestion;
import io.netty.handler.codec.dns.DnsRecord;
import io.netty.handler.codec.dns.DnsRecordType;
import io.netty.handler.codec.dns.DnsResponse;
import io.netty.handler.codec.dns.DnsSection;
import io.netty.resolver.dns.DnsNameResolver;
import io.netty.resolver.dns.DnsNameResolverBuilder;
import io.netty.resolver.dns.DnsServerAddressStream;
import io.netty.resolver.dns.DnsServerAddresses;
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.GenericFutureListener;

public class DNSTestClient {
    private static Thread localDnsTestServerThread;
    private static LocalDNSTestServer localDnsTestServer;
    private static Map<String, List<Record>> expectedMap;
    public static final int LOCAL_DNS_SERVER_PORT = 9595;
    public static final String TEST_BASE_RECORD_NAME = "_fd-srv._tcp.vsdm.telematik-test.";

    public static Map<String, List<Record>> getTestEntries() {
        final Map<String, List<Record>> map = new HashMap<>();
        map.put(TEST_BASE_RECORD_NAME, Arrays.asList(() -> "_Record0._tcp.vsdm.telematik-test.", () -> "_Record1._tcp.vsdm.telematik-test.", () -> "_Record2._tcp.vsdm.telematik-test."));
        return map;
    }

    public static interface Record {
        String getName();
    }

    @BeforeClass
    public static void initTest() throws Exception {
        localDnsTestServer = new LocalDNSTestServer(LOCAL_DNS_SERVER_PORT, expectedMap = getTestEntries());
        localDnsTestServerThread = new Thread(localDnsTestServer);
        localDnsTestServerThread.start();
        int waitCount = 0;
        final int sleepTimeInSeconds = 5;
        final int maxWaits = 42;
        while (!localDnsTestServer.isStarted()) {
            try {
                Thread.sleep(TimeUnit.SECONDS.toMillis(sleepTimeInSeconds));
                if (++waitCount > maxWaits) {
                    throw new InstantiationException("Could not setup LocalDnsTestServer in Time!");
                }
            } catch (final InterruptedException e) {
            }
        }
    }

    @Test
    public void testNewApi() throws Exception {
        final NioEventLoopGroup nioEventLoopGroup = new NioEventLoopGroup();
        final EventLoop next = nioEventLoopGroup.next();
        final DnsNameResolverBuilder dnsNameResolverBuilder = new DnsNameResolverBuilder(next).channelFactory(new ChannelFactory<DatagramChannel>() {
            @Override
            public DatagramChannel newChannel() {
                return new NioDatagramChannel();
            }
        }).nameServerAddresses(new DnsServerAddresses() {
            @Override
            public DnsServerAddressStream stream() {
                return new DnsServerAddressStream() {
                    @Override
                    public InetSocketAddress next() {
                        return new InetSocketAddress("127.0.0.1", LOCAL_DNS_SERVER_PORT);
                    }
                };
            }
        });
        final DnsNameResolver build = dnsNameResolverBuilder.build();
        final DefaultDnsQuestion defaultDnsQuestion = new DefaultDnsQuestion(TEST_BASE_RECORD_NAME, DnsRecordType.PTR);
        build.query(defaultDnsQuestion).addListener(new GenericFutureListener<Future<? super AddressedEnvelope<DnsResponse, InetSocketAddress>>>() {
            @Override
            public void operationComplete(final Future<? super AddressedEnvelope<DnsResponse, InetSocketAddress>> future) throws Exception {
                final AddressedEnvelope<DnsResponse, InetSocketAddress> answer = (AddressedEnvelope<DnsResponse, InetSocketAddress>) future.get();
                final DnsResponse content = answer.content();
                final int count = content.count(DnsSection.ANSWER);
                assertTrue("ANSWER Section has wrong size.", count == expectedMap.get(TEST_BASE_RECORD_NAME).size());
                for (int i = 0; i < count; i++) {
                    final DnsRecord recordAt = content.recordAt(DnsSection.ANSWER, i);
                    System.out.println(recordAt);
                }

            }
        }).await();
        // needed to wait for operationComplete to run.
        Thread.sleep(Long.MAX_VALUE);
    }
}

```

**Comment by normanmaurer** [comment] 2016-08-31 12:57
@MLeipziger ok looking.

**Comment by normanmaurer** [comment] 2016-08-31 20:06
Should be fixed by https://github.com/netty/netty/pull/5784

**Comment by normanmaurer** [comment] 2016-09-01 06:27
Fixed by https://github.com/netty/netty/pull/5784

**Closed by normanmaurer** 2016-09-01 06:27 UTC
Labels: defect
