### ISSUE TITLE
Endless recursion in DefaultPromise

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3450] opened 2015-02-27 02:40 UTC
If the following conditions hold the `DefaultPromise` goes into endless recursion.

1 . The `DefaultPromise` is used with an `ImmediateEventExecutor`
2 . The `DefaultPromise` is completed.
3 . Within a listener another listener is added (aka LateListeners in DefaultPromise)

The line responsible for the endless recursion is ultimately https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L850

I am using this in a test. I can think of a simple, quick and dirty fix that simply wraps the line in question in say a `GlobalEventExecutor`, but that seems rather ugly to me.

The stacktrace looks as follows

```
	....
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850) ~[classes/:na]
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:83) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850) ~[classes/:na]
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:83) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850) ~[classes/:na]
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:83) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:850) ~[classes/:na]
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:83) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) ~[classes/:na]
	at io.netty.util.concurrent.DefaultPromise.access$400(DefaultPromise.java:32) ~[classes/:na]
```

**Comment by Scottmitch** [comment] 2015-02-27 03:01
Similar problem in https://github.com/netty/netty/pull/3392. Need to investigate but I was going to look into it. One suggedtion was for AbstractChannel.newPromise() to delegate to EventExecutor.

**Comment by buchgr** [comment] 2015-02-27 03:39
I don't have a `Channel` and `EventExecutor` in my tests :-). Currently working around it with different Executor.

**Comment by trustin** [comment] 2015-03-12 02:57
It's because you used `ImmediateExecutor`? :-)

DefaultPromise keeps the depth of the current call stack in a thread local variable, and if it exceeds a certain threshold, it will spawn a new `Runnable` so that the invocation continues at lower stack depth.  However, `ImmediateExecutor` is not a real executor, so the stack will overflow eventually. Where do you have to use `ImmediateExecutor`?

**Comment by buchgr** [comment] 2015-03-13 04:12
@trustin I wanted to use it in a test, as I wanted listeners attached to the promise to execute immediately. I am not sure if this is worth fixing, however I would say ideally the `DefaultPromise` should work with any kind of `EventExecutor`.

**Comment by Scottmitch** [comment] 2015-11-03 18:21
@buchgr - Thanks for pointing out that https://github.com/netty/netty/issues/4395 looks like a duplicate of this issue. Is it possible for you to verify the fix for https://github.com/netty/netty/issues/4395 also takes care of this issue? If it does not, please re-open this issue.

**Closed by Scottmitch** 2015-11-03 18:21 UTC
Labels: defect
