### ISSUE TITLE
netty-all 4.1.64 has a broken dependency graph

### ISSUE THREAD

**Issue by fredericBregier** [netty/netty#11272] opened 2021-05-18 07:38 UTC
### Expected behavior
When maven compile (or install) runs on a maven project using both dependencies below, it should not generate errors with dependencies cannot be resolved.

### Actual behavior
It generates errors such as:

`ERROR] Failed to execute goal on project testNetty64: Could not resolve dependencies for project 
org.example:testNetty64:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: io.netty:netty-
tcnative:jar:${os.detected.classifier}:2.0.39.Final, io.netty:netty-transport-native-
epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.64.Final: Could not find artifact io.netty:netty-
tcnative:jar:${os.detected.classifier}:2.0.39.Final in MavenCentral (https://repo.maven.apache.org/maven2) -> [Help 1]
`

### Steps to reproduce
Simple pom.xml as below:

      <?xml version="1.0" encoding="UTF-8"?>
      <project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>

        <groupId>org.example</groupId>
        <artifactId>testNetty64</artifactId>
        <version>1.0-SNAPSHOT</version>
      
        <properties>
          <maven.compiler.source>8</maven.compiler.source>
          <maven.compiler.target>8</maven.compiler.target>
        </properties>
      
        <dependencies>
          <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.64.Final</version>
          </dependency>
          <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <version>2.0.39.Final</version>
          </dependency>
        </dependencies>
      </project>

maven clean compile

### Netty version

Replacing 4.1.64-Final by 4.1.63-Final runs fine.

With 4.1.64-Final: `mvn clean compile -U`

      [INFO] ----------------------< org.example:testNetty64 >-----------------------
      [INFO] Building testNetty64 1.0-SNAPSHOT
      [INFO] --------------------------------[ jar ]---------------------------------
      Downloading from MavenCentral: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-$%7Bos.detected.name%7D-$%7Bos.detected.arch%7D.jar
      Downloading from MavenCentral: https://repo.maven.apache.org/maven2/io/netty/netty-tcnative/2.0.39.Final/netty-tcnative-2.0.39.Final-$%7Bos.detected.classifier%7D.jar
      Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-tcnative/2.0.39.Final/netty-tcnative-2.0.39.Final-$%7Bos.detected.classifier%7D.jar
      Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-$%7Bos.detected.name%7D-$%7Bos.detected.arch%7D.jar
      [INFO] ------------------------------------------------------------------------
      [INFO] BUILD FAILURE
      [INFO] ------------------------------------------------------------------------
      [INFO] Total time:  1.478 s
      [INFO] Finished at: 2021-05-18T09:35:23+02:00
      [INFO] ------------------------------------------------------------------------
      [ERROR] Failed to execute goal on project testNetty64: Could not resolve dependencies for project org.example:testNetty64:jar:1.0-SNAPSHOT: 
      [The following artifacts could not be resolved: io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.39.Final, io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.64.Final: 
      [Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.39.Final in MavenCentral (https://repo.maven.apache.org/maven2) -> [Help 1]

In DEBUG mode, I've got the following possibly useful elements: `mvn clean compile -e -X -U`

      Apache Maven 3.6.3
      Maven home: /usr/share/maven
      Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
      Default locale: fr_FR, platform encoding: UTF-8
      OS name: "linux", version: "5.4.0-73-generic", arch: "amd64", family: "unix"
      ...
      [DEBUG] =======================================================================
      [DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=974120, ConflictMarker.markTime=382215, 
      ConflictMarker.nodeCount=158, ConflictIdSorter.graphTime=782831, ConflictIdSorter.topsortTime=386305, 
      ConflictIdSorter.conflictIdCount=44, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=7735894, 
      ConflictResolver.conflictItemCount=157, DefaultDependencyCollector.collectTime=208052123, 
      DefaultDependencyCollector.transformTime=11590815}
      [DEBUG] org.example:testNetty64:jar:1.0-SNAPSHOT
      [DEBUG]    io.netty:netty-all:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-buffer:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-dns:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-haproxy:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-http:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-http2:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-memcache:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-mqtt:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-redis:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-smtp:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-socks:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-stomp:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-codec-xml:jar:4.1.64.Final:compile
      [DEBUG]          com.fasterxml:aalto-xml:jar:1.0.0:compile
      [DEBUG]             org.codehaus.woodstox:stax2-api:jar:4.0.0:compile
      [DEBUG]       io.netty:netty-common:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-handler:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-handler-proxy:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-resolver:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-resolver-dns:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-transport:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-transport-rxtx:jar:4.1.64.Final:compile
      [DEBUG]          org.rxtx:rxtx:jar:2.1.7:compile
      [DEBUG]       io.netty:netty-transport-sctp:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-transport-udt:jar:4.1.64.Final:compile
      [DEBUG]          com.barchart.udt:barchart-udt-bundle:jar:2.3.0:compile
      [DEBUG]       io.netty:netty-example:jar:4.1.64.Final:compile
      [DEBUG]          com.google.protobuf:protobuf-java:jar:2.6.1:compile
      [DEBUG]          io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.39.Final:compile
      [DEBUG]          org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
      [DEBUG]          com.jcraft:jzlib:jar:1.1.3:runtime
      [DEBUG]          com.yammer.metrics:metrics-core:jar:2.2.0:compile
      [DEBUG]             org.slf4j:slf4j-api:jar:1.7.2:compile
      [DEBUG]          ch.qos.logback:logback-classic:jar:1.1.7:runtime
      [DEBUG]             ch.qos.logback:logback-core:jar:1.1.7:runtime
      [DEBUG]          org.bouncycastle:bcpkix-jdk15on:jar:1.68:compile
      [DEBUG]          org.bouncycastle:bcprov-jdk15on:jar:1.68:compile
      [DEBUG]          com.sun.activation:javax.activation:jar:1.2.0:compile
      [DEBUG]       io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.64.Final:compile
      [DEBUG]          io.netty:netty-transport-native-unix-common:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-transport-native-kqueue:jar:4.1.64.Final:compile
      [DEBUG]       io.netty:netty-resolver-dns-native-macos:jar:4.1.64.Final:compile
      [DEBUG]    io.netty:netty-tcnative:jar:2.0.39.Final:compile
      [DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
      [DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
      [[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
      [[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
      [Downloading from MavenCentral: https://repo.maven.apache.org/maven2/io/netty/netty-tcnative/2.0.39.Final/netty-tcnative-2.0.39.Final-$%7Bos.detected.classifier%7D.jar
      [Downloading from MavenCentral: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-$%7Bos.detected.name%7D-$%7Bos.detected.arch%7D.jar
      [[DEBUG] Writing tracking file /home/frederic/.m2/repository/io/netty/netty-tcnative/2.0.39.Final/netty-tcnative-2.0.39.Final-${os.detected.classifier}.jar.lastUpdated
      [[DEBUG] Writing tracking file /home/frederic/.m2/repository/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-${os.detected.name}-${os.detected.arch}.jar.lastUpdated
      [[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
      [[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
      [Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-tcnative/2.0.39.Final/netty-tcnative-2.0.39.Final-$%7Bos.detected.classifier%7D.jar
      [Downloading from central: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-$%7Bos.detected.name%7D-$%7Bos.detected.arch%7D.jar
      [[DEBUG] Writing tracking file /home/frederic/.m2/repository/io/netty/netty-tcnative/2.0.39.Final/netty-tcnative-2.0.39.Final-${os.detected.classifier}.jar.lastUpdated
      [[DEBUG] Writing tracking file /home/frederic/.m2/repository/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-${os.detected.name}-${os.detected.arch}.jar.lastUpdated
      [[INFO] ------------------------------------------------------------------------
      [[INFO] BUILD FAILURE
      [[INFO] ------------------------------------------------------------------------
      [[INFO] Total time:  6.177 s
      [[INFO] Finished at: 2021-05-18T09:31:45+02:00
      [[INFO] ------------------------------------------------------------------------
      [[ERROR] Failed to execute goal on project testNetty64: Could not resolve dependencies for project org.example:testNetty64:jar:1.0-SNAPSHOT
      [: The following artifacts could not be resolved: io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.39.Final, io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.64.Final: 
      [Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.39.Final in MavenCentral (https://repo.maven.apache.org/maven2) -> [Help 1]

### JVM version (e.g. `java -version`)

Tried using Java 8 and Java 11

      java version "1.8.0_221"
      Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
      Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

      openjdk version "11.0.11" 2021-04-20
      OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
      OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### OS version (e.g. `uname -a`)

      Linux frederic-X510UQ 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment] 2021-05-18 08:29
@fredericBregier one thing... can you verify what the outcome is when your add `netty-handler` in both cases ? Do both fail ?

**Comment by fredericBregier** [comment] 2021-05-18 08:35
@normanmaurer When I removed `netty-all` and replaced it by `netty-handler` (same version 4.1.64-Final), it goes well.

**Comment by fredericBregier** [comment] 2021-05-18 08:36
@normanmaurer Both Java 8 and Java 11

**Comment by fredericBregier** [comment] 2021-05-18 08:36
@normanmaurer Sorry for the "spam", if I let `netty-all` in addition to `netty-handler`, it still has the error of course.

**Comment by normanmaurer** [comment] 2021-05-18 08:40
Ah wait ... I may have an idea... can you try what happens when you do:

```
  <dependencies>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-all</artifactId>
        <version>4.1.64.Final</version>
        <exclusions>
          <exclusion> 
            <groupId>io.netty</groupId>
            <artifactId>netty-example</artifactId>
          </exclusion>
        </exclusions> 
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-tcnative</artifactId>
        <version>2.0.39.Final</version>
      </dependency>
    </dependencies>
```

**Comment by normanmaurer** [comment] 2021-05-18 08:48
@fredericBregier if this helps I am sure the issue will go-away with https://github.com/netty/netty/pull/11273

**Comment by fredericBregier** [comment] 2021-05-18 08:53
@normanmaurer Still not enough:

      [ERROR] Failed to execute goal on project testNetty64: Could not resolve dependencies for project 
      org.example:testNetty64:jar:1.0-SNAPSHOT: Could not find artifact io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.64.Final 
      in MavenCentral (https://repo.maven.apache.org/maven2) -> [Help 1]

But less dependencies concerned (`io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.39.Final` not listed)

**Comment by fredericBregier** [comment] 2021-05-18 09:00
@normanmaurer When I compare (through IntelliJ) the Dependency Analyzer, it seems (is it correct ?) that:
- version 4.1.63-Final of `netty-all` has no specified dependency (alone), and same for `netty-tcnative`
- version 4.1.64-Final of `netty-all` has plenty of dependencies but error seems to be on `netty-tcnative` (not shown)

**Comment by fredericBregier** [comment] 2021-05-18 09:10
@normanmaurer 

I run `mvn dependency:tree -Dverbose` against 4.1.63-Final

      [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ testNetty64 ---
      [INFO] org.example:testNetty64:jar:1.0-SNAPSHOT
      [INFO] +- io.netty:netty-all:jar:4.1.63.Final:compile
      [INFO] \- io.netty:netty-tcnative:jar:2.0.39.Final:compile

It failed using 4.1.64-Final. I tried to remove `netty-tcnative`, in fact, the error is still there (while still exluding `netty-example`)

      [INFO] Scanning for projects...
      [INFO] 
      [INFO] ----------------------< org.example:testNetty64 >-----------------------
      [INFO] Building testNetty64 1.0-SNAPSHOT
      [INFO] --------------------------------[ jar ]---------------------------------
      Downloading from MavenCentral: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.64.Final/netty-transport-native-epoll-4.1.64.Final-$%7Bos.detected.name%7D-$%7Bos.detected.arch%7D.jar
      [INFO] ------------------------------------------------------------------------
      [INFO] BUILD FAILURE
      [INFO] ------------------------------------------------------------------------
      [INFO] Total time:  1.033 s
      [INFO] Finished at: 2021-05-18T11:08:53+02:00
      [INFO] ------------------------------------------------------------------------
      [ERROR] Failed to execute goal on project testNetty64:
       Could not resolve dependencies for project org.example:testNetty64:jar:1.0-SNAPSHOT: 
      Could not find artifact io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.64.Final
       in MavenCentral (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by normanmaurer** [comment] 2021-05-18 09:37
@fredericBregier let me investigate... here are multiple problems into play.

**Comment by fredericBregier** [comment] 2021-05-18 09:48
@normanmaurer Just for information, I tried to exclude all "test" part, but no success yet:


    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>4.1.64.Final</version>
      <exclusions>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-example</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-shading</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-osgi</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-autobahn</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-http2</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-native</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-native-image</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-native-image-client</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-testsuite-native-image-client-runtime-init</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport-native-unix-common-tests</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-microbench</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

**Comment by candrews** [comment] 2021-05-18 13:57
The variables within `jni.classifier` aren't being resolved. The value used for it is literally `${os.detected.name}-${os.detected.arch}`.

I think the problem is that `os-maven-plugin` isn't running in this situation so those variables (`os.detected.name` and `os.detected.arch`) aren't set.

I wonder if using `os-maven-plugin` as a plugin in the parent pom, instead of as an extension, will allow the plugin to be correctly inherited by `netty-all` resulting in those variables being set and everything working. https://stackoverflow.com/a/58513442/791247

**Comment by njhill** [comment] 2021-05-18 14:17
@candrews @normanmaurer actually the correct thing would be to not use `os-maven-plugin` at all for these. This gives you information about the OS/arch of the build system which is irrelevant to the artifacts being published. The classifier for the epoll and tcnative dependencies should just be explicitly set to `linux-x86_64`. See https://github.com/netty/netty/issues/8097.

**Comment by fredericBregier** [comment] 2021-05-18 15:13
@candrews If it fixes the dependencies, great !!!

**Comment by candrews** [comment] 2021-05-18 15:45
Here's the result of running `mvn dependency:tree` on the pom.xml from the description against netty with #11278:
[tree.txt](https://github.com/netty/netty/files/6502577/tree.txt) As far as I can tell, the tree output looks good.

**Comment by boris-unckel** [comment] 2021-05-18 17:10
@normanmaurer Can you estimate when a 4.1.64.1 or 4.1.65 will be released?

**Comment by normanmaurer** [comment] 2021-05-18 17:11
@boris-unckel hopefully this week

**Closed** 2021-05-19 09:12 UTC
Labels: regression

**Comment by fredericBregier** [comment] 2021-05-19 16:34
@normanmaurer Thanks !
I will try to go to explicit dependencies, such that I will not too much depends on Netty-All. I guess it is better, since I don't need each and every codec or modules (even if I used a lot of them).
