### ISSUE TITLE
Adding actuator prefix path to readiness and liveness probe

### ISSUE THREAD

**Issue by techdeba901** [netty/netty#11497] opened 2021-07-21 08:40 UTC
### Expected behavior
I am using webflux and netty in my spring boot app. I tried with the following line in my application.properties file
management.endpoints.web.base-path=/secure

And expecting readiness and liveness probe to be

livenessProbe:
  httpGet:
    path: /secure/actuator/health
	

readinessProbe:
  httpGet:
    path: /secure/actuator/health

### Actual behavior
But during runtime liveness and readiness  path is 
livenessProbe:
  httpGet:
    path: /actuator/health
	

readinessProbe:
  httpGet:
    path: /actuator/health
	

### Steps to reproduce
Add management.endpoints.web.base-path value in configuration file 
Check readiness and liveness  path is having prefix or not 

###Your Environment
SpringBootVersion="2.4.3"
Docker base images: openjdk:15.0.1-jdk-oraclelinux8

**Comment by normanmaurer** [comment] 2021-07-21 08:44
this sounds more like a spring issue to me... @violetagg thoughts ?

**Comment by bclozel** [comment] 2021-07-21 09:09
@techdeba901 Please avoid creating duplicate issues across projects.
@normanmaurer You can close this issue as a duplicate of spring-projects/spring-boot#27423

**Closed** 2021-07-21 09:22 UTC
