### ISSUE TITLE
OutOfDirectMemoryError in netty 4.1.8

### ISSUE THREAD

**Issue by mikewoo** [netty/netty#7522] opened 2017-12-19 03:42 UTC
My data transmission service(base on netty) persisting OutOfDirectMemoryError Exception within few hours, when we restart my server, everything is working again, we use netty 4.1.8 Final version, and it were running for weekings with no issues.
Exception logs:
io.netty.handler.codec.DecoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1811939328, max: 1823473664)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:375)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:342)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1811939328, max: 1823473664)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:718)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:707)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:239)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:209)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:287)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:828)
        at com.myserver.protocol.DataPacketPicker.pickup(DataPacketPicker.java:58)
        at com.myserver.handler.ProtocolDecoder.decode(ProtocolDecoder.java:64)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        ... 17 more

###  startup parameter 
we start my server with the following parameters:
-XX:MaxDirectMemorySize=128M -Dio.netty.allocator.type=pooled -Dio.netty.allocator.tinyCacheSize=0 -Dio.netty.allocator.smallCacheSize=0 -Dio.netty.allocator.normalCacheSize=0 -Dio.netty.leakDetection.level=advanced

### Netty version
4.1.8.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
### OS version (e.g. `uname -a`)
CentOS Linux release 7.3.1611 (Core)
Linux i-q3qwh2ws 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment] 2017-12-19 04:00
Can you try and update to the latest Netty release? Also can you provide a heap dump?

**Comment by HymanMing** [comment] 2017-12-19 05:23
I cannot share the heap dump publicly for security reasons. The following image is the analysis of heap dump, incules some objects.
![heap](https://user-images.githubusercontent.com/8331050/34142009-cb2910f4-e4bf-11e7-8d2b-e68510831282.jpg)

**Comment by normanmaurer** [comment] 2017-12-19 06:04
There are a lot of String references . Can you check the incoming references to these ?

**Comment by normanmaurer** [comment] 2017-12-19 11:46
@mikewoo how many IO threads (EventLoops) you are using ?

**Comment by normanmaurer** [comment] 2017-12-19 13:27
Most likely the problem is that using the pooled allocator with 128MB memory restriction is too low for the number of arenas that are used. By default the number of arenas are `2 * cores` and each arena will at least allocate 16MB of memory on the first allocation.

**Comment by mikewoo** [comment] 2017-12-19 14:53
@normanmaurer  my server used the default EventLoops config, like this `EventLoopGroup bossGroup = new NioEventLoopGroup();  
        EventLoopGroup workerGroup = new NioEventLoopGroup();`
So I should increase the MaxDirectMemorySize to solve the problem?

**Comment by normanmaurer** [comment] 2017-12-19 14:59
@mikewoo either this or not using the pooled allocator or use a smaller number of arenas. You can configure the number of arenas via:

`-D io.netty.allocator.numHeapArenas=` and `-D io.netty.allocator.numDirectArenas=`.

See https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L84

**Comment by normanmaurer** [comment] 2017-12-20 09:15
Let me close this issue... please reopen if you still think there is a problem

**Closed by normanmaurer** 2017-12-20 09:15 UTC
