### ISSUE TITLE
CLOSE_WAITs with Netty 4.0.35 or higher.

### ISSUE THREAD

**Issue by ramtg** [netty/netty#5477] opened 2016-06-30 13:59 UTC
I'm using a Netty based in a TCP socket server app that serves slow clients connecting over cell modems.

With Netty 4.0.35 or higher or 4.1, the server app comes to a grinding halt  after a few hours .
and netstat shows too many sockets in the CLOSE_WAIT OR SYN_RECV states.

With 4.0.34, I've never seen this issue, even after many weeks.. without a restart.

Google search suggests CLOSE_WAIT is a sign of the Server application not responding correctly to close initiated by the clients.  But the server application code seems to be calling the channel close method in all scenarios. 

Additional info:

- EPOLL or no-EPOLL on Ubuntu-14 does not seem to make any difference and we're using the most current 64-bit Oracle JRE 1.8.

- I have KEEP_ALIVEs disabled  and TCP_NODELAY enabled on the NIO Transport.

- Unfortunately I've been unable to get  tshark captures when the issue happened.

Any systematic way to troubleshoot this issue will be gratefully appreciated.

Thank you,
Ram

**Comment by Scottmitch** [comment] 2016-06-30 16:16
@ramtg - To clarify you are observing this issue with the latest Netty release? Can you provide a reproducer for this issue? Are you using autoRead? It would be interesting to see a heap dump and how many channels are still kicking around and also compare this against what channel's Netty has notified with channelInactive. What does a stack trace look like (are any EventLoop threads blocked)?

**Comment by normanmaurer** [comment] 2016-07-11 07:01
@ramtg ping

**Comment by ramtg** [comment] 2016-07-11 19:06
Yes, I observed the issue with the latest Netty 4.1.1 as well as  Netty 4.0.35 and higher.

No, I'm not using autoRead.

No, I don't have a reproducer yet, since we use a custom TCP protocol. 
I'll  need to spend sometime to make a reproducer.

Currently my app is still  [stuck :-( ]  on Netty 4.0.34 with which I haven't seen this issue ever.
but  I'll capture a heap/stack dump if I ever hit the issue again IF I get a chance to try out Netty 4.1.1 again.

Thank you,
Ram

**Comment by Scottmitch** [comment] 2016-07-11 21:21
> No, I'm not using autoRead.

If you are not using auto read is it possible there is a condition that you are not calling `read()`? Doing a read is typically how we detect that the peer has disconnected.

> Currently my app is still [stuck :-( ] on Netty 4.0.34 ... I'll need to spend sometime to make a reproducer.

Plz ping us back when you can provide more data and hopefully we can help!

**Comment by ramtg** [comment] 2016-07-12 02:31
@Scottmitch   

Correction:  I reviewed my application code. I didn't find an explicitly call  'setAutoRead()' anywhere.
Does that mean autoRead would then be true, by default ?

**Comment by Scottmitch** [comment] 2016-07-12 16:20
@ramtg - Autoread is enabled by default.

**Comment by maseev** [comment] 2016-07-19 06:03
I think [this](https://github.com/netty/netty/issues/4932) ticket is related to this one (or even duplicated it). Would it be a problem to close a connection in one of the lifecycle methods (like `channelActive` or `exceptionCaught`) by calling `ctx.channel().close()` instead of `ctx.close()` (where `ctx` has type `ChannelHandlerContext`)?

**Comment by maseev** [comment] 2016-07-19 11:08
ping @Scottmitch, @normanmaurer

**Comment by maseev** [comment] 2016-07-19 19:52
BTW, Is it a problem if I for example set channel's auto_read property to false and for some reason, a client decides to close the connection? Would the server socket connection be closed normally?

**Comment by maseev** [comment] 2016-07-20 03:37
@wahisoufiane, @ramtg - Is there any chance you guys could reproduce the problem?

**Comment by ramtg** [comment] 2016-07-20 04:02
@maseev   My app uses autoRead(true) (the default) and unfortunately I haven't had a chance to make a reproducer yet, since my app uses a custom message demarcation protocol.  The CLOSE_WAIT issue has been seen with only 4.0.35 or higher as well as 4.1.

**Comment by maseev** [comment] 2016-07-20 05:15
@ramtg That's pretty sad. I'm experiencing the same problem and haven't been able to find a reproducer so far.

**Comment by Scottmitch** [comment] 2016-07-20 22:40
> Would it be a problem to close a connection in one of the lifecycle methods (like channelActive or exceptionCaught) by calling ctx.channel().close() instead of ctx.close() (where ctx has type ChannelHandlerContext)

@maseev  - The primary difference is where the close method calls start in the pipeline.
- `ctx.close()` - the "next" outbound handler
- `ctx.channel().close()` - from the "beginning" of the pipeline.
This should not be a "problem" either way, but if one of your handlers overrides `ChannelOutboundHandler.close(..)` and doesn't propagate the close to the next handler in the pipeline this may be a bug.

> BTW, Is it a problem if I for example set channel's auto_read property to false and for some reason, a client decides to close the connection? Would the server socket connection be closed normally?

It would be helpful to clarify if the peer that "sets the auto_read" to false is defined as the client or the server in this example. In general to detect a socket is closed "gracefully" by your peer you have to do some action on the socket ... this is generally accomplished by asking the selector to notify you when the action can be done ... then you try the action and figure out the socket is closed. If the socket is not closed "gracefully" (ethernet unplugged, power gets cut abruptly, tcp protocol not followed) you will have to have some sort of keep alive to detect a "zombie socket".

**Comment by maseev** [comment] 2016-07-21 04:09
@Scottmitch 

> It would be helpful to clarify if the peer that "sets the auto_read" to false is defined as the client or the server in this example.

In this example, I meant that the auto_read property was set to false on the server side, as part of the backpressure implementation. I think it's worth mentioning that the same property is set to true in the `channelWritabilityChanged` method when the channel becomes readable again.

**Comment by christ258** [comment] 2016-07-31 11:40
hi,I want to know what's the difference between ctx.channel().close() and ctx.close(), for example, in the service side, I want to elegant close client connection, ctx.channel().close() or ctx.close() is the most effective closing?Expect to answer.
thank you

**Comment by maseev** [comment] 2016-08-01 04:31
@Scottmitch I just noticed, that IdleStateHandler calls the destroy() method only twice - when [channelInactive](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L256) or [handlerRemoved](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L233) is called. What will happen if the exception is thrown? Those scheduled features will continue to call lifecycle methods because read or write timer expires even though the connection is lost?

**Comment by johnou** [comment] 2016-08-01 10:21
@christ258 Scottmitch explains the difference between ctx.channel().close() and ctx.close() here https://github.com/netty/netty/issues/5477#issuecomment-234106289

@maseev exception thrown from where? If a channel if closed as a result of the developer implementing exception caught and closing the channel ( either by ctx.channel().close() or ctx.close() ) I assume channelInactive will be called on all handlers in the pipeline (not from the position of the close invocation which will include IdleStateHandler) killing the timers.

**Comment by christ258** [comment] 2016-08-07 10:44
@johnou 
thank you,

**Comment by maseev** [comment] 2016-08-13 14:39
@wahisoufiane, @ramtg I was able to track and fix this problem recently. It turned out that the problem was in the application logic (so, it wasn't Netty)  which apparently blocked the eventLoop threads from time to time. So, when the clients disconnected from the server, the event loop threads were blocked for a substantial period of time. Because of that, I'd constantly seen these TCP connections in CLOSE_WAIT state.

I would recommend you to grab [YourKit](https://www.yourkit.com/java/profiler/download/) profiler (which by the way has a free 15-days evaluation period). It has a nice feature that can detect deadlocks in your in your applications.

Hope this helps.

**Comment by Scottmitch** [comment] 2016-08-17 19:05
@maseev - Thanks for explaining ... this is not the first time I have seen blocking the I/O thread cause these symptoms.

@ramtg  - Can you confirm if you observe similar behavior?

**Comment by ramtg** [comment] 2016-08-17 20:02
@Scottmitch : I upgraded my app back to Netty 4.1.4 a week ago and
I haven't yet seen CLOSE_WAIT or SYNC_RECVD issue so far.  
Also  I'll review and profile my code to make sure the Netty threads are not blocked for too long.
Thank you.
Ram

**Closed** 2016-09-04 03:44 UTC

**Comment by Scottmitch** [comment] 2016-09-14 02:35
thanks for following up @ramtg!

BTW our friends at Twitter posted a blog post on this issue https://finagle.github.io/blog/2016/09/01/block-party/
