### ISSUE TITLE
Fix build stability issues with the epoll transport

### ISSUE THREAD

**Issue by trustin** [netty/netty#3848] opened 2015-06-01 06:11 UTC
- http://clinker.netty.io/jenkins/job/netty-oraclejdk7/branch/4.1/412/
- http://clinker.netty.io/jenkins/job/netty-oraclejdk8/branch/4.1/412/

We might have more. Please go through the failures and fix the epoll-related ones.

**Comment by normanmaurer** [comment] 2015-06-01 06:24
@trustin will check... can't reproduce so far here :/

**Comment by trustin** [comment] 2015-06-01 06:56
It seemed to fail on the both centos6 slaves and one of them is yours. :-)

**Comment by normanmaurer** [comment] 2015-06-01 07:01
@trustin will find out

**Comment by normanmaurer** [comment] 2015-06-08 12:56
I think this should be fixed now

**Closed by normanmaurer** 2015-06-08 12:56 UTC
Labels: defect
