### ISSUE TITLE
Unexpected exception in the selector loop. java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vikashsingh009** [netty/netty#9035] opened 2019-04-12 08:04 UTC
### Expected behavior
I have  used RocketMq Client  which  is  java  based used  IKVM  8.1  to  convert to  dll,
should sending  and  recieving  message  
### Actual behavior
its  show  this  Warn  and  after  that  Not  able  to  Recieve Rocket Mq  consumer  Message 

WARN io.netty.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.lang.ArrayIndexOutOfBoundsException
	at io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess.lvElement(UnsafeRefArrayAccess.java:94)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.poll(MpscChunkedArrayQueue.java:244)
	at io.netty.util.concurrent.SingleThreadEventExecutor.pollTask(SingleThreadEventExecutor.java:227)
	at io.netty.channel.nio.NioEventLoop.pollTask(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:424)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:141)
	at java.lang.Thread.run(Thread.java:955)

ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.lang.ArrayIndexOutOfBoundsException
	at io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess.soElement(UnsafeRefArrayAccess.java:70)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.offer(MpscChunkedArrayQueue.java:194)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:347)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:748)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:441)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:121)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1004)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:730)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:820)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:730)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:820)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:36)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1073)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1127)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1061)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:42)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:141)
	at java.lang.Thread.run(Thread.java:955)

### Steps to reproduce
RocketMq  4.5 with  IKVM  DLL using  producer  and  consumer 
### Netty version
netty-all-4.1.34.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by normanmaurer** [comment] 2019-04-12 09:04
@nitsanw any idea ?

**Comment by nitsanw** [comment] 2019-04-12 12:28
There’s no array access, so there should be no AIOOB Exception. This is not something one of the JVMs I test on would do. Can you provide a reproducer?

**Comment by vikashsingh009** [comment] 2019-04-12 12:54
I  have  tested  with  RocketMQ  Server Client  Mode here  is  the  steps

1)  download RocketMq server  from http://mirrors.estointernet.in/apache/rocketmq/4.5.0/rocketmq-all-4.5.0-bin-release.zip
2)   > Start nameserver: 

 # cd /opt/rocketmq/bin
 # ./mqnamesrv &

 or

 # cd /opt/rocketmq
 # nohup sh bin/mqnamesrv &

----------------------------------------------------------------------------------

> Start broker: 

 # cd /opt/rocketmq/bin
 # ./mqbroker -c ../conf/broker.conf -n 0.0.0.0:9876 &

3)  open below projects in visual  Studio 2017 

https://github.com/vikashsingh009/RocketMqProducer  

https://github.com/vikashsingh009/RocketMQ

4)  Start Consumer  Console  AppFirst  then Producer App
5)  Click  on  y to  send  Message  from producer  Continues 
after  some  time Consumer  stopped  Responding till  next  start  and  we  will  see  logs  in 
C:\Users\<USerNAme>\logs\rocketmqlogs

**Comment by nitsanw** [comment] 2019-04-12 17:52
Hi @vikashsingh009, I don't have a windows environment to test this with. IKVM has had issues with JCTools before, e.g.: 
https://sourceforge.net/p/ikvm/mailman/message/35520859/

I understand the error you see is in the process using the dll produced by IKVM, I am not familiar with the IKVM project, you may need to seek help there. @normanmaurer perhaps we can add some JVM detection to use the atomic queues on IKVM JVMs?

**Comment by normanmaurer** [comment] 2019-04-12 18:03
@nitsanw sounds like an idea... 

@vikashsingh009 can you tell me what `java.vm.name` system property tell you on this system ?

**Comment by normanmaurer** [comment] 2019-04-12 18:05
So looks like this:

```
"java.vm.name", "IKVM.NET"
```
https://sourceforge.net/p/ikvm/mailman/message/19032390/

Maybe we should just "disable" sun.misc.Unsafe usage all together

**Comment by vikashsingh009** [comment] 2019-04-12 18:21
Thanks if that the case i have to build netty from source?

**Comment by normanmaurer** [comment] 2019-04-12 18:33
Should be fixed by https://github.com/netty/netty/pull/9042

**Closed** 2019-04-12 20:41 UTC

**Comment by vikashsingh009** [comment] 2019-04-13 07:10
Thanks  for  info but  i  am  still  getting  Error here  is  the  steps i  did

1)  Build  netty Master  branch 
2) used  this  to  put  in  Maven Local  repo
mvn install:install-file -Dfile=netty-all-4.1.35.Final.jar  -DgroupId=io.netty -DartifactId=netty-all -Dversion=4.1.35.Final    -Dpackaging=jar -DgeneratePom=true

3)  changed RocketMq  Netty Jar  from here https://github.com/apache/rocketmq/blob/master/pom.xml

<dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>4.1.35.Final</version>
            </dependency>
4)  after  that  build  RocketMq  and  copy rocketmq  jars  to  IKVM  and  build  it 
5)  start  rocket  mq  with  source  build 
6)  now  used in C#  Producer Consumer  App  ,but  still  getting  Error

here  is  Complete Logs
[rocketmq_client.log](https://github.com/netty/netty/files/3075892/rocketmq_client.log)

**Comment by normanmaurer** [comment] 2019-04-13 07:39
It must be the 4.1 branch

**Comment by vikashsingh009** [comment] 2019-04-13 07:53
yes  my  mistake yes i have  used  4.1  branch  Only,  if  i  see above  attached log  i  am  not  getting  any  Logs  Realted  to  IKVM  like   this  line  on  PlatformDependent

logger.debug("sun.misc.Unsafe: unavailable (IKVM.NET)");

is  somewhere  ikVM  envirnament  not  detected

**Comment by normanmaurer** [comment] 2019-04-13 08:05
Seems so... can you print out system properties and include them here ?

**Comment by vikashsingh009** [comment] 2019-04-13 12:44
@normanmaurer @nitsanw thanks  for  your  great  support now  i  can  able  to  send  and  recieve Message  without  intruption  its  great  help  in  hunting  down  issue

**Comment by normanmaurer** [comment] 2019-04-13 16:29
So my change did work at the end ?

**Comment by vikashsingh009** [comment] 2019-04-13 16:50
Yes its a awesome
