### ISSUE TITLE
SSL Handshake failure closes connection disallowing a response

### ISSUE THREAD

**Issue by dlmarion** [netty/netty#6428] opened 2017-02-21 21:18 UTC
It appears that the resolution to #5860 / #5880 in release 4.0.42 changed how a ssl handshake failure behaves. Previously, the SslHandler would call fireExceptionCaught() before setHandshakeFailure(). The order of the execution of these calls was reversed in one of these issues.

I was using the fireExceptionCaught() to send an HTTP redirect response back to the caller. Is there any way to do this in Netty 4.0.42+ ? Thanks!

**Comment by dlmarion** [comment] 2017-02-21 21:36
FWIW, the purpose of the HTTP redirect was to send the caller to an HTTPS address that would then return a HSTS header. If there is a pattern for doing this differently in Netty, please advise.

**Comment by Scottmitch** [comment] 2017-02-21 21:58
There are currently at least 2 ways to be notified of a handshake failure:

1. [SslHandler#handshakeFuture](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L491).
2. [SslHandshakeCompletionEvent](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandshakeCompletionEvent.java#L36) will be fired up the pipeline as a user event (use [userEventTriggered](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelInboundHandler.java#L61) in your inbound handler to get this).

Both of these are triggered at the same time and I don't think there is any guarantee w.r.t to relationship or ordering between the `fireExceptionCaught` and these methods. Explain why the ordering matters in your case, and what is preventing you from sequencing things "correctly"?

**Comment by dlmarion** [comment] 2017-02-21 23:02
It appears that the client connection is closed before I have the ability to respond. Set HandshakeFailure closes the connection, then fireExceptionCaught gets called. I will look at the handshake future tomorrow when I get back in the office.

**Comment by normanmaurer** [comment] 2017-02-22 05:36
@dlmarion hmm that should Born be the case. Please keep us posted

**Comment by dlmarion** [comment] 2017-02-22 13:49
@normanmaurer Did you find what I was talking about, or do I need to build a test case?

**Comment by normanmaurer** [comment] 2017-02-22 13:50
@dlmarion yep... stay tuned.

**Comment by dlmarion** [comment] 2017-02-22 13:57
The code in  SslHandler looks like the following in version 4.0.41:

```
        if (nonSslRecord) {
            // Not an SSL/TLS packet
            NotSslRecordException e = new NotSslRecordException(
                    "not an SSL/TLS record: " + ByteBufUtil.hexDump(in));
            in.skipBytes(in.readableBytes());
            ctx.fireExceptionCaught(e);
            setHandshakeFailure(ctx, e);
        }
```

and looks like this in 4.0.44:

```
        if (nonSslRecord) {
            // Not an SSL/TLS packet
            NotSslRecordException e = new NotSslRecordException(
                    "not an SSL/TLS record: " + ByteBufUtil.hexDump(in));
            in.skipBytes(in.readableBytes());

            // First fail the handshake promise as we may need to have access to the SSLEngine which may
            // be released because the user will remove the SslHandler in an exceptionCaught(...) implementation.
            setHandshakeFailure(ctx, e);

            ctx.fireExceptionCaught(e);
        }
```
The call to `setHandshakeFailure()`  eventually calls `SslUtils.notifyHandshakeFailure` which ends up calling `ChannelHandlerContext.close()`. I think this is the issue that I am having. In earlier versions, my clients would get the HTTP redirect and in the latest version they don't. I see in my logs that the connection is closed, then my `exceptionCaught()` method fires, but the connection is already closed.

**Comment by dlmarion** [comment] 2017-02-22 13:57
Great, thanks.

**Comment by dlmarion** [comment] 2017-02-22 13:59
FWIW, I think closing the connection on an SSL handshake failure might be the correct action here. But there also might be one or two allowable actions that could occur before the connection is closed. Implementing HTTP Strict Transport Security is one of them.

**Comment by normanmaurer** [comment] 2017-02-22 19:58
@dlmarion i wonder if the best would be not make it configurable if the connection should be closed or not... WDYT ? Also /cc @Scottmitch

**Comment by dlmarion** [comment] 2017-02-22 20:04
That's fine. I'll just add code in my exceptionCaught method that closes the connection after my response is sent.

**Comment by dlmarion** [comment] 2017-02-22 20:05
Another option would be for me to extend the SslHandler and implement a method that is called before you close the connection. This would allow me to send back a response, it would get flushed and closed by the Netty framework. This might be better in case others don't close the connection.

**Comment by normanmaurer** [comment] 2017-02-23 07:35
@dlmarion I think this one should help your use-case and make it more flexible: https://github.com/netty/netty/pull/6438

**Comment by dlmarion** [comment] 2017-02-23 22:19
I didn't get a chance to test this today, I will try tomorrow. Thanks

**Comment by johnou** [comment] 2017-02-24 09:42
@dlmarion silly question but if the SSL handshake fails that means you are trying to send unencrypted data back to the client in order to tell it to do something? Doesn't sound super secure, couldn't you check for SSL handshake failure on the client side instead?

**Comment by normanmaurer** [comment] 2017-02-24 09:43
@johnou in this situation I think its more about when the client not sends encrypted data put just send unencrypted.

**Comment by johnou** [comment] 2017-02-24 09:51
@normanmaurer so maybe he could detect the protocol in a handler instead? we used to have something like that for backwards compatibility until all clients were updated to enforce SSL, something like this..

```java
/**
 * Manipulates the current pipeline dynamically to enable SSL if detected.
 *
 * @author Johno Crawford (johno@sulake.com)
 */
public class SslMessageDecoder extends ByteToMessageDecoder {

    private final SslContext sslContext;

    public SslMessageDecoder(SslContext sslContext) {
        this.sslContext = sslContext;
    }

    @Override
    protected void decode(ChannelHandlerContext context, ByteBuf in, List<Object> out) throws Exception {
        if (in.readableBytes() < 5) {
            return;
        }
        if (SslHandler.isEncrypted(in)) {
            enableSsl(context);
        } else {
            context.pipeline().remove(this);
        }
    }

    private void enableSsl(ChannelHandlerContext context) {
        ChannelPipeline pipeline = context.pipeline();
        pipeline.replace(this, SslHandler.class.getName(), sslContext.newHandler(context.alloc()));
    }

    @Override
    public boolean isSingleDecode() {
        // ByteToMessageDecoder uses this method to optionally break out of the decoding loop after each unit of work.
        // Since we only ever want to decode a single header we always return true to save a bit of work here.
        return true;
    }
}
```

**Comment by dlmarion** [comment] 2017-02-25 00:08
So, I just tried building with the latest SNAPSHOT jar from https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-all/4.0.45.Final-SNAPSHOT/. Getting a compilation error, it appears the change isn't there or I have the wrong artifact:

[342,20] cannot find symbol
  symbol:   method setCloseOnHandshakeFailure(boolean)
  location: variable ssl of type io.netty.handler.ssl.SslHandler

Thoughts?

**Comment by dlmarion** [comment] 2017-05-02 15:45
Any particular reason this keeps getting kicked down the road?

**Comment by normanmaurer** [comment] 2017-05-02 15:47
@dlmarion actually I missed to just close it. You should use https://github.com/netty/netty/issues/6510

**Comment by normanmaurer** [comment] 2017-05-02 15:50
Yes

**Comment by dlmarion** [comment] 2017-05-02 15:50
Thx.

**Closed by normanmaurer** 2017-05-02 15:50 UTC
Labels: defect

**Comment by BaurzhanSakhariev** [comment] 2021-07-04 14:06
Hi @johnou , thx for implementing OptionalSslHandler! 

Let me clarify one thing - it doesn't read handshake bytes but gets them (doesn't increase readerIndex) right? 

I was trying to do something like OptionalSslHandler but for client side, and did just  sslHandker - handshake - remove from pipeline in case of failure and got error `Pending write on removal of SslHandler`. My use case [details](https://stackoverflow.com/questions/68245439/how-can-i-update-client-pipeline-to-ssl-non-ssl-mode-similar-to-what-optionalssl). 

I was thinking about  a PR with shifting readerIndex in pls header check and getting back in case of non-ssl - but I'm not sure my issue is caused by not shifting readerIndex.
