### ISSUE TITLE
ClientCookieEncoder encode cookie unnecessary stripTrailingSeparator

### ISSUE THREAD

**Issue by dmpnv** [netty/netty#10604] opened 2020-09-23 15:58 UTC
### Expected behavior
the cookie should be encoded as expected 
name=value

### Actual behavior
the result string is missing two last characters
name=val

### Steps to reproduce
ClientCookieEncoder encoder;
... skip new encoder initialization
String result = encoder.encode(new DefaultCookie("name", "value"));

### Netty version
4.1

### JVM version (e.g. `java -version`)
jdk-11

### OS version (e.g. `uname -a`)
any

**Comment by slandelle** [comment] 2020-09-23 16:18
Couldn't reproduce. Please provide a **full sample**.

**Comment by dmpnv** [comment] 2020-09-29 17:38
> Couldn't reproduce. Please provide a **full sample**.

this test code should reproduce the wrong behavior:

`package io.netty.handler.codec.http.cookie;`
```
public class SingleClientCookieEncoderTest {
    @org.junit.Test
    public void testEncodingSingleClientCookie() {
        String c1 = "myCookie=myValue";
        Cookie cookie1 = new DefaultCookie("myCookie", "myValue");
        String encodedCookie = ClientCookieEncoder.STRICT.encode(cookie1);
        org.junit.Assert.assertEquals(c1, encodedCookie);
    }
}
```


[ERROR] testEncodingSingleClientCookie(io.netty.handler.codec.http.cookie.ClientCookieEncoderTest)  Time elapsed: 0.234 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<myCookie=myVal[ue]> but was:<myCookie=myVal[]>

**Comment by slandelle** [comment] 2020-09-29 19:28
Still can't reproduce with Netty 4.1.51. You only mention you're using 4.1. If you're running an old version, you should upgrade.

**Comment by normanmaurer** [comment] 2020-10-26 13:24
I will close this one for now... @dmpnv please reopen if you can still reproduce with the latest netty release of the 4.1 branch.

**Closed by normanmaurer** 2020-10-26 13:24 UTC
