### ISSUE TITLE
Retrying requests with SSLEngine ByteBufs

### ISSUE THREAD

**Issue by artgon** [netty/netty#7753] opened 2018-02-27 19:45 UTC
I'm not sure if this is a bug or a feature but just wanted some clarification on the functionality here:

When send a POST body over SSL and then want to retry that request, the ByteBufs are forcibly cleared (I think here: https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L796), so on a retry it sends a series of EmptyByteBufs.

The workaround for now is to duplicate the body into a byte array and manually write it on the second request. We just wanted some clarification on this behavior.

Thanks!

**Comment by normanmaurer** [comment] 2018-04-19 19:01
@artgon ping

**Comment by artgon** [comment] 2018-04-20 22:00
Hey, sorry dropped the ball on this. 

Context: we retry proxying requests if they fail for whatever reason

What we found is with SSL requests, the bytebufs get forcefully cleared whereas plaintext requests we can retry with the same bytebufs. Our workaround was to manually cache and repopulate the body bytebufs for SSL retries: https://github.com/Netflix/zuul/blob/2.1/zuul-core/src/main/java/com/netflix/zuul/filters/endpoint/ProxyEndpoint.java#L510 
For additional context the `setBody()` method is here: https://github.com/Netflix/zuul/blob/abdc1bd416ccf1fd03c32a12a403ea8de0a84cf0/zuul-core/src/main/java/com/netflix/zuul/message/ZuulMessageImpl.java#L136

Just wanted to understand the reasoning for that behavior.

**Comment by normanmaurer** [comment] 2018-04-24 07:02
@artgon I am still not sure I understand your problem... when you say "cleared" you mean it is override (like filled with zeros) or just that the readerIndex is adjusted ? If its the later then generally speaking you need to create a duplicate of the `ByteBuf` before you send it down the pipeline if you want to ensure you will be able to retry it as otherwise the indices may be changed etc.

**Comment by artgon** [comment] 2018-04-25 21:35
Yeah that's essentially what we're doing but it gets tricky with chunked bodies. So what we did is just buffer it and cache before we feed down into the Netty handler. 

The behavior I observed was that the ByteBufs were still there but were all zeroed out. It seems like this only happens in the SSLHander though, not the regular HTTP handlers.

**Comment by normanmaurer** [comment] 2018-05-06 18:17
`zeroed out` sound like a bug. It should only affect the reader / writerIndex but not the content when written to the `SslHandler`. Any simple way for me to reproduce ?

**Comment by normanmaurer** [comment] 2018-05-07 08:07
@artgon I can not reproduce... Here is a test-case. https://github.com/netty/netty/pull/7914.

**Comment by artgon** [comment] 2018-05-07 17:53
Hmm yeah, that test seems to rule out the issue. Let me dig deeper here and see if I can find the cause.

**Comment by normanmaurer** [comment] 2018-05-07 18:08
@artgon I will merge the unit test in the meantime... more tests FTW ;) Let me know when you find out what exactly is going on. I will close the issue in the meantime (so please reopen if you still think there is a problem).

**Closed** 2018-05-07 18:10 UTC
