### ISSUE TITLE
java.lang.IllegalStateException: channel not registered to an event loop

### ISSUE THREAD

**Issue by JuKu** [netty/netty#4686] opened 2016-01-09 23:23 UTC
I get the following error message with Netty 4.0.33.Final if an client connect to server:

```
28327 [nioEventLoopGroup-2-1] WARN io.netty.channel.DefaultChannelPipeline  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: channel not registered to an event loop
    at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:111)
    at io.netty.channel.nio.AbstractNioChannel.eventLoop(AbstractNioChannel.java:117)
    at io.netty.channel.nio.AbstractNioChannel.eventLoop(AbstractNioChannel.java:49)
    at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:113)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:232)
    at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:834)
    at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:500)
    at io.netty.channel.DefaultChannelPipeline.callHandlerAdded(DefaultChannelPipeline.java:482)
    at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:146)
    at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:129)
    at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:257)
    at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:244)
    at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:235)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:240)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
[2016-01-10 00:19:49 WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
```

The handler also implements method exceptionCaught(ChannelHandlerContext ctx, Throwable cause).
Whats the cause of this issue?

**Comment by ifesdjeen** [comment] 2016-01-10 15:17
@JuKu it's a bit hard to say waht exactly might be the cause for the issue without the actual code. Could you try to extract the minimum snippet that would reproduce it?

**Comment by JuKu** [comment] 2016-01-11 17:19
I have reproduced the problem and could solve it.
The ZLib compression has an bug, without zlib, it works fine, but with zlib compression at begin of the pipeline, it throws this exception.

**Comment by normanmaurer** [comment] 2016-01-11 17:23
Can you give a simple reproducer so we can fix it?

**Comment by JuKu** [comment] 2016-01-13 17:54
You only have to add the zlib encoder and decoder to pipeline.

```java
//use gzip compression
pipeline.addLast("deflater", ZlibCodecFactory.newZlibEncoder(ZlibWrapper.GZIP));
pipeline.addLast("inflater", ZlibCodecFactory.newZlibDecoder(ZlibWrapper.GZIP));

//add logger to pipeline
pipeline.addLast("logger", new LoggingHandler(LogLevel.INFO));

//add message encoder and decoder
pipeline.addLast("encoder", new MessageEncoder());
pipeline.addLast("decoder", new MessageDecoder());

//add business logic handler
pipeline.addLast("business", instance);

```

**Comment by Scottmitch** [comment] 2016-01-20 03:44
@JuKu - Thanks for reporting. Could you provide a more complete example so we can fix the issue? What do `MessageEncoder`, `MessageDecoder`, and `instance` do?

**Comment by JuKu** [comment] 2016-01-26 23:26
MessageEncoder converts message object to byte stream.
For example:

public class MessageEncoder extends MessageToByteEncoder<Message>
{
	@Override
	protected void encode(ChannelHandlerContext ctx, Message msg, ByteBuf out) throws Exception
	{
		try {
			out.writeInt(Message.HEADER_LENGHT + msg.content().readableBytes());
			out.writeByte(msg.getType());
			out.writeByte(msg.getVersion());
			out.writeBytes(msg.content());
		} catch (Exception e) {
			//print stacktrace, because netty doesnt print stacktrace in all cases
			e.printStackTrace();

			//throw exception, so netty can also handle this exception and doesnt execute the next pipeline entries
			throw e;
		}
	}
}

MessageDecoder converts byte stream to message object, for example:
public class MessageDecoder extends ByteToMessageDecoder
{	
	@Override
	protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception
	{
		try {
			if (in.readableBytes() < 4) return;
			in.markReaderIndex();

			int length = in.readInt();
			if (in.readableBytes() < length)
			{
				in.resetReaderIndex();
				return;
			}

			byte type = in.readByte();
			byte version = in.readByte();
			ByteBuf content = in.slice(in.readerIndex(), length - Message.HEADER_LENGHT);
			in.skipBytes(length - Message.HEADER_LENGHT);

			// increment refcount since content is a slice of in and ByteToMessageDecoder will release in
			content.retain();

			Message message = new Message(type, version, content);
			out.add(message);
		} catch (Exception e) {
			//print stacktrace, because netty doesnt print stacktrace in all cases
			e.printStackTrace();

			//throw exception, so netty can also handle this exception and doesnt execute the next pipeline entries
			throw e;
		}
	}
}

INSTANCE is only an instance of an bussines logic handler.

**Comment by Scottmitch** [comment] 2016-01-27 00:08
@JuKu - Can you show me the complete initialization of the `ServerBootstrap` (especially the `childHandler` implementation)? As requested by @ifesdjeen in https://github.com/netty/netty/issues/4686#issuecomment-170358928 it would make it easier if you make a complete reproducer available. Is it possible just to create a small github project we can use to reproduce?

**Comment by JuKu** [comment] 2016-01-27 00:41
@Scottmitch Its not so easy, because its an large project and i cannot open source all this code, so i have to rewrite all the code to do this.

Code from Server Start:
```Java
// set handler which does the pipeline initialization
bootstrap.handler(new LoggingHandler(LogLevel.INFO));
bootstrap.childHandler(new ChannelInitHandler());

// bind bootstrap on the given port
return bootstrap.bind(port);
```
Here is ChannelInitHandler:
```Java
@Sharable
private final class ChannelInitHandler extends ChannelHandlerAdapter
{
    /** shared instance to a channel connect handler */
    private final ChannelConnectHandler instance = new ChannelConnectHandler();
		
    @Override
    public void handlerAdded(ChannelHandlerContext ctx) throws Exception
    {
        Logger.getRootLogger().debug("NettyServer handlerAdded.");

	try {
	    ctx.pipeline().addLast(instance);
	    NettyServer.this.initPipeline(ctx.pipeline());
	} catch (Exception e) {
            e.printStackTrace();
        }

        Logger.getRootLogger().debug("NettyServer handlerAdded successful.");
    }
}
```

**Comment by Scottmitch** [comment] 2016-01-27 01:33
@JuKu - while using `ChannelInitHandler` what do you see in the logs when this exception occurs? From the original stack trace It looks like at some point an expected originates from the child handler's `handlerAdded` method, but this exception fails to propagate through the pipeline because the associated channel has not yet been registered to an event loop (this seems like an issue).

**Comment by Scottmitch** [comment] 2016-02-04 11:53
@normanmaurer - I believe your PR https://github.com/netty/netty/pull/4812 is designed to resolve this issue?

**Comment by normanmaurer** [comment] 2016-02-04 12:53
@Scottmitch yes

**Comment by JuKu** [comment] 2016-09-18 12:24
@normanmaurer Is this issue resolved?

**Comment by shixiaoxiang** [comment] 2017-07-18 03:37
In the use of netty tcp communication, I in the handler channelRead0 () method out of the current channel, and then into the redis, and then removed from the redis, the generated object isRegister attribute is true, but in essence, this Channel is not registered, I will be used when the error: channel is not registered, this property is private, I can not change, cancel the registration and display as a registration, how do?

**Comment by Scottmitch** [comment] 2017-07-19 02:22
@normanmaurer - I will close this for now ... please re-open if this is we didn't actually resolve this.

**Closed by Scottmitch** 2017-07-19 02:22 UTC
Labels: defect
