### ISSUE TITLE
Seeing NoSuchElementException in netty ChunkedWriteHandler class

### ISSUE THREAD

**Issue by Arun-LinkedIn** [netty/netty#11046] opened 2021-03-01 19:28 UTC
Hi Netty team,

We are occasionally seeing NoSuchElementException in netty ChunkedWriteHandler.doFlush() method due to remove() being called on empty queue. 

java.util.NoSuchElementException: 
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
	at java.util.ArrayDeque.remove(ArrayDeque.java:452)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:267)
	at io.netty.handler.stream.ChunkedWriteHandler.resumeTransfer0(ChunkedWriteHandler.java:119)
	at io.netty.handler.stream.ChunkedWriteHandler.access$000(ChunkedWriteHandler.java:68)
	at io.netty.handler.stream.ChunkedWriteHandler$1.run(ChunkedWriteHandler.java:111)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

It seems like the object containing the chunk element (PendingWrite) was found in the queue during peek() at the beginning of doFlush(). But later (few lines below), when it attempts to remove the element (PendingWrite) after writing/flushing the message, it seems like the queue was empty resulting in no such element exception.

Looks like we are seeing this exception after upgrading netty version to 4.1.52.Final (from 4.1.42.Final) which has below change https://github.com/netty/netty/commit/69cd04240195c4652413f7a14b7764981815968a.  

### Netty version
4.1.52.Final

Code using the Netty ChunkedWriteHandler class:
https://github.com/linkedin/ambry/blob/master/ambry-rest/src/main/java/com/github/ambry/rest/NettyResponseChannel.java

**Comment by skyguard1** [comment] 2021-03-02 02:55
It seems to be caused by multi-threaded operation of ArrayDeque, it may be that other threads have removed the elements in the queue

**Comment by normanmaurer** [comment] 2021-03-02 07:11
I will have a look..

**Comment by normanmaurer** [comment] 2021-03-02 08:11
Should be fixed by https://github.com/netty/netty/pull/11049

**Closed** 2021-03-02 20:56 UTC
