### ISSUE TITLE
Using SSL protocol to send large file failed

### ISSUE THREAD

**Issue by mrsWangxing** [netty/netty#6203] opened 2017-01-11 09:31 UTC
I write 2 demo test netty ssl.
The first demo, I didn't use the SSL protocol.The second demo I use the SSL protocol.
this is the client code.Send the file to the server

This is my client handler:
```
 public void channelActive(ChannelHandlerContext ctx) throws Exception {
        //Globle.channel = ctx;
    	//Thread.sleep(10000);                                (1)
    	System.out.println(ctx.channel().toString());
        System.out.println(ctx.channel().localAddress() + "channelActive"+'-'+ new Date());
        System.out.println("start" + new Date());
        String fileUrl = "C:/work/setup/ubuntu-14.04.4-desktop-amd64.iso";
        FileControl fileControl = new FileControl(ctx);
        fileControl.sendNotice();
        fileControl.sendFile(fileUrl);
        System.out.println("end" + new Date());
    }
```
```
public void sendFile(String fileUrl) {
        // 开始执行
        RandomAccessFile raf = null;
        try {
            raf = new RandomAccessFile(fileUrl, "rw");
            ChunkedFile chunkedFile = new ChunkedFile(raf);
            channel.writeAndFlush(chunkedFile).addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture future) throws Exception {
                    future.channel().close();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
When I use the SSL protocol ,I found that sending a large file to server.The server receives the file handler will only trigger channelActive and channelInactive without triggering channelRead events
If I send a small file，it is OK. 
But If (1) location using 10 seconds delay, send a small file will fail

### Netty version
netty-all-5.0.0.Alpha1.jar
### JVM version (e.g. `java -version`)
jdk1.7.0_67

**Comment by Scottmitch** [comment] 2017-01-11 20:36
this looks like a duplicate of https://github.com/netty/netty/issues/6202. Please clarify the differences if this is not a duplicate.

**Closed by Scottmitch** 2017-01-11 20:36 UTC
