### ISSUE TITLE
The HTTP response status line contains two leading bytes

### ISSUE THREAD

**Issue by SameerTi** [netty/netty#11111] opened 2021-03-24 08:30 UTC
### Expected behavior
A HTTP Response without leading 2 bytes (2 dots)

### Actual behavior
```
GET /hdm/controller/ws HTTP/1.1
sec-websocket-extensions: bbf-usp-protocol
upgrade: websocket
connection: upgrade
sec-websocket-key: ICvOEOYyohsx+2OkM1zf4w==
host: localhost:5688
sec-websocket-origin: http://localhost:5688
sec-websocket-protocol: v1.usp
sec-websocket-version: 13

..HTTP/1.1 101 Switching Protocols                               //this is the issue, see two dots in front

sec-websocket-extensions: bbf-usp-protocol
upgrade: websocket
connection: upgrade
sec-websocket-key: ICvOEOYyohsx+2OkM1zf4w==
host: localhost:5688
sec-websocket-origin: http://localhost:5688
sec-websocket-protocol: v1.usp
sec-websocket-version: 13
upgrade: websocket
connection: upgrade
sec-websocket-accept: SdhOjxWyTpVTE9XjdAc8XqodfO0=
sec-websocket-protocol: v1.usp
```

==========
### Steps to reproduce
Main-Code
========
```
EventLoopGroup bossGroup = new NioEventLoopGroup(1);   
EventLoopGroup workerGroup = new NioEventLoopGroup(); 
ServerBootstrap        b = new ServerBootstrap();  
        b = b.group(bossGroup, workerGroup).
                channel(NioServerSocketChannel.class).
                handler(new LoggingHandler(LogLevel.INFO)).
                option(ChannelOption.SO_BACKLOG, CHANNEL_SO_BACKLOG).      
                childOption(ChannelOption.SO_KEEPALIVE, CHANNEL_SO_KEEPALIVE).
                option(ChannelOption.AUTO_CLOSE, Boolean.FALSE).
                option(ChannelOption.SO_REUSEADDR, Boolean.TRUE). 
                childHandler(new WsInitializer(this));

```
`ChannelInitializerCode`
=================
```
ChannelPipeline pipeline = socketChannel.pipeline();
pipeline.addLast("httpServerCodec", new HttpServerCodec());
pipeline.addLast(new WsHandshakeHandler(mtp));
```

`Server Side WsHandshakeHandlercode` 

```
ctx.pipeline().addFirst(new ProtobufVarint32FrameDecoder(),
                        new ProtobufDecoder(Record.getDefaultInstance()),
                        new ProtobufVarint32LengthFieldPrepender(),
                        new ProtobufEncoder());
                ctx.pipeline().replace(this, "ws-in-handler", new WsInboundHandler(mtp));
                ctx.pipeline().addLast( "ws-out-handler", new WsOutboundHandler());
                ctx.pipeline().addLast( "ws-exception-handler", new WsInboundExceptionHandler());

protected void handleHandshake(ChannelHandlerContext ctx, HttpRequest req) {
        WebSocketServerHandshakerFactory wsFactory =
                new WebSocketServerHandshakerFactory("ws://127.0.01:5689/uws" "v1.usp", true);
        handshaker = wsFactory.newHandshaker(req);
        handshaker.handshake(ctx.channel(), req, req.headers(), ctx.channel().newPromise());
        
    }
```

`ClientSide HandShaker Code`

```
DefaultHttpHeaders headers = new DefaultHttpHeaders();
headers.add("sec-websocket-extensions", "bbf-usp-protocol");

        final WsHandshakeSender handler =
                new WsHandshakeSender(mtp,
                        WebSocketClientHandshakerFactory.newHandshaker(
                                uri, WebSocketVersion.V13, "v1.usp", true, headers, 1280000));
        b.group(group)
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    public void initChannel(SocketChannel ch) throws Exception {
                        ChannelPipeline pipeline = ch.pipeline();
                        //pipeline.addLast("logging", new LoggingHandler(LogLevel.INFO));
                        pipeline.addLast("http-codec", new HttpClientCodec());
                        pipeline.addLast("aggregator", new HttpObjectAggregator(65536));
                        pipeline.addLast("handler", handler);
                    }
                });
```

**Comment by normanmaurer** [comment] 2021-03-24 09:51
Please upgrade to latest netty version and re-open with more details if you can still reproduce the error.

**Comment by SameerTi** [comment] 2021-03-24 09:59
do you mean 4.1.60.Final ?

**Comment by normanmaurer** [comment] 2021-03-24 10:03
yes

**Comment by SameerTi** [comment] 2021-03-24 10:12
Sorry no luck! with 4.1.60.Final, too i'm get following!

```
GET /hdm/controller/ws HTTP/1.1
sec-websocket-extensions: bbf-usp-protocol
host: 127.0.0.1:5688
upgrade: websocket
connection: upgrade
sec-websocket-key: VYVn4/EdRytI9MzrSnSV6Q==
origin: http://127.0.0.1:5688
sec-websocket-protocol: v1.usp
sec-websocket-version: 13

..HTTP/1.1 101 Switching Protocols
sec-websocket-extensions: bbf-usp-protocol
host: 127.0.0.1:5688
sec-websocket-key: VYVn4/EdRytI9MzrSnSV6Q==
origin: http://127.0.0.1:5688
sec-websocket-version: 13
upgrade: websocket
connection: upgrade
sec-websocket-accept: ICq5p9XmEztevKGT6rBw9TN44jE=
sec-websocket-protocol: v1.usp

h
.1.1..self:hdmept:controller..ops::00BBEF-HDMPC-wsusp-0:..,
.
.1...#
!B.B.
.00BBEF..HDMPC..wsusp-0".1.1
```

**Comment by normanmaurer** [comment] 2021-03-24 10:18
Please capture the traffic with Wireshark and share it

**Comment by SameerTi** [comment] 2021-03-24 10:23
[uspNettyLatest.zip](https://github.com/netty/netty/files/6196228/uspNettyLatest.zip)

P F A

**Comment by normanmaurer** [comment] 2021-03-24 10:37
In your Wireshark dump there is only one HTTP request... you seem to say there are multiple (at least that is what it looks like in your snipped). Can you tell me if I miss anything ? Also what exception do you see ?

**Comment by SameerTi** [comment] 2021-03-24 11:11
[two-samples.zip](https://github.com/netty/netty/files/6196602/two-samples.zip)

P F A two samples:

nettyClient-nettyWebSocketServer.pcap  [this one sends back 2 leading bytes i.e. 2 dots]
nettyClient-extWebSocketServer.pcap  [this one doesn't send back any leading bytes i.e. 2 dots]

PS: we have websocket server and client both implemented with netty libraries
so does above proves , that the way we are implementing websocket server has some issue? please check code snippet, we do some http headers before sending to server.

**Comment by SameerTi** [comment] 2021-03-24 14:09
@normanmaurer  could you please re-open this ticket ? if you agree, because I can't seem to be able to reopen.

**Comment by SameerTi** [comment] 2021-03-24 18:08
Hi
Hopefully you could find some time to respond here ?

Regards

**Comment by SameerTi** [comment] 2021-03-28 17:17
@normanmaurer  could you please open this one? or atleast please specify valid reasons to keep to closed ?

**Comment by SameerTi** [comment] 2021-03-29 08:57
[netty-test.zip](https://github.com/netty/netty/files/6220491/netty-test.zip)

Thanks @normanmaurer  
Herewith I am attaching a sample project, which fixes the issue I was facing i.e. two dots at front in Http handshake Response
However, facing another issue, please see if you could help me quickly on this one ?
```

io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: data frame using reserved opcode 3
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:422)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:238)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by SameerTi** [comment] 2021-03-29 18:31
@normanmaurer could you please give me an update on this one ?

**Comment by amizurov** [comment] 2021-03-30 16:40
Hi, @SameerTi I think the problem here that you mixed protobuf and http/ws handlers inside pipeline.  First of all you need to establish a ws connection, you can listen the WebSocketServerProtocolHandler.HandshakeComplete user event to be sure that it happened and after it you can set protobuf handlers into pipeline in proper oder.

**Comment by SameerTi** [comment] 2021-03-30 17:03
Thanks @amizurov  for response, yes for sure those protoBuf related handlers causing the issue!
However , what you have suggested is exactly what I'm doing, right ?

On client as well as server side both, as soon as Handshake is SUCCESS, I have following set:

```
ctx.pipeline().replace( this,"in-handler", new WsInboundHandler(mtp));
ctx.pipeline().addLast("ws-out-handler", new WsOutboundHandler());
ctx.pipeline().addLast( "ws-exception-handler", new WsInboundExceptionHandler());
ctx.pipeline().addFirst(new ProtobufVarint32FrameDecoder(),
                    new ProtobufDecoder(Record.getDefaultInstance()),
                    new ProtobufVarint32LengthFieldPrepender(),
                    new ProtobufEncoder());
```

Is the above order not correct as far as processing protoBuf is concerned ?

**Comment by amizurov** [comment] 2021-03-31 08:45
@SameerTi,  please take a look to our [stomp over websocket](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/stomp/websocket) example maybe this can help you to find a proper way.

**Comment by chrisvest** [comment] 2021-04-08 13:44
@SameerTi this is about the order of your handlers, so it's not a Netty issue per se, right? Can we close this?

**Comment by SameerTi** [comment] 2021-04-08 15:00
Hi , if it's just order issues
Could someone please help figuring out the correct order !?

**Comment by amizurov** [comment] 2021-04-09 07:10
@SameerTi please take a look in previous message ^^, this exactly an example of how to do this, even if not a `probuf`, but with a `stomp`, anyway the idea is the same.

**Comment by normanmaurer** [comment] 2021-04-27 14:46
let me close this as its not a netty issue

**Closed by normanmaurer** 2021-04-27 14:46 UTC
