### ISSUE TITLE
Sporadic dns reverse lookup failures "name has out-of-range pointer"

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#6051] opened 2016-11-21 10:39 UTC
Found this in the log, not sure how to reproduce, as the same ip sometimes resolves correctly. maybe a race condition?

```
2016-11-21T11:36:03.118+0100 | DEBUG | -dnsresolver-6-1 | DnsNameResolver                  | 20 - io.netty.common - 4.1.6.Final | [id: 0xafed5ee9, L:/0:0:0:0:0:0:0:0:55810] RECEIVED: [32223: /192.168.0.53:53], DatagramDnsResponse(from: /192.168.0.53:53, to: /0:0:0:0:0:0:0:0:55810, 32223, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(138.76.50.52.in-addr.arpa. IN PTR)
	DefaultDnsPtrRecord(138.76.50.52.in-addr.arpa. 300 IN PTR ec2-52-50-76-138.eu-west-1.compute.amazonaws.com.
	DefaultDnsRawRecord(50.52.in-addr.arpa. 900 IN NS 5B)
	DefaultDnsRawRecord(50.52.in-addr.arpa. 900 IN NS 5B)
	DefaultDnsRawRecord(50.52.in-addr.arpa. 900 IN NS 20B)
	DefaultDnsRawRecord(50.52.in-addr.arpa. 900 IN NS 18B)
	DefaultDnsRawRecord(50.52.in-addr.arpa. 900 IN NS 5B)
	DefaultDnsRawRecord(OPT flags:0 udp:1280 0B)
2016-11-21T11:36:03.119+0100 | WARN  | -dnsresolver-6-1 | DnsNameResolver                  | 20 - io.netty.common - 4.1.6.Final | [id: 0xafed5ee9, L:/0:0:0:0:0:0:0:0:55810] Unexpected exception:
io.netty.handler.codec.CorruptedFrameException: name has an out-of-range pointer
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeName(DefaultDnsRecordDecoder.java:152)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeName0(DefaultDnsRecordDecoder.java:109)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:94)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:71)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decodeRecords(DatagramDnsResponseDecoder.java:110)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:66)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:33)[15:io.netty.codec-dns:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)[19:io.netty.codec:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)[25:io.netty.transport:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)[25:io.netty.transport:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)[20:io.netty.common:4.1.6.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)[20:io.netty.common:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_71]
```

**Comment by CodingFabian** [comment] 2016-11-21 10:47
oh this might be https://github.com/netty/netty/pull/5923 - i thought that was fixed in 4.1.6 already

**Comment by normanmaurer** [comment] 2016-11-22 07:41
@CodingFabian yep looks related. Will release 4.1.7.Final this week.

**Comment by normanmaurer** [comment] 2016-12-07 07:13
Yes this looks like a duplicate of  #5923. Let me close this as a duplicate.

**Closed by normanmaurer** 2016-12-07 07:13 UTC
