### ISSUE TITLE
JVM warnings running Netty 4.0.52 on Java 9

### ISSUE THREAD

**Issue by ctron** [netty/netty#7295] opened 2017-10-13 08:48 UTC
### Expected behavior

No warnings from the JVM.

### Actual behavior

The following warnings get written to STDERR when launching an application using Netty 4.0.52:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/user/.m2/repository/io/netty/netty-common/4.0.52.Final/netty-common-4.0.52.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Steps to reproduce

Run a Netty 4.0.52 application on Java 9.

### Minimal yet complete reproducer code (or URL to code)

https://github.com/ctron/milo-ece2017/blob/master/client-examples/src/main/java/de/dentrassi/ece2017/milo/step01/Connect.java

### Netty version

4.0.52.Final

### JVM version (e.g. `java -version`)

openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

### OS version (e.g. `uname -a`)

Linux hostname 3.10.0-693.2.2.el7.x86_64 #1 SMP Sat Sep 9 03:55:24 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by johnou** [comment] 2017-10-13 09:49
Duplicate of https://github.com/netty/netty/issues/7254

**Comment by normanmaurer** [comment] 2017-10-25 14:07
Closing as duplicate...

**Closed by normanmaurer** 2017-10-25 14:07 UTC
