### ISSUE TITLE
worker threads creating per connection not considering input 500

### ISSUE THREAD

**Issue by praveens4all** [netty/netty#10347] opened 2020-06-11 16:18 UTC
### Expected behavior
create more worker threads and high performance
### Actual behavior
created only 1 worker thread per connection giving low performance - most of txns timeout due to late response
### Steps to reproduce
my application static connection (client-server) high volumes of transactions.

### Minimal yet complete reproducer code (or URL to code)
      private EventLoopGroup bossGroup = new EpollEventLoopGroup(4, Executors.newCachedThreadPool());
       private EventLoopGroup  workerGroup = new EpollEventLoopGroup(500, Executors.newCachedThreadPool());

        // ===========================================================
        // 1. define a separate thread pool to execute handlers with
        //    slow business logic. e.g database operation
        // ===========================================================
         group = new DefaultEventExecutorGroup(500); //thread pool of 500
        try {
            ServerBootstrap bootstrap = new ServerBootstrap();
            bootstrap.group(bossGroup, workerGroup)
                    //Linux Native Library classes
                    .channel(EpollServerSocketChannel.class)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        public void initChannel(SocketChannel ch)
                                throws Exception {
                            ch.pipeline().addLast("decoder", new Decoder())
                                    .addLast("encoder", new Encoder())
                                    .addLast(group, new Handler());

                        }
                    }).option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .option(ChannelOption.SO_BACKLOG, 128)
                    .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .childOption(ChannelOption.SO_SNDBUF, 1024 * 1024)
                    .childOption(ChannelOption.SO_RCVBUF, 32 * 1024)
                    .childOption(ChannelOption.TCP_NODELAY, true)
                    .childOption(ChannelOption.SO_KEEPALIVE, true);
### Netty version
4.1.50.Final
### JVM version (e.g. `java -version`)
Open JdK11
### OS version (e.g. `uname -a`)
linux

**Comment by praveens4all** [comment] 2020-06-11 22:20
previously i was with netty 3.X version,

 ChannelFactory factory = new NioServerSocketChannelFactory(new NioServerBossPool(Executors.newCachedThreadPool(), 4, ThreadNameDeterminer.CURRENT),
                new NioWorkerPool(Executors.newCachedThreadPool(),50, ThreadNameDeterminer.CURRENT));


        ServerBootstrap bootstrap = new ServerBootstrap(factory);

        bootstrap.setPipelineFactory(() -> {
            ChannelPipeline cp = Channels.pipeline();

            cp.addLast("decoder", new Decoder());
            cp.addLast("encoder", new Encoder());
            cp.addLast("handler", new Handler());


            return cp;
        });

working fine with threads but memory leaks problem, now threads problem..

In Netty 4.x each EventLoop is tightly coupled with a fixed thread that executes all I/O events of its registered Channels and any tasks submitted to it.

Starting with version 5.0 an EventLoop does no longer use threads directly but instead makes use of an Executor abstraction. That is, it takes an Executor object as a parameter in its constructor and instead of polling for I/O events in an endless loop each iteration is now a task that is submitted to this Executor.

please advise, my application (single client - server) connection with asynchronous high volumes of transactions...how can i create multiple threads for same channel ?

**Comment by amizurov** [comment] 2020-06-12 07:26
Hmm, why you use `Executors.newCachedThreadPool()` for boss and worker threads instead of Netty default thread factory ?

**Comment by praveens4all** [comment] 2020-06-12 07:48
Hi @amizurov  thank you for reply.
I have tried with out Executors, with default threadfactory.
 private EventLoopGroup bossGroup = new NioEventLoopGroup(4, new DefaultThreadFactory("boss", true));
       private EventLoopGroup  workerGroup  workerGroup = new NioEventLoopGroup(50, new DefaultThreadFactory("worker", true));

same result, Only created 4 threads :(

**Comment by amizurov** [comment] 2020-06-12 08:29
Sorry, maybe i missed something only 4 threads for what ? And why you need a lot of threads, on our application only 1 worker thread it handle about 10k event per second and every thing fine.

**Comment by praveens4all** [comment] 2020-06-12 08:59
Hi @amizurov My application current performance 23 TPS (txns per second), netty server receive txn executes business logic, calls webservice, insert data in database completing txn. (if we monitor per transaction taking only 120 milli seconds). we did network packet analysis understand that netty read/write taking longer than executing business logic..not sure.

If we process 10k transaction no time outs but if we try 15k transactions start getting timouts....our application need to process 50k to 100k txns..we are far away to reach goal.

I have also added DefaultEventExecutorGroup for handler..still no improvement.
  group = new DefaultEventExecutorGroup(500); //thread pool of 500

Expectation is worker thread takes care of business logic execution and third party integration (database, webservice...etc) so increasing worker threads increase throughput

**Comment by amizurov** [comment] 2020-06-12 14:41
praveens4all  Could you please share your encoder/decoder and what the payload size of events ?

**Comment by hyperxpro** [comment] 2020-06-13 09:10
Better pass your business login on ExecutorsService instead of increasing Worker threads.

**Comment by praveens4all** [comment] 2020-06-13 20:50
> @praveens4all Could you please share your encoder/decoder and what the payload size of events ?

Decoder : 

@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
@Component
@Slf4j
public class Decoder extends ByteToMessageDecoder {

    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf byteBuf, List<Object> out) throws Exception {

        log.debug("readable bytes {} , readerindex {}",byteBuf.readableBytes(), byteBuf.readerIndex());

        try{

            if (!byteBuf.isReadable()) {
                return;
            }
             //Business logic - nothing speacial reading bytes and adding to out

           out.add(msg);
}carch(Exception e){
throws e;
}
}

Encoder : 

@ChannelHandler.Sharable
@Component
@Slf4j
public class Encoder extends MessageToByteEncoder<Object> {
   
    @Override
    protected void encode(ChannelHandlerContext ctx, Object msg, ByteBuf out) throws Exception {

   //update the message with response object

  out.wrtiteBytes(msg.getBytes());
}
}

**Comment by praveens4all** [comment] 2020-06-13 20:56
> ExecutorsService

Thank you for reply, Please advise/provide example...I am not sure how to use - currently application using decoder, handler and encoder..how executorservice works which logic do i need to move ?

I am extending my classes ByteToMessageDecoder, SimpleChannelInboundHandler and MessageToByteEncoder<Object>

**Comment by hyperxpro** [comment] 2020-06-14 14:17
Lemme try to understand in more detail.

Your business logic works on `SimpleChannelInboundHandler` or `ByteToMessageDecoder and MessageToByteEncoder`?

**Comment by praveens4all** [comment] 2020-06-14 16:33
> Lemme try to understand in more detail.
> 
> Your business logic works on `SimpleChannelInboundHandler` or `ByteToMessageDecoder and MessageToByteEncoder`?

Hi let me explain,
Decoder - decode bytes to msg (java object)
Handler - excutes business logic
Encoder - encodes from object to byte[]
Most of business logic/calling thirdparty services/database operations from handler class.

**Comment by hyperxpro** [comment] 2020-06-14 18:47
Just pass your task to `ExecutorService` as soon as you receive data at `Handler`.

```java
@Override
protected void channelRead0(ChannelHandlerContext ctx, Object msg) {
	ExecutorService#submit(() -> {
  	         // Your Heavy Long-Running Code Goes Here 
	});
}
```

**Comment by praveens4all** [comment] 2020-06-15 15:06
> Just pass your task to `ExecutorService` as soon as you receive data at `Handler`.
> 
> ```java
> @Override
> protected void channelRead0(ChannelHandlerContext ctx, Object msg) {
> 	ExecutorService#submit(() -> {
>   	         // Your Heavy Long-Running Code Goes Here 
> 	});
> }
> ```

Thank you for reply @hyperxpro Appreciated.

I have applied following changes in my handler class,

```
@ChannelHandler.Sharable
@Component
@Slf4j
public class Handler extends SimpleChannelInboundHandler {

ExecutorService executorService = Executors.newFixedThreadPool(50);

@Override
protected void channelRead0(ChannelHandlerContext ctx, Object msg) {

 Future<Msg> future = (Future<Msg>) executorService.submit(() ->{
//Business logic calling code
});
ctx.writeAndFlush(future.get());
}
}
```

Looks promising in my local build...let me test with high volumes of msgs and update you.

**I am using newFixedThreadPool is this effective in performance OR do i need to consider alternative thread pool ?, please advise.**

_As per my understanding with netty configuration for Handler (business logic)  the below code need to serve the same but its not working as expected.
    // ===========================================================
    // 1. define a separate thread pool to execute handlers with
    //    slow business logic. e.g database operation
    // ===========================================================
     group = new DefaultEventExecutorGroup(500); //thread pool of 500_

**Thank you again for solution will post the results after high volume testing.**

**Comment by hyperxpro** [comment] 2020-06-15 15:17
The problem is not the number of threads, you can spawn Million threads running at the same time (depending on the hardware of course) provided you use threads efficiently. Don't create threads for small operations (e.g. 5 seconds) and destroy it immediately, reuse them.

Use `ExecutorService#newCachedThreadPool` keeps the thread alive for 60 Seconds which is good if you've reasonable amount of threads running. But if you're hitting 100K threads or somewhere near, keep threads alive for longer duration because spawning thread will get costlier at that point.

Here is what I use:
```java
ExecutorService catService = new ThreadPoolExecutor(25000, 100000, 300L, TimeUnit.SECONDS, new LinkedBlockingQueue<>());
```

I keep threads alive for 5 minutes which is decent for the job which I am doing. But YMMV. Calculate amount of threads you need and what your server can handle.

As far as you're concerned about Netty's behavior, it's perfectly normal. Use external threads for heavy-lifting, not Netty's.

**Comment by praveens4all** [comment] 2020-06-17 13:17
Thank you performance improved but still timeouts out of 15k msgs 69 timeouts..if i look at failed ones which are taking socketconnect taking longer...am not sure..
what to check how to fix socket time cosuming...
![image](https://user-images.githubusercontent.com/19388738/84902778-8bd45280-b0ad-11ea-86ae-bc08c50d7b22.png)
and otherone
![image](https://user-images.githubusercontent.com/19388738/84902851-a4dd0380-b0ad-11ea-8db9-6e2c3483c5ea.png)

**Comment by hyperxpro** [comment] 2020-06-17 13:37
I think it has more to do with network layer not Netty itself. Are you performing tests over local network?

**Comment by praveens4all** [comment] 2020-06-17 15:44
> I think it has more to do with network layer not Netty itself. Are you performing tests over local network?

Thanks for reply, No not in local environment, will check with network team.

`    ExecutorService executorService = new ThreadPoolExecutor(2500, 5000, 300L, TimeUnit.SECONDS, new LinkedBlockingQueue<>())`

creating only 2500 threads (core threads) not increasing - my understanding grow upto 5000. please advise am i missing something. thx.

**Comment by hyperxpro** [comment] 2020-06-17 16:31
Core Threads count is the minimum number of threads that will be available forever in that ExecutorService. Adjust according to your needs.

**Comment by praveens4all** [comment] 2020-06-18 11:45
Big Thank you @hyperxpro @amizurov  for responses and various solutions, Appreciated. 
My application Thread issues sorted. closing issue.

**Comment by hyperxpro** [comment] 2020-06-18 11:49
@praveens4all Close it if you're done. Controls are in your hand :-D.

**Comment by praveens4all** [comment] 2020-07-12 19:16
@hyperxpro 
please advise even I have added separate thread pool for business logic.. Netty i/o thread waiting for thread to finish process and not running parallel.. Running sequential.. Slow response time..

If I look at my thread pool different thread number serving for different msg but sequential order not running parallel.. 

Sample code 
@ChannelHandler.Sharable
@Component
@Slf4j
public class Handler extends SimpleChannelInboundHandler {

ExecutorService executorService = Executors.newFixedThreadPool(50);

@Override
protected void channelRead0(ChannelHandlerContext ctx, Object msg) {

 Future<Msg> future = (Future<Msg>) executorService.submit(() ->{
//Business logic calling code
});
ctx.writeAndFlush(future.get());
}
}

**Comment by hyperxpro** [comment] 2020-07-12 19:43
Haha, looks cute.

`Future#get` is a blocking call so you're blocking Netty there.

Use this:
```java
CompletableFuture.supplyAsync(() -> "Meow", Executors.newFixedThreadPool(1)).whenComplete(new BiConsumer<String, Throwable>() {
             @Override
             public void accept(String string, Throwable throwable) {
                 ChannelHandlerContext#writeAndFlush(string);
             }
});
```

**Comment by praveens4all** [comment] 2020-07-13 16:36
Thank you Very much @hyperxpro 
lot  of improvement with performance. i can see 32 (messages per second) compare to 15 (messages per second) earlier with 100 thread pool even i made 150 threads count no difference..seems netty boss single thread (i/o) supports maximum..is there any other place i can change to improve...my expectation is 50 messages per second.

**Comment by hyperxpro** [comment] 2020-07-13 16:39
Without looking at code and understanding what you doing, it's impossible for me to suggest something.

**Comment by praveens4all** [comment] 2020-07-13 16:40
business logic I am calling third party service for appending response ( which is taking 0.40 milliseconds)..not much logic just passing request for service and appending response.

**Comment by hyperxpro** [comment] 2020-07-13 16:43
Boss Threads: NUMBER OF CPU THREADS / 2
Worker Threads: NUMBER OF CPU THREADS x 2

**Comment by praveens4all** [comment] 2020-07-13 16:44
my current config,
bossGroup = new EpollEventLoopGroup(4, Executors.newCachedThreadPool());
  workerGroup = new EpollEventLoopGroup(12, Executors.newCachedThreadPool());

**Comment by hyperxpro** [comment] 2020-07-13 16:45
bossGroup = new EpollEventLoopGroup(4);
workerGroup = new EpollEventLoopGroup(12);

**Comment by hyperxpro** [comment] 2020-07-13 16:46
> my current config,
> bossGroup = new EpollEventLoopGroup(4, Executors.newCachedThreadPool());
> workerGroup = new EpollEventLoopGroup(12, Executors.newCachedThreadPool());

Try this:
bossGroup = new EpollEventLoopGroup(4);
workerGroup = new EpollEventLoopGroup(12);

**Comment by praveens4all** [comment] 2020-07-13 16:49
still same single boss thread doing read/write..

as per netty documentation listening port tightly couple with boss thread..am listening 8080 port so single thread serving even though 4 boss threads created

https://netty.io/wiki/new-and-noteworthy-in-5.0.html

In Netty 4.x each EventLoop is tightly coupled with a fixed thread that executes all I/O events of its registered Channels and any tasks submitted to it.

Starting with version 5.0 an EventLoop does no longer use threads directly but instead makes use of an Executor abstraction. That is, it takes an Executor object as a parameter in its constructor and instead of polling for I/O events in an endless loop each iteration is now a task that is submitted to this Executor.

**Comment by hyperxpro** [comment] 2020-07-13 16:53
What do you mean by 32 messages per second? Is Netty only receiving 32 HTTP messages per second?

**Comment by praveens4all** [comment] 2020-07-13 16:57
> What do you mean by 32 messages per second? Is Netty only receiving 32 HTTP messages per second?

I am using dynatrace to monitor TPS (transactions per second) - its TCP messages processing 32 per second.

**Comment by hyperxpro** [comment] 2020-07-13 16:59
You have a problem with your code. Netty is doing its job as expected.

**Comment by hyperxpro** [comment] 2020-07-13 17:00
Maybe I can help if you contact me via email because I don't feel this is the right place to discuss about something which is not a Netty issue.

**Comment by praveens4all** [comment] 2020-07-13 17:02
sure, please provide me email. Thanks.

**Comment by hyperxpro** [comment] 2020-07-13 17:02
Check my profile.

**Closed by hyperxpro** 2020-07-13 17:02 UTC
