### ISSUE TITLE
heap memory still an issue - buffer not releasing memory.

### ISSUE THREAD

**Issue by praveens4all** [netty/netty#10310] opened 2020-05-20 21:20 UTC
my application - netty server needs to run continuously with out closing client connection and keep serving messages 24/7. 

#https://github.com/netty/netty/issues/10252#issue-613256739
Thank you for reply @amizurov  @normanmaurer 

if i try 
public class Handler extends ChannelInboundHandlerAdapter {
 @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
//process msg
 **ChannelFuture future = ctx.writeAndFlush(nmm);
                      future.addListener(ChannelFutureListener.CLOSE);**
}

I use following lines then clears buffer/memory but 

 **ChannelFuture future = ctx.writeAndFlush(nmm);
                      future.addListener(ChannelFutureListener.CLOSE);** 

closing client connection  but my requirement is server and client always connected with out filling my buffer memory.

Please help.

**Comment by praveens4all** [comment] 2020-05-20 21:24
![Capture](https://user-images.githubusercontent.com/19388738/82498924-10ed3b80-9af1-11ea-9656-9ab0f0e05fc9.JPG)

**Comment by hyperxpro** [comment] 2020-05-21 10:37
`ChannelFutureListener.CLOSE` is indeed for closing client connection. You should use `PooledByteBufAllocator` if you don't want GC to handle buffers.

**Comment by praveens4all** [comment] 2020-05-21 13:20
> `ChannelFutureListener.CLOSE` is indeed for closing client connection. You should use `PooledByteBufAllocator` if you don't want GC to handle buffers.

Thank you for reply, i am using PooledByteBufAllocator still my old generation G1 old memory keeps growing.

![image](https://user-images.githubusercontent.com/19388738/82563049-a252c100-9b76-11ea-98ef-3d574e022c68.png)

**Comment by hyperxpro** [comment] 2020-05-21 13:25
Can you show debug logs of Netty?

**Comment by amizurov** [comment] 2020-05-21 15:59
Also could you please provide your pipeline and handler where you process messages.

**Comment by praveens4all** [comment] 2020-05-21 16:22
Please find my server class looks like :

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_SINGLETON)
@Slf4j
public class Server {

  
    @Autowired
    private Handler handler;

    @Autowired
    private Encoder encoder;

    private EventLoopGroup bossGroup;
    private EventLoopGroup workerGroup;
    private EventExecutorGroup group;

    private Collection<Channel> channels;

    public void start() throws InterruptedException {

        bossGroup = new NioEventLoopGroup(8, Executors.newCachedThreadPool());
        workerGroup = new NioEventLoopGroup(500, Executors.newCachedThreadPool());

        // ===========================================================
        // 1. define a separate thread pool to execute handlers with
        //    slow business logic. e.g database operation
        // ===========================================================
         group = new DefaultEventExecutorGroup(500); //thread pool of 500
        try {
            ServerBootstrap bootstrap = new ServerBootstrap();
            bootstrap.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        public void initChannel(SocketChannel ch)
                                throws Exception {
                            ch.pipeline().addLast("decoder", new Decoder())
                                    .addLast("encoder", encoder)
                                    .addLast(group, handler);

                        }
                    }).option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .option(ChannelOption.SO_BACKLOG, 128)
                    .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .childOption(ChannelOption.TCP_NODELAY, true)
                    .childOption(ChannelOption.SO_KEEPALIVE, true);

           

            List<Integer> ports = Arrays.asList(8080,8081,8082,8083);
             channels = new ArrayList<>(ports.size());
            for (int port : ports) {
                Channel serverChannel = bootstrap.bind(port).sync().channel();
                channels.add(serverChannel);
            }


        } catch (Exception ex) {
            log.error("Error binding server to server socket, possibly already in use. {}", ex);
            group.shutdownGracefully();
            workerGroup.shutdownGracefully();
            bossGroup.shutdownGracefully();
            for (Channel ch : channels) {
                ch.closeFuture().sync();
            }
        }
    }


    @PreDestroy
    public void shutdown() throws InterruptedException {
        if (Objects.nonNull(group)) {
            group.shutdownGracefully();
        }
        if (Objects.nonNull(workerGroup)) {
            workerGroup.shutdownGracefully();
        }
        if (Objects.nonNull(bossGroup)) {
            bossGroup.shutdownGracefully();
        }
        if (!CollectionUtils.isEmpty(channels)) {
            for (Channel ch : channels) {
                ch.closeFuture().sync();
            }
        }
    }

and my vm argumnets for netty :
-Dio.netty.noUnsafe=true
-Dio.netty.noKeySetOptimization=true
-Dio.netty.recycler.maxCapacityPerThread=0
-Dio.netty.allocator.numHeapArenas=0
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+AlwaysPreTouch
-XX:MaxDirectMemorySize=4096m
-Xms8G
-Xmx8G
-XX:+UseStringDeduplication
-XX:+UseG1GC 

My Grabage collection young generation space doing well, but old generation space keep increasing...

also still need to improve performance of application even i am increasing threads still not improving much..

**Comment by praveens4all** [comment] 2020-05-25 10:36
Any update pls ..still am facing memory issue - out of memory if we process high volumes of messages without disconnecting client.

**Comment by hyperxpro** [comment] 2020-05-25 10:46
The problem is in GC itself. I should not say problem but that's how old GC works. Different GCs have different ways of cleaning.

**Comment by praveens4all** [comment] 2020-05-25 10:57
> The problem is in GC itself. I should not say problem but that's how old GC works. Different GCs have different ways of cleaning.

Thanks for reply, I have tried concurrent-mark-sweep and now busy testing G1. same issue.

If i disconnect client from netty server (network listner close) clearing memory but we cant disconnect - messages processing all the time.

**Comment by hyperxpro** [comment] 2020-05-25 11:02
Try `System.gc();`

**Comment by praveens4all** [comment] 2020-05-25 11:11
> Try `System.gc();`

ok, pls advise what time of operation  i should call this? meaning Handler, Encoder classes finally blocks ? And importantly netty still holding buffer thread - i think that wont help releasing memory...i will try and update.

**Comment by hyperxpro** [comment] 2020-05-25 11:13
First, see if `System.gc();` works. You can call it whenever you feel now you need to free up memory. `System.gc();` doesn't guarantee successful garbage collection but if you call it, it'll look for objects which are ready to be collected. So call when you've processed X amount of objects.

Many people argue calling `System.gc();` is bad but in my opinion, call it whenever you really feel the need.

**Comment by SplotyCode** [comment] 2020-05-25 11:42
A System.gc() might help in specific cases to reduce the memory but it should NEVER prevent OutOfMemoryErrors. OutOfMemoryErrors is the last thing the JVM throws meaning it tried all thinks to get free memory (Including full GC event).

How do you know that the problem is caused by Netty btw? 
I believe you should make a memory snapshot (heap dump) and analyze witch Classes have the most instances. You can add -XX:+HeapDumpOnOutOfMemoryError to get a heap dump on OutOfMemory or use jmap to get the heap dump of a running VM. You will get a hprof file that you can analyze with many free applications.

**Comment by yuanrw** [comment] 2020-05-25 11:49
> A System.gc() might help in specific cases to reduce the memory but it should NEVER prevent OutOfMemoryErrors. OutOfMemoryErrors is the last thing the JVM throws meaning it tried all thinks to get free memory (Including full GC event).
> 
> How do you know that the problem is caused by Netty btw?
> I believe you should make a memory snapshot (heap dump) and analyze witch Classes have the most instances. You can add -XX:+HeapDumpOnOutOfMemoryError to get a heap dump on OutOfMemory or use jmap to get the heap dump of a running VM. You will get a hprof file that you can analyze with many free applications.

Agree. Also could you check your log to see if there is memory leak? @praveens4all

**Comment by praveens4all** [comment] 2020-05-25 11:56
if i add below statement after message processed (ctx.writeAndFlush()) method.
ChannelFuture future = ctx.writeAndFlush(nmm);
future.addListener(ChannelFutureListener.CLOSE);
memory looks fine and performance also good. 

But my requirement i should not close client connection (client is external system)

**Comment by hyperxpro** [comment] 2020-05-25 12:20
WWWWWWHHHHHHHYYYYYYYYYYYYYYYYY you using `future.addListener(ChannelFutureListener.CLOSE);` when YYYYYYYYOOOOOOOOUUUUUUUUU don't want to close connection?

**Comment by zhenjunMa** [comment] 2020-05-26 02:38
To summarize:

@praveens4all 's problem is when only call
```
ChannelFuture future = ctx.writeAndFlush(nmm)
```
the JVM heap size will be growing by time，maybe lead to OOM?

but when change the code to
```
ChannelFuture future = ctx.writeAndFlush(nmm)
future.addListener(ChannelFutureListener.CLOSE);
```
the JVM heap size will be fine.

this seems very tricky,  so  as @SplotyCode says,  dump the heap snapshot or
when it growing just call 
```
jmap -histo:live PID
```
see which Class have the most instances

**Comment by praveens4all** [comment] 2020-05-26 07:13
> WWWWWWHHHHHHHYYYYYYYYYYYYYYYYY you using `future.addListener(ChannelFutureListener.CLOSE);` when YYYYYYYYOOOOOOOOUUUUUUUUU don't want to close connection?

I was explaining scenario, i am not using it.

**Comment by praveens4all** [comment] 2020-05-26 07:16
if i use System.gc() worst performance, please find monitor tool below,

![image](https://user-images.githubusercontent.com/19388738/82871231-87df6580-9f31-11ea-9279-184d8698cb78.png)

**Comment by hyperxpro** [comment] 2020-05-26 07:21
I hope you're not calling `System.gc();` after writing every message.

**Comment by praveens4all** [comment] 2020-05-26 07:52
> I hope you're not calling `System.gc();` after writing every message.

i did called after message. my observation is no change in garbage collection. IF that works i thought of changing that.

**Comment by praveens4all** [comment] 2020-05-26 07:53
> To summarize:
> 
> @praveens4all 's problem is when only call
> 
> ```
> ChannelFuture future = ctx.writeAndFlush(nmm)
> ```
> 
> the JVM heap size will be growing by time，maybe lead to OOM?
> 
> but when change the code to
> 
> ```
> ChannelFuture future = ctx.writeAndFlush(nmm)
> future.addListener(ChannelFutureListener.CLOSE);
> ```
> 
> the JVM heap size will be fine.
> 
> this seems very tricky, so as @SplotyCode says, dump the heap snapshot or
> when it growing just call
> 
> ```
> jmap -histo:live PID
> ```
> 
> see which Class have the most instances

trying this option lets see

**Comment by normanmaurer** [comment] 2020-06-08 08:34
Let me close this for now and you can reopen if the problem still exist and add more debug info

**Closed by normanmaurer** 2020-06-08 08:34 UTC
