### ISSUE TITLE
Application fails to fetch dependencies for offline builds (mvn dependency:go-offline) due to ${os.detected.name}-${os.detected.arch} not resolved

### ISSUE THREAD

**Issue by avodonosov** [netty/netty#10829] opened 2020-11-28 14:14 UTC
### Expected behavior
Applications that depend on netty should be able to use maven-dependency-plugin go-offline operation to fetch all dependencies for offline builds

### Actual behavior

The below error happens (mvn -X flag is used to include also the maven stack trace):

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project redisson: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project redisson: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.plugins.dependency.resolvers.GoOfflineMojo.doExecute(GoOfflineMojo.java:88)
	at org.apache.maven.plugins.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:144)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.shared.transfer.dependencies.resolve.internal.Maven31DependencyResolverException: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:251)
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:90)
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.DefaultDependencyResolver.resolveDependencies(DefaultDependencyResolver.java:85)
	at org.apache.maven.plugins.dependency.resolvers.GoOfflineMojo.resolveDependableCoordinate(GoOfflineMojo.java:125)
	at org.apache.maven.plugins.dependency.resolvers.GoOfflineMojo.resolveDependencyArtifacts(GoOfflineMojo.java:112)
	at org.apache.maven.plugins.dependency.resolvers.GoOfflineMojo.doExecute(GoOfflineMojo.java:68)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.shared.transfer.dependencies.resolve.internal.Maven31DependencyResolver.resolveDependencies(Maven31DependencyResolver.java:227)
	... 28 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 29 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.54.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 31 more
```
### Steps to reproduce
```shell
git clone https://github.com/redisson/redisson.git
cd redisson
 # to be sure we speak of the same version:
git checkout 2a507699c3208e6856b6fb0f67a8b921718f7945
mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
```
### Netty version
4.1.54.Final

### JVM version (e.g. `java -version`)
Linux hostname 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### OS version (e.g. `uname -a`)
Linux hostname 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment] 2020-11-30 21:21
I use Maven 3.6.3 and this works for me on the latest `4.1` branch.

**Comment by avodonosov** [comment] 2020-12-06 23:06
@chrisvest , redisson [uses](https://github.com/redisson/redisson/blob/b12cf1bd7732aae06287b1398ea46f2436e62694/pom.xml#L131) version 4.1.54.Final.

Note that I run go-offline on on netty itself, but on an application that uses netty - redisson.

Fails for me with maven 3.6.3 (and on 3.3.9 the same way).

I don't know if that netty's fault, maven-dependency-plugin fault or os-maven-plugin fault.

**Comment by chrisvest** [comment] 2020-12-07 10:20
@avodonosov I just checked out redisson and ran `mvn clean install -DskipTests && mvn dependency:go-offline` with Java 8 and Maven 3.6.3, and it worked. However, if I override the version of the dependency plugin as in the reproducer steps, then it fails. So it turns out I'm getting a different version of the dependency plug-in by default: `org.apache.maven.plugins:maven-dependency-plugin:2.8:go-offline`. And that version is being resolved from the redisson-parent POM file: `[DEBUG] Resolved plugin prefix dependency to org.apache.maven.plugins:maven-dependency-plugin from POM org.redisson:redisson-parent:pom:3.14.1-SNAPSHOT`.

So I'm thinking the dependency-plugin should be investigated first.

**Comment by normanmaurer** [comment] 2020-12-18 09:50
LEt me close this for now

**Closed by normanmaurer** 2020-12-18 09:50 UTC
