### ISSUE TITLE
Choose better defaults for the properties related with memory consumption

### ISSUE THREAD

**Issue by trustin** [netty/netty#4146] opened 2015-08-27 02:48 UTC
Netty seems to choose the default values of the properties related with memory consumption too aggressively/greedly, according to the recent reports related with `Recycler`. (See: https://github.com/netty/netty/issues/4134#issuecomment-135205920) Perhaps it's time to choose a better default? /cc @tea-dragon

**Comment by ninja-** [comment] 2015-08-27 02:53
first things first... why are the settings _ignored_?

**Comment by trustin** [comment] 2015-08-27 03:01
@ninja- We would have fixed it already if we knew why. :-) It takes time because the devs cannot reproduce the problem. We all run Netty in production and didn't have such a problem. It means a certain usage pattern is triggering this. I'm not necessarily saying it's a bug in your code, though.

**Comment by ninja-** [comment] 2015-08-27 03:05
@trustin I would just disable this pooling, if I could.

**Comment by trustin** [comment] 2015-08-27 03:11
@ninja- I believe we can add that option, too. See #4147.

**Comment by ninja-** [comment] 2015-08-27 03:14
@trustin what I am observing now on  a testing server is that ~ every bot leaks a io.netty.channel.ChannelOutboundBuffer$Entry + buffer combo per second...maybe _this time_ it's unrelated to the Recycler, but netty leak detector would notify if it was a logic error inside the app...

**Comment by ninja-** [comment] 2015-08-27 03:53
@trustin hm could that be my fault this time unfortunately blamed on the recycler instead + netty leak detector being unhelpful :(
wasn't Channel#write supposed to be decrease reference count after writing the packet?

**Comment by ninja-** [comment] 2015-08-27 04:24
@trustin what's the proper way to enable netty's debug mode I can't find a way? what useful data I can get for you? it seems really really use to reproduce but I don't want to waste your time trying to run Minecraft

**Comment by trustin** [comment] 2015-08-27 05:12
@ninja- My daughter is a Minecraft fan, and I played it with her every day during her summer vacation, although it was PS Vita version. How easy is it to set it up and reproduce with a single player?

**Comment by normanmaurer** [comment] 2015-08-27 05:33
@trustin ha i see a possible first contribution from a little girl coming ;)

**Comment by ninja-** [comment] 2015-08-27 05:51
@trustin 

The testcaste for the OutboundBuffer$Entry problem consists of:
- a bungeecord instance
- any local minecraft server so the proxy can connect to something
- a snakebot which creates bots, and the bots are following your movements
- a minecraft client _just to join the snakbot port_
- a script that monitors instancesof $Entry via jmap -histo:live

**Comment by ninja-** [comment] 2015-08-27 16:24
@trustin my problem was that my recycler settings were ignored...I looked up the property on _master_ and it's different on 4.0. I guess it should work correctly now.

Maybe we can discuss ideas for a new Recycler backend which isn't exactly fixed size?
For example: recycle() would only recycle the object if there are ~ 0 recycled objects, otherwise ignore. Something like that. wdyt?

**Comment by tea-dragon** [comment] 2015-08-28 21:42
it's been a while since I tinkered with these, and that was probably on an older version than the one I'm using now -- which is in turn only 4.0.28. It might be fair to interpret those as signs in their favor though since "tinkering" usually means "fixing something causing problems". Anyway, here are (probably at least most) of the system properties currently used in prod (along with their original comments):

        ## lots of processes use netty buffers now, so set them here
        # max number of thread-locally cached buffers per power of 2 up to 512
        # default is 512, which seems kind of high (although not having 600 frame
        # reader threads helps the most). The cached space is less of an issue than
        # the overhead for all the little entries
        io.netty.allocator.tinyCacheSize: 32
        # same deal for powers of 2 up to the page size (8192), defaults to 256
        io.netty.allocator.smallCacheSize: 32
        # same deal for powers of 2 up to the maximum cachable size (32K), defaults to 64
        io.netty.allocator.normalCacheSize: 32
        # this is the thread-local caching control for non-buffers; mostly only an issue due to some blind-write cases
        io.netty.recycler.maxCapacity.default: 512

**Comment by ninja-** [comment] 2015-08-28 21:54
@tea-dragon that looks useful. does it also limit PoolSubpage by any chance?

**Comment by tea-dragon** [comment] 2015-08-28 22:36
possibly indirectly. They work well enough for my purposes, but as you can see, they might be a little conservative for a program that primarily does netty biz. For instance, in some cases, i'm just using the buffer pooling to do disk i/o.

**Comment by ninja-** [comment] 2015-09-04 17:25
@trustin I analyzed the topic to give you some better defaults. My conclusion is that something like 32-512 per thread would be really fine as a default even for some weird http apps. Additionally you could implement my idea about tracking the "balance" of recycled and used objects.

**Comment by daschl** [comment] 2016-04-27 05:26
Putting this in here since it got bumped a few times: Looks like we hit this or a similar issue in a Couchbase Java SDK deployment as well. Looks like the capacity was "ignored" and the recycler grew out of bounds. Disabling the recycler fixed the issue (workaround `
-Dcom.couchbase.client.deps.io.netty.recycler.maxCapacity=0`).

**Comment by normanmaurer** [comment] 2016-04-27 06:24
Which version?

**Comment by daschl** [comment] 2016-04-27 06:31
A slightly older version of the Java SDK which depends on netty 4.0.32

**Comment by daschl** [comment] 2016-05-03 13:38
@normanmaurer any idea what that can be?

**Comment by ninja-** [comment] 2016-05-03 13:44
@daschl that seems like normmal behaviour unless your APP started crashing ?

**Comment by daschl** [comment] 2016-05-03 13:47
@ninja- I wouldn't consider it normal behaviour if the "maxCapacity" setting is ignored and it just keeps growing and growing?

**Comment by normanmaurer** [comment] 2016-05-03 14:23
@daschl so only `maxCapacity = 0` helped ?

**Comment by daschl** [comment] 2016-05-03 14:24
yes, the customer applied that as a workaround and the issue vanished.

**Comment by normanmaurer** [comment] 2016-05-03 14:24
Ok will have a look .

**Comment by normanmaurer** [comment] 2017-02-28 14:09
I will close this as we did a lot of work there. @daschl if you still see issues please reopen

**Closed by normanmaurer** 2017-02-28 14:09 UTC
Labels: improvement

**Comment by daschl** [comment] 2017-02-28 14:41
@normanmaurer sounds good, currently we run "stable" - if I'll see issues again I'll reopen with more info
