### ISSUE TITLE
【偶现】服务器多次重启后客户端的FixedChannelPool有概率卡死

### ISSUE THREAD

**Issue by LinHuiG** [netty/netty#12648] opened 2022-07-27 02:30 UTC
使用FixedChannelPool.acquire()获取channel链接卡死
将服务端多次重启（几十次）后，出现每次获取链接必然报java.util.concurrent.TimeoutException: Acquire operation took longer then configured maximum time，即使此时服务端已经恢复正常。
若将FixChannelPool的超时行为设置为FixedChannelPool.AcquireTimeoutAction.NEW，则多次重启后不再报上面错误，而是每次acquire后必然要等待到超时时间后才能获取到channel。

怀疑：服务端多次重启后，客户端的acquire或者addListener出现异常，导致无法进入listenser释放该channel，此时该acquire操作给FixChannelPool的acquiredChannelCount加的1永远也无法消除，由于该连接池数量被设置为1，后续所有acquire请求都将超时

FixChannelPool创建代码：
FixedChannelPool fixedChannelPool = new FixedChannelPool(bootstrap.remoteAddress(new InetSocketAddress(ip, port)),
                        connChannelPoolHandler,
                        ChannelHealthChecker.ACTIVE,
                        FixedChannelPool.AcquireTimeoutAction.FAIL,
                        3000,
                        1,
                        1024
                );

连接获取代码：
        CompletableFuture<Channel> f = new CompletableFuture<>();
        channelPool.acquire().addListener(future -> {
            if (!future.isSuccess()) {
                f.completeExceptionally(future.cause());
                return;
            }
            Channel channel = (Channel) future.get();
            try {
                if (channel.isActive() && channel.isWritable()) {
                    f.complete(channel);
                } else {
                    f.completeExceptionally(new RuntimeException("链接不可用"));
                }
            } catch (Throwable e) {
                f.completeExceptionally(e);
            } finally {
                channelPool.release(channel);
                System.out.println();
            }
        });
        try {
            Channel channel = f.get(5, TimeUnit.SECONDS);
            if (channel != null && channel.isOpen() && channel.isActive()) {
                return channel;
            }
            return null;
        } catch (Throwable e) {return null;}

**Comment by LinHuiG** [comment] 2022-07-27 02:31
该问题与https://github.com/netty/netty/issues/10224 可能有关联

**Comment by hyperxpro** [comment] 2022-07-27 17:07
English please.

**Comment by chrisvest** [comment] 2022-07-27 17:23
Are you really using Netty 4.1.6? That version is very old. I recommend upgrading to the latest version, and then call `asStage()` on the netty future, instead of creating your own completable future.

**Comment by LinHuiG** [comment] 2022-07-28 00:47
> English please.

I use FixedChannelPool in client，when server restart  scores of times ，FixedChannelPool.acquire will cause "java.util.concurrent.TimeoutException: Acquire operation took longer then configured maximum time",even though server has been restored.
if we set FixedChannelPool.AcquireTimeoutAction.NEW, after restart server  scores of times ,FixedChannelPool.acquire  wont cause ' Acquire operation took longer then......',but we have to wait time out to get channel .
Once the above phenomenon is triggered, it will continue to trigger until restart client.

**Comment by LinHuiG** [comment] 2022-07-28 00:49
> Are you really using Netty 4.1.6? That version is very old. I recommend upgrading to the latest version, and then call `asStage()` on the netty future, instead of creating your own completable future.

let me try ，the  latest stable version is 4.1.80.Final？

**Comment by LinHuiG** [comment] 2022-07-28 01:31
> asStage



> Are you really using Netty 4.1.6? That version is very old. I recommend upgrading to the latest version, and then call `asStage()` on the netty future, instead of creating your own completable future.

how to call asStage() ,could u give me a demo ,i cant find this method

**Comment by hyperxpro** [comment] 2022-07-28 05:38
> > asStage
> 
> > Are you really using Netty 4.1.6? That version is very old. I recommend upgrading to the latest version, and then call `asStage()` on the netty future, instead of creating your own completable future.
> 
> how to call asStage() ,could u give me a demo ,i cant find this method

`asStage` is a Netty 5 feature.

**Comment by LinHuiG** [comment] 2022-07-28 05:55
> > > asStage
> > 
> > 
> > > Are you really using Netty 4.1.6? That version is very old. I recommend upgrading to the latest version, and then call `asStage()` on the netty future, instead of creating your own completable future.
> > 
> > 
> > how to call asStage() ,could u give me a demo ,i cant find this method
> 
> `asStage` is a Netty 5 feature.

ok，i update version to 4.1.79.Final now，netty5 not for the moment，is there anything wrong with the above method of getting channel

**Comment by jackwurj** [comment] 2022-08-15 21:53
后来查出直接原因了吗？

**Comment by LinHuiG** [comment] 2022-08-21 08:44
> 后来查出直接原因了吗？

没查出来，不过我们升级到4.1.79.Final后暂时没有再遇到类似问题了。

**Comment by LinHuiG** [comment] 2022-08-21 08:48
> 后来查出直接原因了吗？

旧版本还有另一个地方，使用bootstrap.connect(ip, port).sync().await().sync().channel()这行代码重连服务端，在服务端频繁重启，客户端频繁重连的时候也有概率直接卡死，怀疑可能和这个问题有点关联。

**Comment by chrisvest** [comment] 2022-10-28 18:47
Sounds like the problem is not showing up after a version upgrade. Closing.

**Closed by chrisvest** 2022-10-28 18:47 UTC
