### ISSUE TITLE
bytebuf reference count bug?

### ISSUE THREAD

**Issue by wenweihu86** [netty/netty#8474] opened 2018-11-07 11:16 UTC
### Expected behavior
    private int addComponent0(boolean increaseWriterIndex, int cIndex, ByteBuf buffer) {
        assert buffer != null;
        boolean wasAdded = false;
        try {
            checkComponentIndex(cIndex);

            int readableBytes = buffer.readableBytes();

            // No need to consolidate - just add a component to the list.
            @SuppressWarnings("deprecation")
            Component c = new Component(buffer.order(ByteOrder.BIG_ENDIAN).slice());
            if (cIndex == components.size()) {
                wasAdded = components.add(c);
                if (cIndex == 0) {
                    c.endOffset = readableBytes;
                } else {
                    Component prev = components.get(cIndex - 1);
                    c.offset = prev.endOffset;
                    c.endOffset = c.offset + readableBytes;
                }
            } else {
                components.add(cIndex, c);
                wasAdded = true;
                if (readableBytes != 0) {
                    updateComponentOffsets(cIndex);
                }
            }
            if (increaseWriterIndex) {
                writerIndex(writerIndex() + buffer.readableBytes());
            }
            return cIndex;
        } finally {
            if (!wasAdded) {
                buffer.release();
            }
        }
    }

### Actual behavior
executed this line "buffer.release();"
### Steps to reproduce
called  "Unpooled.wrappedBuffer(headerBuf, metaBuf);"
### Netty version
4.1.30.Final

**Comment by normanmaurer** [comment] 2018-11-07 11:17
@wenweihu86 can you please add a unit test that shows the problem ?

**Comment by wenweihu86** [comment] 2018-11-07 12:55
@normanmaurer unit test can not recurrent the problem.
it has very small probability to happen under large pressure test.

**Comment by normanmaurer** [comment] 2018-11-07 12:57
@wenweihu86 then you will need to give me more details... I dont understand what the problem is.

**Comment by wenweihu86** [comment] 2018-11-08 02:06
my code is as following:
ByteBuf outBuf = Unpooled.wrappedBuffer(headerBuf, metaBuf, bodyBuf);
ctx.channel.writeAndFlush(outBuf);

and then it throws exception at this line:
CompositeByteBuf.java:285

the exception is 
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

**Comment by njhill** [comment] 2018-11-08 05:34
@wenweihu86 could you provide a bit more detail than that.. specifically
- how are headerBuf, metaBuf, bodyBuf created, do more than one of them derive from a common buffer?
- are any of them or any buffer they are derived from used in any way after being wrapped?
- a more complete stacktrace of the exception

**Comment by wenweihu86** [comment] 2018-11-08 06:09
@njhill headerBuf, metaBuf, bodyBuf is created as following:
ByteBuf headerBuf = Unpooled.buffer(12);
ByteBuf metaBuf = Unpooled.wrappedBuffer(new byte[128]);
ByteBuf bodyBuf = Unpooled.wrappedBuffer(new byte[256]);
ByteBuf outBuf = Unpooled.wrappedBuffer(headerBuf, metaBuf, bodyBuf);
ctx.channel.writeAndFlush(outBuf);

outBuf may be send multi times when need to retry rpc request.
originally, i forgot to retain the outBuf; 
latterly, I have retain the outBuf when send outBuf repeatedly.
I confused why it throws IllegalReferenceCountException at the following line code:
if (!wasAdded) {
    buffer.release();
}

**Comment by njhill** [comment] 2018-11-08 06:32
@wenweihu86 so it sounds like you found the source of the issue and have now resolved it (writing multiple times without retaining), is that correct?

> I confused why it throws IllegalReferenceCountException at the following line code

I can't see how that could happen given the code example you provided. It is likely you are referring to some different code where you wrap the same buffer(s) more than once without retaining them first.

**Comment by wenweihu86** [comment] 2018-11-08 07:33
@njhill Yes, I have solved the problem.
But I just don't know why it crashed at that line, maybe as your said reason.

**Comment by normanmaurer** [comment] 2018-11-08 07:40
closing

**Closed by normanmaurer** 2018-11-08 07:40 UTC
