### ISSUE TITLE
Building 4.0 branch failures in SniHandlerTest.testServerNameParsing:113

### ISSUE THREAD

**Issue by garydgregory** [netty/netty#5971] opened 2016-11-02 17:36 UTC
Building the 4.0 branch with:
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: E:\Java\apache-maven-3.2.5
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_79\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```
I get:

```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.003 sec - in io.netty.handler.ssl.OpenSslClientContextTest
Running io.netty.handler.ssl.JdkSslEngineTest
10:32:58.829 [nioEventLoopGroup-9-1] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.io.netty.buffer.ByteBufMatcher
10:32:58.847 [nioEventLoopGroup-9-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
10:32:58.855 [nioEventLoopGroup-8-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xd6fffb30, L:/10.18.99.172:65375 - R:/10.18.99.172:65376] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:32:58.856 [nioEventLoopGroup-9-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xcd1ed556, L:/10.18.99.172:65376 - R:/0:0:0:0:0:0:0:0:65375] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:32:59.316 [nioEventLoopGroup-12-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
10:32:59.323 [nioEventLoopGroup-11-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xb6e7c2ae, L:/10.18.99.172:65473 - R:/10.18.99.172:65474] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:32:59.324 [nioEventLoopGroup-12-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x1f3bb978, L:/10.18.99.172:65474 - R:/0:0:0:0:0:0:0:0:65473] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:32:59.746 [nioEventLoopGroup-15-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
10:32:59.753 [nioEventLoopGroup-14-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xb03490c3, L:/10.18.99.172:1066 - R:/10.18.99.172:1067] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:32:59.754 [nioEventLoopGroup-15-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x5c5ae3da, L:/10.18.99.172:1067 - R:/0:0:0:0:0:0:0:0:1066] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:00.182 [nioEventLoopGroup-23-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xdb53888d, L:/127.0.0.1:1365 - R:/127.0.0.1:1366] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:00.185 [nioEventLoopGroup-24-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xd49f62ce, L:/127.0.0.1:1366 - R:/127.0.0.1:1365] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:00.254 [nioEventLoopGroup-26-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x2a03d9e1, L:/10.18.99.172:1431 - R:/10.18.99.172:1464] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:00.342 [main] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
10:33:00.421 [main] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1336)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:519)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:796)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:764)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        ... 16 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:203)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1703)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:281)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1527)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:841)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:839)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1273)
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1123)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1008)
        ... 18 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:283)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:138)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
        ... 26 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 32 more
10:33:00.841 [nioEventLoopGroup-35-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xcc289654, L:/127.0.0.1:1807 - R:/127.0.0.1:1808] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:01.005 [nioEventLoopGroup-36-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x89389384, L:/127.0.0.1:1808 - R:/127.0.0.1:1807] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:01.080 [nioEventLoopGroup-38-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
10:33:01.086 [nioEventLoopGroup-37-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x11c088bf, L:/10.18.99.172:1811 - R:/10.18.99.172:1814] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:01.087 [nioEventLoopGroup-38-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x060f60d9, L:/10.18.99.172:1814 - R:/0:0:0:0:0:0:0:0:1811] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:01.093 [nioEventLoopGroup-38-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
10:33:01.100 [nioEventLoopGroup-37-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x11c088bf, L:/10.18.99.172:1811 - R:/10.18.99.172:1814] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
10:33:01.101 [nioEventLoopGroup-38-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x060f60d9, L:/10.18.99.172:1814 - R:/0:0:0:0:0:0:0:0:1811] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
Tests run: 19, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 1.493 sec - in io.netty.handler.ssl.JdkSslEngineTest

Results :

Failed tests:
  SniHandlerTest.testServerNameParsing:113
Expected: is <true>
     but: was <false>

Tests run: 93, Failures: 1, Errors: 0, Skipped: 21

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Netty .............................................. SUCCESS [ 17.167 s]
[INFO] Netty/Common ....................................... SUCCESS [ 50.901 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 44.086 s]
[INFO] Netty/Transport .................................... SUCCESS [01:10 min]
[INFO] Netty/Codec ........................................ SUCCESS [ 17.127 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  7.133 s]
[INFO] Netty/Handler ...................................... FAILURE [ 30.584 s]
[INFO] Netty/Codec/HTTP ................................... SKIPPED
[INFO] Netty/Codec/Socks .................................. SKIPPED
[INFO] Netty/Transport/RXTX ............................... SKIPPED
[INFO] Netty/Transport/SCTP ............................... SKIPPED
[INFO] Netty/Transport/UDT ................................ SKIPPED
[INFO] Netty/Example ...................................... SKIPPED
[INFO] Netty/Testsuite .................................... SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:59 min
[INFO] Finished at: 2016-11-02T10:33:01-07:00
[INFO] Final Memory: 66M/1418M
[INFO] ------------------------------------------------------------------------
```
Same with Java 8:
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: E:\Java\apache-maven-3.2.5
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_101\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
Wed 11/02/2016 10:42:55.39
```

**Comment by normanmaurer** [comment] 2016-11-02 18:14
@Scottmitch I think you were working on this... Any update ?

**Comment by Scottmitch** [comment] 2016-11-04 16:16
I got pulled onto other items. The behavior between OpenSslEngine and JdkSslEngine is not consistent, and I was investigating the cause of this. IIRC one was was related to generating an alert while the other was not.

**Comment by normanmaurer** [comment] 2016-11-09 08:56
@garydgregory @Scottmitch working on a fix

**Comment by normanmaurer** [comment] 2016-11-16 07:07
Fixed by https://github.com/netty/netty/pull/6011

**Closed by normanmaurer** 2016-11-16 07:07 UTC
