### ISSUE TITLE
NettyClientWorkerThread cpu 100%

### ISSUE THREAD

**Issue by hxnan** [netty/netty#11956] opened 2021-12-25 11:15 UTC
# issue
It 's a strange issue.
Tomcat application run normally A few hours until 3 NettyClientWorkerThread use 100% cpu.
jstack is bellow. there is no memeory error, but PooledByteBuf.deallocate action seems not work correctly.

I reserve 1G memory for netty direct memory, keep watching whether there is improvement.

Any idea will be helpful, thankyou.

# jstack
```
"NettyClientWorkerThread_2" #15648 prio=5 os_prio=0 tid=0x0000ffff78104000 nid=0x67ef runnable [0x0000fffe4d1fb000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.poll(BaseMpscLinkedArrayQueue.java:340)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.poll(MpscChunkedArrayQueue.java:43)
	at io.netty.util.Recycler$LocalPool.claim(Recycler.java:262)
	at io.netty.util.Recycler.get(Recycler.java:158)
	at io.netty.util.internal.ObjectPool$RecyclerObjectPool.get(ObjectPool.java:84)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.newEntry(PoolThreadCache.java:454)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.add(PoolThreadCache.java:358)
	at io.netty.buffer.PoolThreadCache.add(PoolThreadCache.java:187)
	at io.netty.buffer.PoolArena.free(PoolArena.java:227)
	at io.netty.buffer.PooledByteBuf.deallocate(PooledByteBuf.java:171)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```
### Netty version
netty-all 4.1.72.Final

### JVM version (e.g. `java -version`)
openjdk 1.8.0_212

### OS version
docker container 4C 4G
centos 7

**Comment by normanmaurer** [comment] 2021-12-27 09:39
hmm this might be a jctools bug. /cc @nitsanw .

@hxnan so can you confirm it basically is "busy spin" here and never return from the `claim` method ?

**Comment by normanmaurer** [comment] 2021-12-27 09:41
@hxnan also it seems the version you are using is not `4.1.47.Final`. Beside this the JDK version you are using is super old. Please try to upgrade and see if it helps.

**Comment by franz1981** [comment] 2021-12-27 10:03
I suggest to:
- upgrade latest Netty version
- use a different method to collect stack traces eg java mission control or async profiler

I see that docker is used: how many cores and memory are dedicated to netty JVM?

Having 100% CPU cycle spent on that spin loop can happen if:
- out of memory has happened while allocating a new chunk and the consumer think there's some more element to consume that's never been set 
- there's few cpu cycles available and producer and consumer compete for it 

In both cases the previous question related memory/CPU dedicated to the JVM is key to determine the cause

**Comment by normanmaurer** [comment] 2021-12-27 10:06
> Having 100% CPU cycle spent on that spin loop can happen if:
> 
> * out of memory has happened while allocating a new chunk and the consumer think there's some more element to consume while the producer has failed to set it
> * there's few cpu cycles available and producer and consumer compete for it

@franz1981 I agree... I wonder if we maybe should also "limit" the number of loops we want to do in this case. Here we could just not return a recycled object.

**Comment by franz1981** [comment] 2021-12-27 10:10
I have taken another look at the queue code and 
> Having 100% CPU cycle spent on that spin loop can happen if:
- out of memory has happened while allocating a new chunk and the consumer think there's some more element to consume while the producer has failed to set it 

Is not correct, given that I have been the one fixing that bug on JCTools :P so out of memory is not an issue, but lack of CPU time to the docker container, yep

**Comment by franz1981** [comment] 2021-12-27 10:12
@normanmaurer 

We can use relaxed poll instead of poll if the available cores are just 1 but sadly with docker you risk to have N cores with very few real available CPU cycles

**Comment by franz1981** [comment] 2021-12-27 10:20
@chrisvest and probably this loop can change as well
https://github.com/netty/netty/blob/d5faba2fbeb7da65daa0a10f41560f47443c1026/common/src/main/java/io/netty/util/Recycler.java#L263
If we cannot find any in the queue and no available we can just move on, making it wait free?

To make it a but more container-friendly wdyt?

**Comment by hxnan** [comment] 2021-12-28 07:48
> > Having 100% CPU cycle spent on that spin loop can happen if:
> > 
> > * out of memory has happened while allocating a new chunk and the consumer think there's some more element to consume while the producer has failed to set it
> > * there's few cpu cycles available and producer and consumer compete for it
> 
> @franz1981 I agree... I wonder if we maybe should also "limit" the number of loops we want to do in this case. Here we could just not return a recycled object.

# UPDATE

I corrceting the netty verion (netty-4.1.72) and jdk(1.8.0_212) version.
It is an enterprise application, difficult to upgrade the jdk version.

There are 4 cores in container.
Three thead(NettyClientWorkerThread) keeping use (98% ~ 100%) cpu, all send data action is fail.
One thread do other things.

I did not reproduce the issue in test environment with stress testing,
I have no idea about the cause, but one thing can be sure,  out of memory is not the cause, `PlatformDependent.usedDirectMemory()` show the direct memeory usage is stable，a few increase only, and there is no memory exception log.

**Comment by normanmaurer** [comment] 2021-12-28 09:57
@hxnan is this x86 or arm machine ?

**Comment by nitsanw** [comment] 2021-12-28 10:40
Hi :-)

 @franz1981 :
> use a different method to collect stack traces eg java mission control or async profiler

If the application is indeed stuck at the stack described, `jstack` should be OK. The line in question is in `poll` : 
```
        final long offset = modifiedCalcCircularRefElementOffset(index, mask);
        Object e = lvRefElement(buffer, offset);
        if (e == null)
        {
            if (index != lvProducerIndex())
            {
                // poll() == null iff queue is empty, null element is not strong enough indicator, so we must
                // check the producer index. If the queue is indeed not empty we spin until element is
                // visible.
                do
                {
                    e = lvRefElement(buffer, offset); 
                }
                while (e == null); // <---- We're stuck here, line 340.
            }
            else
            {
                return null;
            }
        }
```
This would imply a fault in producer code where the `pIndex` has moved and no element was made visible in the queue. We have tests covering these paths, and this is a very well used part of JCTools. But concurrent code is hard to reason about, so there might be a bug in here somewhere. I've re-read the code, but can't see anything. I've also re-run the tests for longer concurrency periods and with a queue setup matching the Netty defaults for the pool, but can't reproduce the issue so far.

Alternatively, there might be an issue here with JDK. JCTools has been known to trigger JDK concurrency bugs in older versions, and you are on a 2 year old JDK here. I will run our tests with the version above and see if I can reproduce.

**Comment by nitsanw** [comment] 2021-12-28 11:32
I'm testing on Zulu 8u212, macOS, running with 60 producer threads and hitting the tests for 100 seconds. I can't reproduce the issue. @hxnan It would be good if you could provide a reproducer for us to debug.

**Comment by franz1981** [comment] 2021-12-28 11:33
@nitsanw I see a case where it could happen, but tbh it involves and out of memory to happen while adding a new chunk, due to the fix I have added to handle OOM some time ago: 
- producer detect a new chunk is needed and set parity bit
- consumer check producer index != consumer index
- OOM on producer while resizing (before setting JUMP) makes the producer to rollback the parity bit change
- consumer is stucked forever awaiting the JUMP element to be set 

The user reported no OOM but tbh, beside JDK bugs on concurrency primitives I don't see how cases that can make it happens

**Comment by nitsanw** [comment] 2021-12-28 11:40
@franz1981 good catch! This is worth considering a fix for

**Comment by franz1981** [comment] 2021-12-28 12:13
Thanks @nitsanw, so considered they got 3/4 cores 100% busy on application code, having just a single core left for both compiler and GC threads sounds a recipe for OOM...
I think they should better check if oom is happening, because I see they regularly check for Netty pool used Memory that's more related to direct memory exhaustion not heap one

**Comment by franz1981** [comment] 2021-12-28 12:54
@hxnan can you please check if out of memory isn't happening? You can easily check by adding a JVM option to exit on oom. If you have an option to restart the container it shouldn't be a problem.

https://github.com/netty/netty/blob/d5faba2fbeb7da65daa0a10f41560f47443c1026/common/src/main/java/io/netty/util/Recycler.java#L65 has introduced a system property  to

**Comment by hxnan** [comment] 2021-12-29 03:45
> @hxnan can you please check if out of memory isn't happening? You can easily check by adding a JVM option to exit on oom. If you have an option to restart the container it shouldn't be a problem.
> 
> https://github.com/netty/netty/blob/d5faba2fbeb7da65daa0a10f41560f47443c1026/common/src/main/java/io/netty/util/Recycler.java#L65
> 
> has introduced a system property to set the chunk size of the JCtools queue used on the recycler and if it's changed to be high enough, the recycler won't allocate new chunks, but reuse the existing one over and over, making the issue on OOM I have mentioned less likely to happen; this can be a potential workaround while awaiting a fix to land (although I strongly discourage keep running any Java application after a OOM).

It is  arm machine.
I will set `-Dio.netty.recycler.chunkSize=73400320 ` and try.
70MB should be enough.

**Comment by franz1981** [comment] 2021-12-29 07:37
I would try with something much smaller (eg 1024*128 or 1024*1024) because that's the capacity of a single chunk used a the linked list made of arrays, hence the memory footprint is way higher then 70MB.
Anyway, this change become relevant just if the issue was caused by a OutOfMemory: did you find any?

**Comment by franz1981** [comment] 2021-12-29 07:40
@nitsanw 

> It is arm machine

So maybe *it is* a JDK bug on concurrency primitives or in our code. 
Maybe in putOrdered/lazySet? I don't have any arm to try it sadly

**Comment by martin-g** [comment] 2021-12-29 12:46
You can use Oracle Cloud. They provide Linux ARM64 VMs for free!
You can use my [article](https://martin-grigorov.medium.com/github-actions-arm64-runner-on-oracle-cloud-a77cdf7a325a) as a guide, just skip the Github Actions related stuff.

**Comment by nitsanw** [comment] 2021-12-29 13:43
I'll have a go at reproducing on an ARM setup with the tests we have.

**Comment by hxnan** [comment] 2021-12-30 01:11
> 

Awesome!  
So set -Dio.netty.recycler.chunkSize to a bigger value is a valid workaround？
Or upgrade to a  specified version ？

**Comment by franz1981** [comment] 2021-12-30 01:41
@hxnan 
> Anyway, this change become relevant just if the issue was caused by a OutOfMemory: did you find any?

Depends by this: did you see an OutOfMemoryError in your application?

**Comment by nitsanw** [comment] 2021-12-30 16:17
The issue does not reproduce in tests AFAICT.
Tested with Zulu build for macOS/arm 8u302, and on Ubuntu with Zulu build for Linux/arm 8u212.

**Comment by hxnan** [comment] 2022-01-05 01:44
We work around this issue by set the netty version to 4.1.69.Final.
The issue not happned until now.

**Comment by franz1981** [comment] 2022-01-05 08:57
@chrisvest maybe the issue is on the new recycler code? Or...the issue is triggered by the interaction between the new recycler and JCTools queue; the easier way to find it out would be:
- reproduce it
- opt-out JCTools queue in the recycler code with some sys prop (probably running with no unsafe will work the same) and see that happen

**Comment by chrisvest** [comment] 2022-01-05 20:44
@franz1981 sounds like only @hxnan has been able to observe the problem, so the opt-out will have to be included in a release, unless @hxnan is fine with deploying a snapshot version.

**Comment by chrisvest** [comment] 2022-01-05 21:45
@franz1981 @hxnan See https://github.com/netty/netty/pull/11972

**Comment by franz1981** [comment] 2022-01-05 22:16
I have re-read the whole issue and the phrase that ring some bell on my brain is
> run normally A few hours

So, assuming JIT get hot much before that it doesn't seems something related the JVM itself really

@hxnan you said jstack report 
https://github.com/netty/netty/blob/d5faba2fbeb7da65daa0a10f41560f47443c1026/common/src/main/java/io/netty/util/Recycler.java#L262 but maybe the issue is that the loop on 
https://github.com/netty/netty/blob/d5faba2fbeb7da65daa0a10f41560f47443c1026/common/src/main/java/io/netty/util/Recycler.java#L263 has accumulated a long backlog of not available to claim handles, causing many polls in a row to happen, is it possible @chrisvest ?
This would cause jstack to report poll and specifically the element consumption on the queue as the most relevant/costy method called, because it causes a cache miss while reading the next element to be consumed.

**Comment by chrisvest** [comment] 2022-01-05 22:45
The `availableToClaim()` and `toAvailable()` methods are sanity checks that guards for the same handle somehow ending up in the queue multiple times, and from being claimed multiple times. So `availableToClaim()` should always return `true` for any non-null handle.
The queues are also bounded by a max capacity, which is 4096 by default, and it should be possible to loop through that quite quickly, and not look like a persistent busy-spin except on very small time scales.

**Comment by normanmaurer** [comment] 2022-01-07 09:18
A workaround was merged via https://github.com/netty/netty/pull/11972. That said I still suspect its a JDK bug which would be fixed by upgrading your JDK @hxnan

**Closed** 2022-01-07 09:18 UTC

**Comment by johnyannj** [comment] 2022-06-10 02:31
@normanmaurer  #11972  not resovle this problem。 and netty 4.1.69 is ok

**Comment by chrisvest** [comment] 2022-06-10 17:10
@johnyannj What does the debug logging say about `io.netty.recycler.blocking`?

**Comment by johnyannj** [comment] 2022-07-04 02:15
Sorry， I cant get it now。

It is recommended to reopen the current issue because the issue has not been resolved.

**Comment by hxnan** [comment] 2024-04-26 02:57
> > 
> 
> Awesome! So set -Dio.netty.recycler.chunkSize to a bigger value is a valid workaround？ Or upgrade to a specified version ？

Set this env ： -Dio.netty.recycler.blocking=true ， it‘s work for me  when use the netty version >  4.1.68
