### ISSUE TITLE
ChannelOption.SO_REUSEADDR=true ,no effect

### ISSUE THREAD

**Issue by zzy444626905** [netty/netty#13379] opened 2023-05-11 09:35 UTC
java.net.BindException: Address already in use: bind when set ChannelOption.SO_REUSEADDR=true,it does not work

it can work on golang/windows

	cfg := net.ListenConfig{
		Control: func(network, address string, c syscall.RawConn) error {
			return c.Control(func(fd uintptr) {
				syscall.SetsockoptInt(syscall.Handle(int(fd)), syscall.SOL_SOCKET, syscall.SO_REUSEADDR, 1)
				syscall.SetsockoptInt(syscall.Handle(int(fd)), syscall.SOL_SOCKET, syscall.SO_REUSEPORT, 1)
			})
		},
	}

I plan to rewrite my code using the Go programming language.

**Comment by martinKindall** [comment] 2023-05-11 20:20
Please elaborate more, follow this format as example
https://github.com/netty/netty/issues/13378

**Comment by chrisvest** [comment] 2023-06-15 00:28
Duplicate of #13332

**Closed by chrisvest** 2023-06-15 00:28 UTC
