### ISSUE TITLE
Race condition in SslHandler

### ISSUE THREAD

**Issue by nickmbailey** [netty/netty#4705] opened 2016-01-13 22:13 UTC
Originally a thread on the mailing list: https://groups.google.com/forum/#!topic/netty/h2ulbfw3uF8

(using Netty 4.0.33, via jython 2.7.1)

I'm wondering if this is a race condition/bug within netty itself or perhaps just a misuse of netty. I'm seeing the following stack trace intermittently when dealing with ssl sockets via jython:

```
java.lang.NullPointerException
	at org.python.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:585)
	at org.python.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1405)
	at org.python.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:1443)
	at org.python.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:193)
	at org.python.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:179)
	at org.python.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:817)
	at org.python.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:260)
	at org.python.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:290)
	at org.python.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at org.python.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at org.python.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at org.python.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

You can ignore the 'org.python' prefix on the stack trace, thats just because it's running via Jython.

I did some code diving and it looks to me like this is a possible race condition between SslHandler and DefaultChannelPipeline. What I think is happening is this:

In jython, we create an SslHandler object. We then add that handler to our pipeline by calling addFirst:

https://github.com/netty/netty/blob/netty-4.0.33.Final/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L89

Eventually, that ends up calling callHandlerAdded:

https://github.com/netty/netty/blob/netty-4.0.33.Final/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L472

The behavior of callHandlerAdded depends on if you are in the event loop or not. If you are, it immediately calls 'handlerAdded' on the handler, and if not, it submits a task to a threadpool to that eventually calls handlerAdded. This is where I think the race condition is. SslHandler.handlerAdded(...) needs to be called *before* SslHandler.channelActive(...) is called. Otherwise, you will get the NPE I pasted above becase 'this.ctx' isn't set on the SslHandler object, that's done in the handlerAdded method.

**Comment by windie** [comment] 2016-01-13 22:53
Fixed in #4706

**Comment by jimbaker** [comment] 2016-01-13 23:30
Corresponding Jython bug: http://bugs.jython.org/issue2401 - we should be able to build shortly, then Nick can see if he reproduce in his environment

**Comment by nickmbailey** [comment] 2016-01-14 01:19
Can we also merge this into 4.0?

**Comment by normanmaurer** [comment] 2016-01-14 06:12
This will need a more general fix... Looking into it now.

As workaround you can add a task o the EventLoop that will actually add the handler to the pipeline

**Comment by normanmaurer** [comment] 2016-01-15 13:34
This is a big tricky... so may take some time.

**Comment by nickmbailey** [comment] 2016-01-15 15:33
So I applied the fix from #4706 by subclassing SslHandler and setting ctx in channelActive. That fixed the race condition for me and I don't see any other negative effects, at least so far. Would you recommend against actually utilizing that as a fix until it can be fixed more generally?

**Comment by normanmaurer** [comment] 2016-01-15 17:29
@nickmbailey could you try to use netty 4.1 and use this patch ? :

https://github.com/netty/netty/pull/4716

I hope this is a fundamental fix.

**Comment by nickmbailey** [comment] 2016-01-15 17:52
I'll have to set up another environment for reproducing the issue, but I'll try to get to that sometime today and verify the issue.

Since we need a fix in Jython and won't be able to upgrade netty to 4.1 in the immediate future, is the approach I described above relatively safe in your opinion?

**Comment by normanmaurer** [comment] 2016-01-15 17:54
It is a workaround and should work…

That said once I know it works I will backport the fix to 4.0 as well.

**Comment by nickmbailey** [comment] 2016-01-17 00:35
So since I'm hitting the error running through jython on 4.0.33, I can't easily test out this fix.. I tried switching out 4.0.33 with 4.1 but apparently there are big enough changes that it isn't a drop in replacement.

**Comment by normanmaurer** [comment] 2016-01-17 11:21
Can you share the project?

**Comment by slandelle** [comment] 2016-01-17 11:24
https://bitbucket.org/jython/jython/src

**Comment by slandelle** [comment] 2016-01-17 11:27
Jython seems to be using Netty: https://bitbucket.org/jython/jython/src/6855fa289d48cf741a3daed2a0bb9c9c87cdf07f/build.xml?at=default&fileviewer=file-view-default#build.xml-181:185

**Comment by nickmbailey** [comment] 2016-01-17 20:16
Yeah jython uses netty under the hood. I'm hitting the issue using jython, I have a script that reproduces the issue and I can provide that. I only see the issue on ubuntu 14.04 and not on OSX for whatever reason.

**Comment by nickmbailey** [comment] 2016-01-17 20:29
Here's the script I can reproduce with and an example run:

https://gist.github.com/nickmbailey/f80ad965a048c1d4df22

**Comment by normanmaurer** [comment] 2016-01-17 20:53
@nickmbailey thanks.. what are the setup steps for jython ?

**Comment by nickmbailey** [comment] 2016-01-17 20:58
There isn't any. You can download the jar from here: http://mvnrepository.com/artifact/org.python/jython-standalone/2.7.1b2

I commented on the gist with how to run that script, so once you download that jar and script, that should be all you need.

**Comment by normanmaurer** [comment] 2016-01-17 21:00
@nickmbailey got it... will check

**Comment by normanmaurer** [comment] 2016-01-24 18:48
@nickmbailey can you give me any pointers how I can use a custom netty jar with jython ?

**Comment by johnou** [comment] 2016-01-25 10:50
@nickmbailey @normanmaurer I assume adding it to the classpath first should be ok? Unfortunately I am still seeing issues with 27df0cc6945d43e20d6469ce2bf2fa3a9b8f61dd

[johno@habbo-dev-1 netty]$ git log --name-status HEAD^..HEAD
commit 27df0cc6945d43e20d6469ce2bf2fa3a9b8f61dd
Author: Norman Maurer <norman_maurer@apple.com>
Date:   Fri Jan 15 14:23:41 2016 +0100

    [#4705] Ensure ChannelHandler.handlerAdded(...) is always called as first method of the handler

    Motivation:

    If a user adds a ChannelHandler from outside the EventLoop it is possible to get into the situation that handlerAdded(...) is scheduled on the EventLoop and so called after another methods of the ChannelHandler as the EventLoop may a

    Modification:

    - Ensure we always check if the handlerAdded(...) method was called already and if not add the currently needed call to the EventLoop so it will be picked up after handlerAdded(...) was called. This works as if the handler is added t
    - Some cleanup in the DefaultChannelPipeline

    Result:

    Correctly order of method executions of ChannelHandler.

M       transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java
M       transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java

[johno@habbo-dev-1 netty]$ java -cp all/target/netty-all-4.1.0.CR1-SNAPSHOT.jar:jython-standalone-2.7.1b2.jar org.python.util.jython netty-ssl-bug.py
200 OK
0
200 OK
1
200 OK
2
200 OK
3
Traceback (most recent call last):
  File "netty-ssl-bug.py", line 4, in <module>
    conn.request("GET", "/")
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 1001, in request
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 1035, in _send_request
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 997, in endheaders
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 850, in _send_output
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 812, in send
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 1204, in connect
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/_socket.py", line 357, in handle_exception
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/_socket.py", line 357, in handle_exception
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/ssl.py", line 320, in wrap_socket
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/ssl.py", line 147, in __init__
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/ssl.py", line 196, in do_handshake
_socket.SSLError: [Errno 1] Unmapped exception: java.lang.NullPointerException
[johno@habbo-dev-1 netty]$ java -cp all/target/netty-all-4.1.0.CR1-SNAPSHOT.jar:jython-standalone-2.7.1b2.jar org.python.util.jython netty-ssl-bug.py
200 OK
0
200 OK
1
200 OK
2
200 OK
3
Traceback (most recent call last):
  File "netty-ssl-bug.py", line 4, in <module>
    conn.request("GET", "/")
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 1001, in request
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 1035, in _send_request
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 997, in endheaders
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 850, in _send_output
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 812, in send
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/httplib.py", line 1204, in connect
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/_socket.py", line 357, in handle_exception
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/_socket.py", line 357, in handle_exception
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/ssl.py", line 320, in wrap_socket
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/ssl.py", line 147, in __init__
  File "/home/johno/netty/jython-standalone-2.7.1b2.jar/Lib/ssl.py", line 196, in do_handshake
_socket.SSLError: [Errno 1] Illegal state exception

**Comment by normanmaurer** [comment] 2016-01-25 10:54
@johnou I don't think so as it seems like they shadow the netty version /cc @nickmbailey

**Comment by johnou** [comment] 2016-01-25 11:00
@normanmaurer ah I see what you mean, it's in the jar as io/netty and org/python/netty.

**Comment by johnou** [comment] 2016-01-25 11:42
@normanmaurer looking at their build.xml it's just an uber jar created with jarjar, I took the pipeline_race branch, built the artifacts, then I unzipped the all artifact then replaced all files in jython-standalone-2.7.1b2.jar with that, created a simple jarjar ant script to rewrite the package and then replaced all files in the jython jar with those, I can no longer reproduce the errors I pasted above (ran the script about 10 times).

```
[johno@habbo-dev-1 netty]$ unzip all/target/netty-all-4.1.0.CR1-SNAPSHOT.jar
[johno@habbo-dev-1 netty]$ zip -r jython-standalone-2.7.1b2.jar io
.. same with the shaded jar
```

```
<project name="MyProject" default="dist" basedir=".">
<target name="dist">
    <taskdef name="jarjar" classname="com.tonicsystems.jarjar.JarJarTask"
        classpath="jarjar-1.4.jar"/>
    <jarjar jarfile="netty-all-4.1.0.CR1-shaded.jar">
          <zipfileset src="netty-all-4.1.0.CR1-SNAPSHOT.jar" excludes="META-INF/**"/>
          <rule pattern="io.netty.**" result="org.python.netty.@1"/>
    </jarjar>
</target>
</project>
```

```
[johno@habbo-dev-1 netty]$ java -jar jython-standalone-2.7.1b2.jar netty-ssl-bug.py
200 OK
0
200 OK
1
200 OK
2
200 OK
3
200 OK
4
200 OK
5
200 OK
6
200 OK
7
200 OK
8
200 OK
9
200 OK
10
200 OK
11
200 OK
12
200 OK
13
200 OK
14
200 OK
15
200 OK
16
200 OK
17
200 OK
18
200 OK
19
```

**Comment by nickmbailey** [comment] 2016-01-25 16:44
Yeah, when I tried to run the pipeline branch previously I copied the updated netty jars into the jython checkout and updated build.xml to use those instead. I think the approach @johnou took should work as well.

**Comment by normanmaurer** [comment] 2016-01-26 10:26
@nickmbailey @johnou ok cool. Let me backport the change to 4.0 as well.

**Comment by johnou** [comment] 2016-01-26 15:10
@normanmaurer are you actively working on this? If not I have some time to backport your commit to 4.0.

**Comment by normanmaurer** [comment] 2016-01-26 15:13
Yep should have it done later today.

**Comment by johnou** [comment] 2016-01-26 15:16
![yourock](https://cloud.githubusercontent.com/assets/323497/12584518/266863d8-c448-11e5-9e76-932373ab5410.jpg)

**Comment by normanmaurer** [comment] 2016-01-28 13:42
Fixed

**Closed by normanmaurer** 2016-01-28 13:42 UTC
