### ISSUE TITLE
ArrayIndexOutOfBoundsException With PooledByteBufAllocator Recycler implementaion

### ISSUE THREAD

**Issue by patel-bhavik** [netty/netty#10821] opened 2020-11-24 23:44 UTC
### Issue Description

While trying to write an HttpMessage using HTTP1 with HttpClientCodec i.e HttpObjectEncoder, Netty is throwing an ArrayIndexOutOfBounds Exception while trying to allocate buffer for headers. Exception seems to be happening in the  PooledByteBufAllocator Recycler Implementation.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -841651488 out of bounds for length 256 
at io.netty.util.Recycler$Stack.pushNow(Recycler.java:666)  
at io.netty.util.Recycler$Stack.push(Recycler.java:642)  
at io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:236)  
at io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry.recycle(PoolThreadCache.java:482)     
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.allocate(PoolThreadCache.java:412)   
at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:187)  
at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:171)  
at io.netty.buffer.PoolArena.allocate(PoolArena.java:189)    
at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)  
at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)  
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)    
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)  
at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)  
at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:93)  
at io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:189)  
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)     ... 111 more
```

A new buffer is being allocated in Encoder here - https://github.com/netty/netty/blob/ee3b9a5f7b1829e1095fdbbccb5490949ac3e94e/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L93. 

Recycler code triggering the exception - https://github.com/netty/netty/blob/ee3b9a5f7b1829e1095fdbbccb5490949ac3e94e/common/src/main/java/io/netty/util/Recycler.java#L666

Similar issue seen with Recycler in the past - https://github.com/netty/netty/issues/9608

### Netty version
4.1.51.Final

### JVM version
Java 11

### OS version
x86_64 GNU/Linux

**Comment by normanmaurer** [comment] 2020-11-25 09:36
Is this reproducible for you ?

**Comment by normanmaurer** [comment] 2020-11-25 14:22
Also I wonder if there was another exception before this as well .

**Comment by patel-bhavik** [comment] 2020-11-25 19:34
We are not able to reproduce this behavior. There was no other exception thrown before this.

**Comment by normanmaurer** [comment] 2020-12-27 09:46
I was not able to spot any bug yet :/

**Comment by rishika728** [comment] 2021-03-26 23:47
We saw this issue re-occur with the same exact stack trace. There were no other exceptions logged before this. @normanmaurer are you looking to see some specific exception messaging from a specific file ? Also what is the log level for that line ?

**Comment by normanmaurer** [comment] 2021-03-27 09:09
Just share whatever exception was logged

**Comment by chrisvest** [comment] 2021-11-26 09:43
Since we're suspecting the Recycler is at fault here, I'm going to close this because the Recycler has been rewritten for Netty 4.1.71.

**Closed by chrisvest** 2021-11-26 09:43 UTC

**Comment by EzajAnsari** [comment] 2021-11-28 06:48
@chrisvest I am facing similar issue while PooledByteBuAllocator while writing Http/2 request

Attaching the stack trace

java.lang.ArrayIndexOutOfBoundsException: Index 39 out of bounds for length 39
	at io.netty.buffer.PoolArena.findSubpagePoolHead(PoolArena.java:267) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolChunk.free(PoolChunk.java:453) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolChunkList.free(PoolChunkList.java:120) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:258) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.trim(PoolThreadCache.java:414) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:277) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:269) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:258) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:170) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:134) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:126) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:116) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeadersInternal(DefaultHttp2FrameWriter.java:515) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeaders(DefaultHttp2FrameWriter.java:260) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.sendHeaders(DefaultHttp2ConnectionEncoder.java:184) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:233) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:151) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:45) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.rt.jio.scp.http2.client.active.standby.ScpHttp2EgressActiveStandbyClientRequestHandler.write(ScpHttp2EgressActiveStandbyClientRequestHandler.java:118) [rtSDP_Run.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by atanu1991** [comment] 2021-12-09 00:48
@EzajAnsari Did this fix your issue?

@chrisvest When will 4.1.71 be released? I have been facing the exact issue as @EzajAnsari for a couple of months and its blocking a production rollout

```
java.lang.ArrayIndexOutOfBoundsException: 39, exiting...
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 39
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 39
at io.netty.buffer.PoolArena.findSubpagePoolHead(PoolArena.java:267)
at io.netty.buffer.PoolChunk.free(PoolChunk.java:453)
at io.netty.buffer.PoolChunkList.free(PoolChunkList.java:120)
at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:258)
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430)
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396)
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.trim(PoolThreadCache.java:414)
at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:277)
at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:269)
at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:258)
at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:170)
at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151)
at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2194)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1402)
at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1265)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1302)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
... 16 more
```

**Comment by normanmaurer** [comment] 2021-12-09 08:40
@atanu1991 today

**Comment by atanu1991** [comment] 2021-12-10 08:39
> @EzajAnsari Did this fix your issue?
> 
> @chrisvest When will 4.1.71 be released? I have been facing similar issue as @EzajAnsari for a couple of months and its blocking a production rollout. I am hoping [this](https://github.com/netty/netty/pull/11858) fixes the below issue too.
> 
> ```
> java.lang.ArrayIndexOutOfBoundsException: 39, exiting...
> io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 39
> at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
> at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
> at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
> at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
> at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 39
> at io.netty.buffer.PoolArena.findSubpagePoolHead(PoolArena.java:267)
> at io.netty.buffer.PoolChunk.free(PoolChunk.java:453)
> at io.netty.buffer.PoolChunkList.free(PoolChunkList.java:120)
> at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:258)
> at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430)
> at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396)
> at io.netty.buffer.PoolThreadCache$MemoryRegionCache.trim(PoolThreadCache.java:414)
> at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:277)
> at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:269)
> at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:258)
> at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:170)
> at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151)
> at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148)
> at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
> at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
> at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
> at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
> at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
> at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2194)
> at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1402)
> at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1265)
> at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1302)
> at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
> at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
> ... 16 more
> ```

@chrisvest The error seems to still exist with 4.1.71 version of Netty. Any clue why this could be happening? Why is the number 39 (ArrayIndexOutOfBoundsException) always fixed?

**Comment by normanmaurer** [comment] 2021-12-10 13:24
@atanu1991 can you give us a stacktrace with 4.1.71.Final in use ?

**Comment by chrisvest** [comment] 2021-12-10 13:26
@atanu1991 Also, if you could enable debug logging and collect the `-Dio.netty.allocator.*` lines, that would be helpful.

**Comment by atanu1991** [comment] 2021-12-11 02:16
@chrisvest  @normanmaurer 

This is the log from 4.1.71.Final

```
java.lang.ArrayIndexOutOfBoundsException: 39
at io.netty.buffer.PoolArena.findSubpagePoolHead(PoolArena.java:267)
at io.netty.buffer.PoolChunk.free(PoolChunk.java:458)
at io.netty.buffer.PoolChunkList.free(PoolChunkList.java:120)
at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:258)
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:430)
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:396)
at io.netty.buffer.PoolThreadCache$MemoryRegionCache.trim(PoolThreadCache.java:414)
at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:277)
at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:269)
at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:258)
at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:170)
at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151)
at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1031)
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:826)
at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:797)
at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:778)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204)
at io.netty.handler.flush.FlushConsolidationHandler.flushIfNeeded(FlushConsolidationHandler.java:197)
at io.netty.handler.flush.FlushConsolidationHandler.resetReadAndFlushIfNeeded(FlushConsolidationHandler.java:192)
at io.netty.handler.flush.FlushConsolidationHandler.channelReadComplete(FlushConsolidationHandler.java:145)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
at io.netty.handler.ssl.SslHandler.channelReadComplete0(SslHandler.java:1302)
at io.netty.handler.ssl.SslHandler.channelReadComplete(SslHandler.java:1291)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1415)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.lang.Thread.run(Thread.java:748)
```

For context we are using Netty from Apache Giraph: https://github.com/apache/giraph

I did start our service in debug mode but I dont see io.netty.allocator log lines. Is there some special command I need to pass?

**Comment by atanu1991** [comment] 2021-12-14 19:45
@chrisvest  @normanmaurer 

Any thoughts on this?

**Comment by normanmaurer** [comment] 2021-12-20 16:47
@atanu1991 dint have time yet. Are you able to share a reproducer ?

**Comment by chrisvest** [comment] 2021-12-20 22:53
https://github.com/netty/netty/pull/11939
