### ISSUE TITLE
java.net.SocketException Connection reset

### ISSUE THREAD

**Issue by scratchy** [netty/netty#12082] opened 2022-02-07 16:31 UTC
"java.net.SocketException Connection reset" is not handlet correctly inside of netty. 

Leading to thread crashes using [netty-4.1.72] (https://github.com/netty/netty/releases/tag/netty-4.1.72.Final)

```
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

```

**Comment by normanmaurer** [comment] 2022-02-07 16:33
All these exceptions are actually fired through the exception. So not sure what issue you have

**Comment by scratchy** [comment] 2022-02-07 16:44
Im registering crash handlers with Thread.UncaughtExceptionHandler. 

Nettys crashed thread is bouncing up to this handler. Looking at the code its obvious whats going on:

```
 return new Runnable() {
            @Override
            public void run() {
                setCurrentEventExecutor(eventExecutor);
                try {
                    command.run();
                } finally {
                    setCurrentEventExecutor(null);
                }
            }
        };
```

"command.run(); "

is not catching the exception thrown at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394), (bouncing through the whole netty framework)

which on the final stage leads to a crashed runnable. 

Not catching exceptions up to a thread dies is bad practice and should be fixed. Ether by 
`
               try {
                    command.run();
                } catch (java.net.SocketExceptione) {
                  System.out.println("dont let it crash!");
                }
                 finally {
                    setCurrentEventExecutor(null);
                }
`
or much earlier in the framework.

**Comment by normanmaurer** [comment] 2022-02-07 16:49
@scratchy we catch `Throwable` so not sure what exactly happens for you:

 
https://github.com/netty/netty/blob/netty-4.1.73.Final/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L151

**Comment by scratchy** [comment] 2022-02-07 17:02
In this case there must a different thread / lambda involved where read is going against.

As you can see on the stack:

io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)

its prob. executed in the NioByteUnsafe scope, which would not be catched on the other thread.

**Comment by normanmaurer** [comment] 2022-02-08 07:35
Can you provide a reproduce that I can run ?

**Comment by saschaarthur** [comment] 2022-02-08 07:55
happens a lot when you register 
a handler by using

Thread.setDefaultUncaughtExceptionHandler

like in the example above.

Im using it netty together with https://github.com/cdapio/netty-http
every couple of calls i get the crash inside of netty.

This should help you reproduce it.

**Comment by scratchy** [comment] 2022-02-08 07:57
happens a lot when you register 
a handler by using

Thread.setDefaultUncaughtExceptionHandler

like in the example above.

Im using netty together with https://github.com/cdapio/netty-http
every couple of calls i get the crash inside of netty.

This should help you reproduce it.

**Comment by normanmaurer** [comment] 2022-02-08 15:17
Will have a look

**Comment by Victorgreat4** [comment] 2022-03-31 11:27
Im having issues with the exact same problem on our tcp server, this connection reset problem:
https://i.stack.imgur.com/vRlCH.png

It can happen at anytime and very hard to reproduce, sometimes during the serverhandler part and sometimes even before the initation of decoderheader and tcpserverhandler inside the TCPserver class that holds the runTCP.
It started happening last week, never had any problems with this isse since 2021 - august, we have not changed the network code only data proccessing inside decoderheader.
Have you any new information about this?

**Comment by LV-223** [comment] 2022-04-01 10:07
We also sometimes have a similar problem for several months after moving to another hosting (but we are not sure if this could be the cause of the problem?), before that our application worked for two years without this error, we did not change anything in the code of our application. Help me catch what is the reason?

> java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Victorgreat4** [comment] 2022-04-01 11:32
> We use Netty for the websocket server and we also sometimes have a similar problem for several months after moving to another hosting (but we are not sure if this could be the cause of the problem?), before that our application worked for two years without this error, we did not change anything in the code of our application. Help me catch what is the reason?
> 
> > java.net.SocketException: Connection reset
> > at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
> > at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
> > at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
> > at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
> > at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
> > at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
> > at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> > at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> > at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> > at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> > at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> > at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> > at java.base/java.lang.Thread.run(Thread.java:833)

looks like we have the same issue, Do you remeber when this started happening to you? For me and my collegue we started getting this error 1-2 weeks ago at random. Also what other hosting are you using now instead?

**Comment by LV-223** [comment] 2022-04-01 11:38
> looks like we have the same issue, Do you remeber when this started happening to you? For me and my collegue we started getting this error 1-2 weeks ago at random. Also what other hosting are you using now instead?

now we are renting a virtual server from OVHcloud

**Comment by robinroos** [comment] 2022-06-06 08:49
I am getting the same issue when I run Glowroot Central (which uses Netty, but I don't know which version) inside an OpenShift platform.  OpenShift is Red Hat's container execution platform based on Kubernetes.  My Java version is 17.

```
2022-06-06 08:16:16.503 INFO  org.glowroot - Glowroot version: 0.14.0-beta.4-SNAPSHOT, built 2022-06-02 07:19:47 +0000
2022-06-06 08:16:16.506 INFO  org.glowroot - Java version: 17.0.2
...
2022-06-06 08:16:16.727 INFO  com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
...
2022-06-06 08:24:27.528 INFO  org.glowroot - gRPC listening on 0.0.0.0:8181
2022-06-06 08:24:27.820 INFO  org.glowroot - UI listening on 0.0.0.0:4000
2022-06-06 08:24:27.820 INFO  org.glowroot - startup complete
2022-06-06 08:25:19.214 WARN  org.glowroot.ui.HttpServerHandler - Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The "Connection reset" exception is then repeated once every minute (approx).

**Comment by chrisvest** [comment] 2022-06-07 00:30
@robinroos This is where Glowroot is logging that message: https://github.com/glowroot/glowroot/blob/main/ui/src/main/java/org/glowroot/ui/HttpServerHandler.java#L194-L200

It ends up there because exceptions from read IOs will be fired through the pipeline.

**Closed** 2022-06-07 00:45 UTC

**Comment by TajudeenBusari** [comment] 2025-03-23 07:13
I am having this issue: 
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[netty-buffer-4.1.117.Final.jar:4.1.117.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.117.Final.jar:4.1.117.Final]
 when i run my integration test class. Though the test is passing but it seems some connection are closing abruptly, like Redis instance
