### ISSUE TITLE
netty 4.1.0.Beta5 with Epoll Channel: accept() failed: Too many open files

### ISSUE THREAD

**Issue by bobwenx** [netty/netty#3911] opened 2015-06-24 03:35 UTC
In my environment, i build a TCP server base on netty(4.1.0.Beta5) and using native-epoll socket  transport. before last week, it works very well。
But after i increase system memory from 4GB -> 32GB at yesterday, the server repeating report IOException:
```java
10:45:27.776 [epollEventLoopGroup-2-3] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: accept() failed: Too many open files
	at io.netty.channel.epoll.Native.newIOException(Native.java:127) ~[netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.epoll.Native.accept(Native.java:570) ~[netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:101) ~[netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254) [netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703) [netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
``` 
the config of my OS:

```bash
# uname -a
Linux app1 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 256697
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 256697
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

# cat /proc/sys/fs/file-max
3265425

# sudo lsof | awk '$5 == "REG" {freq[$2]++ ; names[$2] = $1 ;} END {for (pid in freq) print freq[pid], names[pid], pid ; }' | sort -n -r -k 1,1
255 java 11098
110 java 11071
48 sudo 13885
48 puppetd 1646
47 nginx 1317
46 sudo 16605
46 sshd 25621
46 sshd 13867
46 sshd 13865
46 sshd 10633
45 nginx 1316
43 snmpd 1960
37 zabbix_ag 1344
37 zabbix_ag 1343
37 zabbix_ag 1342
37 zabbix_ag 1341
37 zabbix_ag 1340
37 zabbix_ag 1330
30 sshd 1268
19 nscd 1163
17 rsyslogd 1040
14 ntpd 1276
12 crond 1347
10 init 1
8 udevd 427
8 bash 25623
8 bash 13886
8 bash 13868
8 bash 10635
7 sort 16607
7 lsof 16608
7 gshelld 1406
7 awk 16606
6 udevd 1676
6 udevd 1675
6 lsof 16609
3 mingetty 1671
3 mingetty 1669
3 mingetty 1667
3 mingetty 1665
3 mingetty 1663
3 mingetty 1661
```

Right now, i switch socket transport from native-epoll to NIO, and it seems work fine.
How can i debug such problems? any advice and suggestions will be appreciated.

**Comment by normanmaurer** [comment] 2015-06-24 15:28
That's interesting and sounds like a bug. Could you provide a simple reproducer ?

**Comment by bobwenx** [comment] 2015-06-25 03:01
I will try to reproduce this on similar environment. If there is any progress, i will update it here.

**Comment by normanmaurer** [comment] 2015-06-25 08:23
@bobwenx could you try to use netty 4.1.0.Beta6-SNAPSHOT ? This may be fixed by:
https://github.com/netty/netty/commit/49643fb5b12fc8426cc8d5cf98adb55687961770

**Comment by bobwenx** [comment] 2015-06-26 09:25
i will try `4.1.0.Beta6-SNAPSHOT` at this weekend. If there is any progress, i will update it here.

**Comment by normanmaurer** [comment] 2015-06-26 09:28
Thanks!

**Comment by normanmaurer** [comment] 2015-06-30 10:10
@bobwenx any update ?

**Comment by bobwenx** [comment] 2015-06-30 11:29
Hi @normanmaurer, Sorry for the late reply :)

i already using `4.1.0.Beta6-SNAPSHOT` in my environment at last weekend, and right now, it works fine without problems!

```
# ls -al /proc/{pid}/fd/ | grep socket: | wc -l
8820
```

**Comment by normanmaurer** [comment] 2015-06-30 11:31
@bobwenx let us wait a few days and if it still looks good close this as fixed :) Will ping you again on the end of week.

**Comment by bobwenx** [comment] 2015-07-04 19:36
Hi @normanmaurer, right now, native-epoll transport works fine.

But i have another question about `OpenSslEngine.OpenSslSession`'s object life cycle.
In my server, i took a JVM heap dump during night, and at that moment, the server have about `4500+` TCP/SSL connection established. 
And the heap dump shows that channel-related objects exactly matched the count of established TCP connection.

![image](https://cloud.githubusercontent.com/assets/2533748/8509128/af06fa9a-22c4-11e5-82e4-03749eee3936.png)


Except for `OpenSslEngine.session`, which seems still lives after system GC.

![image](https://cloud.githubusercontent.com/assets/2533748/8509150/45d84ce4-22c5-11e5-9fe9-914650121723.png)

Are `OpenSslEngine.session` field using something like weak/soft reference or cache? 
And perhaps i missing some options/method to release the field?

[Here](https://dl.dropboxusercontent.com/u/89874741/memory.hprof.zip) is heap dump of my server. Thanks for helping out!

**Comment by normanmaurer** [comment] 2015-07-04 19:57
Thats interesting. Let me check the heap dump

**Comment by bobwenx** [comment] 2015-07-05 05:42
The init code of  `OpenSSLEngine`:
```java
SslContext sslContext = SslContextBuilder.forServer(certification.toFile(), keyFile.toFile(), keyPass)
                 .sslProvider(SslProvider.OPENSSL)
                 // avoid client makes multiple ssl handshake, jdk default: 0(unlimited), openssl default: 1024 * 20
                 .sessionCacheSize(1024 * 500)
                 // keep 12-hour to invalid cache, jdk default: 86400 (24 hours), openssl default: 300(sec)
                 .sessionTimeout(TimeUnit.HOURS.toSeconds(12))
                 .build();

     // ...
     // create SslHandler in init pipeline
     // sslContext.newHandler(pipeline.channel().alloc()))
```

Are `SSLContext.setSessionCacheSize(ctx, sessionCacheSize)` will enable object cache of  `OpenSslEngine.session`?

**Comment by normanmaurer** [comment] 2015-09-09 12:17
@bobwenx sorry this totally fell off my to do list :/ Do you still have problems and if so what are these exactly ?

**Comment by normanmaurer** [comment] 2016-01-05 18:30
Let me close this for now and please reopen if the issues still exists with latest 4.1.0 release.

**Closed by normanmaurer** 2016-01-05 18:30 UTC

**Comment by gl-works** [comment] 2016-01-08 11:10
I'm experiencing the same error with netty-all-4.1.0.Beta6.jar. The error stack is as follows

```
java.io.IOException: accept() failed: Too many open files
	at io.netty.channel.epoll.Native.newIOException(Native.java:130)
	at io.netty.channel.epoll.Native.accept(Native.java:577)
	at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:112)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:325)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:257)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

The error happens after about 4xxx connections have been established.

```
# lsof -p {pid} |wc
4275
```

The ulimit should be enough

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31221
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 32768
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Appreciate for any help!

**Comment by Scottmitch** [comment] 2016-01-09 02:17
@gl-works - can you try to reproduce with the latest snapshot off the 4.1 branch?

**Comment by gl-works** [comment] 2016-01-09 03:31
@Scottmitch Actually, I encounter exact the same error with latest beta (4.1.0.Beta8) version. I did switch to 4.1.0.Beta6 after reading previous comments. Unfortunately it didn't help anyway :(

**Comment by Scottmitch** [comment] 2016-01-20 04:45
@gi-works - What does `cat /proc/sys/fs/file-max` output? Can you try with `4.1.0.RC1-SNAPSHOT`? What state are most of the sockets in (netstat)? Can you provide a stack trace and heap dump?

**Comment by gl-works** [comment] 2016-02-14 09:39
@Scottmitch Thanks for you help. We finally found it was caused by OS fd limitation. The *ulimit* check didn't help because we started the process using 'systemctl' utility, which brought different fd limitation than *ulimit* check.

**Comment by Scottmitch** [comment] 2016-02-15 18:59
@gl-works - Thanks for the followup ... glad to hear you figured out the issue!
