### ISSUE TITLE
Netty 4.1.16.Final Could not initialize class io.netty.channel.epoll.Native

### ISSUE THREAD

**Issue by Delostik** [netty/netty#10537] opened 2020-09-07 06:01 UTC
I use brpc(a rpc framework) with netty 4.1.16.Final to create epoll event loop, but see following error:
```
Exception in thread "Thread-bat2-test" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81)
	at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:55)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)
	at com.baidu.brpc.thread.BrpcThreadPoolManager.createClientIoThreadPool(BrpcThreadPoolManager.java:75)
	at com.baidu.brpc.thread.BrpcThreadPoolManager.getOrCreateClientIoThreadPool(BrpcThreadPoolManager.java:50)
	at com.baidu.brpc.client.channel.BootstrapManager.createBooStrap(BootstrapManager.java:94)
	at com.baidu.brpc.client.channel.BootstrapManager.getOrCreateBootstrap(BootstrapManager.java:48)
	at com.baidu.brpc.client.channel.AbstractBrpcChannel.<init>(AbstractBrpcChannel.java:40)
	at com.baidu.brpc.client.channel.BrpcSingleChannel.<init>(BrpcSingleChannel.java:83)
	at com.baidu.brpc.client.channel.BrpcChannelFactory.createChannel(BrpcChannelFactory.java:12)
	at com.baidu.brpc.client.CommunicationClient.<init>(CommunicationClient.java:67)
	at com.baidu.brpc.client.InterceptCommunicationClient.<init>(InterceptCommunicationClient.java:22)
	at com.baidu.brpc.naming.NamingServiceProcessor.addInstance(NamingServiceProcessor.java:112)
	at com.baidu.brpc.naming.NamingServiceProcessor.addInstances(NamingServiceProcessor.java:102)
	at com.baidu.brpc.naming.NamingServiceProcessor.<init>(NamingServiceProcessor.java:59)
	at com.baidu.brpc.client.RpcClient.setServiceInterface(RpcClient.java:155)
	at com.baidu.brpc.client.BrpcProxy.getProxy(BrpcProxy.java:130)
	at com.baidu.brpc.client.BrpcProxy.getProxy(BrpcProxy.java:126)
	at com.test-project.ProxyClient.<init>(ProxyClient.java:49)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.Native
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)
	... 34 more
```

It seems that the shaded package was loaded but cannot load native library.
And I unpackage the jar
```
root@mytestenv:~# ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

root@mytestenv:~# ldd ./META-INF/native/libnetty_transport_native_epoll_x86_64.so
	linux-vdso.so.1 =>  (0x00007ffddd186000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7b59749000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7b5937f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7b59162000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7b59b5f000)
```

### Netty version
4.1.16.Final

### JVM version (e.g. `java -version`)
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### OS version (e.g. `uname -a`)
` Linux 1b97d8fc550b 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by hyperxpro** [comment] 2020-09-07 06:02
Try upgrading to `4.1.51.Final` and see if issue persists.

**Comment by Delostik** [comment] 2020-09-07 13:01
> Try upgrading to `4.1.51.Final` and see if issue persists.

Okay I will try later. But is there any way to make 4.1.16.Final available? I'm gonna provide an sdk, internal specification may not take effect.

**Comment by hyperxpro** [comment] 2020-09-07 14:35
Here is the error: `Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.Native`. Are all modules present?

**Comment by Delostik** [comment] 2020-09-11 06:00
> Here is the error: `Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.Native`. Are all modules present?

yes, libraries were found in the shaded jar

**Comment by normanmaurer** [comment] 2020-09-14 10:06
Please upgrade to latest netty release and provide all the error logs.

**Comment by normanmaurer** [comment] 2020-09-21 13:24
LEt me close this for now and please reopen if you still see issues after upgrading

**Closed by normanmaurer** 2020-09-21 13:24 UTC
