### ISSUE TITLE
Epoll native library does NOT load after upgrade between 4.1.39 and 4.1.40

### ISSUE THREAD

**Issue by ursaj** [netty/netty#9758] opened 2019-11-05 16:35 UTC
### Expected behavior

Native epoll support keeps working after upgrade.

### Actual behavior

Server apps fail on startup with the following stack trace:

    ...
	Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
		at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:80)
		at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:52)
		at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:142)
		at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
		at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
		at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
		at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
		at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
		at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
		at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
		at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)
		at com.db.abos.common.api.transport.netty.NettyOsFactory.newGroup(NettyOsFactory.java:66)
		at com.db.abos.common.api.transport.netty.ServerWebSocketFactory.<init>(ServerWebSocketFactory.java:91)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
		... 19 common frames omitted
	Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_643970988024581631659.so: /lib64/libc.so.6: version `GLIBC_2.12' not found (required by /tmp/libnetty_transport_native_epoll_x86_643970988024581631659.so)
		at java.lang.ClassLoader$NativeLibrary.load(Native Method)
		at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
		at java.lang.Runtime.load0(Runtime.java:810)
		at java.lang.System.load(System.java:1086)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:203)
		at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:228)
		at io.netty.channel.epoll.Native.<clinit>(Native.java:57)
		at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
		... 36 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_643970988024581631659.so: /lib64/libc.so.6: version `GLIBC_2.12' not found (required by /tmp/libnetty_transport_native_epoll_x86_643970988024581631659.so)
			at java.lang.ClassLoader$NativeLibrary.load(Native Method)
			at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
			at java.lang.Runtime.load0(Runtime.java:810)
			at java.lang.System.load(System.java:1086)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
			at java.security.AccessController.doPrivileged(Native Method)
			at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
			... 40 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 39 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:871)
				at java.lang.System.loadLibrary(System.java:1122)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
				... 40 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
			at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:231)
			... 38 common frames omitted
		Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
			... 39 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:871)
				at java.lang.System.loadLibrary(System.java:1122)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
				at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
				... 39 common frames omitted
				Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
					at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
					at java.lang.Runtime.loadLibrary0(Runtime.java:871)
					at java.lang.System.loadLibrary(System.java:1122)
					at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
					at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
					at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
					at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
					at java.lang.reflect.Method.invoke(Method.java:498)
					at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
					at java.security.AccessController.doPrivileged(Native Method)
					at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
					at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
					... 40 common frames omitted

### Steps to reproduce

    assertNull(Epoll.unavailabilityCause())

### Netty version

4.1.39 - epoll works
4.1.40 - epoll does NOT work

### JVM version (e.g. `java -version`)

    % java -version
    openjdk version "1.8.0_221"
    OpenJDK Runtime Environment (Zulu 8.39.0.8-SA-linux64) (build 1.8.0_221-b08)
    OpenJDK 64-Bit Server VM (Zulu 8.39.0.8-SA-linux64) (build 25.221-b08, mixed mode)

### OS version (e.g. `uname -a`)

    % uname -a
    Linux gmafxu43 3.0.101-108.98-default #1 SMP Mon Jul 15 13:58:06 UTC 2019 (262a94d) x86_64 x86_64 x86_64 GNU/Linux

	% cat /etc/os-release
	NAME="SLES"
	VERSION="11.4"
	VERSION_ID="11.4"
	PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
	ID="sles"
	ANSI_COLOR="0;32"
	CPE_NAME="cpe:/o:suse:sles:11:4"

**Comment by normanmaurer** [comment] 2019-11-05 16:56
What is the Linux distro and Version ?

**Comment by ursaj** [comment] 2019-11-05 20:41
Updated description

**Comment by carl-mastrangelo** [comment] 2019-11-06 01:17
Can you give the exact maven / gradle dependency you are using?    I think you need to depend on the os specific version.

**Comment by ursaj** [comment] 2019-11-06 09:27
% mvn --projects api\serverapi dependency:tree | grep netty | tee build.log
	5697 [BuilderThread 0] [INFO] |  +- io.netty:netty-transport:jar:4.1.43.Final:compile
	5698 [BuilderThread 0] [INFO] |  |  \- io.netty:netty-resolver:jar:4.1.43.Final:compile
	5698 [BuilderThread 0] [INFO] |  +- io.netty:netty-handler:jar:4.1.43.Final:compile
	5698 [BuilderThread 0] [INFO] |  |  \- io.netty:netty-codec:jar:4.1.43.Final:compile
	5699 [BuilderThread 0] [INFO] |  \- io.netty:netty-codec-http:jar:4.1.43.Final:compile
	5701 [BuilderThread 0] [INFO] |  \- ...:jar:SNAPSHOT:compile
	5701 [BuilderThread 0] [INFO] |     \- io.netty:netty-all:jar:4.1.43.Final:compile
	5705 [BuilderThread 0] [INFO] +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.43.Final:compile
	5706 [BuilderThread 0] [INFO] |  +- io.netty:netty-common:jar:4.1.43.Final:compile
	5706 [BuilderThread 0] [INFO] |  +- io.netty:netty-buffer:jar:4.1.43.Final:compile
	5707 [BuilderThread 0] [INFO] |  \- io.netty:netty-transport-native-unix-common:jar:4.1.43.Final:compile
	5707 [BuilderThread 0] [INFO] +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.7.Final:compile
	5723 [BuilderThread 0] [INFO] +- org.glassfish.jersey.containers:jersey-container-netty-http:jar:2.28:compile
	5724 [BuilderThread 0] [INFO] |  \- org.glassfish.jersey.connectors:jersey-netty-connector:jar:2.28:compile

**Comment by normanmaurer** [comment] 2019-11-06 09:34
@ursaj can you show me your libc version ?

**Comment by ursaj** [comment] 2019-11-06 18:18
sure, if you tell me, what should I be looking for. I'm not familiar with native libraries...

**Comment by normanmaurer** [comment] 2019-11-06 18:21
Just run ldd-v

**Comment by ursaj** [comment] 2019-11-06 22:40
% ldd -v /lib64/libc.so.6
			/lib64/ld-linux-x86-64.so.2 (0x00007f175f4c5000)
			linux-vdso.so.1 =>  (0x00007fff373d5000)

			Version information:
			/lib64/libc.so.6:
					ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
					ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2

**Comment by carl-mastrangelo** [comment] 2019-11-07 01:32
glibc 2.3 was released in 2002.  I think you need to upgrade.

**Comment by normanmaurer** [comment] 2019-11-07 07:38
@ursaj huh... 2.3 ? That is super strange and I don't think we changed anything in how we build stuff. Can you try to upgrade one version after the other and let me know in which version it exactly broke ?

**Comment by ursaj** [comment] 2019-11-07 11:15
Checker:

    package test;
    
    import io.netty.channel.epoll.Epoll;
    
    /**
     * Dependencies:<pre>
     *     io.netty:netty-transport-native-epoll:${project.version}:linux-x86_64
     * </pre>
     */
    public class NettyEpollChecker {
        public static void main(String[] args) {
            System.out.println("Epoll.isAvailable: " + Epoll.isAvailable());
            Throwable cause = Epoll.unavailabilityCause();
            if (cause != null) {
                cause.printStackTrace(System.out);
            }
        }
    }

Output:

	% java -jar netty-epoll-checker-4.1.39.Final.jar
	Epoll.isAvailable: true

	% java -jar netty-epoll-checker-4.1.40.Final.jar
	Epoll.isAvailable: false
	java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_641851005851198575174.so: /lib64/libc.so.6: version `GLIBC_2.12' not found (required by /tmp/libnetty_transport_native_epoll_x86_641851005851198575174.so)
			at java.lang.ClassLoader$NativeLibrary.load(Native Method)
			at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
			at java.lang.Runtime.load0(Runtime.java:810)
			at java.lang.System.load(System.java:1086)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:203)
			at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:218)
			at io.netty.channel.epoll.Native.<clinit>(Native.java:59)
			at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
			at test.NettyEpollChecker.main(NettyEpollChecker.java:12)
			Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_641851005851198575174.so: /lib64/libc.so.6: version `GLIBC_2.12' not found (required by /tmp/libnetty_transport_native_epoll_x86_641851005851198575174.so)
					at java.lang.ClassLoader$NativeLibrary.load(Native Method)
					at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
					at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
					at java.lang.Runtime.load0(Runtime.java:810)
					at java.lang.System.load(System.java:1086)
					at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
					at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
					at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
					at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
					at java.lang.reflect.Method.invoke(Method.java:498)
					at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
					at java.security.AccessController.doPrivileged(Native Method)
					at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
					at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
					... 5 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
					at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
					at java.lang.Runtime.loadLibrary0(Runtime.java:871)
					at java.lang.System.loadLibrary(System.java:1122)
					at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
					at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
					at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
					... 4 more
					Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
							at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
							at java.lang.Runtime.loadLibrary0(Runtime.java:871)
							at java.lang.System.loadLibrary(System.java:1122)
							at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
							at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
							at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
							at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
							at java.lang.reflect.Method.invoke(Method.java:498)
							at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
							at java.security.AccessController.doPrivileged(Native Method)
							at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
							at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
							... 5 more
			Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll
					at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
					at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:221)
					... 3 more
			Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so
					at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
					... 4 more
					Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
							at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
							at java.lang.Runtime.loadLibrary0(Runtime.java:871)
							at java.lang.System.loadLibrary(System.java:1122)
							at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
							at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
							at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
							... 4 more
							Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
									at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
									at java.lang.Runtime.loadLibrary0(Runtime.java:871)
									at java.lang.System.loadLibrary(System.java:1122)
									at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
									at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
									at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
									at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
									at java.lang.reflect.Method.invoke(Method.java:498)
									at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
									at java.security.AccessController.doPrivileged(Native Method)
									at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
									at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
									... 5 more

**Comment by normanmaurer** [comment] 2019-11-07 13:17
ok interesting... let me try to find out what changed

**Comment by normanmaurer** [comment] 2019-11-07 13:34
@ursaj can you paste the output of : `ldd --version` ?

**Comment by ursaj** [comment] 2019-11-07 23:25
% ldd --version
	ldd (GNU libc) 2.11.3
	Copyright (C) 2009 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	Written by Roland McGrath and Ulrich Drepper.

**Comment by normanmaurer** [comment] 2019-11-08 08:12
hmm that's super strange. We use centos 6 to compile our native epoll transport which uses `glibc. 2.12` since forever. I fail how there could be any difference :(

**Comment by ursaj** [comment] 2019-11-08 19:41
--- % ldd -v libnetty_transport_native_epoll_x86_64_4.1.39.so
	---         linux-vdso.so.1 =>  (0x00007ffd53dc5000)
	---         librt.so.1 => /lib64/librt.so.1 (0x00007fa7c037d000)
	---         libc.so.6 => /lib64/libc.so.6 (0x00007fa7bfffd000)
	---         libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa7bfddd000)
	---         /lib64/ld-linux-x86-64.so.2 (0x00007fa7c07a5000)
	+++ % ldd -v libnetty_transport_native_epoll_x86_64_4.1.40.so
	+++ ./libnetty_transport_native_epoll_x86_64_4.1.40.so: /lib64/libc.so.6: version `GLIBC_2.12' not found (required by ./libnetty_transport_native_epoll_x86_64_4.1.40.so)
	+++         linux-vdso.so.1 =>  (0x00007ffec3d8d000)
	+++         librt.so.1 => /lib64/librt.so.1 (0x00007fda30f85000)
	+++         libc.so.6 => /lib64/libc.so.6 (0x00007fda30c05000)
	+++         libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fda309e5000)
	+++         /lib64/ld-linux-x86-64.so.2 (0x00007fda313ad000)

				Version information:
	---         ./libnetty_transport_native_epoll_x86_64_4.1.39.so:
	+++         ./libnetty_transport_native_epoll_x86_64_4.1.40.so:
						librt.so.1 (GLIBC_2.2.5) => /lib64/librt.so.1
						libc.so.6 (GLIBC_2.8) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.10) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
	+++                 libc.so.6 (GLIBC_2.12) => not found
						libc.so.6 (GLIBC_2.5) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.9) => /lib64/libc.so.6
				/lib64/librt.so.1:
						ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
						libpthread.so.0 (GLIBC_PRIVATE) => /lib64/libpthread.so.0
						libpthread.so.0 (GLIBC_2.2.5) => /lib64/libpthread.so.0
						libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
						libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
				/lib64/libc.so.6:
						ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
						ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
				/lib64/libpthread.so.0:
						ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
						ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
						ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
						libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
						libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
						libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6

**Comment by ursaj** [comment] 2019-11-08 20:41
Maybe there are some logs from build, that could clarify this (new) dependency on GLIBC_2.12 ?

**Comment by ursaj** [comment] 2019-11-08 21:39
% strings /lib64/libc.so.6 | grep "^GLIBC_" | sort | uniq
	GLIBC_2.10
	GLIBC_2.11
	GLIBC_2.2.5
	GLIBC_2.2.6
	GLIBC_2.3
	GLIBC_2.3.2
	GLIBC_2.3.3
	GLIBC_2.3.4
	GLIBC_2.4
	GLIBC_2.5
	GLIBC_2.6
	GLIBC_2.7
	GLIBC_2.8
	GLIBC_2.9
	GLIBC_PRIVATE

**Comment by normanmaurer** [comment] 2019-11-22 07:52
@ursaj Let me try to build 4.1.39.Final on the docker image. That said I am pretty sure it is linked the same way.

**Comment by normanmaurer** [comment] 2019-11-22 13:30
Alright I know what the problem is and I think I have a fix :) Stay tuned.

**Comment by normanmaurer** [comment] 2019-11-22 13:39
@ursaj PTAL https://github.com/netty/netty/pull/9797

**Closed** 2019-11-23 20:12 UTC

**Comment by ursaj** [comment] 2019-11-25 02:17
@normanmaurer thanks a lot!
