### ISSUE TITLE
When auto read is false, SslHandler should invoke Channel.read() if whole encrypted packets are not coming yet.

### ISSUE THREAD

**Issue by hyangtack** [netty/netty#3529] opened 2015-03-24 05:56 UTC
Netty version: 4.0.26.Final (auto read option is false)

I'm using Netty as HTTP/SPDY file server. My server turns off auto read option in order to control incoming request traffic.

I found that sometimes the final handler's channelRead() method was not called even it called Channel.read() before. It's caused by the following codes, when the whole encrypted packets didn't coming yet. SslHandler consumed other handler's Channel.read() call, but it did not call the method again.

I found this problem more often when using FixedRecvByteBufAllocator of 8Kbytes than AdaptiveRecvByteBufAllocator. (FYI) 

        // If we calculated the length of the current SSL record before, use that information.
        if (packetLength > 0) {
            if (endOffset - startOffset < packetLength) {
                return;
            } else {
                offset += packetLength;
                totalLength = packetLength;
                packetLength = 0;
            }
        }

I think that SslHandler should invoke Channel.read() before returning its decode() method when the followings are met:
1. the channel is not set as auto read 
2. SslHandler didn't fire channelRead to the next handler during decoding. 

What do you think?

**Comment by trustin** [comment] 2015-03-25 07:52
That's interesting. We thought we address this issue in 4.0.26. (See `AbstractChannelHandlerContext.fireChannelReadComplete()` calls `ctx.read()` automatically to prevent the stall like you mentioned.)

Would you mind if I ask you to write a simple reproducer?  You could take a look at `SocketSslEchoTest` and write something similar.

**Comment by hyangtack** [comment] 2015-03-26 15:55
@trustin I read the codes you mentioned and found steps of this problem. 

1. SslHandler decodes packets and call next.fireChannelRead()
 - At this time, invokeNextChannelRead of SslHandler context is true, and invokePrevRead is false.

2. The next handler handles channelRead() and call Channel.read() before returning it.
 - At this time, invokePrevRead of SslHandler context becomes true.

3. SslHandler handles channelReadComplete().
 - At this time, the flags are changed to false by the following codes.

        if (invokedNextChannelRead ||  // The handler of this context produced a message, or
            !invokedThisChannelRead) { // it is not required to produce a message to trigger the event.

            invokedNextChannelRead = false;
            invokedPrevRead = false;

4. SslHandler handles channelRead(). But SslHandler cannot call next.fireChannelRead() because it does not have the whole encrypted packets. (I mentioned above)
 - At this time, there is no change of the flags of SslHandler context.

5. SslHandler handles channelReadComplete(). Channel.read() will not be called because invokePrevRead of context is false. Refer to the following codes.

        /**
         * At this point, we are sure the handler of this context did not produce anything and
         * we suppressed the {@code channelReadComplete()} event.
         *
         * If the next handler invoked {@link #read()} to read something but nothing was produced
         * by the handler of this context, someone has to issue another {@link #read()} operation
         * until the handler of this context produces something.
         *
         * Why? Because otherwise the next handler will not receive {@code channelRead()} nor
         * {@code channelReadComplete()} event at all for the {@link #read()} operation it issued.
         */
        if (invokedPrevRead && !channel().config().isAutoRead()) {
            /**
             * The next (or upstream) handler invoked {@link #read()}, but it didn't get any
             * {@code channelRead()} event. We should read once more, so that the handler of the current
             * context have a chance to produce something.
             */
            read();
        } else {
            invokedPrevRead = false;
        }

6. After that, no more channelRead() will be called.

Could you review the steps I found? I will try to write a simple reproducer later.

**Comment by trustin** [comment] 2015-04-02 03:10
Didn't have time for taking a close look yet, but I didn't forget about this.

**Comment by hyangtack** [comment] 2015-04-06 14:52
https://github.com/hyangtack/netty/commit/b52bac04c0f8b49cb10079783132dabf1768ad99

@trustin Could you take a look at this commit? Should I call ctx.read at channelReadComplete?  When I moved it to channelReadComplete, tests succeeded. Please let me know if I'm wrong.

**Comment by trustin** [comment] 2015-04-08 08:54
@hyangtack Thanks for the detailed analysis. The expected user behavior was to call `ctx.read()` at `channelReadComplete()`, but it should work even if `ctx.read()` was called at `channelRead()`. So, yeah, the workaround in your case would be to move `ctx.read()` from `channelRead()` to `channelReadComplete()`.

**Comment by trustin** [comment] 2015-04-08 08:55
@hyangtack Please stay tuned. I'm working on a fix.

**Comment by trustin** [comment] 2015-04-08 09:13
Related commits:
https://github.com/netty/netty/commit/375b9e1307c83a648329711c02237b360d8e3cd5
https://github.com/netty/netty/commit/8b2fb2b985cd969719f23da689eb3dc67282070a
https://github.com/netty/netty/commit/a41b46ff430369112bdc9ab2474cb40667c289a3
https://github.com/netty/netty/commit/5fca3de09869b168586b6ab6fc3e2d05b2b9ecba

**Comment by trustin** [comment] 2015-04-08 10:20
@normanmaurer Given:

* the complexity of the commits that affects this issue and #3587, and
* potential performance hit by accessing volatile fields,

I guess it's better reverting the changes mentioned above and think again. WDYT?

**Comment by normanmaurer** [comment] 2015-04-08 10:22
@trustin hmm... can you give me some more details on why the issue is there ? I'm not sure I understood the issue. Once I better understand it I would like to think about it before do any action.

**Comment by trustin** [comment] 2015-04-08 11:27
@normanmaurer Read @hyangtack 's comment - especially [this one](https://github.com/netty/netty/issues/3529#issuecomment-86587767)

**Comment by trustin** [comment] 2015-04-08 11:28
@normanmaurer and [this one](https://github.com/netty/netty/issues/3587#issuecomment-89821570)

**Comment by normanmaurer** [comment] 2015-04-09 12:31
@trustin so with reverting you say we should "just" handle it again in the ByteToMessageDecoder explicit as before, right ?

**Comment by trustin** [comment] 2015-04-10 02:51
@normanmaurer Yes. Currently, our change affects all handlers and some of them don't really need it.  Perhaps it's better for us to provide a superclass that ByteToMessageDecoder and other aggregating handlers can extend.  If that's impossible, we should go back to the bad old days.

**Comment by normanmaurer** [comment] 2015-04-10 04:22
@trustin I see :) you want to work on it or should I do?

**Comment by trustin** [comment] 2015-04-10 05:01
You can take it if you want :-)

**Comment by normanmaurer** [comment] 2015-04-10 05:17
@trustin so what you think about revert first and work in a proper fix after? So at least it's not broken in the meantime.

**Comment by trustin** [comment] 2015-04-10 05:18
@normanmaurer We could just issue a pull request with a revert commit and a fix.

**Comment by normanmaurer** [comment] 2015-04-10 05:26
@trustin ok... Let me see if I can come up with a good fix today.

**Comment by normanmaurer** [comment] 2015-04-10 11:31
@trustin actually can you take this as I'm investigate in #3539 atm :/

**Comment by normanmaurer** [comment] 2015-04-14 04:40
@trustin you can check or you have no time ?

**Comment by normanmaurer** [comment] 2015-04-20 08:44
Fixed by:

2e1325aa9de21b7fd10f2ac56b49fd5a3bbaa189
f35158f40206c8fa22ec30cf581216184314fb35
76dcda8259d60a822a2617cab6ebdd4e12d3fcb5
b35f2b4cb4dd82a174c64c3d38486cb0b33c8c18
3b1bf6348a563ecc23ccd4f1b651141f33fff1a9
5cd541c537bbf5f3faa6cf2dbceac5f1e4d75af9

**Closed by normanmaurer** 2015-04-20 08:44 UTC
Labels: defect
