### ISSUE TITLE
Netty vs Nginx: Pros and Cons based on Performance, Memory Management, Memory Footprint

### ISSUE THREAD

**Issue by vicky22291** [netty/netty#5040] opened 2016-03-25 09:37 UTC
Question: What are the Pros and Cons of Nginx and Netty for using building a Proxy Server.

Elaborating the problem:

We are trying to implement a proxy server (forward or reverse proxy) which is placed in front of a service and takes care of good practices that can be applied on our services.

So we are evaluating different solutions that are available in the market mainly Nginx and Netty. So when we initially did our research on Nginx, we came across a good amount of positive blogs which suggested that Nginx is very fast, easily configurable by writing the custom modules to plugin to Nginx.

But when we did a POC on Netty, we got much better performance numbers while using Netty 4. So I would like to know if some one have performed some comparison between Nginx and Netty and also what are the reasons for not using Netty as a reverse/forward proxy solution. We are worried on GC problems associated with Java Server solutions hence we want to know the Pros and Cons of Nginx and Netty before going ahead with a solution.

Thanks, Vinay.

**Comment by normanmaurer** [comment] 2016-03-25 09:56
I think @burtonator saw the same in the past. Maybe he can share more infos

**Comment by Scottmitch** [comment] 2016-03-25 17:55
@vicky22291 - I don't have much experience with Nginx, but I have also heard positive things about it.

Interesting comparison ... would you be able to share some numbers, and what version of Netty/Nginx you are using? Are you doing SSL ... if so which SSL provider are you using for Netty (OpenSSL I'm assuming)?

**Comment by burtonator** [comment] 2016-03-25 18:18
Thanks @normanmaurer  ... If you are having GC issues the problem is with the way Java handles direct buffers (it's basically broken - I can explain at length if necessary).  You can move to Jetty buffer pooling (enabled via system property) and it should fix the issue.

Also you should checkout our noxy project:

https://github.com/spinn3r/noxy

we haven't yet put it into production but will in the next 2-4 months.  It's actually 99% complete but we just haven't had the time to put it online.

It's basically a full and reverse proxy (plus extra magic) as a stand alone daemon similar to nginx.

It's based on netty 4.x + littleproxy.

**Comment by normanmaurer** [comment] 2016-03-25 18:19
@burtonator I guess you mean Netty buffer pooling and NOT Jetty, right ?

**Comment by burtonator** [comment] 2016-03-25 18:29
mea maxima culpa.  

Correct.. I meant netty.  We use jetty for some stuff internally (usually super simple stuff) and sometimes I transpose their names.

**Comment by wmorgan** [comment] 2016-03-25 23:29
@vicky22291 we're in the process of benchmarking our netty-based proxy (https://github.com/BuoyantIO/linkerd) against nginx. Will post results when we have them.

**Comment by normanmaurer** [comment] 2016-03-26 07:09
@wmorgan thanks this will be very useful :)

**Comment by normanmaurer** [comment] 2016-03-29 09:38
@wmorgan one thing which may be a problem here tho... Isn't finagle and so (linkerd) still using netty 3.x ?

**Comment by doom369** [comment] 2016-03-31 08:43
@wmorgan waiting for benchmarks. Please share as soon as you get some results.

**Comment by Scottmitch** [comment] 2016-04-08 20:05
@wmorgan - Ping. How is the bench marking coming?

**Comment by Scottmitch** [comment] 2016-04-23 18:37
I'll close this now as it is an interesting topic no issue or feature request came out of it.

**Closed by Scottmitch** 2016-04-23 18:37 UTC
