### ISSUE TITLE
Channel.Unsafe.closeForcibly() fails for EpollSocketChannel if not registered to event loop

### ISSUE THREAD

**Issue by trustin** [netty/netty#6770] opened 2017-05-23 06:00 UTC
### Expected behavior

`Channel.Unsafe.closeForcibly()` should close the connection immediately even if the channel is not registered to an event loop.

### Actual behavior

The connection is closed, but an exception is accompanied.
```
05:53:55.405 [armeria-server-boss-epoll-26-1] WARN  io.netty.channel.AbstractChannel - Failed to close a channel.
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:158)
	at io.netty.channel.epoll.AbstractEpollChannel.doDeregister(AbstractEpollChannel.java:140)
	at io.netty.channel.epoll.AbstractEpollChannel.doClose(AbstractEpollChannel.java:117)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doClose(AbstractEpollStreamChannel.java:721)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.closeForcibly(AbstractChannel.java:703)
```

### Steps to reproduce

Accept an incoming connection from an epoll server socket and close the accepted connection using `Channel.Unsafe.closeForcibly()` before it's registered to an event loop.

### Minimal yet complete reproducer code (or URL to code)

```java
ServerBootstrap sb = new ServerBootstrap();
...
sb.handler(new ChannelInboundHandlerAdapter() {
    @Override
    public void channelRead(ctx, msg) {
        Channel childChannel = (Channel) msg;
        if (isBlacklisted(childChannel)) {
            ((SocketChannelConfig) childChannel.config()).setSoLinger(0); // Send RST
            childChannel.unsafe().closeForcibly();
        } else {
            ctx.fireChannelRead(msg);
        }
    }
});
```

### Netty version

4.1.11

**Comment by normanmaurer** [comment] 2017-05-23 06:03
@trustin does it fail with nio as well or only epoll ?

**Comment by trustin** [comment] 2017-05-23 06:07
Epoll only. By the way, the connection seems to be closed because `socket.close()` is in the `finally` block. It raises an exception while trying to deregister.

**Comment by normanmaurer** [comment] 2017-05-23 06:10
@trustin will check

**Comment by trustin** [comment] 2017-05-23 06:12
Thanks, @normanmaurer !

**Comment by Scottmitch** [comment] 2017-05-23 22:40
To clarify ... the issue is an exception is thrown, not that the channel isn't closed, correct?

**Comment by Scottmitch** [comment] 2017-05-23 22:43
We need to deregister the channel to ensure the state of the EventLoop is correctly updated. Seems safe to ignore (or not generate) an expiation if the EventLoop is null in this case.

**Comment by Scottmitch** [comment] 2017-05-23 22:47
just saw @normanmaurer's PR ... seems like we are on the same page 👍

**Comment by trustin** [comment] 2017-05-23 23:45
> To clarify ... the issue is an exception is thrown, not that the channel isn't closed, correct?

Yes.

**Comment by normanmaurer** [comment] 2017-05-24 09:46
@trustin ok le mt merge

**Comment by normanmaurer** [comment] 2017-05-24 12:18
Fixed by https://github.com/netty/netty/pull/6772

**Closed by normanmaurer** 2017-05-24 12:18 UTC
Labels: defect
