### ISSUE TITLE
Connections to SSL servers with untrusted client certificates succeed after upgrade to Netty 4.1.7

### ISSUE THREAD

**Issue by jchambers** [netty/netty#6312] opened 2017-02-04 15:02 UTC
After upgrading to Netty 4.1.7, I've observed that Netty SSL clients can connect to Netty SSL servers that require client authentication even if they present a certificate that is not trusted by the server.

### Steps to reproduce

1. Create an SSL server with an `SslHandler` that requires client authentication and a trust chain that contains a single root certificate.
2. Create an SSL client with an `SslHandler` that will present a randomly-generated client certificate (i.e. definitely not in the server's trust chain).
3. Connect the client to the server.

### Expected behavior

The server rejects the connection attempt (or at least fails the handshake attempt) because client authentication is required and the client has presented a certificate that is not trusted by the server. This was the behavior in Netty 4.1.6 and earlier.

### Actual behavior

The connection attempt succeeds without error as of Netty 4.1.7.

### Minimal yet complete reproducer code (or URL to code)

Minimal test case pending. In the interim, I offer [`ApnsClientTest#testConnectWithUntrustedCertificate`](https://github.com/relayrides/pushy/blob/v0.9.2/pushy/src/test/java/com/relayrides/pushy/apns/ApnsClientTest.java#L370).

### Netty version

4.1.8 (using both the `JDK` and `OPENSSL` SSL providers)

### JVM version

```
$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

### OS version

```
$ uname -a
Darwin stratus.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment] 2017-02-04 16:16
So this happens with jdk and OpenSSL ?

**Comment by jchambers** [comment] 2017-02-04 17:44
> So this happens with jdk and OpenSSL ?

Correct. It also happens across JDK versions: https://travis-ci.org/relayrides/pushy/builds/198243545

**Comment by normanmaurer** [comment] 2017-02-04 17:53
Ok this Sounds Strange... let me investigate

**Comment by normanmaurer** [comment] 2017-02-06 07:40
@jchambers hmm... I have the same failure with 4.1.7.Final. Didn't you say it was "ok" with 4.1.7.Final ?

```
╭─[8:39:09] norman@Normans-MacBook-Pro-8/~/Documents/workspace/pushy
( v0.9.2: ✘, 1 file changed, 1 insertion(+), 1 deletion(-)
╰─○ grep "<netty.version>" pom.xml
        <netty.version>4.1.7.Final</netty.version>
```
```
╭─[8:39:49] norman@Normans-MacBook-Pro-8/~/Documents/workspace/pushy
( v0.9.2: ✘, 1 file changed, 1 insertion(+), 1 deletion(-)
╰─✘ mvn test -Dtest='ApnsClientTest#testConnectWithUntrustedCertificate'
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Pushy parent
[INFO] Pushy
[INFO] Pushy benchmarks
[INFO] Dropwizard Metrics listener for Pushy
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pushy parent 0.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ pushy-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Pushy 0.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ pushy ---
[INFO]
[INFO] --- maven-dependency-plugin:2.8:get (get-alpn-boot) @ pushy ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.5 with transitive dependencies
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pushy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pushy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 32 source files to /Users/norman/Documents/workspace/pushy/pushy/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pushy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 14 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pushy ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ pushy ---
[INFO] Surefire report directory: /Users/norman/Documents/workspace/pushy/pushy/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[6916]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/bin/java (0x1088aa4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1089a64e0). One of the two will be used. Which one is undefined.
[jetty-alpn-agent] Using: alpn-boot-8.1.9.v20160720.jar
Running com.relayrides.pushy.apns.ApnsClientTest
[jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
[jetty-alpn-agent] Replacing: sun/security/ssl/ServerHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/ServerHandshaker$3
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.992 sec <<< FAILURE! - in com.relayrides.pushy.apns.ApnsClientTest
testConnectWithUntrustedCertificate(com.relayrides.pushy.apns.ApnsClientTest)  Time elapsed: 0.662 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.relayrides.pushy.apns.ApnsClientTest.testConnectWithUntrustedCertificate(ApnsClientTest.java:382)


Results :

Failed tests:
  ApnsClientTest.testConnectWithUntrustedCertificate:382 null

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by jasontedor** [comment] 2017-02-06 18:50
I can't say what is going on here, but I investigated this, and we are not impacted by it.

That said, I think that the Netty project needs a responsible disclosure policy for issues like this. If there is any truth to this issue at all, it would have been better if it not be disclosed in the open until a fix is available and downstream projects have an opportunity to react.

I poked around the docs looking for a responsible disclosure policy. Is there one that I missed @normanmaurer? If not, can you please formulate one and communicate it clearly? I would be happy to open a separate issue for this.

**Comment by normanmaurer** [comment] 2017-02-06 18:58
@jasontedor we have `netty-security@googlegroups.com` for reporting security stuff, but I think you are right its not clearly communicated. So yes please open an issue and  will write it up.

**Comment by jasontedor** [comment] 2017-02-06 19:07
I opened #6319.

**Comment by jchambers** [comment] 2017-02-06 19:07
Haven't had time to investigate further (but will soon!), but in the meantime, please accept my apologies for missing the disclosure policy.

**Comment by normanmaurer** [comment] 2017-02-06 19:09
@jasontedor thanks..

@jchambers no worries its our fault to make it not clear enough. Let me know once you know more (even if you can just tell me it worked in version X but not working anymore after version Y).

**Comment by normanmaurer** [comment] 2017-02-06 19:15
Also I will try to come-up with a reproducer with plain netty as well in the meantime.

**Comment by normanmaurer** [comment] 2017-02-06 19:31
@jchambers also I were wondering how is your "test" different the one we have here:
https://github.com/netty/netty/blob/4.1/handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java#L501
https://github.com/netty/netty/blob/4.1/handler/src/test/java/io/netty/handler/ssl/SSLEngineTest.java#L486

**Comment by jchambers** [comment] 2017-02-06 20:46
> Didn't you say it was "ok" with 4.1.7.Final ?

I did, but you're correct: the problem appears to have crept in with 4.1.7.Final with both netty-tcnative fork25 and the JDK provider. I'll update the title and summary accordingly.

**Comment by normanmaurer** [comment] 2017-02-06 20:47
@jchambers thx... looking into it.

**Comment by normanmaurer** [comment] 2017-02-06 20:48
@jchambers also can you tell me how your test is different to what we have in netty ? Just so I can adjust it easily and have a pure netty reproducer.

**Comment by jchambers** [comment] 2017-02-06 20:59
> also can you tell me how your test is different to what we have in netty ?

Not in detail yet (sorry—my life is like one contiguous meeting these days), but I agree that's the critical question. Off the top of my head and with an extremely fast read of the existing Netty tests:

- We're using an HTTP/2 pipeline, so we're passing [some fancy configuration to the SSL handler](https://github.com/relayrides/pushy/blob/v0.9.1/pushy/src/main/java/com/relayrides/pushy/apns/ApnsClientBuilder.java#L407-L414)
- Our certificates have some vendor-specific [extensions](https://github.com/relayrides/pushy/blob/v0.9.1/pushy/script/generate-certs.sh)

Details to follow as soon as I can devote an hour to the problem.

**Comment by normanmaurer** [comment] 2017-02-06 21:02
Alright… as soon as you know let me know. I will try to find more in the meantime as well.

**Comment by bm3780** [comment] 2017-02-07 00:23
Tested with [MutualSSLAuthServer](https://gist.github.com/bm3780/0fe9b73a32dfcd7b940054409c77e607) against 4.0.44 and 4.1.8 using openssl  _s_client_ with no issues.

1. Launch MutualSSLAuthServer with either JDK or OPENSSL provider
2. generate a dummy (untrusted by server) certificate
```bash
 openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```
3. connect to server with openssl s_client using untrusted certificate
```bash
 openssl s_client -connect localhost:8443 -cert cert.pem -key key.pem -state -msg
```
4. client will see SSL Alert from server indicating that server failed to trust peer's certificate:

 ```bash
SSL_connect:before/connect initialization
>>> SSL 2.0 [length 0080], CLIENT-HELLO
SSL_connect:SSLv2/v3 write client hello A
<<< TLS 1.0 Handshake [length 0051], ServerHello
...
SSL_connect:SSLv3 read server hello A
<<< TLS 1.0 Handshake [length 0311], Certificate
...
SSL_connect:SSLv3 read server certificate A
<<< TLS 1.0 Handshake [length 004d], CertificateRequest
...
SSL_connect:SSLv3 read server certificate request A
<<< TLS 1.0 Handshake [length 0004], ServerHelloDone
    0e 00 00 00
SSL_connect:SSLv3 read server done A
>>> TLS 1.0 Handshake [length 05ae], Certificate
...
SSL_connect:SSLv3 write client certificate A
>>> TLS 1.0 Handshake [length 0106], ClientKeyExchange
...
SSL_connect:SSLv3 write client key exchange A
>>> TLS 1.0 Handshake [length 0206], CertificateVerify
...
SSL_connect:SSLv3 write certificate verify A
>>> TLS 1.0 ChangeCipherSpec [length 0001]
    01
SSL_connect:SSLv3 write change cipher spec A
>>> TLS 1.0 Handshake [length 0010], Finished
    14 00 00 0c 34 81 ae c0 bc 8d 79 35 1f 27 75 82
SSL_connect:SSLv3 write finished A
SSL_connect:SSLv3 flush data
<<< TLS 1.0 Alert [length 0002], fatal internal_error
    02 50
SSL3 alert read:fatal:internal error
SSL_connect:failed in SSLv3 read finished A
```

**Comment by jchambers** [comment] 2017-02-07 02:12
I've made a mistake, and it *could* be that everything is working exactly as expected. It turns out that I was actually using `ClientAuth.OPTIONAL` instead of `ClientAuth.REQUIRE`, which changes the picture significantly. A better summary of the situation is now:

1. We tell our server that clients MAY authenticate.
2. A client presents an untrusted certificate to the server.
3. The server recognizes that the certificate is bogus, but allows the connection to happen anyway.

Prior to Netty 4.1.7, the server would have rejected the connection attempt with a bogus certificate, or at least indicated that something screwy was happening. From Netty 4.1.7 onward, the connection attempt succeeds with (I think?) no warning.

**Comment by Scottmitch** [comment] 2017-02-07 06:40
@jchambers - Thanks for reporting back. I created a unit tests with the keys you referenced and the ssl configuration you referenced and I couldn't get a failure. Please refactor the below code to demonstrate the behavior you are seeing. I ran the below test and got the expected handshake failure OpenSSL 1.0.2.

SSLEngineTest.java
```java
    @Test
    public void testMutualAuthDiffCertsClientFailure2() throws Exception {
        final KeyStore serverKeyStore = KeyStore.getInstance("PKCS12");
        serverKeyStore.load(getClass().getResourceAsStream("pushy_server.p12"), "pushy-test".toCharArray());
        final KeyStore clientKeyStore = KeyStore.getInstance("PKCS12");
        clientKeyStore.load(getClass().getResourceAsStream("pushy_untrusted-client.p12"), "pushy-test".toCharArray());
        final KeyManagerFactory serverKeyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        serverKeyManagerFactory.init(serverKeyStore, "pushy-test".toCharArray());
        final KeyManagerFactory clientKeyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        clientKeyManagerFactory.init(clientKeyStore, "pushy-test".toCharArray());
        File commonCertChain = new File(getClass().getResource("pushy_ca.pem").getFile());

        mySetupMutualAuth(serverKeyManagerFactory, commonCertChain, clientKeyManagerFactory, commonCertChain);
        assertTrue(clientLatch.await(2, TimeUnit.SECONDS));
        assertTrue(clientException instanceof SSLHandshakeException);
        assertTrue(serverLatch.await(2, TimeUnit.SECONDS));
        assertTrue(serverException instanceof SSLHandshakeException);
    }

    private void mySetupMutualAuth(KeyManagerFactory serverKMF, final File serverTrustManager,
                                   KeyManagerFactory clientKMF, File clientTrustManager) throws SSLException, InterruptedException {
        serverSslCtx = SslContextBuilder.forServer(serverKMF)
                .sslProvider(sslServerProvider())
                .trustManager(serverTrustManager)
                .clientAuth(ClientAuth.OPTIONAL)
                .ciphers(null, IdentityCipherSuiteFilter.INSTANCE)
                .sessionCacheSize(0)
                .sessionTimeout(0)
                .build();

        clientSslCtx = SslContextBuilder.forClient()
                .sslProvider(sslClientProvider())
                .trustManager(clientTrustManager)
                .keyManager(clientKMF)
                .ciphers(null, IdentityCipherSuiteFilter.INSTANCE)
                .sessionCacheSize(0)
                .sessionTimeout(0).applicationProtocolConfig(
                        new ApplicationProtocolConfig(ApplicationProtocolConfig.Protocol.ALPN,
                                ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                                ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                                ApplicationProtocolNames.HTTP_2))
                .build();
        serverConnectedChannel = null;
        sb = new ServerBootstrap();
        cb = new Bootstrap();

        sb.group(new NioEventLoopGroup(), new NioEventLoopGroup());
        sb.channel(NioServerSocketChannel.class);
        sb.childHandler(new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ch.config().setAllocator(new TestByteBufAllocator(ch.config().getAllocator(), type));

                ChannelPipeline p = ch.pipeline();
                SSLEngine engine = serverSslCtx.newEngine(ch.alloc());
                engine.setUseClientMode(false);
                engine.setNeedClientAuth(true);
                p.addLast(new SslHandler(engine));
                p.addLast(new MessageDelegatorChannelHandler(serverReceiver, serverLatch));
                p.addLast(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                        if (cause.getCause() instanceof SSLHandshakeException) {
                            serverException = cause.getCause();
                            serverLatch.countDown();
                        } else {
                            serverException = cause;
                            ctx.fireExceptionCaught(cause);
                        }
                    }
                });
                serverConnectedChannel = ch;
            }
        });

        cb.group(new NioEventLoopGroup());
        cb.channel(NioSocketChannel.class);
        cb.handler(new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ch.config().setAllocator(new TestByteBufAllocator(ch.config().getAllocator(), type));

                ChannelPipeline p = ch.pipeline();
                p.addLast(clientSslCtx.newHandler(ch.alloc()));
                p.addLast(new MessageDelegatorChannelHandler(clientReceiver, clientLatch));
                p.addLast(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                        cause.printStackTrace();
                        if (cause.getCause() instanceof SSLHandshakeException) {
                            clientException = cause.getCause();
                            clientLatch.countDown();
                        } else {
                            ctx.fireExceptionCaught(cause);
                        }
                    }
                });
            }
        });

        serverChannel = sb.bind(new InetSocketAddress(0)).sync().channel();
        int port = ((InetSocketAddress) serverChannel.localAddress()).getPort();

        ChannelFuture ccf = cb.connect(new InetSocketAddress(NetUtil.LOCALHOST, port));
        assertTrue(ccf.awaitUninterruptibly().isSuccess());
        clientChannel = ccf.channel();
    }
```

**Comment by normanmaurer** [comment] 2017-02-07 15:47
@jchambers as @Scottmitch said I think everything works as expected (at least I could also not reproduce it). It correctly triggers an `exceptionCaught(...)` event and also fires the correct `SslHandshakeCompletionEvent`. Could you try to change the reproducer done by @Scottmitch so it fails ?

**Comment by jchambers** [comment] 2017-02-07 16:17
I'm working on it now.

**Comment by jchambers** [comment] 2017-02-07 18:10
I am *also* having a hard time reproducing the issue with a minimal test case. I'm still actively working on identifying what's different between the minimal and non-minimal cases, though.

FWIW, I took a brief detour to `git bisect` and confirmed that it was be8c16cd0c54f9013b539741bf2a1db13ddc0126 that introduced this new behavior.

**Comment by normanmaurer** [comment] 2017-02-07 18:17
@jchambers this is strange as you said it also happens with JDK and this commit only touches OpenSSL .

**Comment by jchambers** [comment] 2017-02-07 18:56
Scratch that. I have a [minimal test case](https://gist.github.com/jchambers/3113072156d49b3106fc5f2634de96c7) working, though I have not yet adapted the test from @Scottmitch to reproduce the problem; will get to that ASAP.

@normanmaurer I think you're right about the OpenSSL/JDK thing; it looks like this has been the JDK behavior for a long time, but some configuration in my non-minimal test case masked it until now. Please pardon the bad information there.

**Comment by normanmaurer** [comment] 2017-02-07 18:58
@jchambers got it... If I understand you correct the current behaviour may be the correct one now and the old was not. But will see soon after you adjusted the test case of @Scottmitch .

**Comment by Scottmitch** [comment] 2017-02-07 19:59
@jchambers - I extracted out your test case and I still get a failure. Am I missing something?

For JDK I see the following user event:
```
client user event: SslHandshakeCompletionEvent(javax.net.ssl.SSLException: Received fatal alert: bad_certificate)
server user event: SslHandshakeCompletionEvent(javax.net.ssl.SSLHandshakeException: null cert chain)
server user event: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
client user event: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
```

For OpenSSL I see the following user event:
```
server user event: SslHandshakeCompletionEvent(javax.net.ssl.SSLHandshakeException: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate)
client user event: SslHandshakeCompletionEvent(javax.net.ssl.SSLHandshakeException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure)
server user event: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
client user event: SslCloseCompletionEvent(java.nio.channels.ClosedChannelException)
```

The JDK `SSLEngineImpl` doesn't generate a `SSLHandshakeException` on the client side but the handshake still appears to fail.

SSLEngineTest.java
```java
    private static KeyStore.PrivateKeyEntry getFirstPrivateKeyEntryFromP12InputStream(final InputStream p12InputStream,
                                                                                      final String password)
            throws KeyStoreException, CertificateException,
            NoSuchAlgorithmException, IOException, UnrecoverableEntryException {
        final KeyStore keyStore = KeyStore.getInstance("PKCS12");
        keyStore.load(p12InputStream, password.toCharArray());

        final Enumeration<String> aliases = keyStore.aliases();
        final KeyStore.PasswordProtection passwordProtection = new KeyStore.PasswordProtection(password.toCharArray());

        while (aliases.hasMoreElements()) {
            final String alias = aliases.nextElement();

            KeyStore.Entry entry;

            try {
                entry = keyStore.getEntry(alias, passwordProtection);
            } catch (final UnsupportedOperationException e) {
                entry = keyStore.getEntry(alias, null);
            }

            if (entry instanceof KeyStore.PrivateKeyEntry) {
                return (KeyStore.PrivateKeyEntry) entry;
            }
        }

        throw new KeyStoreException("Key store did not contain any private key entries.");
    }

    @Test
    public void testMutualAuthDiffCertsClientFailure3() throws Exception {
        final File rootCertificatePemFile = new File(getClass().getResource("ca.pem").getFile());
        final File serverCredentialsP12File = new File(getClass().getResource("server.p12").getFile());
        final File untrustedClientP12File = new File(getClass().getResource("untrusted-client.p12").getFile());

        KeyStore.PrivateKeyEntry serverKeyEntry = getFirstPrivateKeyEntryFromP12InputStream(
                new FileInputStream(serverCredentialsP12File), "example");
        KeyStore.PrivateKeyEntry clientKeyEntry = getFirstPrivateKeyEntryFromP12InputStream(
                new FileInputStream(untrustedClientP12File), "example");
        mySetupMutualAuth(serverKeyEntry.getPrivateKey(),
                (java.security.cert.X509Certificate) serverKeyEntry.getCertificate(),
                "example",
                clientKeyEntry.getPrivateKey(),
                (java.security.cert.X509Certificate) clientKeyEntry.getCertificate(),
                "example",
                rootCertificatePemFile);
        assertTrue(clientLatch.await(2, TimeUnit.SECONDS));
        assertTrue(clientException instanceof SSLHandshakeException);
        assertTrue(serverLatch.await(2, TimeUnit.SECONDS));
        assertTrue(serverException instanceof SSLHandshakeException);
    }

    private void mySetupMutualAuth(java.security.PrivateKey serverKey, java.security.cert.X509Certificate serverCert,
                                   String serverKeyPassword,
                                   java.security.PrivateKey clientKey, java.security.cert.X509Certificate clientCert,
                                   String clientKeyPassword,
                                   File rootCertsFile) throws SSLException, InterruptedException {
        serverSslCtx = SslContextBuilder.forServer(serverKey, serverKeyPassword, serverCert)
                .sslProvider(sslServerProvider())
                .trustManager(rootCertsFile)
                .clientAuth(ClientAuth.OPTIONAL)
                .ciphers(null, IdentityCipherSuiteFilter.INSTANCE)
                .sessionCacheSize(0)
                .sessionTimeout(0)
                .applicationProtocolConfig(
                        new ApplicationProtocolConfig(ApplicationProtocolConfig.Protocol.ALPN,
                                ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                                ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                                ApplicationProtocolNames.HTTP_2))
                .build();

        clientSslCtx = SslContextBuilder.forClient()
                .sslProvider(sslClientProvider())
                .keyManager(clientKey, clientKeyPassword, clientCert)
                .trustManager(rootCertsFile)
                .ciphers(null, IdentityCipherSuiteFilter.INSTANCE)
                .sessionCacheSize(0)
                .sessionTimeout(0)
                .applicationProtocolConfig(
                        new ApplicationProtocolConfig(ApplicationProtocolConfig.Protocol.ALPN,
                                ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                                ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                                ApplicationProtocolNames.HTTP_2))
                .build();
        serverConnectedChannel = null;
        sb = new ServerBootstrap();
        cb = new Bootstrap();

        sb.group(new NioEventLoopGroup(), new NioEventLoopGroup());
        sb.channel(NioServerSocketChannel.class);
        sb.childHandler(new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ch.config().setAllocator(new TestByteBufAllocator(ch.config().getAllocator(), type));

                ChannelPipeline p = ch.pipeline();
                SSLEngine engine = serverSslCtx.newEngine(ch.alloc());
                engine.setUseClientMode(false);
                engine.setNeedClientAuth(true);
                p.addLast(new SslHandler(engine));
                p.addLast(new MessageDelegatorChannelHandler(serverReceiver, serverLatch));
                p.addLast(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                        if (cause.getCause() instanceof SSLHandshakeException) {
                            serverException = cause.getCause();
                            serverLatch.countDown();
                        } else {
                            serverException = cause;
                            ctx.fireExceptionCaught(cause);
                        }
                    }
                });
                serverConnectedChannel = ch;
            }
        });

        cb.group(new NioEventLoopGroup());
        cb.channel(NioSocketChannel.class);
        cb.handler(new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ch.config().setAllocator(new TestByteBufAllocator(ch.config().getAllocator(), type));

                ChannelPipeline p = ch.pipeline();
                p.addLast(clientSslCtx.newHandler(ch.alloc()));
                p.addLast(new MessageDelegatorChannelHandler(clientReceiver, clientLatch));
                p.addLast(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                        cause.printStackTrace();
                        if (cause.getCause() instanceof SSLHandshakeException) {
                            clientException = cause.getCause();
                            clientLatch.countDown();
                        } else {
                            ctx.fireExceptionCaught(cause);
                        }
                    }
                });
            }
        });

        serverChannel = sb.bind(new InetSocketAddress(0)).sync().channel();
        int port = ((InetSocketAddress) serverChannel.localAddress()).getPort();

        ChannelFuture ccf = cb.connect(new InetSocketAddress(NetUtil.LOCALHOST, port));
        assertTrue(ccf.awaitUninterruptibly().isSuccess());
        clientChannel = ccf.channel();
    }
```

**Comment by jchambers** [comment] 2017-02-07 21:16
@Scottmitch Still actively working on it. I agree that handshakes are failing in your test and am still trying to figure out what's different between your test and mine. As a sanity check, though, do you agree that connections succeed in my test case with either the JDK provider or a native provider under 4.17+?

**Comment by jchambers** [comment] 2017-02-07 21:25
…FWIW, at this point, I've jettisoned almost all optional `SslContext` configuration in both my test and yours (gist is updated) and made sure that the event loop group setup is the same in both tests, but continue to get different results.

**Comment by Scottmitch** [comment] 2017-02-08 02:42
@jchambers - I am able to reproduce with your test case and I think I found the difference (copy/pasta):

```java
SSLEngine engine = serverSslCtx.newEngine(ch.alloc());
engine.setUseClientMode(false);
engine.setNeedClientAuth(true);
```

The certs/keys you are using are also part of the equation. I see consistent behavior between JDK and OpenSSL engines which is with `ClientAuth.REQUIRE` they both fail the handshake (although the JDK doesn't use a `SSLHandshakeException` which seems like a JDK bug), and with `ClientAuth.NONE` or `ClientAuth.Optional` the handshakes complete. So in summary it seems like the behavior is now consistent.

It looks like there is some attempt at providing the behavior you are after in netty-tcnative [1] but it looks broken. I will investigate this.

[1] https://github.com/netty/netty-tcnative/blob/master/openssl-dynamic/src/main/c/sslutils.c#L590

**Comment by jchambers** [comment] 2017-02-08 03:44
Gooooood catch. Never thought to look there; is there a difference between setting those properties on the engine directly and using [`SslContextBuilder#forClient()`](http://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#forClient())?

In any case, I agree the behavior is now consistent. If that's all we're after, I'll happily close this ticket with my sincere apologies for both the false alarm and clumsy reproduction process.

**Comment by Scottmitch** [comment] 2017-02-08 03:53
> is there a difference between setting those properties on the engine directly and using

There shouldn't be. At one time we didn't support all these fancy features in our APIs and on the OpenSslEngine, and these tests haven't been updated to use the new APIs.

> If that's all we're after

I just wanted to be clear that I don't think there is a security related issue and no-one should panic. The behavior may have changed in OpenSslEngine, but it is now more consistent with JDK's SSLEngine.

However I am working on a feature for OpenSslEngine which is "optional, but if the peer presents a certificate it must be valid". It seems unexpected to accept a certificate that is invalid (even though that maybe the default behavior).

**Comment by normanmaurer** [comment] 2017-02-08 06:48
@jchambers thanks for reporting back :)

@Scottmitch nice find buddy ! But yeah I agree the behaviour is now consistent with the JDK which is what we want by default IMHO. Adding a new configuration option is fine tho.

**Comment by Scottmitch** [comment] 2017-02-08 08:49
Also note that in my version of the test case the client actually elected not to send the certificate in this case. In the event that the Certificates list is of 0 length, OpenSSL doesn't call the certificate verification callback and completes the handshake (expected behavior):

<img width="299" alt="screen shot 2017-02-08 at 12 40 01 am" src="https://cloud.githubusercontent.com/assets/7562868/22729333/2bae453c-ed97-11e6-95d4-00676c6e4693.png">

@jchambers - Can you verify you see the same behavior. This behavior is described in the RFC:

https://tools.ietf.org/html/rfc5246#section-7.4.6
> This is the first message the client can send after receiving a
      ServerHelloDone message.  This message is only sent if the server
      requests a certificate.  If no suitable certificate is available,
      the client MUST send a certificate message containing no
      certificates.  That is, the certificate_list structure has a
      length of zero.

**Comment by Scottmitch** [comment] 2017-02-08 23:05
@jchambers - I think we should close this issue. I will add unit tests to verify existing behavior, but from what I can tell everything is working as expected. Please reopen if you feel there is still an issue here.

**Closed by Scottmitch** 2017-02-08 23:05 UTC
Labels: feature

**Comment by jchambers** [comment] 2017-02-08 23:15
> I think we should close this issue.

Agreed. I went one further and made the title a lot less alarming, too.

Would you still like me to verify the certificates count thing? If so, can you clarify where you were looking?

**Comment by Scottmitch** [comment] 2017-02-09 00:36
> Would you still like me to verify the certificates count thing? If so, can you clarify where you were looking?

Yes. Use some network analyzer (tcpdump, Wireshark) to inspect the handshake data. Wireshark can actually analyze the packets and understands the SSL/TLS handshake and gives you a nice GUI (which is the screenshot above). What I want to verify is the ServerHello includes the `CertificateRequest` and the client's response includes an empty certificate list (list shown above). Under these conditions (optional authentication) it is expected that the handshake succeeded.
