### ISSUE TITLE
NullPointerException causing connection shutdown

### ISSUE THREAD

**Issue by nhnFreespirit** [netty/netty#4869] opened 2016-02-12 23:00 UTC
Hi again

This _might_ be caused by me dosing something wrong, but having debugged it for a while it feels more like a race condition in Netty itself.

Running a test server for a while, I have gotten a couple of exceptions like this one:

```
Unhandled exception, shutting down connection
java.lang.NullPointerException
    at io.netty.util.internal.PriorityQueue.poll(PriorityQueue.java:106)
    at io.netty.util.internal.PriorityQueue.poll(PriorityQueue.java:32)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.poll(WeightedFairQueueByteDistributor.java:305)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(WeightedFairQueueByteDistributor.java:175)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:128)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:715)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:279)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:160)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.channelReadComplete(Http2ConnectionHandler.java:464)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:91)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:168)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:454)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:169)
    at io.netty.handler.ssl.SslHandler.channelReadComplete(SslHandler.java:947)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:91)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:168)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:454)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:169)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:91)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:168)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:454)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:169)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadCompleteNow(ChannelHandlerInvokerUtil.java:91)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelReadComplete(DefaultChannelHandlerInvoker.java:168)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:454)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:169)
    at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:930)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
```

This causes my clients to time out.

I am not that familiar with the Netty code but stepping through that backtrace, I did wonder if in DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:715)

     
```
        protected final void writePendingBytes() throws Http2Exception {
            int bytesToWrite = writableBytes();
            // Make sure we always write at least once, regardless if we have bytesToWrite or not.
            // This ensures that zero-length frames will always be written.
            for (;;) {
                if (!streamByteDistributor.distribute(bytesToWrite, writer) ||
                    (bytesToWrite = writableBytes()) <= 0 ||
                    !isChannelWritable0()) {
                    break;
                }
            }
        }
```

Would we not want to check whether the channel is writable _before_ doing the initial 'distribute' call? Maybe that is unrelated, but it was the only thing I could spot.

**Comment by normanmaurer** [comment] 2016-02-13 00:03
@nmittler @Scottmitch PTAL

**Comment by Scottmitch** [comment] 2016-02-13 07:18
@nhnFreespirit - Thanks for reporting. What version of Netty are you using?

> Would we not want to check whether the channel is writable before doing the initial 'distribute' call?

We limit the amount of bytes we are willing to write based upon how many bytes the channel is able to accept upfront (see [DefaultHttp2RemoteFlowController](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L260))

**Comment by Scottmitch** [comment] 2016-02-13 07:27
@nhnFreespirit - Is all of your interaction with the http2 codec on the event loop thread? For example what thread do you use the `Http2ConnectionEncoder` interface's write methods from?

**Comment by nhnFreespirit** [comment] 2016-02-13 07:40
@Scottmitch Thanks for looking at this.

 I'm on 4.1.0-CR2, should have remembered to add that

I filed issue 4868 earlier today, It has a bit more context about what I'm doing.

I don't have the code right here and it's a relatively new code base for me, so will need to check exactly which treads call write when I have a chance.

It's worth mentioning that while running a test server for more than 24 hours, taking between 5 and 30 RPS the entire time, I saw exactly two of these exceptions.

**Comment by nhnFreespirit** [comment] 2016-02-16 17:39
We are using multiple worker threads but for each stream, the handling of Http2 frames, writing http1 requests and converting those responses back into Http2 frames should be localized to one event loop thread.

**Comment by Scottmitch** [comment] 2016-02-16 19:27
@nhnFreespirit - The reason why I ask is because the http2-codec only supports being interacted with from the I/O thread and is not thread safe. The exception stack trace you presented points to:

1. [PriorityQueue](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PriorityQueue.java#L106) has a bug. It doesn't allow null entries in offer, it checks if size is 0 in poll, but it still gets a NPE when it looks at the first element.
2. Multiple threads may be interacting with the same `PriorityQueue`.

I glanced over `PriorityQueue` and it looks like the `size` variable is being incremented/decremented correctly (feel free to double check), and so I would like to rule out (2).  Can you show me an example code snippet of how you transition calls from the worker threads to the I/O thread? Also we have some assert statements in a few areas which may detect if the incorrect thread is interacting with [DefaultHttp2RemoteFlowController](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java) ... if you are able to repro can you run with assert statements enabled and see if any of these asserts are tripped.

Also if you are able to repro I would be interested as to what the state of the PriorityQueue before the exception is thrown. what is `size`, what is `queue.length`, and what is in `queue`?

**Comment by nhnFreespirit** [comment] 2016-02-16 20:00
I don't have a repro at this time as I have seen this happen exactly once after filing this bug, and that occurrence was several days ago on a server that is taking constant traffic. I do plan on testing with significantly more load some time this week, so it is possible this will show up more frequently then and I can add some debugging around it.

I'm happy to try running with the assertions enabled, how do I turn those on?

I cannot show you the exact code unfortunately, but in essence I just have a ChannelOutboundHandlerAdapter subclass that in it's 'write' method, depending on what type of message object it sees, triggers some combination of 'writeHeaders', 'writeData', 'writePushPromise' or 'writeRstStream' on a DefaultHttp2FrameWriter

**Comment by Scottmitch** [comment] 2016-02-16 22:22
> I'm happy to try running with the assertions enabled, how do I turn those on?

`-ea` command line arg to the JVM. This is expected to add overhead so be cautious about running under production load.

> but in essence I just have a ChannelOutboundHandlerAdapter subclass that in it's 'write' method, depending on what type of message object it sees, triggers some combination of 'writeHeaders', 'writeData', 'writePushPromise' or 'writeRstStream' on a DefaultHttp2FrameWriter

Is the ChannelOutboundHandlerAdapter's write method always invoked on the I/O thread, or do you have some code like the following:

```java
public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
        DefaultHttp2FrameWriter writer = ...;
        EventExecutor executor = ctx.executor();
        if (executor.inEventLoop()) {
            writer.writeHeaders(...);
        } else {
            executor.execute(new OneTimeTask() {
                writer.writeHeaders(...);
            });
        }
}
```

**Comment by nhnFreespirit** [comment] 2016-02-16 22:43
I do not have anything like that check.

Digging a little deeper, I do actually think there is a chance that other code is calling 

ctx.writeAndFlush(response) 
or 
ctx.getChannel().write(response)

From a thread other than the I/O thread which I guess would eventually enter the pipeline and hit my ChannelOutboundHandlerAdapter.

('response' here being an http1 responses from a backend that i'm proxying http2 requests to).

Thanks for nearing with my Netty noobish'ness so far! :)

**Comment by Scottmitch** [comment] 2016-02-18 23:47
@nhnFreespirit - Please report back when you can confirm one way or another. Thanks!

**Comment by nhnFreespirit** [comment] 2016-02-19 01:00
I working on getting some more info.

I'm currently testing the code in a much higher traffic environment, ~500 RPS on a large 24 worker thread box. 
  
I have added something akin to

```
if (!ctx.executor().inEventLoop()) {
  ... logging and stats ...
}
```

in the function wrapping all writes, and even though I see a number of the exceptions of the kind originally posted, I have not seen this log message or stat trigger at all.

**Comment by Scottmitch** [comment] 2016-02-19 03:54
You mention having multiple threads going on ... does `ctx` correlate to the channel reading the `http1 responses` or the channel which represents the `proxying http2` connection?

**Comment by nhnFreespirit** [comment] 2016-02-24 18:40
the ctx is the one representing the Http2 connection.

**Comment by Scottmitch** [comment] 2016-02-25 05:07
@nhnFreespirit - I'm going to need more info to help debug this one. Have you been able to reproduce, and can you provide a reproducer, you can send via email or other means to keep confidential if necessary.

**Comment by nhnFreespirit** [comment] 2016-03-25 17:51
Hi @Scottmitch, sorry for the long silence. Have been on leave and a few other more urgent projects came up.

I have upgraded to 4.1.0.CR4 and I am still seeing this (or at least a very similar, as the backtrace is slightly different) issue. (The upgrade did solve a number of other issues I was seeing, so yay you guys! :)  )

The current stacktrace I'm seeing is the following:

```
java.lang.NullPointerException
    at io.netty.util.internal.PriorityQueue.bubbleDown(PriorityQueue.java:229)
    at io.netty.util.internal.PriorityQueue.poll(PriorityQueue.java:111)
    at io.netty.util.internal.PriorityQueue.poll(PriorityQueue.java:32)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.poll(WeightedFairQueueByteDistributor.java:305)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(WeightedFairQueueByteDistributor.java:175)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:128)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:715)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:279)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:160)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:347)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:590)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:276)
```

after calling ctx.flush()

interestingly enough, this seems to happen much more frequently now, without any other code changes on my side. I have not yet been able to repo it in a debugger but am going to see if that is possible next.

One thing that confuses me a little is an earlier comment in this thread:

> the http2-codec only supports being interacted with from the I/O thread and is not thread safe

I'm currently reading through the "Netty in Action" book. My understanding from that was that any task (write in this case) you try to execute while within the event loop thread will get executed immediately, while any write you try to perform from any other thread will get enqueued and picked up by the even loop thread at its convenience. 

This seems to be confirmed by stepping through the above backtrace, as in DefaultChannelHandlerInvoker.java we hit the following code:

```
    @Override
    public void invokeFlush(final ChannelHandlerContext ctx) {
        if (executor.inEventLoop()) {
            invokeFlushNow(ctx);
        } else {
            AbstractChannelHandlerContext dctx = (AbstractChannelHandlerContext) ctx;
            Runnable task = dctx.invokeFlushTask;
            if (task == null) {
                dctx.invokeFlushTask = task = new Runnable() {
                    @Override
                    public void run() {
                        invokeFlushNow(ctx);
                    }
                };
            }
            executor.execute(task);
        }
    }
```

And according to the backtrace we fall into the first condition.

Again, While my understanding of Netty is increasing as a work on this, I'm still in rookie territory, so it's possible I'm way off the mark here.

To your last comment, unfortunately I cannot provide you the code I am working on for a number of different reasons. One is confidentiality, another is that is is part of a quite large system with many moving parts that makes little sense on it's own.

**Comment by Scottmitch** [comment] 2016-03-25 18:59
> I'm currently reading through the "Netty in Action" book. My understanding from that was that any task (write in this case) you try to execute while within the event loop thread will get executed immediately, while any write you try to perform from any other thread will get enqueued and picked up by the even loop thread at its convenience.

Yes this is generally true of most codecs. However the HTTP/2 codec currently is a bit of a black sheep and currently does not follow this convention because the API directly exposes a `Http2FrameWriter` interface to write with, and a `Http2FrameListener` to read from.  There is a PR https://github.com/netty/netty/pull/4503 which moves the API to conform with the typical codec API, but it is not quite ready for prime time.  So with the current API when you are writing you must take care that you are in the event loop when you interact with `Http2FrameWriter` (and other parts of http2-codec). Using the approaches you listed above will work.

**Comment by normanmaurer** [comment] 2016-04-07 15:47
Let me close this for now and if you still think there is an issue reopen it.

**Closed by normanmaurer** 2016-04-07 15:47 UTC
Labels: needs info
