### ISSUE TITLE
[question]how to set LocalAddress for Channel?

### ISSUE THREAD

**Issue by PaniniGelato** [netty/netty#9154] opened 2019-05-17 08:32 UTC
My bootstrap code:
```
        Bootstrap bootstrap = new Bootstrap();
        MyRpcClientHandler handler = new MyRpcClientHandler();
        bootstrap.group(new NioEventGroup());
        bootstrap.channel(NioSocketChannel.class);
        bootstrap.option(ChannelOption.TCP_NODELAY, true);
        bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 30000);
        bootstrap.option(ChannelOption.SO_KEEPALIVE, true);
        bootstrap.handler(new ChannelInitializer<Channel>(){
            @Override
            protected void initChannel(Channel ch) throws Exception {                
                ch.pipeline().addLast("frame_encoder", new MyEncoder(true));
                ch.pipeline().addLast("frame_decoder", new MyDecoder(true));
                ch.pipeline().addLast("client_handler", handler);
            }
        });
```

My handler code:
```
public void channelActive(ChannelHandlerContext ctx) throws Exception {
        this.ctx = ctx;
        this.rpcClient.connected();
        LOGGER.info("channel : " + ctx.channel());
}
```

Running with netty-4.0.56,  it prints:
```
channel : [id: 0x5a50ab21, L:/11.1.2.3:38272 - R:/11.9.10.159:20013]
```

After upgrade to netty-4.1.36, it prints:
```
channel : [id: 0x48f60263, L:0.0.0.0/0.0.0.0:58081 ! R:/11.9.85.43:20013]
```

The localAddress should be 11.1.2.3 in my case

I've tried `bootstrap.localaddress("11.1.2.3", randomPort())`, but not work

Are there any Options or APIs to set LocalAddress for all Channel?

**Comment by normanmaurer** [comment] 2019-05-17 08:38
@PaniniGelato this should work... if it does not its a bug. I will have a look.

**Comment by qeesung** [comment] 2019-05-17 09:38
@PaniniGelato I can't reproduce this problem locally. Would you please provide more detailed, reproducible code snippets?

**Comment by PaniniGelato** [comment] 2019-05-17 11:13
> @PaniniGelato I can't reproduce this problem locally. Would you please provide more detailed, reproducible code snippets?

The server endpoints are written in cpp, I am not able to provide them.

In my case,  everything runs good with Netty-4.0.56,  but failed with "connection reset by peer" exception while trying to call writeAndFlush() after upgrade to 4.1.36 

I dont change any codes, except the version, the only difference I can tell is the LocalAddress of Channels, and the connect part seems OK

I'll try provide the client code later

**Comment by PaniniGelato** [comment] 2019-05-18 09:04
Running with netty-StringEncoder is OK,  looks like my legacy encoder/decoder dont work with 4.1.x

Trying to re-write them...thanks for help anyway

**Comment by normanmaurer** [comment] 2019-05-18 17:41
So can we close this one ?

**Closed** 2019-05-19 17:03 UTC
