### ISSUE TITLE
Netty3 NioWorker spin infinitely in write loop

### ISSUE THREAD

**Issue by Karry** [netty/netty#2360] opened 2014-04-03 15:35 UTC
Netty version: 3.9.0.Final

When we produce data stream slowly enough that newer fill up kernel buffer (or kernel is fast enough with transmiting) NioWorker is spinning in write loop related with one socket. As result, other events related with this worker are processed when stream ends (they are never processed in case of infinite stream).

I indentify two use cases how to reproduce this:

1) We have ChunkedWriteHandler in pipeline. In some handler we write (in worker thread context) ChunkedInput that slowly produces infinite stream. [ChunkedWriteHandler](https://github.com/netty/netty/blob/3.9/src/main/java/org/jboss/netty/handler/stream/ChunkedWriteHandler.java#L196) process chunks until channel "isWritable". I created simple http server with single worker. First client starts receiving data, but other waiting for response... https://gist.github.com/Karry/9955752

2) When ChunkedInput is written from other thread (A-thread), situation is different, but result is the same (can be). After some chunks, ChunkedWriteHandler can fill up write buffer (WriteRequestQueue), channel become non-writtable and A-thread ends its work. NioWorker continue with writting data to the kernel, when size of write queue is reduced under "low water mark", ChunkedWriteHandler is notified by ["interest event"](https://github.com/netty/netty/blob/3.9/src/main/java/org/jboss/netty/channel/socket/nio/AbstractNioChannel.java#L310) and writter buffer is filled up again. If kernel is fast enough, Netty worker is then spinning in "write0" method until stream ends.

Suggested solution: 
- Rewrite ChunkedWriteHandler that flush method is newer called from worker thread. This modification should solve case 1.
- Setup maximum time for spinning in write0. After this time, new write request should be enqueued and write0 method should be leaved.

I can help with possible solution because I need working ChunkedInput...

**Comment by normanmaurer** [comment] 2016-09-09 08:14
@trustin any news ?

**Comment by trustin** [comment] 2016-09-09 08:25
Nope. But I guess the problem is still there.

**Comment by Scottmitch** [comment] 2016-09-15 03:59
Netty 3 is EOL ... should we just close this as won't fix and upgrade to Netty 4.x is the answer?

**Comment by normanmaurer** [comment] 2017-12-13 13:45
Yes closing.

**Closed by normanmaurer** 2017-12-13 13:45 UTC
Labels: defect
