### ISSUE TITLE
IllegalArgumentException on AIX J9 1.6 (20121024_126067) with example-http2 demo in netty source code

### ISSUE THREAD

**Issue by D3Hunter** [netty/netty#6437] opened 2017-02-23 03:28 UTC
### Expected behavior
this demo should run without exception
the demo runs correctly with environment below, but not on AIX  j9 1.6 with jvm version `J9VM - ```
20121024_126067`
```
on windows, sun jdk 1.7
on linux, sun jdk 1.8
on aix, j9 jdk 1.6 with jvm version J9VM - 20110203_074623(notice this small difference)
```

### Actual behavior
```
----------------OUTBOUND--------------------
[id: 0x38163a7b, L:/127.0.0.1:33534 - R:/127.0.0.1:8080] DATA: streamId=5, padding=0, endStream=true, length=10, bytes=74657374206461746121
------------------------------------
Feb 22, 2017 5:15:04 PM io.netty.handler.codec.http2.Http2FrameLogger log
INFO: 
----------------OUTBOUND--------------------
[id: 0x38163a7b, L:/127.0.0.1:33534 - R:/127.0.0.1:8080] HEADERS: streamId=7, headers=DefaultHttp2Headers[:path: /whatever, :method: GET, :scheme: http, :authority: 127.0.0.1:8080, accept-encoding: gzip, accept-encoding: deflate], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
------------------------------------
Exception in thread "main" java.lang.IllegalArgumentException: a header value contains a prohibited character ' ': 127.0.0.1:8080
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.validateValueChar(DefaultHttpHeaders.java:431)
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:411)
Feb 22, 2017 5:15:04 PM io.netty.handler.codec.http2.Http2FrameLogger log
INFO: 
----------------OUTBOUND--------------------
[id: 0x38163a7b, L:/127.0.0.1:33534 - R:/127.0.0.1:8080] HEADERS: streamId=9, headers=DefaultHttp2Headers[:path: /thisispost, :method: POST, :scheme: http, :authority: 127.0.0.1:8080, accept-encoding: gzip, accept-encoding: deflate], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
------------------------------------
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:402)
	at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:318)
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:123)
	at io.netty.example.http2.helloworld.client.Http2Client.doRequest(Http2Client.java:118)
	at io.netty.example.http2.helloworld.client.Http2Client.main(Http2Client.java:101)
Feb 22, 2017 5:15:04 PM io.netty.handler.codec.http2.Http2FrameLogger log
```
**the `prohibited character` is `\0`** as it's invisible
### Steps to reproduce

use demo `io/netty/example/http2`  in `netty  source code`, i have change this demo to do `get `and `post` at same time, and repeat for `100` times.

### Minimal yet complete reproducer code (or URL to code)
Http2Client.java after change:
``` java
public final class Http2Client {

    static final boolean SSL      = System.getProperty("ssl") != null;
    static final String  HOST     = System.getProperty("host", "127.0.0.1");
    static final int     PORT     = Integer.parseInt(System.getProperty("port", SSL ? "8443" : "8080"));
    static final String  URL      = System.getProperty("url", "/whatever");
    static final String  URL2     = System.getProperty("url2", "/thisispost");
    static final String  URL2DATA = System.getProperty("url2data", "test data!");

    public static void main(String[] args) throws Exception {
        // Configure SSL.
        final SslContext sslCtx;
        if (SSL) {
            SslProvider provider = OpenSsl.isAlpnSupported() ? SslProvider.OPENSSL : SslProvider.JDK;
            sslCtx = SslContextBuilder.forClient().sslProvider(provider)
                /* NOTE: the cipher filter may not include all ciphers required by the HTTP/2 specification.
                 * Please refer to the HTTP/2 specification for cipher requirements. */
                    .ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .applicationProtocolConfig(new ApplicationProtocolConfig(Protocol.ALPN,
                            // NO_ADVERTISE is currently the only mode supported by both OpenSsl and JDK providers.
                            SelectorFailureBehavior.NO_ADVERTISE,
                            // ACCEPT is currently the only mode supported by both OpenSsl and JDK providers.
                            SelectedListenerFailureBehavior.ACCEPT, ApplicationProtocolNames.HTTP_2,
                            ApplicationProtocolNames.HTTP_1_1)).build();
        } else {
            sslCtx = null;
        }

        EventLoopGroup workerGroup = new NioEventLoopGroup();
        Http2ClientInitializer initializer = new Http2ClientInitializer(sslCtx, Integer.MAX_VALUE);

        try {
            // Configure the client.
            Bootstrap b = new Bootstrap();
            b.group(workerGroup);
            b.channel(NioSocketChannel.class);
            b.option(ChannelOption.SO_KEEPALIVE, true);
            b.remoteAddress(HOST, PORT);
            b.handler(initializer);

            // Start the client.
            Channel channel = b.connect().syncUninterruptibly().channel();
            System.out.println("Connected to [" + HOST + ':' + PORT + ']');

            // Wait for the HTTP/2 upgrade to occur.
            Http2SettingsHandler http2SettingsHandler = initializer.settingsHandler();
            http2SettingsHandler.awaitSettings(5, TimeUnit.SECONDS);

            HttpResponseHandler responseHandler = initializer.responseHandler();
            int streamId = 3;
            HttpScheme scheme = SSL ? HttpScheme.HTTPS : HttpScheme.HTTP;
            AsciiString hostName = new AsciiString(HOST + ':' + PORT);
            System.err.println("Sending request(s)...");
            for (int i = 0; i < 100; i++) {
                doRequest(channel, responseHandler, streamId, scheme, hostName);
            }
            responseHandler.awaitResponses(5, TimeUnit.SECONDS);
            System.out.println("Finished HTTP/2 request(s)");

            // Wait until the connection is closed.
            channel.close().syncUninterruptibly();
        } finally {
            workerGroup.shutdownGracefully();
        }
    }

    private static void doRequest(Channel channel, HttpResponseHandler responseHandler, int streamId, HttpScheme scheme,
            AsciiString hostName) {
        if (URL != null) {
            // Create a simple GET request.
            FullHttpRequest request = new DefaultFullHttpRequest(HTTP_1_1, GET, URL);
            request.headers().add(HttpHeaderNames.HOST, hostName);
            request.headers().add(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), scheme.name());
            request.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);
            request.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.DEFLATE);
            responseHandler.put(streamId, channel.writeAndFlush(request), channel.newPromise());
            streamId += 2;
        }
        if (URL2 != null) {
            // Create a simple POST request with a body.
            FullHttpRequest request = new DefaultFullHttpRequest(HTTP_1_1, POST, URL2,
                    Unpooled.copiedBuffer(URL2DATA.getBytes(CharsetUtil.UTF_8)));
            request.headers().add(HttpHeaderNames.HOST, hostName);
            request.headers().add(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), scheme.name());
            request.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);
            request.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.DEFLATE);
            responseHandler.put(streamId, channel.writeAndFlush(request), channel.newPromise());
            streamId += 2;
        }
    }
}

```
### Netty version
`4.1.8.FINAL`
### JVM version (e.g. `java -version`)
run demo below with ibm j9 JDK, version:
```
java version "1.6.0"
Java(TM) SE Runtime Environment (build pwi3260sr12ifix-20121108_01(SR12+IV31417))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows XP x86-32 jvmwi3260sr12-20121
024_126067 (JIT enabled, AOT enabled)
J9VM - 20121024_126067
JIT  - r9_20120914_26057
GC   - 20120928_AA)
JCL  - 20121108_01
```
### OS version (e.g. `uname -a`)
`AIX JT-OWT01 1 6 00f914cd4c00`

**Comment by Scottmitch** [comment] 2017-02-23 05:25
Can you clarify what the issue is? It seems like you are setting the contents of `HOST` to contain a character that is not valid, and the client throws an exception indicating this. This seems like expected behavior.

You increment streamId in `doRequest` but this only impacts the method's local copy. Then you continue to use the `streamId` in the loop to call this method (which doesn't change). This results in the client receiving responses that it doesn't expect which is a bug.

**Comment by D3Hunter** [comment] 2017-02-23 06:21
@Scottmitch  
> use demo io/netty/example/http2 in netty source code, i have change this demo to do getand post at same time, and repeat for 100 times.

this code works on platforms below, i have test it repeatly, but not on `AIX J9 1.6 (20121024_126067) `:
```
on windows, sun jdk 1.7
on linux, sun jdk 1.8
on aix, j9 jdk 1.6 with jvm version J9VM - 20110203_074623(notice this small difference)
```

**Comment by Scottmitch** [comment] 2017-02-23 17:49
The code also "works" (minus the bug identified in https://github.com/netty/netty/issues/6437#issuecomment-281898223) on my machine. I don't see the exception you indicate and this is why I would like to know your exact environment when starting the application. For example what is the value of `HOST` and `PORT`? Can you provide a complete reproducer (which includes how you set all the variables) ... the goal being I can run your code and reproduce the issue.

**Comment by D3Hunter** [comment] 2017-02-24 03:29
it only throw this exception on 
```
java version "1.6.0"
Java(TM) SE Runtime Environment (build pwi3260sr12ifix-20121108_01(SR12+IV31417))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows XP x86-32 jvmwi3260sr12-20121
024_126067 (JIT enabled, AOT enabled)
J9VM - 20121024_126067
JIT  - r9_20120914_26057
GC   - 20120928_AA)
JCL  - 20121108_01


OS version (e.g. uname -a)

AIX JT-OWT01 1 6 00f914cd4c00
```

it's on a machine of our client. i cannot reproduce this issue in my local environment either.

**Comment by D3Hunter** [comment] 2017-02-24 03:38
I have describe all the information i know to reproduce this issue in the initial description.
can you be specific about  what `exact environment` is  except what has been described in the initial description.
@Scottmitch

**Comment by D3Hunter** [comment] 2017-02-24 03:48
I guess it's a bug of `AIX J9 1.6 (20121024_126067)`, because `AIX J9 1.6 (20110203_074623)` and `AIX J9 1.7` works.

**Comment by Scottmitch** [comment] 2017-02-24 04:57
Which ever environment this reproduces in please add the following code and provide the results:

```java
private static void doRequest(Channel channel, HttpResponseHandler responseHandler, int streamId, HttpScheme scheme, AsciiString hostName) {
            System.err.println("HOST.length(): " + HOST.length() + " HOST: [" + HOST + "]");
            System.err.println("hostName.length(): " + hostName.length() + " hostName: [" + hostName + "]");
            byte[] hostNameBytes = hostName.toByteArray();
            for (byte hostNameByte : hostNameBytes) {
                System.err.print((int) hostNameByte + " ");
            }
            System.err.println();
...
}
```

Also is it necessary to modify the client? Based upon the exception it seems like you should be able to reproduce this on the first request with an un-modified `Http2Client`.

**Comment by D3Hunter** [comment] 2017-02-24 06:52
the thing is it only reproduce at some request, not all.
i put full log in my fork of `netty` project, check it out.
[netty client log](https://github.com/D3Hunter/netty/blob/4.1/issue-6437/netty_client.log)
[netty server log](https://github.com/D3Hunter/netty/blob/4.1/issue-6437/netty_server.log)

**PS:**
the full scenerio is we're using `grpc` to send messages, but we encounter `invalid byte sequence` error.
but **after running some demo, we found it comes from `netty` itself.**
[grpc client log](https://github.com/D3Hunter/netty/blob/4.1/issue-6437/grpc-client.log)
[grpc server log](https://github.com/D3Hunter/netty/blob/4.1/issue-6437/grpc-server.log)
as you can see from `grpc server log`, http2 header has all been messed up, `method` should be `POST` but server side received `T\0\0\0`, `scheme` should be `http`, but received `p\0\0\0`:
```
----------------INBOUND--------------------
.....
headers=GrpcHttp2RequestHeaders[: ilers, :authority: .0.0.1:12345, :path: llector.TransactionData/storeStringInt32, :method: T, :scheme: p, content-type: lication/grpc, user-agent: c-java-netty, grpc-accept-encoding: p, grpc-census-bin: ]
.....
```

**Comment by Scottmitch** [comment] 2017-02-24 07:37
I don't see the output in the log files I requested in https://github.com/netty/netty/issues/6437#issuecomment-282204393. Please add this and report back. I don't understand why this would only happen some times on the client for a variable whose content is fixed.

Can you provide a reproducer for the gRPC use case (/cc @nmittler)?

**Comment by D3Hunter** [comment] 2017-02-24 09:18
right now i don't have chance to run anything on our client's environment, i'll supply more info when i have it.

**Comment by CodingFabian** [comment] 2017-02-24 09:37
Thanks for bringing this up. We also have reports of an AIX user who says that http2 connection fails. We will get some version details and come up with a plan on how to debug it.
Right now my best quess is an encoding issue

**Comment by normanmaurer** [comment] 2017-02-24 09:38
Do you know what endianness AIX uses there ?


2017-02-24 10:37 GMT+01:00 Fabian Lange <notifications@github.com>:

**Comment by CodingFabian** [comment] 2017-02-24 11:47
So the client where we cannot connect using http2 uses:
 IBM J9 VM (build 2.8, JRE 1.8.0 AIX ppc64-64 Compressed References 20161013_322271 (JIT enabled, AOT enabled)

**Comment by normanmaurer** [comment] 2017-02-24 13:05
@Scottmitch @D3Hunter I wonder if this is maybe somehow also related to https://github.com/netty/netty/issues/6373 as this also uses Java6 when issues show up

**Comment by Scottmitch** [comment] 2017-02-24 21:44
@CodingFabian - thanks.

@normanmaurer- in this case - ppc64 -> big endian and JRE 1.8 ... so not sure if it is specific to idk 1.6. They do have AIX and IBM J9 in common though.

> right now i don't have chance to run anything on our client's environment, i'll supply more info when i have it.

@D3Hunter - Sounds good thanks. Keep us posted.

Also you listed the java version as:

```
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows XP x86-32
```

and the OS version as:

```
AIX JT-OWT01 1 6 00f914cd4c00
```

Is it expected to have a Windows XP build of J9 running on AIX?

**Comment by CodingFabian** [comment] 2017-02-24 22:03
Its possible my problem is different, but it also has http2 in common, which triggered my attention :)

**Comment by CodingFabian** [comment] 2017-03-02 09:40
I got more intel on this. The same problem with our http2 connection is reported by another customer
java version "1.8.0" 
Java(TM) SE Runtime Environment (build pxp3280sr4fp1-20170215_01(SR4 FP1)) 
IBM J9 VM (build 2.8, JRE 1.8.0 Linux ppc-32 20170209_336038 (JIT enabled, AOT enabled) 
J9VM - R28_20170209_0201_B336038 
JIT - tr.r14.java.green_20170125_131456 
GC - R28_20170209_0201_B336038 
J9CL - 20170209_336038) 
JCL - 20170215_01 based on Oracle jdk8u121-b13

Linux 2.6.32-642.13.1.el6.ppc64 #1 SMP Wed Nov 23 16:02:25 EST 2016 ppc64 ppc64 ppc64 GNU/Linux


now that I am pretty sure there is an encoding problem probably related to endianess, i am going to look for a way to reproduce and fix it.

**Comment by Scottmitch** [comment] 2017-03-02 17:27
> I am pretty sure there is an encoding problem probably related to endianess

Seems reasonable ... it would be nice to have a big endian CI server 😢

**Comment by CodingFabian** [comment] 2017-03-02 21:00
I tried to setup a qemu based debian ppc, but failed getting either ibms or oracles jdk 8 running.

**Comment by Scottmitch** [comment] 2017-03-03 01:57
I have run Netty builds on qemu with ppc x86 debian in the past ... but I was only able to emulate a single CPU and it is extremely slow ... not something we can use for CI builds.

**Comment by CodingFabian** [comment] 2017-03-07 09:34
IBM offers open source contributers a programm to get access to a linux on power, maybe thats sufficient to reproduce and fix:
https://www-356.ibm.com/partnerworld/wps/servlet/ContentHandler/stg_com_sys_power-development-platform

I looked into the http2 codec, and i see that it decodes stuff forcing a little endian encoding. is that right?

**Comment by normanmaurer** [comment] 2017-03-07 09:37
@CodingFabian can you point me to the code where it forces to little endian ?

**Comment by CodingFabian** [comment] 2017-03-07 09:40
HPack decoding:
https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java#L455

**Comment by meier-christoph** [comment] 2017-03-07 15:12
Hi guys,
I can help with debugging and provide some logs.

$ cat /proc/version
Linux version 2.6.32-642.13.1.el6.ppc64 (mockbuild@ppc-030.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Wed Nov 23 16:02:25 EST 2016

$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxp3280sr4fp1-20170215_01(SR4 FP1))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux ppc-32 20170209_336038 (JIT enabled, AOT enabled)
J9VM - R28_20170209_0201_B336038
JIT  - tr.r14.java.green_20170125_131456
GC   - R28_20170209_0201_B336038
J9CL - 20170209_336038)
JCL - 20170215_01 based on Oracle jdk8u121-b13

I used the client by D3Hunter (with the additional logs requested) and everything else from master (a9d7c72cde9d522161e7275df6490a8b9765d57f) i.e. netty-example-4.1.9.Final-SNAPSHOT

[http2-client-jdk8.txt](https://github.com/netty/netty/files/824793/http2-client-jdk8.txt)
[http2-server-jdk8.txt](https://github.com/netty/netty/files/824792/http2-server-jdk8.txt)

Just ask if you need anything else.

Chris

**Comment by Scottmitch** [comment] 2017-03-07 17:20
@CodingFabian - IIUC HPACK's integer representation is always "little endian" (see https://tools.ietf.org/html/rfc7541#section-5.1).

**Comment by Scottmitch** [comment] 2017-03-07 17:24
@meier-christoph - Thanks for offering to help. I don't see the same exception that was originally reported in this issue ... are you seeing the same failure or any failure? Can you please fix the bug I identified above https://github.com/netty/netty/issues/6437#issuecomment-281898223 and also add the debug output in https://github.com/netty/netty/issues/6437#issuecomment-282204393 if you are able to reproduce.

**Comment by CodingFabian** [comment] 2017-03-07 17:26
@Scottmitch @meier-christoph is using our software which uses netty and its loosing and reconnecting http2 connections on their ppc systems. He asked if he could help, and I said that we believe it is caused by the same problem. It might not hold, and we are actually making a debug build of our software which is currently potentially swallowingthe root cause.

**Comment by meier-christoph** [comment] 2017-03-07 19:07
sorry my bad, I should have uploaded all files not just the jdk8

on jdk6 I think I have the expected error (L:356) and the logs requested are in there as well

on the other jdks it seems to work

```
----------------OUTBOUND--------------------
[id: 0xa8bb9d45, L:/127.0.0.1:35376 - R:/127.0.0.1:8080] HEADERS: streamId=55, headers=DefaultHttp2Headers[:path: /whatever, :method: GET, :scheme: http, :authority: 127.0.0.1:8080, accept-encoding: gzip, accept-encoding: deflate], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
------------------------------------
56 48 
HOST.length(): 9 HOST: [127.0.0.1]
hostName.length(): 14 hostName: [127.0.0.1:8080]
49 50 55 46 48 46 48 46 49 58 56 48 56 48 
HOST.length(): 9 HOST: [127.0.0.1]
hostName.length(): 14 hostName: [127.0.0.1:8080]
49 50 55 46 48 46 48 46 49 58 56 48 56 48 
15:53:58.728 [nioEventLoopGroup-2-1] INFO  i.n.e.h.h.c.Http2ClientInitializer - 
```

```
$ java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxp3260sr16fp41-20170215_04(SR16 FP41))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux ppc-32 jvmxp3260sr16fp40-20161215_329869 (JIT enabled, AOT enabled)
J9VM - 20161215_329869
JIT  - r9_20160630_120368
GC   - GA24_Java6_SR16_20161215_0927_B329869)
JCL  - 20170215_01
```

[http2-server-jdk6.txt](https://github.com/netty/netty/files/825437/http2-server-jdk6.txt)
[http2-client-jdk6.txt](https://github.com/netty/netty/files/825438/http2-client-jdk6.txt)

and for jdk7 as well (no error so far)

```
$ java -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build pxp3270sr10fp1-20170215_01(SR10 FP1))
IBM J9 VM (build 2.6, JRE 1.7.0 Linux ppc-32 20170111_332921 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR10_20170111_1358_B332921
JIT  - tr.r11_20170107_130494
GC   - R26_Java726_SR10_20170111_1358_B332921
J9CL - 20170111_332921)
JCL - 20170215_01 based on Oracle jdk7u131-b12
```

[http2-client-jdk7.txt](https://github.com/netty/netty/files/825469/http2-client-jdk7.txt)
[http2-server-jdk7.txt](https://github.com/netty/netty/files/825470/http2-server-jdk7.txt)

**Comment by meier-christoph** [comment] 2017-03-07 19:36
I also tried the original client (io.netty.example.http2.helloworld.client.Http2Client) but could not reproduce the error.

[http2-server-jdk6-err.txt](https://github.com/netty/netty/files/825521/http2-server-jdk6-err.txt)
[http2-server-jdk6-out.txt](https://github.com/netty/netty/files/825522/http2-server-jdk6-out.txt)
[http2-client-jdk6-err.txt](https://github.com/netty/netty/files/825524/http2-client-jdk6-err.txt)
[http2-client-jdk6-out.txt](https://github.com/netty/netty/files/825523/http2-client-jdk6-out.txt)

and once more with the streamId incremented (and the error is showing)

[http2-client-jdk6-err.txt](https://github.com/netty/netty/files/825550/http2-client-jdk6-err.txt)
[http2-client-jdk6-out.txt](https://github.com/netty/netty/files/825553/http2-client-jdk6-out.txt)
[http2-server-jdk6-err.txt](https://github.com/netty/netty/files/825552/http2-server-jdk6-err.txt)
[http2-server-jdk6-out.txt](https://github.com/netty/netty/files/825551/http2-server-jdk6-out.txt)

hope it helps

**Comment by Scottmitch** [comment] 2017-03-07 20:10
@meier-christoph - What does `PlatformDependent#hasUnsafe()` with the JDK6 configuration? If this returns `true` can you try to reproduce with `-Dio.netty.noUnsafe=true` as a JVM argument?

**Comment by meier-christoph** [comment] 2017-03-08 09:29
@Scottmitch it was indeed returning `true` but for all jdks not just jdk6

I ran the tests again (with the jvm argument) but could not reproduce the issue

[http2-client-jdk6.txt](https://github.com/netty/netty/files/827089/http2-client-jdk6.txt)
[http2-server-jdk6.txt](https://github.com/netty/netty/files/827090/http2-server-jdk6.txt)

**Comment by CodingFabian** [comment] 2017-03-08 13:45
Got granted access by IBM to a Power8 system. But apparently they only run LE Linuxes. Will see if it provides any intel on the problem.

**Comment by johnou** [comment] 2017-03-08 13:48
@CodingFabian bonus points if you can run the full Netty testsuite 😉

**Comment by CodingFabian** [comment] 2017-03-08 15:03
Ill try :-)

The system is
´´´
[u0018404@sys-86064 ~]$ uname -a
Linux sys-86064 3.10.0-514.el7.ppc64le #1 SMP Wed Oct 19 11:27:06 EDT 2016 ppc64le ppc64le ppc64le GNU/Linux
[u0018404@sys-86064 ~]$ /home/u0018404/jdk/bin/java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxl6480sr4fp1-20170215_01(SR4 FP1))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux ppc64le-64 Compressed References 20170209_336038 (JIT enabled, AOT enabled)
J9VM - R28_20170209_0201_B336038
JIT  - tr.r14.java.green_20170125_131456
GC   - R28_20170209_0201_B336038_CMPRSS
J9CL - 20170209_336038)
JCL - 20170215_01 based on Oracle jdk8u121-b13
´´´
but i get

´´´
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-tools) @ netty-parent ---
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireProperty failed with message:
x86_64 JDK must be used.
´´´
suggestions?

**Comment by normanmaurer** [comment] 2017-03-08 15:12
Just disable the enforcer plugin for now

**Comment by CodingFabian** [comment] 2017-03-08 15:23
I was able to reproduce our issue with above ibm jdk, so its not endianness, as the vm is LE.
however it works using 

/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.ppc64le/bin/java
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

so maybe it is indeed different, and possibly some ssl issues with the ibm jdk.

**Comment by CodingFabian** [comment] 2017-03-08 15:52
netty compile fails because there is no compatible tcnative. maybe i can comment that stuff out somehow

**Comment by Scottmitch** [comment] 2017-03-08 17:08
@meier-christoph - It sounds like there may be a bug in our usage of `sun.misc.Unsafe` or in IBM's implementation on jdk6. `AsciiString` (which is the class we use to store header data in for codec-http2) uses unsafe to avoid some extra bounds checking [1]. Can you comment out these lines in `AsciiString`, keep unsafe enabled, and see if you are able to reproduce on jdk6?

We ignore `UNSAFE.arrayIndexScale(byte[].class)` as it is generally assumed to be 1 for `byte[]`. We should either use this value, or explicitly enforce this though. Could you put the following line of code at `PlatformDependent0.java:231` [2] and report back this value:

```java
long byteArrayIndexScale = UNSAFE.arrayIndexScale(byte[].class);
logger.info("byteArrayIndexScale: {}", byteArrayIndexScale);
``` 

[1] https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AsciiString.java#L331
[2] https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L231

**Comment by Scottmitch** [comment] 2017-03-08 17:22
PR https://github.com/netty/netty/pull/6515 will explicitly enforce the assumptions made about `UNSAFE.arrayIndexScale(byte[].class)`.

**Comment by meier-christoph** [comment] 2017-03-09 09:52
@Scottmitch - I ran the sample again with the changes you requested (I also added a log for `UNSAFE.arrayBaseOffset(byte[].class)` just in case).

The run was successfull and did complete without errors. 

```
10:48:08.648 [main] INFO  i.n.util.internal.PlatformDependent0 - byteArrayIndexScale: 1
10:48:08.652 [main] INFO  i.n.util.internal.PlatformDependent0 - byteArrayBaseOffset: 16
```

[http2-client-jdk6.txt](https://github.com/netty/netty/files/830386/http2-client-jdk6.txt)
[http2-server-jdk6.txt](https://github.com/netty/netty/files/830387/http2-server-jdk6.txt)

**Comment by Scottmitch** [comment] 2017-03-09 17:18
Thanks ... interesting ... if `byteArrayIndexScale == 1` then I don't think we are using `Unsafe` incorrectly. However by removing the usage of `Unsafe ` in this case mitigating the issue seems to point to unexpected behavior from `Unsafe `. Since IBM's J9 JRE 1.6.0 is the only VM we have observed to have this issue it makes me suspicious of this VM. We could remove `Unsafe` in this specific case, but `Unsafe` is used elsewhere and there is no guarantee we won't also see unexpected behavior there too.

Can you change the code around [DefaultHttpHeaders.java:431](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L431) to the following:

```java
                case 0x0: // NULL
                {
                    if (seq instanceof AsciiString) {
                        AsciiString asciiString = (AsciiString) seq;
                        StringBuilder sb = new StringBuilder();
                        sb.append("arrayOffset: ").append(asciiString.arrayOffset())
                          .append("length: ").append(asciiString.length())
                          .append("isEntireArrayUsed: ").append(asciiString.isEntireArrayUsed())
                          .append("array: ");
                        int end = asciiString.arrayOffset() + asciiString.length();
                        byte[] array = asciiString.array();
                        for (int i = asciiString.arrayOffset(); i < end; ++i) {
                            sb.append((int) array[i]).append(' ');
                        }
                        byte[] bytesCopy = asciiString.toByteArray();
                        sb.append("bytesCopy len: ").append(bytesCopy.length)
                          .append("bytesCopy val: ");
                        for (byte hostNameByte : bytesCopy) {
                            sb.append((int) hostNameByte).append(' ');
                        }
                        System.err.println(sb.toString());
                    }
                    throw new IllegalArgumentException("a header value contains a prohibited character '\0': " + seq);
                }
```

It would also be helpful to know what index we are failing on. Put a breakpoint on the `throw new IllegalArgumentException` and step up in the call stack to see the index and report back.

**Comment by meier-christoph** [comment] 2017-03-09 17:56
@Scottmitch - I added the index to the logs instead of debugging it, seems to be the first char after the `:` ?

```
for (int index = 0; index < seq.length(); index++) {
     state = validateValueChar(seq, state, seq.charAt(index), index);
}
```
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L411

```
index: 11
arrayOffset: 0
length: 14
isEntireArrayUsed: true
array: 49 50 55 46 48 46 48 46 49 58 56 48 56 48 
bytesCopy len: 14
bytesCopy val: 49 50 55 46 48 46 48 46 49 58 56 48 56 48 
```

[http2-client-jdk6.txt](https://github.com/netty/netty/files/831857/http2-client-jdk6.txt)
[http2-server-jdk6.txt](https://github.com/netty/netty/files/831858/http2-server-jdk6.txt)

**Comment by Scottmitch** [comment] 2017-03-09 18:51
thanks. this adds to the theory that the issue is related to `Unsafe`. the value at index 11 is ascii code `48` which is ascii character `0` ... these byte arrays are obtained without using `Unsafe`.

Can you also add the following to see the contents when `Unsafe` is used.

```java
sb.append("asciiString byteAt value:");
for (int i = 0; i < asciiString.length(); ++i) {
  sb.append((int) asciiString.byteAt(i)).append(' ');
}
```

**Comment by meier-christoph** [comment] 2017-03-10 08:57
@Scottmitch - new logs with byteAt

```
index: 11
arrayOffset: 0
length: 14
isEntireArrayUsed: true
array: 49 50 55 46 48 46 48 46 49 58 56 48 56 48 
bytesCopy len: 14
bytesCopy val: 49 50 55 46 48 46 48 46 49 58 56 48 56 48 
asciiString byteAt value: 825374510 842477104 925773870 774909488 808333358 774909489 808333626 774978104 825899056 976760888 942684208 808988672 942669824 805306579 
```

[http2-client-jdk6.txt](https://github.com/netty/netty/files/833385/http2-client-jdk6.txt)
[http2-server-jdk6.txt](https://github.com/netty/netty/files/833384/http2-server-jdk6.txt)

**Comment by Scottmitch** [comment] 2017-03-11 21:44
@meier-christoph - Thanks. Just to confirm you have never been able to reproduce this with IBM's J9 JVM versions JRE 1.7.0 or 1.8.0, correct? The values obtained from unsafe are clearly not what we would expect and if the issue is isolated to J9 JRE 1.6.0 then I would recommend the following:

- Report an issue to IBM
- Disable unsafe when running on this JVM (`-Dio.netty.noUnsafe=true`)

If there is a generic/reliable way to detect this JVM configuration we could disable unsafe by default in Netty when this JVM is used.

**Comment by meier-christoph** [comment] 2017-03-13 09:13
@Scottmitch - None of the other JVMs we use were able to reproduce this issue.

However, I got an other message when using different combinations of jvms together.

```
User Event Triggered: UPGRADE_SUCCESSFUL
Exception in thread "main" java.lang.IllegalStateException: Timed out waiting for settings
	at io.netty.example.http2.helloworld.client.Http2SettingsHandler.awaitSettings(Http2SettingsHandler.java:49)
	at io.netty.example.http2.helloworld.client.Http2Client2.main(Http2Client2.java:103)
```

This should probably be moved to a different ticket but still, there are only 3 combinations working as expected.

 \ | server jvm6 | server jvm7 | server jvm8
-- | -- | -- | --
| __client jvm6__ | F | F | T |
| __client jvm7__ | Ok | Ok | T |
| __client jvm8__ | T | T | Ok |

F: The failure initialy described by this issue
T: The timeout I got during those final tests
Ok: it is working fine

All the logs are available here:
[logs.zip](https://github.com/netty/netty/files/837683/logs.zip)

**Comment by Scottmitch** [comment] 2017-03-31 23:02
@meier-christoph - Interesting. The timeout does seem like a different (although maybe related) issue. Would you mind opening another issue for this?

**Comment by normanmaurer** [comment] 2017-05-30 09:28
@meier-christoph ping

**Comment by meier-christoph** [comment] 2017-05-30 18:28
@normanmaurer still here but not much time available, the hack with no unsafe worked for us and we didn't push it any further

**Comment by normanmaurer** [comment] 2017-08-06 13:35
I will close this for now... please re-open if the issue still exists in the latest release

**Closed by normanmaurer** 2017-08-06 13:35 UTC
