### ISSUE TITLE
java.io.IOException: Connection reset by peer ？

### ISSUE THREAD

**Issue by honyee** [netty/netty#5936] opened 2016-10-24 08:49 UTC
@trustin 
 Hi, trustin：
    My netty application have a exception ,please help me look the question , Thank you ! 

> Exception:_ WARN An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Scottmitch** [comment] 2016-10-24 16:29
Can you describe your issue? `Connection reset by peer` is typically a result of your peer sending a TCP RST to you ... which without more context doesn't say much.

**Comment by honyee** [comment] 2016-10-25 09:15
@Scottmitch  Thank you, This problem has been solved，Is due to the load balance caused by the exception !

**Comment by Scottmitch** [comment] 2016-10-27 01:42
@honyee - Thanks for confirming. I will close this for now. If you could be more descriptive about how you resolved the issue that also may help users who face similar issues in the future.

**Closed by Scottmitch** 2016-10-27 01:42 UTC

**Comment by kiransunkari** [comment] 2017-05-29 06:06
@honyee   how  did you solve this problem , the same problem arised in the production for us

**Comment by xptree** [comment] 2017-09-05 21:39
@honyee how did you solve this problem? could you be more descriptive about the load balance issues?

**Comment by velikanov** [comment] 2018-01-23 11:05
@honyee you know what I want to write here :)

**Comment by debashisdeb** [comment] 2018-02-22 12:30
HOW DID YOU 😄

**Comment by youngss56** [comment] 2018-04-20 19:11
hi, how did you resolve the issue? how did you know it's Load Balance caused it? I am getting the same message

**Comment by bduisenov** [comment] 2018-07-30 20:26
+1

**Comment by MarsYoung** [comment] 2018-07-31 03:05
any one can post this solution?  catch the exception in java or forbidden these request?

**Comment by dyorgio** [comment] 2019-04-24 20:13
You can supress this error (Caused by client closing connection between comunication) by implementing method exceptionCaught in your Handler:
```java
@Override
public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
    // ignore, just a example
}
```

**Comment by lby1992** [comment] 2019-08-22 06:01
@honyee I want to know that too, thanks.

**Comment by TheJacobKim** [comment] 2019-10-10 10:53
How did you solve this issue.

**Comment by echojuliett** [comment] 2019-12-02 08:08
Anyone who solved this issue?
