### ISSUE TITLE
ClassCastException in PooledByteBuf

### ISSUE THREAD

**Issue by rockwotj** [netty/netty#7231] opened 2017-09-19 21:15 UTC
Getting this error in our netty client.

```
java.lang.ClassCastException: java.lang.String cannot be cast to [B
        at io.netty.buffer.PoolArena$HeapArena.memoryCopy(PoolArena.java:669)
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:399) 
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:116) 
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:271) 
        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:251) 
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:831) 
        at io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:66) 
```

### Netty version
4.0.50.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

### OS version (e.g. `uname -a`)
Linux hostname 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rockwotj** [comment] 2017-09-19 22:04
Also seeing:

```
java.lang.ArrayIndexOutOfBoundsException: null
        at io.netty.buffer.PoolArena$HeapArena.memoryCopy(PoolArena.java:713) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.PoolArena$HeapArena.memoryCopy(PoolArena.java:669) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:399) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:116) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:271) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:251) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:831) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:66) ~[firebase-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

**Comment by normanmaurer** [comment] 2017-09-20 00:21
interesting... what happens if you disable Unsafe ?

`-Dio.netty.noUnsafe=true`

Also is it easy to reproduce and can you provide a reproducer at all ?

**Comment by rockwotj** [comment] 2017-09-20 01:21
It is not easy to reproduce, and I don't have a reproducer at all, this started happening on our servers after many days, and seemingly at random.

I switched to UnpooledBuffers which has fixed the problem, but I can try with disabling unsafe.

**Comment by rockwotj** [comment] 2017-09-20 01:29
If I disable the unsafe, then we cannot use Epoll sockets which we need to set `EpollChannelOption.TCP_USER_TIMEOUT`

**Comment by normanmaurer** [comment] 2017-09-20 05:13
Got it… I will need to have a deeper look :(

**Comment by normanmaurer** [comment] 2017-09-20 14:56
@rockwotj can you give some more details about what GC you are using etc ?

**Comment by rockwotj** [comment] 2017-09-20 15:03
Here are some of the important GC related flags:
```
-XX:+AggressiveOpts -XX:+UseG1GC -XX:-UseNUMA -XX:+UseStringDeduplication
```

**Comment by normanmaurer** [comment] 2017-09-20 18:29
@rockwotj can you also tell me what is logged in startup of the app for unaligned access ? Like here:

```
11:29:06.601 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true

```

**Comment by normanmaurer** [comment] 2017-09-20 18:44
Seems related to https://github.com/netty/netty/issues/6133

**Comment by rockwotj** [comment] 2017-09-20 22:05
It does seem related, here is the output:

```
21:59:59.848 [main] DEBUG i.n.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
21:59:59.849 [main] DEBUG i.n.util.internal.PlatformDependent0 - Java version: 8
21:59:59.850 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
21:59:59.850 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
21:59:59.851 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
21:59:59.851 [main] DEBUG i.n.util.internal.PlatformDependent0 - direct buffer constructor: available
21:59:59.852 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
21:59:59.852 [main] DEBUG i.n.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
21:59:59.852 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
21:59:59.852 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
21:59:59.853 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
21:59:59.853 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
21:59:59.854 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: true
21:59:59.854 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: [redacted] bytes
21:59:59.854 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
21:59:59.855 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
```

**Comment by normanmaurer** [comment] 2017-09-20 23:38
@rockwotj ok I hoped it would log false. So back to trying to find something in our code :( Would it be possible to get a heap dump once this happens or not (I kind of guess I know what the answer will be).

**Comment by rockwotj** [comment] 2017-09-20 23:46
Yeah thank you for looking :/ I can't give you a heap dump, but I'll see if I can get this to happen in our staging environment. If I can I'll take a heap dump and maybe I can find something. I'll ask for pointers if I get there however.

**Comment by normanmaurer** [comment] 2017-09-26 12:25
@rockwotj any update ? also do you "transfer" the ownership of a `ByteBuf` from one Thread to another or is everything just happening one one thread ?

**Comment by rockwotj** [comment] 2017-09-26 14:07
No update. I haven't yet reproduced this, but still trying. 

I serialize the byte buf on one thread pool then pass it off to an event loop to be sent. I am marking, resetting reader indexes and calling retain so I can preform retries without reserializing.

I'll try to get a minimal example of what I'm doing in a gist

**Comment by normanmaurer** [comment] 2017-09-26 18:12
@rockwotj thanks

**Comment by Apache9** [comment] 2017-09-27 01:10
You can try upgrading your java version. When testing HBase with G1GC, we found that under heavy load the JVM will crash randomly, at least for 1.8.0_91. It seems that the heap is corrupted. When upgrading to 1.8.0_111 the problem is gone. So I think there must be something wrong with the G1GC implementation before 1.8.0_111.

**Comment by normanmaurer** [comment] 2017-09-27 08:56
@Apache9 interesting... Do you have any jira issues for this ? Would be interested to read up on it.

**Comment by rockwotj** [comment] 2017-09-27 12:54
@normanmaurer I have compiled an example of almost exactly what we're doing. I can't put it on GitHub without going though hoops so I'm going to email it to you.

**Comment by rockwotj** [comment] 2017-09-27 12:55
We're upgrading to Java9 soon, so I might try it again after that's rolled out.

**Comment by Apache9** [comment] 2017-09-27 13:13
@normanmaurer Sorry, we just tested it inside our company and as long as the problem is gone after we upgrade the java version, we had not post it out.

One of the crash log is
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f72c0bc0784, pid=24181, tid=140130494002944
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 )
# Problematic frame:
# V  [libjvm.so+0x5c2784]  G1ParScanThreadState::copy_to_survivor_space(InCSetState, oopDesc*, markOopDesc*)+0x174
```

There is a similar issue here:
https://bugs.openjdk.java.net/browse/JDK-8143310

But was closed as Cannot reproduce as the developer said that it is really hard to debug...

**Comment by rockwotj** [comment] 2017-09-27 13:15
I feel like these are difference issues. I didn't get any segfaults.

**Comment by Apache9** [comment] 2017-09-27 13:22
As long as the heap is corrupted then everything is possible I think. I had seen it crashed at other place. Though I haven't seen any ClassCastException...

**Comment by normanmaurer** [comment] 2017-10-25 12:47
@rockwotj did you see it again and if so any new ideas ?

**Comment by rockwotj** [comment] 2017-10-25 14:37
I ended up switching back to an `Unpooled` buffer and haven't seen this issue since then. I'm in the middle of rolling out Java 9 so I might try again after we've upgraded.

**Comment by normanmaurer** [comment] 2018-11-09 19:11
I will close this as we did not receive any reports like this for a long time, so I assume we fixed it.

**Closed by normanmaurer** 2018-11-09 19:11 UTC
