### ISSUE TITLE
FixedChannelPool close(Async) still blocks after rarely "An event executor terminated with non-empty task queue"

### ISSUE THREAD

**Issue by boaks** [netty/netty#9603] opened 2019-09-25 14:45 UTC
Since version 4.1.25 I observed in 4.1.26, 4.1.39, and 4.1.41, that using a  
`FixedChannelPool` on the client side causes trouble, when it gets closed. That occurs randomly, if my test repeats to open and close connections. The same tests, but using `SimpleChannelPool` works proper (as expected by me).

The effect is reported with:

> 16:11:30.781 [nioEventLoopGroup-657-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 1 thread-local buffer(s) from thread: nioEventLoopGroup-657-1
> 16:11:30.781 [nioEventLoopGroup-658-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 2 thread-local buffer(s) from thread: nioEventLoopGroup-658-1
> 16:11:30.781 [nioEventLoopGroup-658-1] WARN io.netty.util.concurrent.SingleThreadEventExecutor - An event executor terminated with non-empty task queue (1)
> 

and after that, stopping the "groups" on shutdown hangs always. 

I would expect, that closing (maybe async) a `FixedChannelPool" didn't stop my system from being able to shutdown connections.

It occurs with openjdk version "1.8.0_222" on ubuntu 18.05, and oracle version 1.8.0_221 on Windows 10.

There have been some similar issues as #8398 or #8238 .The first is closed as fixed, but I'm not sure, if the test could be successful repeated (several hundred times).

Maybe the hint, that  `SimpleChannelPool` works, but `FixedChannelPool" rarely cause that misbehaviour helps to find the cause.

**Comment by normanmaurer** [comment] 2019-09-27 08:16
@boaks can you provide a test case ?

**Comment by boaks** [comment] 2019-09-27 08:47
What I have, are test-cases within my open-source project [Californium - netty close issue](https://github.com/eclipse/californium/tree/netty_close_issue). The module "element-connector-tcp" contains unit test. The "TcpConnectorTest" is configured to repeat the 24 tests up to 100 times (2400 test in all). "On my machine" it hangs after 100 to 500.

What may get harder would be, to provide a isolated test (mainly I have to check, what I need to do in my company to provided that under apache 2.0 legal stuff, that may get big ...). I would assume, if other tests, which checks the `close` of the `FixedChannelPool` are executed repeated, they should show the same effect.

So, could you try it with that test? I know, isolate will make it easier, but may be you can try the californium testst. If "isolated tests" are required, I have to do the legal check, and that may take some time.

**Comment by normanmaurer** [comment] 2019-12-05 08:14
Can you check if latest 4.1 branch fixes it for you ?

**Comment by boaks** [comment] 2019-12-05 13:11
I checked it with 4.1.44.Final-SNAPSHOT, commit 63d33b390a.
My first result is, now the `SimpleChannelPool` also blocks on shutdown (but much less).

14:08:52.383 WARN [SingleThreadEventExecutor]: An event executor terminated with non-empty task queue (1) (i.n.u.c.SingleThreadEventExecutor$4.run:1043)

**Comment by boaks** [comment] 2019-12-05 13:27
Just to mention: 
4.1.43.Final
SimpleChannelPool - works reliable
FixedChannelPool - hangs on shutdown

But the above commit (4.1.44 ...) hangs on both, with the SimpleChannelPool much less frequently (about 8 times less).

**Comment by boaks** [comment] 2019-12-05 14:58
Would it help, to enable more logging?
If yes, please advice :-).

**Comment by mihalyr** [comment] 2019-12-07 09:23
Hi,

I was wondering if this was related to my changes in #8238, it doesn't seem to be the cause of it, but it exaggerated this due to how the pools and loops are closed here.

The issue seems to be with closing the worker group before a channel from the pool is closed, so `the SimpleChannelPool#close` is blocking the `GlobalEventExecutor` which in turn seems to be standing in the way of the signal for `EventLoopGroup.shutdownGracefully(...).sync()` which hangs.

Below is a reproducer, might not work 100% reliably, so might need to retry if it doesn't hang. This is basically what the TcpConnectorTest does in Californium, but I removed the ChannelPool here to simplify.


```java
import io.netty.bootstrap.Bootstrap;
import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.pool.AbstractChannelPoolHandler;
import io.netty.channel.pool.FixedChannelPool;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;
import io.netty.util.CharsetUtil;
import org.junit.Test;

import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

public class EventLoopShutdownHangTest {

    @Test
    public void testClientGroupShutdownHangNio() throws Exception {

        // Server
        final NioEventLoopGroup serverBossGroup = new NioEventLoopGroup(1);
        final NioEventLoopGroup serverWorkerGroup = new NioEventLoopGroup(1);

        final CountDownLatch latch = new CountDownLatch(1);

        ServerBootstrap serverBootstrap = new ServerBootstrap();
        serverBootstrap.group(serverBossGroup, serverWorkerGroup).channel(NioServerSocketChannel.class)
                .childHandler(new ChannelInitializer<NioSocketChannel>() {
                    @Override
                    protected void initChannel(NioSocketChannel ch) throws Exception {
                        ch.pipeline().addLast(new LoggingHandler(LogLevel.INFO));
                        ch.pipeline().addLast(new ChannelInboundHandlerAdapter() {
                            @Override
                            public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
                                latch.countDown();
                            }
                        });
                    }
                });

        InetSocketAddress serverAddress = new InetSocketAddress(InetAddress.getLoopbackAddress(), 0);
        NioServerSocketChannel serverChannel = (NioServerSocketChannel) serverBootstrap.bind(serverAddress).sync().channel();
        InetSocketAddress localAddress = serverChannel.localAddress();

        // Client
        final NioEventLoopGroup clientWorkerGroup = new NioEventLoopGroup(1);

        Bootstrap clientBootstrap = new Bootstrap()
                .group(clientWorkerGroup)
                .channel(NioSocketChannel.class)
                .remoteAddress(localAddress);

        final FixedChannelPool channelPool = new FixedChannelPool(clientBootstrap, new AbstractChannelPoolHandler() {
            @Override
            public void channelCreated(Channel ch) throws Exception {
                ch.pipeline().addLast(new LoggingHandler(LogLevel.INFO));
            }
        }, 1);

        // Acquire channel from pool
        Channel clientChannel = channelPool.acquire().sync().getNow();
        // Send a message (not sure why is this relevant, but it increases the chance of hanging,
        // so until this can be more deterministic leaving it here)
        clientChannel.writeAndFlush(Unpooled.copiedBuffer("hello", CharsetUtil.UTF_8)).sync();

        // Releasing the pool (this seems to be imprtant too to reproduce)
        channelPool.release(clientChannel).sync();


        // Wait for server to read, although this is not necessary, only here for some verification
        latch.await(1, TimeUnit.SECONDS);

        // Server stop
        serverBossGroup.shutdownGracefully(0, 500, TimeUnit.MILLISECONDS).syncUninterruptibly();
        serverWorkerGroup.shutdownGracefully(0, 500, TimeUnit.MILLISECONDS).syncUninterruptibly();

        // Pool/channel close and client stop
        // Using closeAsync() with quietPeriod=0 usually hangs
        // Either using close()/closeAsync().sync() or quietPeriod>0 fixes the hang
        channelPool.closeAsync();
        clientWorkerGroup.shutdownGracefully(0, 500, TimeUnit.MILLISECONDS).sync();
    }
}
```


My changes in #8238 might have made this situation worse as it made `AbstractChannelPoolMap#remove` use `closeAsync()` on pools and `AbstractChannelPoolMap#close` is using `#remove` when closing the pool. This kind of recreates the above situation from the reproducer.

Regarding the Californium tests case, I tried two things that fixes the test runs:

1. Use non-zero quietPeriod for shutdownGracefully (this is not really ideal, but helps here)
2. Make `AbstractChannelPoolMap#close` block until all pools close. This alone didn't work for Californium until I removed the `poolMap.remove` part from `TcpClientConnector.RemoveEmptyPoolHandler`.

I can submit a change to make `AbstractChannelPoolMap.close` synchronously to help to ensure there is a way to close pools before a shutdown is called. However, there is a different issue as well, the blocking of `GlobalEventExecutor` by `SimpleChannelPool#close`, which seems to be the root cause here.

**Comment by mihalyr** [comment] 2019-12-07 09:36
Added a thread dump and some logs from the above reproducer when it hung.

[netty-close-hang-threaddump.txt](https://github.com/netty/netty/files/3934925/netty-close-hang-threaddump.txt)
[netty-close-hang-test.log](https://github.com/netty/netty/files/3934926/netty-close-hang-test.log)

**Comment by mihalyr** [comment] 2019-12-07 16:57
I think I found the root cause of the hanging on exit. It happens when a SimpleChannelPool#close executes on GlobalEventExecutor while the EventLoop is shutting down.
1. Schedule SimpleChannelPool#close on GlobalEventExecutor (FixedChannelPool#close does that)
1. Initiate EventLoop shutdown
1. GlobalEventExecutor schedules channel#close() on EventLoop which is in ST_SHUTTING_DOWN state and still accepts the task after the last confirmShutdown execution
1. EventLoop terminates with a message about the remaining task which will be abandoned, not executed neither cancelled
1. GlobalEventExecutor is blocking on the channel#close which will never finish since the task has been abandoned on the event loop
1. EventLoopGroup terminateFuture that is scheduled on GlobalEventExecutor cannot finish because the GlobalEventExecutor is blocked and the shutdown is hanging

One way to fix this is could be to switch to `ST_SHUTDOWN` (from `ST_SHUTTING_DOWN`) in the `SingleThreadEventExecutor` before the last `confirmShutdown()` call (e.g. [this](https://github.com/netty/netty/files/3935307/netty-st_shutdown-before-terminate.txt)). Once we switch all new tasks will be rejected, then confirmShutdown will execute any remaining tasks from the queue before terminating. 

While this would most likely fix this issue, it would break graceful shutdown with `quietPeriod` unless we do something like, switch to `ST_SHUTDOWN if quietPeriod == 0`... Or maybe run confirmShutdown once in shutting down state and just before exit switch to ST_SHUTDOWN and run it once again to ensure all tasks are killed. What do you think?

**Comment by boaks** [comment] 2019-12-10 17:58
Sorry for the delay.
For me the fix mitigates the issue very good. Not 200%, but good enough.
Thanks a lot!

**Comment by mihalyr** [comment] 2019-12-10 21:30
@boaks When you say not 200% I guess you mean that you still see some occasional hangs, is that right? If that is the case, could you perhaps give a try against netty with commits from both #9857 and #9858? 

It might still not be 200% since you also do some async closes (or remove that makes an async close after #8238) from a callback that might exhibit the edge case I described in https://github.com/netty/netty/pull/9858#issuecomment-562922024 I think one more layer against this would be if you could use a non-zero quiet period when shutting down gracefully, if that is an option for you.

**Comment by boaks** [comment] 2019-12-11 08:48
> When you say not 200% I guess you mean that you still see some occasional hangs, is that right?

Yes, if I repeat my tests 10000 times (x24 single tests), it still hangs. But on rather high numbers of successful tests.

> If that is the case, could you perhaps give a try against netty with commits from both #9857 and #9858?

I will check it.

> if you could use a non-zero quiet period when shutting down gracefully

Oh, yes, I can adapt this (I overseen that hint before, sorry).

**Closed** 2019-12-11 09:48 UTC

**Comment by boaks** [comment] 2019-12-11 18:51
With a small quietperiod it works now more than 40000 times! Great!
