### ISSUE TITLE
Failed to include netty-bom:4.1.71.FINAL, as tcnetty-classes:2.0.44.FINAL is not on maven central

### ISSUE THREAD

**Issue by barclay-reg** [netty/netty#11914] opened 2021-12-13 08:38 UTC
### Expected behavior
tcnetty-classes:2.0.44.FINAL can be downloaded from maven central
### Actual behavior
only tcnetty-classes:2.0.46.FINAL is availeble on maven central

**Comment by normanmaurer** [comment] 2021-12-13 08:39
Duplicate of https://github.com/netty/netty/pull/11902

**Closed by normanmaurer** 2021-12-13 08:39 UTC
