### ISSUE TITLE
Error while generating self-signed certificate on JDK15-EA

### ISSUE THREAD

**Issue by eolivelli** [netty/netty#10318] opened 2020-05-26 12:08 UTC
### Expected behavior
Netty is able to generate a self-signed certificate with io.netty.handler.ssl.util.SelfSignedCertificate

### Actual behavior

```
ERROR] test(herddb.network.LocalChannelTest)  Time elapsed: 0.924 s  <<< ERROR!
java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate. See debug log for the root cause.
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:248)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:165)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:114)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:89)
	at herddb.network.netty.NettyChannelAcceptor.start(NettyChannelAcceptor.java:209)
	at herddb.network.LocalChannelTest.test(LocalChannelTest.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
	Suppressed: java.lang.NoSuchFieldError: sha256WithRSAEncryption_oid
		at io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator.generate(OpenJdkSelfSignedCertGenerator.java:68)
		at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:239)
		... 30 more
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:244)
	... 30 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

```

### Steps to reproduce
Just run HerdDB Network module tests.
a simple
`new io.netty.handler.ssl.util.SelfSignedCertificate()`
should be enough

### Minimal yet complete reproducer code (or URL to code)
`new io.netty.handler.ssl.util.SelfSignedCertificate()`
### Netty version
4.1.50Final + tcnative 2.0.30.Final

### JVM version (e.g. `java -version`)
mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/eolivelli/dev/maven
Java version: 15-ea, vendor: Oracle Corporation, runtime: /data/dev/jdk-15
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.11-200.fc31.x86_64", arch: "amd64", family: "unix"

### OS version (e.g. `uname -a`)
Fedora 31
uname -a
Linux localhost.localdomain 5.6.11-200.fc31.x86_64 #1 SMP Wed May 6 19:10:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hyperxpro** [comment] 2020-05-27 08:39
Duplicate of #10317

**Closed** 2020-05-27 08:40 UTC

**Comment by eolivelli** [comment] 2020-05-27 09:01
@hyperxpro thank you. I missed that one
