### ISSUE TITLE
flush sometimes ignored, growing outbound entries

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4203] opened 2015-09-09 12:35 UTC
I have experimented with various things, my primary concern is CPU usage.
What I found is that the demand for the buffers is quite high - knowing the Recycler's logic, the needed number of instances at the same time, at peak is:

   1:       5051237      444508856  io.netty.buffer.PooledUnsafeDirectByteBuf
   4:       5050085      323205440  io.netty.channel.ChannelOutboundBuffer$Entry

Obviously not a bug here(also, I am not angry that they stay at the Recycler). We can see a correlation between the number of buffers and the number of $Entrys. Conclusion: while the writeAndFlush(...) stuff happens, new buffers are requested pumping the "peak" count(so even _that_ flush is not immediate?)
But it's fair to say that 5 million buffers + entries is quite a high peak when proxying just ~ 1000 connections.
I think I would more like the model where it's read-write-discard, read-write-discard which would keep the demand < 10000 instances.

Questions / ideas:
1. It looks like the frame decoders, by default, decode the frames independently of the channelRead0 etc. logic. or at least can decode more than one frame at the time. Would it be beneficial to the CPU usage / peak buffer count if it would wait for the decoded buffer to be handled first?
After applying setSingleDecode(true) to the classical varint decoder, it broke the app logic, by hanging the waiting packets for about ~ 30s, making the game unplayable. Even if I manually called .read() after reading a packet.
2. I am currently flushing after every packet write and when disconnecting the client.
Would it make sense if I flushed not after every write, but with a task that flushes every X where X is the client's ping? Would it make a noticable difference to peak buffer count / cpu usage? I think it wouldn't decrease the "peak" because it would also need to keep the buffers before flushing while the new buffers are requested.
3. Considering that flush() currently happens after every flushandwrite and it's not magically scheduled, what keeps pushing the "peak" instances - I guess it's not a bug? But it's so much higher than the number of connections...

<s>Looking at ChannelOutboundBuffer, I feel like recycle() is missing when canceling entries during flush, *but I doubt this case applies to me*.  It's just a guess.
https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/ChannelOutboundBuffer.java#L154 (like, be it recycleAndNext() instead of entry.next here and there)</s>

Thanks for any help with optimising this logic.

**Comment by ninja-** [comment] 2015-09-09 16:11
A quick pattern which shows how it grows larger than it should/could be...https://gist.github.com/ninja-/5dd5d1f264b21092a15c

**Comment by ninja-** [comment] 2015-09-09 17:04
I am pretty sure that it's forceFlush getting in my way...I'll post the stacktraces in a sec

**Comment by ninja-** [comment] 2015-09-09 17:56
it's a mess to analyse so I am sorry if I messed something up...but it seems like the original problem is caused that flush() doesn't ALWAYS flush as desired and sometimes just adds the message to queue and ignores.

**Comment by normanmaurer** [comment] 2015-09-10 08:58
@ninja- the problem is that you are not stop "writing" if Channel.isWritable() return false. Even if you call `flush()` the flush will only happen once the underlying socket will be come writable again.

**Comment by ninja-** [comment] 2015-09-10 14:25
@normanmauer so I am supposed to cache them by myself? Isn't the solution to set the channel marks in some way so it would be writable?

**Comment by ninja-** [comment] 2015-09-10 16:58
@normanmaurer I created a debug in writePacket() before channel.writeAndFlush that shows if Channel.isWritable() returns false. It always returns true while the "flush ignore" behaviour still applies. Are you sure that isWritable() could be the only cause here?

**Comment by ninja-** [comment] 2015-09-10 17:48
@normanmaurer I did a working fix inside netty internals :D I'll open you a bug without all this nonsense :-)

**Comment by ninja-** [comment] 2015-09-10 18:11
filtered nonsense and created #4205

**Comment by normanmaurer** [comment] 2015-09-10 18:12
Let me close this first....

**Closed by normanmaurer** 2015-09-10 18:12 UTC
