### ISSUE TITLE
Re-add pooled sliced buffers?

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4333] opened 2015-10-08 20:58 UTC
https://github.com/netty/netty/commit/77ff24b66b726638385a65509532635e72a608e6 has deleted the sliced pooled buffer.
@Scottmitch could you re-evaluate this decision. I really liked using slices here and there but I got rid of them to reduce garbage creation after this was reverted.

I am aiming to get rid of copy() etc. again and have another strategy for rewriting packets that would need to expand the buffer.

So instead of operating on a copy

Original (a copy from stream):
-> AAA BBB CCC
rewrite into
-> AAA DDDD CCC

Aiming to do something like this if only the slices are to be recycled again:

Original:
-> AAA BBB CCC

Send:
1. send slice1 AAA
2. send DDDD
3. send slice2 containing CCC

**Comment by ninja-** [comment] 2015-10-08 20:59
not to mention the composite buffers :D

**Comment by Scottmitch** [comment] 2015-10-09 15:11
@ninja- - I considered fixing the pooling code for derived buffers but it boiled down to having feedback from the `PooledByteBuf` to all derived buffers when the reference count when to 0. This would require keeping some sort of collection in `PooledByteBuf` that must be thread safe. I did not go through this exercise because it seemed like overhead of maintaining this thread safe collection may out weight the benefits of pooling in some/most cases.

That lead me to take the "easier" path which was to pull it out because it was not functioning as originally intended.

Can you explain why `copy()` is preferred over `slice()` due to the objects returned by `slice()` not being pooled?

**Comment by ninja-** [comment] 2015-10-09 15:46
Well whether replacing most copy()s with slice() is a premature optimization is an another topic. But what I mean by copy is, well, I forgot to mention that I am not using directly copy().

        ByteBuf dst = ctx.alloc().directBuffer( length );
        in.readBytes( dst );

here's the "copy" as copy() would also use unpooled buffers or something like that.

So using slices avoids memory copies at frame decoder level but would come at a cost of trashing the memory with garbage as there is no pooling. For each single packet read, garbage. And I worked quite hard to pool everything so that the number of garbage it creates during I/O is an exact 0.

**Comment by Scottmitch** [comment] 2015-10-09 16:09
@ninja- - If you can make it work without API changes or change in expected behavior then that would be good :)  Also be sure to consider the case where there are slice objects of other slice objects.

**Comment by ninja-** [comment] 2015-10-09 16:10
@Scottmitch what do you think about the proposed model? the part when I mention that it's hard not to break buf.slice().copy()?

**Comment by ninja-** [comment] 2015-10-10 22:33
@Scottmitch @normanmaurer ok I see now how it worked. I have an idea how to re-add it, but under another function like rslice() while slice() would stay without ref-counting.
I am struggling to make a class structure that will make both a sliced and reference-counted buffer. any help?

**Comment by ninja-** [comment] 2015-10-10 23:11
ok I think I got it...the class structure is quite ugly but it works. basically the derived buffer is refCnted by default and UnpooledSlicedByteBuf contains erasure for refCnting that forwards to parent. PooledSlicedByteBuf extends directly over AbstractSlicedByteBuf

**Comment by ninja-** [comment] 2015-10-11 01:07
@normanmaurer @Scottmitch fyi https://github.com/ninja-/netty/commits/ninja

**Comment by normanmaurer** [comment] 2016-05-17 09:17
Fixed by https://github.com/netty/netty/pull/5144

**Closed by normanmaurer** 2016-05-17 09:17 UTC
