### ISSUE TITLE
FullHttpRequest doesn't return proper content anymore

### ISSUE THREAD

**Issue by bxqgit** [netty/netty#11298] opened 2021-05-24 16:19 UTC
It is server code. Server receives HTTP POST request, which contains body content. Server converts the request to `FullHttpRequest`and gets its content as a buffer. For some unknown reason buffer became not readable in versions `4.1.64.Final` and `4.1.65.Final`, but up to version `4.1.63.Final` everything worked just fine. Pipeline contains just `HttpServerCodec` and `HttpObjectAggregator`.

### Expected behavior

FullHttpRequest of Multipart POST request returns proper content of the body.

### Actual behavior

FullHttpRequest of Multipart POST request doesn't return proper content of the body.

### Steps to reproduce

Try to read content of FullHttpRequest and get it as a String.

### Minimal yet complete reproducer code (or URL to code)

```
if (req instanceof FullHttpRequest) {
    final FullHttpRequest fhr = (FullHttpRequest) req;
    // Actually contains data, but is not ready for reading anymore
    final ByteBuf bb = fhr.content();
    // String is empty now, but was ok in versions <= 4.1.63.Final
    final String s = bb.toString(StandardCharsets.UTF_8);
}
```

### Netty version

Works ok up to `4.1.63.Final`, but doesn't work anymore in `4.1.64.Final` and `4.1.65.Final`

### JVM version (e.g. `java -version`)

openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux x86_64 x86_64 x86_64 GNU/Linux
and
Windows 10

**Comment by NiteshKant** [comment] 2021-05-24 16:40
The reproducer code does not really provide any context around what is the code that produces the `FullHttpRequest` and whether the request is supposed to have any content. Please provide more details about the scenario where this happens? Does it happen for all requests, specific requests? Does it happen for the client or the server? What is the pipeline setup for the same?

**Comment by bxqgit** [comment] 2021-05-24 16:43
My guess it is somehow related to this [commit](https://github.com/netty/netty/commit/93f021141d93e6529215601ba6b5938e44f499c8)

**Comment by bxqgit** [comment] 2021-05-24 16:47
@NiteshKant It is server code. Server receives HTTP POST request, which contains body content. Server converts the request for `FullHttpRequest`and get its content as buffer. For some unknown reason buffer became not readable, in version  4.1.64.Final and 4.1.65.Final, but up to version 4.1.63.Final everything worked just fine.

**Comment by NiteshKant** [comment] 2021-05-24 17:16
Can you provide a complete reproducer?

**Comment by bxqgit** [comment] 2021-05-24 18:26
@NiteshKant What's a complete reproducer? You mean create a complete client/server project which reproduces this issue?

**Comment by bxqgit** [comment] 2021-05-24 18:29
It's worth to note that buffer contains data. if I call `bb.readerIndex(0);` and then convert it to `String` - everything works fine. But I it looks more like a hack or workaround. So it seems that the issue still exists and should be fixed. 🤷‍♂️

**Comment by bxqgit** [comment] 2021-05-24 18:31
It's something related to parsing Multipart POST request. Something has changed in `4.1.64.Final` and this issue was introduced.

**Comment by fredericBregier** [comment] 2021-05-25 05:41
@bxqgit Hi, could you elaborate a bit ?
If I understand, your code is doing something like:

1. the server uses `HttpServerCodec `and `HttpObjectAgregator`
2. it receives one body data only, so not multipart, using standard codec only
3. it creates from the buffer given by `HttpObjectAgregator` a `FullHttpRequest`: does it done manually?
4. when it is done, the buffer seems empty but it is not (changing `readerIndex` to 0 gives back access to the data)

If this is this first scenario, where comes the Multipart things?

Maybe you're using Multpart things, so it might be point 3 as:
3. Uses `HttpPostMultipartRequestDecoder` as:
  - `HttpDataFactory factory = new DefaultHttpDataFactory(true or false or limit size);`
  - `HttpPostMultipartRequestDecoder decoder = new HttpPostMultipartRequestDecoder(factory, request);`
  - for each HttpContent, doing `decoder.offer(content)`
  - once done, retrieving the `HttpData`(s), and creates a new HttpRequest from the `HttpData`(s)?
  - then destroying `decoder` and `factory`
    - `factory.cleanAllHttpData();` and `decoder.destroy();`

If this is the second case, why are you using `HttpObjectAgregator` ? There is no need for that, and of no use with `HttpPostMultipartRequestDecoder`.

Maybe you're using Multpart things, but as encoder, so it might be point 3 as:
3. Uses `HttpPostRequestEncoder` as:
  - `HttpPostRequestEncoder encoder = new HttpPostRequestEncoder(true);`
  - add the received content from original request to the encoder: one or the other
    - `encoder.addBodyAttribute(...);`
    - `encoder.addBodyFileUpload(...);`
 - add maybe other datas
 - retrieve the final request: 
   - `HttpRequest newRequest = encoder.finalizeRequest();`
   - `factory.cleanAllHttpData();` and `decoder.destroy();`

Then, here the `HttpObjectAgregator` usage is probably correct. It is only encoder part that is concerned.
As there are Junit tests doing like this, if you could gives more information, that could be helpful.

Which scenario is it?

**Comment by bxqgit** [comment] 2021-05-25 16:24
@fredericBregier

Yes, the server uses `HttpServerCodec` and `HttpObjectAgregator`.

I mentioned term 'Mutlipart' just because some classes are from `io.netty.handler.codec.http.multipart` package and I could not find anything else _possibly relevant_ in commits of versions `4.1.64.Final` and `4.1.65.Final`.

At first `HttpRequest` is processed using `HttpPostRequestDecoder`, something like:

```
final HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(req);
for (final InterfaceHttpData data : decoder.getBodyHttpDatas()) {
  // ...
  data.release();
}
decoder.destroy();
```

At next step, the `HttpRequest` is checked if it is FullHttpRequest, and `content` is retrieved:

```
if (req instanceof FullHttpRequest) {
  final FullHttpRequest fhr = (FullHttpRequest) req;
  final String s = fhr.content().toString(UTF_8);
}
```

This chain of processing worked fine up to version `4.1.63.Final`. In version `4.1.64.Final` something has changed and it does not work anymore. 🤷‍♂️

**Comment by bxqgit** [comment] 2021-05-25 17:00
Maybe the problem is that `HttpPostRequestDecoder` now somehow modifies `HttpRequest` and now `FullHttpRequest` can not process modified `HttpRequest`.

To me it looks like that `HttpRequest` should be _immutable_, so that it could be processed by various processors several times in a chain. 🙄

**Comment by fredericBregier** [comment] 2021-05-25 17:28
@bxqgit OK, I understand.

So you are indeed using a Multipart decoding.
I have found several issues in the way you using it:

- **In general, it is not recommended to use the `HttpObjectAgregator` in your pipeline when facing Multipart**. The reason is that it will fully load everything in memory. But as you're using a Multipart, it might be "too much" for the JVM. So you might change this as follow:

  - First, remove the `HttpObjectAgregator` from your pipeline
  - Then adapt your code as follow (inspired from https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/upload/HttpUploadServerHandler.java )


        // The factory in general is initialized once
        private static final HttpDataFactory factory =
            new DefaultHttpDataFactory(DefaultHttpDataFactory.MINSIZE); // Disk if size exceed
        
        // Store the decoder between each and every "chunk" for the same request
        private HttpPostRequestDecoder decoder;

        @Override
        public void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
            if (msg instanceof HttpRequest) {
                HttpRequest request = (HttpRequest) msg;
                try {
                    decoder = new HttpPostRequestDecoder(factory, request);
                } catch (ErrorDataDecoderException e1) {
                    // Your error handling
                    return;
                }
            }
        
            // check if the decoder was constructed before (if not, could be an issue)
            if (decoder != null) {
                if (msg instanceof HttpContent) {
                    // New chunk is received
                    HttpContent chunk = (HttpContent) msg;
                    try {
                        decoder.offer(chunk);
                    } catch (ErrorDataDecoderException e1) {
                        // Your error handling
                        return;
                    }
                }
                // check for end of multipart (which is also an HttpContent)
                if (chunk instanceof LastHttpContent) {
                    // finaly use all data (may be use before the end,
                    // but keep in mind that not all data are there, so up to your business logic)
                    readHttpDataChunkByChunk()
                    // Finalize the decoder
                    reset();
                }
            }
        }
       
        private void reset() {
            // destroy the decoder to release all resources
            decoder.destroy();
            decoder = null;
        }
        
        /**
         * Example of reading request by chunk and getting values from chunk to chunk
         */
        private void readHttpDataChunkByChunk() {
            try {
                while (decoder.hasNext()) {
                    InterfaceHttpData data = decoder.next();
                    if (data != null) {
                        // new value to use in your way
                        useTheNewData(data);
                        data.release();
                    }
                }
            } catch (EndOfDataDecoderException e1) {
                // end
            }
        }

- Now to your issue:
  - Whatever using onely one `FullHttpRequest` or using multiple `HttpContent` (when chunked, the first item is a `HttpRequest` without any content, followed by multiple `HttpContent`, ending with a last `LastHttpContent` that closes the chunk reception)
  - When you offer the chunks to the decoder, the decoder consumes each and every chunk or the only one `FullHttpRequest` if not chunked
  - This means that the request is now fully read, and therefore the `ByteBuf` has its `readerIndex` sets to `writerInder`.
  - So the reason you cannot read it anymore (except if you reset `readerIndex` to 0 as you did).
  - The change occurs since previously the decoder did not act as needed. It should read all buffers, and not keeping them unchanged (indeed, it was really depending on how the chunks arrived, so not consistent). **All decoders reads the input ByteBufs and therefore the `HttpRequest` is not immutable regarding its content**.

_So it is not an issue but a normal way. You're not using a decoder correctly._

**I don't know why you want to get the "full" content of a Multipart request into a String, but if so, you can build it through the `HttpData` retrieves from the decoder, as follow:**


        /**
         * NEW: add a StringBuilder that you can define as attached to the session and initialize
         * and destroyed for each and every HttpRequest as the decoder
         */
        private StringBuilder builder = null;
        @Override
        public void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
            if (msg instanceof HttpRequest) {
                HttpRequest request = (HttpRequest) msg;
                try {
                    decoder = new HttpPostRequestDecoder(factory, request);
                } catch (ErrorDataDecoderException e1) {
                    // Your error handling
                    return;
                }
                // NEW: initialize the StringBuilder
                builder = new StringBuilder();
            }
            ...
                // check for end of multipart (which is also an HttpContent)
                if (chunk instanceof LastHttpContent) {
                    // finaly use all data (may be use before the end,
                    // but keep in mind that not all data are there, so up to your business logic)
                    readHttpDataChunkByChunk()
                    // NEW: Use your StringBuilder
                    final String s = builder.toString();
                    // Finalize the decoder
                    reset();
                }
            }
        }

        /**
         * Example of reading request by chunk and getting values from chunk to chunk
         */
        private void readHttpDataChunkByChunk() {
            try {
                while (decoder.hasNext()) {
                    InterfaceHttpData data = decoder.next();
                    if (data != null) {
                        // new value to use in your way
                        useTheNewData(data);
                        // NEW: Change here: use the StringBuilder
                        builder.append(data.getString(UTF_8));
                        data.release();
                    }
                }
            } catch (EndOfDataDecoderException e1) {
                // end
            }
        }
        
        private void reset() {
            // destroy the decoder to release all resources
            decoder.destroy();
            decoder = null;
            // NEW: StringBuilder clean
            builder = null;
        }


Hoping this is clear enough to help you.

**Comment by bxqgit** [comment] 2021-05-25 20:51
@fredericBregier Thanks for the detailed answer! 👍🏻

I want to use `HttpObjectAgregator` and `FullHttpRequest` to keep the code simple, even though it may not be the most efficient. Sometimes I think that _Netty_ is too low level for my needs. 😄 But since everything works just fine, I have no reason to rewrite code to some other high level framework. 🤷‍♂️

I want to extract all the possible representations of the POST data. If it is a _form_, then I want to have `key -> value` pairs. If it is just a simple plain _content_, I want to have it as a `String`.

So I just changed the order. First I get the _content_ from `FullHttpRequest` and then I use `HttpPostRequestDecoder`, and now I don't care if it modifies the request or not. 😄

**Comment by fredericBregier** [comment] 2021-05-26 05:53
@bxqgit OK, I understand the reason and how you handle it.
The question still is, if you know it is a regular form, and you retrieve all data from String from buffer directly, why do you use Multipart decoder then? For what usage?
You can still create your map from the HttpData by getting the name and the value for each, without going to parse the String yourself?

But that's another story.
So I think we can close this issue, right?

**Comment by bxqgit** [comment] 2021-05-26 07:25
@fredericBregier I use `HttpPostRequestDecoder` because I also want to handle file uploads.

If you think all the changes in behavior are right and modifications of request work as intended, then I guess yes, we can close the issue. But I think I won't be the only one, who relied on behavior of versions up to `4.1.63`. 🤷‍♂️

**Comment by fredericBregier** [comment] 2021-05-26 10:36
@bxqgit OK, I will close then.
If you plan to have File upload, then I stringly recommend to not use `HttpObjectAgregator` neither a `String` from `ByteBuf` from the request, since you could have memory issue.
Take care also when using `FileUpload` (extends `HttpData`) to not do something like `byte[] bytes = fileUpload.get()` or `ByteBuf buf = fileUpload.getByteBuf()` since this will load all content of the file in memory, giving the very same issue of probable OOME.
Keep it as it is and use `isInMemory()` to decide to get it directly (`true` => already in Memory, `false` => on disk) or use `renameTo(File file)` directly to be able to access to your final `File` (whatever the way then).

**Comment by fredericBregier** [comment] 2021-05-26 10:37
Closing issue since wrong assumption on usage of decoder was the reason (decoder reads the ByteBuf so at the end, the ByteBuf is no more readable, even if still in memory).

**Closed by fredericBregier** 2021-05-26 10:37 UTC

**Comment by bxqgit** [comment] 2021-05-26 13:14
@fredericBregier By the way, after I have changed the order in the chain of processing, the memory started to leak. First get `content` from `FullHttpRequest` and second I use `HttpPostRequestDecoder` to extract form data. Just changed the order and now it's a leak. 🤷‍♂️ Am I supposed to release the buffer of request?

**Comment by fredericBregier** [comment] 2021-05-26 14:50
@bxqgit 
So you do now something like:

       if (req instanceof FullHttpRequest) {
         final FullHttpRequest fhr = (FullHttpRequest) req;
         // Does not modify the ByeBuf, neither its start and writer Indexes
         final String s = fhr.content().toString(UTF_8); 
       }
       // Does modify the start index
       final HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(req); 
       for (final InterfaceHttpData data : decoder.getBodyHttpDatas()) {
         // ...
         // Important if you want to release each internally allocated ByteBuffers, different from the original one
         data.release(); 
       }
       // Mandatory, since it will really release all internally allocated ByteBufs, different from original one
       // Moreover, it deletes the temporary files associated with the HttpData if any
       decoder.destroy(); 

I suppose you are using a Handler that `extends SimpleChannelInboundHandler<HttpObject>` ?
So, it should also take care about releasing the `HttpObject` itself, therefore the underlying original `ByteBuf`.

You can check manually in your code by logging the following:
- for each `InterfaceHttpData`: `data.refCnt()` after `data.release()`. It should be 0.
- for your request content: `request.content().refCnt()` after everything. It should be 1 (since the `SimpleChannelInboundHandler<HttpObject>` shall release it once the `channelRead0` is over

Maybe you are doing something else ?


IdemPotent is not for everuthing, mainly for REST, not for each and every Java Object. For instance, a Stream when consumed, cannot be read again.
Here, you can think of `ByteBuf` as a buffer "Stream" like. A decoder will consume and produce something new from them, either by copying, either by reusing the buffers, but still consuming them.
Decoders act often as if they have not all the needed data already, but some. So, to prevent OOME, they consume as much as possible and leave the final part of the current buffer for a further usage when the next buffer comes.
When not using `HttpObjectAgregator` , this is mandatory, or you will loose everything when the next chunk arrived, since the previous one is released and goes back to the memory.

**Comment by bxqgit** [comment] 2021-05-26 15:57
@fredericBregier 

I use `SimpleChannelInboundHandler<HttpRequest>` and again, from memory leaking point of view, everything worked fine until changes in codec behavior in version `4.1.64`.

**Comment by fredericBregier** [comment] 2021-05-26 18:31
@bxqgit Did you try to log the `refCnt()` to see if this related to this part of code?
Indeed, the fix in 4.1.64 fix such memory leaking, so my question to see what are the numbers from each HttpData and for the request.content() ByeBuf at the end of the `channelRead0()`.

**Comment by fredericBregier** [comment] 2021-05-26 18:33
Also another point, could you try to run with the `java -Dio.netty.leakDetection.level=paranoid ...` option such that Netty prints out any leaking ByBuf detections, where it was created and where it was used ?

**Comment by bxqgit** [comment] 2021-05-27 16:51
@fredericBregier Actually I run the server with `paranoid` option, that is exactly how I was informed about a leak. Exception was caught in `public void exceptionCaught(final ChannelHandlerContext ctx, final Throwable cause) throws Exception` method, saying something about `refCnt` and something else. One number was `0` and another number was `1`, it was the message of `cause` exception. I can't find the exact message, I have deleted the error logs. The `ChannelHandlerContext` was the name of the class that extends `SimpleChannelInboundHandler<HttpRequest>`, so I have no clue how to find the exact buffer that had leaked, the message was to general. 🤷‍♂️

**Comment by fredericBregier** [comment] 2021-05-27 20:55
@bxqgit  If there was an exception about refCnt, it means there is a ByteBuf that probably was trying to be released while already done (refCnt = 0 before calling release).
But it might be something else.
If you can regenerate the log and copy paste here, that would be helpful.
