### ISSUE TITLE
Netty 4.1.2.Final tcp closed but netty pipeline can not unregistered handler which lead to memory leak？

### ISSUE THREAD

**Issue by hushi55** [netty/netty#5741] opened 2016-08-23 08:39 UTC
I have netty http server‘s java instance，a few days ago， i finded java instace full GC frequently appear  and  time long， I use 'jmap -F  -dump:format=b,file=/tmp/jmap.xxx pid' command dump java instance memory. Memory Analyzer result:

- Leak Suspects report: 

![leak suspects](https://cloud.githubusercontent.com/assets/1675120/17884882/2f9d8e92-694d-11e6-83ed-e7b15a530236.png)

- Histogram order by byte desc
![histogram](https://cloud.githubusercontent.com/assets/1675120/17884909/6005f9d4-694d-11e6-8f7f-0fbcacbd4234.png)

- list object io.netty.util.concurrent.DefaultEventExecutor order by byte desc
![list_object](https://cloud.githubusercontent.com/assets/1675120/17884937/79d3b4dc-694d-11e6-937c-d006a16f25bd.png)

- select first object of io.netty.util.concurrent.DefaultEventExecutor 
![pipeline_ch_open](https://cloud.githubusercontent.com/assets/1675120/17885029/e1622ebc-694d-11e6-8d37-295d808842a9.png)
ch of pipeline is flase

- io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe
![pipeline_unsave_register](https://cloud.githubusercontent.com/assets/1675120/17885086/25e876f4-694e-11e6-9f7b-ac3179ecaf4f.png)

registered of io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe value is false

- io.netty.channel.AbstractChannel.AbstractUnsafe
![pipeline_unsave_unsave_nerverregistered](https://cloud.githubusercontent.com/assets/1675120/17885107/49c50272-694e-11e6-817d-e934e3e4ec57.png)

- io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe
![pipeline_unsave_unsave_nerverregistered](https://cloud.githubusercontent.com/assets/1675120/17885118/5adf0972-694e-11e6-8868-ec33dbea9453.png)

neverRegistered of io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe value is false

- but netty code is 
io.netty.channel.AbstractChannel.AbstractUnsafe.register0(ChannelPromise)

...
                boolean firstRegistration = neverRegistered;
                doRegister();
                neverRegistered = false;
                registered = true;
...

why neverRegistered  and registered  all is false ?

$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

$ uname -a
Linux hz0514 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- GC param 

-XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./logs/ -XX:InitialHeapSize=8589934592 -XX:+ManagementServer -XX:MaxHeapSize=8589934592 -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+UseCompressedOops -XX:+UseG1GC

**Comment by normanmaurer** [comment] 2016-08-29 08:07
@hushi55 sorry but I think I not fully understand how you get into the problem... To answer the question its most likely because the channel was once registered but now was unregistered.

Please provide some code to reproduce or show at least how you setup your pipeline. Without more infos I can not help :(

**Comment by hushi55** [comment] 2016-08-30 06:34
@normanmaurer  sorry，the question can not reproduce。I have 25 instances  runing over 3  months，Only one instance appeared this problem only once 。the issue is my  analysis process，I can provide the dump file, but this file is more than 2G, decompression this after more than 12G. github support large files?

my pipeline code :
`public class Pull10GatewayServerInitializer extends ChannelInitializer<SocketChannel> {
	
	private static final Logger logger = LoggerFactory.getLogger(Pull10GatewayServerInitializer.class);
	
	volatile static DefaultEventExecutorGroup POOL = null;

    @Override
    public void initChannel(SocketChannel ch) {
        ChannelPipeline p = ch.pipeline();
        
        if (logger.isDebugEnabled()) {
        	p.addLast(new LoggingHandler(LogLevel.INFO));
        }
        
        // ChannelInboundHandlerAdapter
        p.addLast(new HttpRequestDecoder());
        
        // ChannelInboundHandlerAdapter
        // Uncomment the following line if you don't want to handle HttpChunks.
        p.addLast(new HttpObjectAggregator(1024*64));
        
        //ChannelOutboundHandlerAdapter
        p.addLast(new HttpResponseEncoder());
        // Remove the following line if you don't want automatic content compression.
        //p.addLast(new HttpContentCompressor());
        
        //ChannelInboundHandlerAdapter
        if (PullConfig.instance().isUserThreadPool()) {
        	
        	this.initThreadPool();        	
        	p.addLast(POOL, new Pull10GatewayHandler());
        	
        } else {
        	p.addLast(new Pull10GatewayHandler());
        }
        
    }
    
    /***
     * 初始化线程池
     */
    private void initThreadPool() {
    	
    	if (POOL == null) {
    		synchronized (Pull10GatewayServerInitializer.class){
        		if (POOL == null) {
        			POOL = new DefaultEventExecutorGroup(200, new NamingThreadFactory("netty-buzz-handler-"));
        		}
        	}
    	}
    		
    }
} `

**Comment by normanmaurer** [comment] 2016-09-02 05:39
@hushi55 sorry but without more infos I think it is impossible to help...  Alternative please share the heap dump and I will see if I can find something. That said super busy atm

**Comment by normanmaurer** [comment] 2016-09-09 07:04
Closing and mark as need more info. Please reopen once you can share more ...

**Closed by normanmaurer** 2016-09-09 07:04 UTC
