### ISSUE TITLE
FastThreadLocal slower than jdk

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4402] opened 2015-10-28 17:33 UTC
```
# Run complete. Total time: 00:01:21

Benchmark                                    Mode  Cnt      Score      Error  Units
FastThreadLocalBenchmark.fastThreadLocal    thrpt   20  50264,632 ± 6021,328  ops/s
FastThreadLocalBenchmark.jdkThreadLocalGet  thrpt   20  83866,710 ± 6483,523  ops/s

Benchmark                                    Mode  Cnt      Score      Error  Units
FastThreadLocalBenchmark.fastThreadLocal    thrpt   20  33525,425 ± 2633,724  ops/s
FastThreadLocalBenchmark.jdkThreadLocalGet  thrpt   20  65947,751 ± 4391,956  ops/s


```

it's slower for a number of reasons including casts, instanceof etc. but why is it here if jdk's one is faster on java 8?
<s>Maybe the current benchmark isn't exactly fair because it doesn't use the "fast threads" to test...but still it's off in "real tests"</s>
surprisingly the test executor is using fast threads so nevermind above line

**Comment by Scottmitch** [comment] 2015-10-28 18:02
Thanks for reporting @ninja- !

@normanmaurer - assigned to you.

**Comment by ninja-** [comment] 2015-10-28 18:11
@Scottmitch :smiley: I am squashing every last bit of top hot methods and found lots of interesting things already.
btw. recycler.get() was something like 6% for the work and 94% for the thread local madness...

**Comment by ninja-** [comment] 2015-10-28 20:22
I have a commit that removes the "fast" internals(but keeps the "fast" threads, they may be useful later) while keeping the API and wrapping around java's ThreadLocal...can PR.

**Comment by normanmaurer** [comment] 2015-10-28 20:50
@ninja- please hold of for now... I want to investigate a bit more

**Comment by buchgr** [comment] 2015-10-28 21:46
@ninja- could you run it on Java 7 as well please? Maybe it's just a change in the runtime that makes FastThreadLocalBenchmark regress. Also looking at the commit 7d37af5dfb33c9ca67c596, it seems like this change was justified due to improved performance in `ByteBufAllocatorBenchmark` and `RecyclableArrayListBenchmark`. So it would be interesting to see if that's still true for those two benchmarks.

**Comment by ninja-** [comment] 2015-10-28 21:49
@buchgr Regarding byte buf allocator I have some other (quite simple) ideas so I'll test it as a whole

**Comment by normanmaurer** [comment] 2015-10-28 21:51
@ninja- please if you do any benchmarks do it with "isolated" changes and not change multiple things at the same time.

**Comment by ninja-** [comment] 2015-10-28 21:53
@normanmaurer @buchgr's question is easy to test: either these two benchmarks with jdk's threadlocal will regress or not. So that's not a problem to test too

**Comment by buchgr** [comment] 2015-10-28 21:57
> @buchgr are you referring to that millions-something score benchmark? I left a notice under it that it's a version that uses less iterations to test. Below is the non-modified benchmark

looking at your first post, numbers seem significantly different between the runs.

**Comment by ninja-** [comment] 2015-10-28 21:59
@buchgr pc load I think. It would be 2x faster in every attempt to test

**Comment by normanmaurer** [comment] 2015-10-29 09:11
@ninja- can reproduce it... looking :)

**Comment by ninja-** [comment] 2015-10-29 11:35
@normanmaurer I have a patch that removes thread-local recycler stack lookups(lookup once) in places where the object is either thread local already (like the PoolThreadCache) or called only inside the event loop so: PoolThreadCache(memory regions),PooledByteBufAllocator(pooled buffer objects),ChannelOutboundBuffer(outbound buffer entries). No chance to break anything and benchmarks should like this change(I'll test) and doesn't depend on other changes. Thread locals would never be free as long as Thread.currentThread() is there.

**Comment by normanmaurer** [comment] 2015-10-29 11:37
Like I said please hold off

**Comment by ninja-** [comment] 2015-10-29 11:37
@normanmaurer ...it's barely related

**Closed** 2015-10-29 20:40 UTC
