### ISSUE TITLE
OpenSslEngine.handshake() Failed to mark a promise as failure because it has succeeded already

### ISSUE THREAD

**Issue by johnou** [netty/netty#5931] opened 2016-10-20 21:50 UTC
``` noformat
    2016-10-20 21:48:33,264 WARN  [epollEventLoopGroup-3-4] (io.netty.channel.DefaultChannelPipeline) Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@59a67d5(success)
javax.net.ssl.SSLException: engine closed
    at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake()(Unknown Source) ~[netty-handler-4.0.42.Final.jar:4.0.42.Final]
```

Haven't had a chance to investigate further yet but in the meantime I wanted to report the stacktrace.

**Comment by Scottmitch** [comment] 2016-10-20 23:36
@johnou - can you provide a reproducer? does your use case involve renegotation? If you are not able to provide a reproducer easily ... can you change [ReferenceCountedOpenSslEngine#HANDSHAKE_ENGINE_CLOSED](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L86) to not be statically defined so we can get a stack trace?

**Comment by Scottmitch** [comment] 2016-10-21 22:18
If you aren't required to support renegotiation I would be curious if the behavior changes when you explicitly disable it.

**Comment by johnou** [comment] 2016-10-24 08:33
@Scottmitch I would be hesitant to disable renegotiation as we need to support multiple platforms and I doubt they all use the same parameters. Here is the full stacktrace from the client side, I imagine the server side stacktrace is the same.

```noformat
javax.net.ssl.SSLException: engine closed
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake(ReferenceCountedOpenSslEngine.java:1294) 
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:571) 
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_40]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:699) 
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:522) 
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:490) 
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:1267) 
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1259) 
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:448) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) 
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) 
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) 
	at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:36) 
	at io.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:618) 
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) 
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455) 
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) 
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

**Comment by johnou** [comment] 2016-10-24 13:57
And here is the full server side stacktrace.

```noformat
 (io.netty.channel.DefaultChannelPipeline) Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@42d430ff(success)
javax.net.ssl.SSLException: engine closed
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake(ReferenceCountedOpenSslEngine.java:1294) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:571) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:699) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:522) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:490) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:1267) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1259) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:448) ~[netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:470) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at com.sulake.h4k.proxy.network.ProxyHandler.userEventTriggered(ProxyHandler.java:99) [proxy-service.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:336) [netty-codec-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:336) [netty-codec-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:340) [netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:388) [netty-handler-4.0.42.Final-sulake.jar:4.0.42.Final-sulake]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:315) [netty-transport-native-epoll-4.0.42.Final-linux-x86_64.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by normanmaurer** [comment] 2016-10-31 06:45
@johnou can I see your `ProxyHandler`. It looks like you do something wrong with the promise .

**Comment by johnou** [comment] 2016-10-31 07:45
Sure, where shall I drop it, your googlemail?

**Comment by normanmaurer** [comment] 2016-10-31 07:47
@johnou yep

**Comment by johnou** [comment] 2016-10-31 11:30
@normanmaurer sent, let me know if you need the pipeline or anything else.

**Comment by johnou** [comment] 2016-11-17 19:45
@normanmaurer did it come through? I should have time to look into it next week.

**Comment by johnou** [comment] 2016-11-17 19:51
Looking at the stack trace it seems as though it is closing an idle socket and trying to complete the handshake..

**Comment by johnou** [comment] 2016-11-17 19:52
I'll step through the code later tonight after I get the daughter to bed..

**Comment by Scottmitch** [comment] 2016-11-18 00:52
sounds good @johnou ... ping with questions or if you find anything.

**Comment by johnou** [comment] 2016-11-18 08:48
I thought it might be related to a hung connection which didn't init the SSL handshake and then was cleaned up by the IdleStateHandler but I wasn't able to reproduce it yet.

**Comment by normanmaurer** [comment] 2016-11-24 19:33
@johnou any news ?

**Comment by johnou** [comment] 2016-11-24 20:27
@normanmaurer unfortunately not, I wasn't able to reproduce it with any unit test I came up with. Silly question though, why is it trying to handshake when closing the channel?

**Comment by normanmaurer** [comment] 2016-11-24 20:31
@johnou yeah I don't think it should try... that said I think it should also not try to fail a promise that was marked as success before.

**Comment by johnou** [comment] 2016-11-24 20:35
@normanmaurer maybe I could store the stack of where the promise is marked as success and then log it if the promise cannot be marked..?

**Comment by normanmaurer** [comment] 2016-11-24 20:36
@johnou yes... I will check why it tries to do a handshake in the meantime

**Comment by johnou** [comment] 2016-11-24 21:18
@normanmaurer I added a small debug hack into our next RC build, will let you know the results when it goes live.

io.netty.channel.DefaultChannelPromise

```java
    private Exception stacktrace;

    @Override
    public ChannelPromise setSuccess(Void result) {
        super.setSuccess(result);
        if (logger.isDebugEnabled()) {
            stacktrace = new Exception();
        }
        return this;
    }

    @Override
    public boolean tryFailure(Throwable cause) {
        boolean result = super.tryFailure(cause);
        if (!result && stacktrace != null) {
            logger.error("Trace of success marker", stacktrace);
        }
        return result;
    }
```

**Comment by normanmaurer** [comment] 2016-11-24 21:44
Thx

**Comment by normanmaurer** [comment] 2016-11-25 14:17
@johnou good news... I think I have at least some idea about the handshake error. That said still interested in the stacktrace ;)

**Comment by johnou** [comment] 2016-11-25 14:22
@normanmaurer awesome! Yeah no problem, the canary build version is in master branch now, although I might end up creating a hotfix package..

**Comment by johnou** [comment] 2016-11-26 22:36
@normanmaurer 

```noformat
2016-11-26 22:27:20,760 ERROR [epollEventLoopGroup-3-1] (io.netty.channel.DefaultChannelPromise) Trace of success marker
java.lang.Exception: null
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:75) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$4.operationComplete(AbstractChannel.java:571) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$4.operationComplete(AbstractChannel.java:568) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) ~[netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488) ~[netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427) ~[netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:170) ~[netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:111) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:568) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:554) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1236) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.ChannelDuplexHandler.close(ChannelDuplexHandler.java:73) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) ~[netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1415) ~[netty-handler-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1261) ~[netty-handler-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:448) ~[netty-handler-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:629) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:613) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:470) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at ProxyHandler.userEventTriggered(ProxyHandler.java:99) [proxy-service.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:336) [netty-codec-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:336) [netty-codec-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:321) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:313) [netty-transport-4.0.42.Final-sulake2.jar:4.0.42.Final-sulake2]
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:340) [netty-handler-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:388) [netty-handler-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:315) [netty-transport-native-epoll-4.0.42.Final-linux-x86_64.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.0.42.Final.jar:4.0.42.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by johnou** [comment] 2016-11-28 13:47
@normanmaurer is this enough to go on or is there more information I can provide? We are about to deploy another hotfix for an unrelated issue and could push some more debugging if required.

**Comment by normanmaurer** [comment] 2016-11-28 13:54
@johnou sorry had no time yet to check... Will ping you once I have :)

**Comment by johnou** [comment] 2016-11-29 11:51
fwiw I updated the comment above to include both the success and failure stacktraces.

**Comment by johnou** [comment] 2016-11-29 11:56
Here's the pipeline.

```java
    @Override
    public void initChannel(SocketChannel channel) throws Exception {
        ChannelPipeline pipeline = channel.pipeline();
        pipeline.addLast(new IdleStateHandler(MAX_READ_IDLE_SECONDS, 0, 0));
        pipeline.addLast(new ProxyMessageDecoder(trustedIpMatcher)); // HAProxy ByteToMessageDecoder which is removed when finished
        pipeline.addLast(sslContext.newHandler(channel.alloc()));
        pipeline.addLast(new LengthFieldBasedFrameDecoder(MAX_BODY_SIZE, 0, Integer.BYTES, 0, Integer.BYTES)); 
        pipeline.addLast(lengthFieldPrepender); // new LengthFieldPrepender(Integer.BYTES)
        pipeline.addLast(statisticsHandler); // stateless sharable ChannelInboundHandlerAdapter
        pipeline.addLast(proxyHandler); // SimpleChannelInboundHandler, source I sent via email
    }
```

**Comment by normanmaurer** [comment] 2016-11-29 13:48
@johnou can you show me again the diff of your "DefaultChannelPromise" ?

**Comment by normanmaurer** [comment] 2016-11-29 14:00
@johnou ha! I think I know why you get the error... Stay tuned

**Comment by johnou** [comment] 2016-11-29 14:23
@normanmaurer you tease.

**Comment by johnou** [comment] 2016-11-29 14:31
https://gist.github.com/johnou/4b8d0d82cc80b0efd48a1882f24e8db7

**Comment by normanmaurer** [comment] 2016-12-04 08:00
Fixed

**Closed by normanmaurer** 2016-12-04 08:00 UTC
Labels: defect
