### ISSUE TITLE
ObjectCleanerThread leaking

### ISSUE THREAD

**Issue by jprante** [netty/netty#7759] opened 2018-03-01 14:44 UTC
### Expected behavior

After using Netty, all Netty threads should terminate. This is the behavior of Netty 4.1.19. But ObjectCleanerThread leaks since 4.1.20.

### Actual behavior

ObjectCleanerThread only terminates when JVM terminates.

### Steps to reproduce

1. Start to use Netty (NettyRuntime.setAvailableProcessors, EventLoopGroup etc.)
2. Use Netty
3. Stop using Netty by eventLoopGroup.shutdownGracefully() 
4. ObjectCleanerThread still in thread list

### Minimal yet complete reproducer code (or URL to code)

```
  public void shutdown() {
        eventLoopGroup.shutdownGracefully();
        Set<Thread> allThreads = Thread.getAllStackTraces().keySet();
        for (Thread thread : allThreads) {
            if (thread.getName().equals(ObjectCleaner.class.getSimpleName() + "Thread")) {
                logger.info("found Netty object cleaner thread after shutdown");
            }
        }
    }
```

### Netty version
4.1.20, 4.1.21, 4.1.22

### JVM version (e.g. `java -version`)
openjdk version "9.0.4.1"
OpenJDK Runtime Environment (Zulu build 9.0.4.1+11)
OpenJDK 64-Bit Server VM (Zulu build 9.0.4.1+11, mixed mode)

### OS version (e.g. `uname -a`)
Darwin Jorg-Prantes-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment] 2018-03-02 01:54
@jprante thats most likely because you used the `PooledByteBufAllocator.DEFAULT` and so a reference is still be hold to it. Because of this the cleaner thread is still alive as there is still allocated memory that was not collected.

**Comment by johnou** [comment] 2018-03-02 09:04
@jprante that said in 4.1.21 the thread is daemon, so it shouldn't stop your JVM from exiting https://github.com/netty/netty/pull/7627.

**Comment by jprante** [comment] 2018-03-05 01:03
I have several integration tests on a single JVM where I need to restart Netty completey, including PooledByteBufAllocator.DEFAULT usage. A JVM exit is not possible.

How can I kill the thread?

**Comment by johnou** [comment] 2018-03-05 06:09
Run your tests with the leak detector level set to paranoid to try and find the leaking bytebuf(s).

**Comment by jprante** [comment] 2018-03-08 09:53
Gotcha. I think this issue can be closed. 

Probably a small note in the documentation can be helpful to look for pooled byte buffer leaks when the cleaner thread keeps hanging around.

> Simplified shutdown
> There's no more releaseExternalResources(). You can close all open channels immediately and make  all I/O threads stop themselves by calling EventLoopGroup.shutdownGracefully().

https://github.com/netty/netty/wiki/New-and-noteworthy-in-4.0

**Comment by jprante** [comment] 2018-03-08 15:33
Sorry, I have to come back. 

I can not find my ByteBufs are leaking, and I find no problems with `PooledByteBufAllocator.DEFAULT`.

I am running with leak detector on "paranoid" and it does not report anything. 

But the "ObjectCleanerThread" is still running and does not terminate.

The test consists of a simple Netty-based HTTP client. Starting the client, and shutting it down completely after issuing a simple HTTP GET request, should be successful - with the ObjectCleanerThread exiting.

The test can be run with

./gradlew test -Dtest.single=SimpleHttp1Test

I have prepared a gist with the test output will log level ALL. 

https://gist.github.com/jprante/216348c3a9839ab96bad5129baefe631

Please note the last line, it prints "ObjectCleanerThread," after the test has been run and the Netty client has finished.  In the gist, I have also included the complete test source code (285 lines) with only Netty as dependency.

My project is at 

https://github.com/jprante/netty-http-client

Maybe you want to have a look. Thank you.

**Comment by normanmaurer** [comment] 2018-03-29 15:16
@jprante the problem is once you used `PooledByteBufAllocator.DEFAULT` the thread can only exists once the JVM terminates as there is a static instance of PooledByteBufAllocator.

**Comment by normanmaurer** [comment] 2018-04-19 19:00
Closing

**Closed by normanmaurer** 2018-04-19 19:00 UTC
