### ISSUE TITLE
HTTP/2 FlowController and flushing

### ISSUE THREAD

**Issue by blucas** [netty/netty#4052] opened 2015-07-31 11:55 UTC
Netty Version: 5.0.0.Alpha3-SNAPSHOT (latest from master).

Issue:
When my server sends a larger HTTP response to a client (chrome), the client receives most of the response and then hangs.  Once the connection is closed, the client receives the rest of the response and completes processing.

I think the problem stems from the ```FlowController``` which writes frames out and respects ```channelWritability``` changes.  I believe the FlowController should be issuing a ```ctx.flush()```, but at what point, I am unsure of... maybe from ```channelWritabilityChanged```?

An easy way to reproduce this is:
1) create an SSL HTTP/2 server (that converts HTTP/1.x responses to HTTP/2 Frames)
2) when the server processes a request, create a ```FullHttpResponse``` with a decent sized body (this should be ~100KB - I used jquery.js)
3) send the response with ```ctx.write``` (```ctx.writeAndFlush()``` should have the same outcome, I haven't tried though)
4) If you sent the response with ```ctx.write```, override the ```channelReadComplete``` method and issue a ```ctx.flush()``` from there.

The browser should receive part of the response and then just hang until the connection (or stream?) is closed.  Upon closure the rest of the response is received.  This is because netty issues another ```flush``` when the connection closes.

If you need a reproducer I have one, just let me know where I should mail it to :)

**Comment by blucas** [comment] 2015-07-31 11:55
@Scottmitch @nmittler - Tagging you guys in this for your feedback.

**Comment by Scottmitch** [comment] 2015-08-02 15:47
@blucas - Thanks again for reporting this issue. A reproducer would be appreciated :)

You can send the repro here:
scott dot k dot mitch1 at gmail dot com

**Comment by Scottmitch** [comment] 2015-08-02 15:54
@blucas - You mention you are overriding `channelReadComplete`.  Can you confirm that [Http2ConnectionHandler.channelReadComplete](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L431) is still being called?

**Comment by blucas** [comment] 2015-08-03 08:17
@Scottmitch - I'll send you the reproducer tonight.  ```channelReadComplete``` is calling ```super.channelReadComplete``` so should be executing ```Http2ConnectionHandler.channelReadComplete```.  I also think it may make a slight difference if you are using Epoll or NIO.  In production I use Epoll.  I know those two vary slightly in their processing logic.

**Comment by Scottmitch** [comment] 2015-08-03 18:59
@blucas - There *should not* be a difference in terms of your programming for EPOLL an NIO. If this is the case there is likely an issue we need to take a look at.  Can you confirm if you are observing different behaviour in this case?

**Comment by blucas** [comment] 2015-08-03 19:20
@Scottmitch - Reproducer sent via email, please let me know if you get it.

Regarding EPOLL vs NIO, I haven't noticed a difference.  I only mention it because I've seen in the past that the EPOLL and NIO transports aren't always interchangeable (as an example, I believe attempting to disable auto read within an application handler has no effect in EPOLL ET mode).  When I have a bit more time, I will test the reproducer on both EPOLL and NIO environments.

**Comment by Scottmitch** [comment] 2015-08-03 19:45
@blucas - Responded to your email. Looks like a bug. Expect a follow up PR :)

> I believe attempting to disable auto read within an application handler has no effect in EPOLL ET mode

Thanks for clarifying. In this specific case the difference is expected behaviour.

**Comment by blucas** [comment] 2015-08-09 11:02
Hey scott, any update on this?  If it is something pretty simple to fix, I have a few spare cycles and don't mind chipping in if need be.

**Comment by Scottmitch** [comment] 2015-08-09 16:54
@blucas I have a PR waiting approval. It should be simple but should make it through the process by mid week.

**Comment by nmittler** [comment] 2015-08-11 20:33
@blucas thanks for reporting!

@Scottmitch Just ping me on the PR when it's ready.

**Comment by Scottmitch** [comment] 2015-08-12 22:14
@blucas @nmittler - See https://github.com/netty/netty/pull/4084

**Comment by Scottmitch** [comment] 2015-08-13 16:44
@blucas - #4084 has been merged. Please re-open if this does not address the issue you observed.

Thanks for reporting!

**Closed by Scottmitch** 2015-08-13 16:44 UTC
Labels: defect
