### ISSUE TITLE
binding an ipv6 address on an epoll channel when ipv6 is disabled "succeeds"

### ISSUE THREAD

**Issue by benjaminp** [netty/netty#10402] opened 2020-07-13 23:32 UTC
### Expected behavior
Trying to bind an IPv6 address if IPv6 is disable on the system should fail.

### Actual behavior

The program silently binds the wrong port.

### Steps to reproduce

Run the code below after `sysctl net.ipv6.conf.all.disable_ipv6=0`. When nio is used, the program fails with an expected exception:
```
Exception in thread "main" java.net.SocketException: Protocol family unavailable
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
```
When epoll is enabled, the program binds IPv4 `0.0.0.1`!

### Minimal yet complete reproducer code (or URL to code)

```
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.*;
import io.netty.channel.epoll.*;
import io.netty.channel.nio.*;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.*;
import java.net.InetSocketAddress;

public class Example {
  public static void main(String[] args) throws Exception {
    EventLoopGroup bossGroup;
    EventLoopGroup workerGroup;
    Class clazz;
    if (args.length > 1) {
      bossGroup = new EpollEventLoopGroup(1);
      workerGroup = new EpollEventLoopGroup();
      clazz = EpollServerSocketChannel.class;
    } else {
      bossGroup = new NioEventLoopGroup(1);
      workerGroup = new NioEventLoopGroup();
      clazz = NioServerSocketChannel.class;
    }

    ServerBootstrap b = new ServerBootstrap();
    b.group(bossGroup, workerGroup)
        .channel(clazz)
        .childHandler(
            new ChannelInitializer<SocketChannel>() {
              @Override
              public void initChannel(SocketChannel ch) throws Exception {}
            });

    ChannelFuture f = b.bind(new InetSocketAddress("[::1]", 0)).sync();
    f.channel().closeFuture().sync();
  }
}
```

### Netty version

4.1.51

### JVM version (e.g. `java -version`)

8

### OS version (e.g. `uname -a`)

Linux

**Comment by normanmaurer** [comment] 2020-07-14 05:59
This sounds unexpected... I will try to have a look soon. That said if you have time and want to contribute I am happy to review a PR as well

**Comment by meteorcloudy** [comment] 2020-07-15 14:46
@normanmaurer 
I tried to work around this in Bazel by checking `NetUtil.isIpV4StackPreferred()` as suggested by @benjaminp , but it didn't work for me. It still returned `false` in my docker container where ipv6 is disabled (net.ipv6.conf.all.disable_ipv6 = 1).

Is there any other way to check ipv6 availability in netty?

**Comment by meteorcloudy** [comment] 2020-07-15 18:42
`io.netty.channel.unix.Socket.isIPv6Preferred()` returned `true` in a docker container where `net.ipv6.conf.all.disable_ipv6 = 1`, maybe this implies the issue is in the JNI library?

**Comment by meteorcloudy** [comment] 2020-07-15 18:53
Looks like related issue is https://github.com/netty/netty/issues/7021

**Comment by normanmaurer** [comment] 2020-07-16 10:07
@meteorcloudy @benjaminp I can't reproduce this with latest 4.1 release in a vm (I am using parallels) after running `sudo sysctl net.ipv6.conf.all.disable_ipv6=1`

It fails with:

```
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address
```

Which I think is what you are after. Can you provide a reproducer docker image ?

**Comment by meteorcloudy** [comment] 2020-07-16 10:21
@normanmaurer 
The docker image can be found here: https://github.com/bazelbuild/bazel/issues/11756#issuecomment-657722457

I haven't tried to reproduce with the lastet netty release, the version I was using is 4.1.34

**Comment by meteorcloudy** [comment] 2020-07-16 10:24
Just confirmed the issue still exists with 4.1.51

**Comment by normanmaurer** [comment] 2020-07-16 10:26
@meteorcloudy can you provide a docker image that just contains Netty and the test code that fails without bazel etc?

**Comment by meteorcloudy** [comment] 2020-07-16 10:50
You can just login to the docker container and run:
```
#!/bin/bash

set -x

mkdir netty-bug
cd netty-bug

wget https://repo1.maven.org/maven2/io/netty/netty-all/4.1.51.Final/netty-all-4.1.51.Final.jar -O netty-all.jar

cat > Example.java <<EOF
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.*;
import io.netty.channel.epoll.*;
import io.netty.channel.nio.*;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.*;
import java.net.InetSocketAddress;

public class Example {
  public static void main(String[] args) throws Exception {
    EventLoopGroup bossGroup;
    EventLoopGroup workerGroup;
    Class clazz;
    if (args.length < 1) {
      System.out.println("Use epoll");
      bossGroup = new EpollEventLoopGroup(1);
      workerGroup = new EpollEventLoopGroup();
      clazz = EpollServerSocketChannel.class;
    } else {
      System.out.println("Use nio");
      bossGroup = new NioEventLoopGroup(1);
      workerGroup = new NioEventLoopGroup();
      clazz = NioServerSocketChannel.class;
    }

    ServerBootstrap b = new ServerBootstrap();
    b.group(bossGroup, workerGroup)
        .channel(clazz)
        .childHandler(
            new ChannelInitializer<SocketChannel>() {
              @Override
              public void initChannel(SocketChannel ch) throws Exception {}
            });

    ChannelFuture f = b.bind(new InetSocketAddress("[::1]", 0)).sync();
    f.channel().closeFuture().sync();
  }
}
EOF

javac -cp netty-all.jar Example.java

# Use NIO
java -cp netty-all.jar:. Example nio

# Use Epoll
java -cp netty-all.jar:. Example

```

**Comment by meteorcloudy** [comment] 2020-07-16 10:52
```
wget https://gist.githubusercontent.com/meteorcloudy/a3704682ed60965cb360ae926ac705c0/raw/9922772bef8335a6e5061c69f75861b1330e8499/reproduce.sh
chmod +x reproduce.sh
./reproduce.sh
```

**Comment by normanmaurer** [comment] 2020-07-16 17:47
I had no time to dig further into this today... Will try to pick up tomorrow again

**Comment by normanmaurer** [comment] 2020-07-17 07:38
@benjaminp @meteorcloudy thanks for the reproducer... This should be fixed by https://github.com/netty/netty/pull/10415

**Closed** 2020-08-10 14:29 UTC
