### ISSUE TITLE
Calling ctx.close() in write() will hang forever

### ISSUE THREAD

**Issue by Sahasrara** [netty/netty#7764] opened 2018-03-02 07:49 UTC
### Expected behavior
It's possible I missed some documentation, but this seems strange.  If I call ctx.close() in a handler's write() method, I'd expect the channel to close.

### Actual behavior
The channel hangs open indefinitely.

### Steps to reproduce
Run: nc -lk 9999
Run: the java program below

### Minimal yet complete reproducer code (or URL to code)
`public class NeverGiveUpNeverCloseChannel {

    public static void main(String[] args) throws InterruptedException {
        // Initialize the culprit
        NioEventLoopGroup sinner = new NioEventLoopGroup(5);

        try {
            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(sinner);
            bootstrap.channel(NioSocketChannel.class);
            bootstrap.option(ChannelOption.SO_KEEPALIVE, true);
            bootstrap.handler(new ChannelInitializer<Channel>() {
                protected void initChannel(Channel channel) throws Exception {
                    channel
                            .pipeline()
                            .addLast(new ChannelOutboundHandlerAdapter() {
                                @Override
                                public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
                                        throws Exception {
                                    System.out.println("Closing (jk hanging forever)");
                                    ctx.close();
                                }
                            });
                }
            });
            try {
                // Start the client.
                ChannelFuture connectionFuture = bootstrap
                        .connect("localhost", 9999)
                        .syncUninterruptibly();

                // Fire off a request
                if (connectionFuture.isSuccess()) {
                    System.out.println("Connected");
                    ByteBuf message = UnpooledByteBufAllocator.DEFAULT.buffer(6);
                    message.writeBytes("Hello\n".getBytes());
                    System.out.println("Writing");
                    connectionFuture
                            .channel()
                            .writeAndFlush(message)
                            .syncUninterruptibly();
                } else {
                    System.out.println("Failed to connect.");
                    connectionFuture.channel().close();
                }
            } catch (Exception e) {
                System.out.println("Sending failed to send message " + e.getMessage());
            }
        } catch (Exception e) {
            System.out.println("Something dumb happened " + e.getMessage());
        } finally {
            sinner.shutdownGracefully();
        }
    }
}`

### Netty version
4.1.22.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

### OS version (e.g. `uname -a`)
Darwin Kernel Version 17.4.0

**Comment by Sahasrara** [comment] 2018-03-02 07:50
Maybe I missed some vital documentation, but this behavior seems odd to me.

**Comment by johnou** [comment] 2018-03-02 08:05
@Sahasrara try with 4.1.22.Final

**Comment by Sahasrara** [comment] 2018-03-02 08:22
Same result

**Comment by normanmaurer** [comment] 2018-03-02 09:10
@Sahasrara I will check as soon as I have a few cycles

**Comment by kiril-me** [comment] 2018-03-02 09:12
I got the same results on the latest build. The eventLoop doesn't exit.

**Comment by normanmaurer** [comment] 2018-03-02 09:18
@kiril-me I am a bit confused... I think this issue is about the `Channel` which is not closed.

That said I think this is expected in the example code as the `promise` in the write is never notified.

@Sahasrara the problem is this:

```
@Override
public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
    throws Exception {
    System.out.println("Closing (jk hanging forever)");
    ctx.close();
}
```

Here the `promise` is never failed and so of-course the `ChannelFuture` returned by `writeAndFlush` is never notified. If you would either failed the promise directly or called `ctx.write(msg, promise)` before calling `ctx.close()` it would have worked as you expected.

**Comment by normanmaurer** [comment] 2018-03-02 09:18
@Sahasrara I closed this as I think this is an usage error

**Closed by normanmaurer** 2018-03-02 09:18 UTC

**Comment by Sahasrara** [comment] 2018-03-02 17:44
Oh ok, so if you want to close a channel you have to mark the future as succeeded or failed then I guess.  That must be the part I missed.  So if you want to close the channel from exceptionCaught, you HAVE to fireExceptionCaught().  You can't just call ctx.close().  Is that right?
