### ISSUE TITLE
netty framework only support the following 4 http post

### ISSUE THREAD

**Issue by wangqianfront** [netty/netty#6143] opened 2016-12-19 09:08 UTC
### netty version: 4.1

![default](https://cloud.githubusercontent.com/assets/692238/21306811/d12c5f8c-c60d-11e6-95f5-5b8817f3092b.png)

**Comment by normanmaurer** [comment] 2016-12-19 13:25
@wangqianfront as @fredericBregier noted we could most likely change this to only "throw" if the method is `HEAD`. Interested in providing a PR ?

**Comment by normanmaurer** [comment] 2016-12-19 19:22
actually this is a duplicate of #6138

**Closed by normanmaurer** 2016-12-19 19:22 UTC
