### ISSUE TITLE
Strange pauses before handling Http2 Header Frames in 4.1.9

### ISSUE THREAD

**Issue by nhnFreespirit** [netty/netty#6578] opened 2017-03-28 18:45 UTC
After upgrading From Netty 4.1.8 to 4.1.9 we are seeing strange pauses in our TSL HTTP/2 server, specifically it seems to have long (several seconds) pause before processing header frames in some cases.

I have bisected this with a local build of Netty, and that pointed to this commit as being the cause https://github.com/netty/netty/commit/6353c229fd11c6e6306011d55993775f7685d122

I do not have much in the form of a standalone repro right now as we don't really understand what is happening yet, but we are actively investigating and wanted to hear if anyone has any ideas?

Will update this ticket as we learn more.

**Comment by nhnFreespirit** [comment] 2017-03-28 18:47
I should probably add that the current version of the server is using the "old" Netty HTTP/2 API to build our pipeline.

**Comment by normanmaurer** [comment] 2017-03-28 18:53
@Scottmitch can you please have a look ?

**Comment by Scottmitch** [comment] 2017-03-29 18:37
@nhnFreespirit - Are you doing renegotiations, and is this pause related to handshake/setup time? Or does this pause occur after the handshake is setup and you are sending application data?

**Comment by fsareshwala** [comment] 2017-03-30 01:39
@Scottmitch I looked at this problem briefly today with Wireshark and it looks like the pause is after the handshake is complete and application data has started being sent. I am currently working on decrypting the data being sent back and forth between our client and server so that I can see where exactly things are getting blocked. I should have more information regarding that tomorrow.

**Comment by Scottmitch** [comment] 2017-03-30 21:24
@fsareshwala - Thanks for the update. Keep me posted. It would be nice to keep some of this optimization but if necessary we can also revert it.

**Comment by normanmaurer** [comment] 2017-03-31 05:52
@Scottmitch +1

**Comment by fsareshwala** [comment] 2017-04-01 02:33
I have a bit more information to share. We were able to decrypt the data going being transferred between our services and see this in Wireshark:

```
```

**Comment by fsareshwala** [comment] 2017-04-01 02:46
I have a bit more information to share. We were able to decrypt the data going being transferred between our services.

In the Wireshark trace below, we have two services communicating with each other. The netty server is listening on port `8443` and the ssl client is using port `55507`. Packet 75 is where the client sends its request. It receives no response from the netty server for about 9 seconds at which point the client sends a `PING` request. Receiving no response from the netty server for another 0.5 seconds, the client closes the connection.

```
#   timestamp   src port    dst port    protocol    size    summary
15  2.331795    55507       8443        TLSv1.2     159     Client Hello
21  2.510309    8443        55507       TLSv1.2     2534    Server Hello, Certificate, Certificate Request, Server Hello Done
59  2.523263    55507       8443        TLSv1.2     1516    Certificate, Client Key Exchange
61  2.523360    55507       8443        TLSv1.2     328     Certificate VerifyChange Cipher Spec, Encrypted Extensions, Finished
63  2.539672    8443        55507       HTTP2       163     SETTINGS
71  2.542824    55507       8443        HTTP2       130     Magic, SETTINGS
73  2.542842    55507       8443        HTTP2       98      WINDOW_UPDATE
75  2.542851    55507       8443        HTTP2       779     DATA
77  2.542859    55507       8443        HTTP2       94      SETTINGS
83  2.548908    8443        55507       HTTP2       94      SETTINGS
168 11.556147   55507       8443        HTTP2       102     PING
229 12.061929   55507       8443        HTTP2       98      RST_STREAM
```

I'll try and put together some minimal code that will reproduce this.

**Comment by Scottmitch** [comment] 2017-04-03 15:46
thanks for the update @fsareshwala. I'm assuming there a missing headers frame before packet 75?

**Comment by fsareshwala** [comment] 2017-04-05 18:11
@Scottmitch I think so. Those packets are the only http2 packets being sent back and forth. Here's a screenshot of Wireshark so you can see what exactly I see.

<img width="1680" alt="screen shot 2017-04-05 at 11 10 29 am" src="https://cloud.githubusercontent.com/assets/212864/24719994/8ec5942e-19f0-11e7-8efe-5ac156ef2776.png">

In my opinion, I think we should revert this commit and investigate in a branch. Since it's an optimization, we don't have to worry about a backwards compatible transition plan or anything like that.

**Comment by Scottmitch** [comment] 2017-04-06 00:25
@fsareshwala - Reverting sounds good to me but are you able to provide a reproducer? I would like to understand what scenario causes the issue and hopefully fix the root cause.

I will list out the message sequence below and please provide more details so I can try to replicate the scenario:

packet # | direction of packet | description and questions
--|--|--
63 | server -> client | SETTINGS (can you share the contents)
71 | client -> server | SETTINGS (can you share the contents, what does Magic mean)
73 | client -> server | WINDOW_UPDATE (are you expanding the connection window?)
75 | client -> server | HEADERS+DATA (what is the contents and stream ID, is the stream ended)
77 | client -> server | SETTINGS ACK?
83 | server -> client | SETTINGS ACK?

I started to try to put together a reproducer but since I'm not quite sure of the message sequence I think there are pieces missing. Here is what I have so far ... feel free to adjust it to replicate your scenario:

```java
public class TlsPauseTest {
    final int serverExpectedDataFrames = 1;
    final int maxClientStreamId = 3 + (2 * (serverExpectedDataFrames - 1)); // 1 data frame per stream
    final int clientDataPayloadSize = 600;

    @Test
    public void testTlsPause() throws InterruptedException {
        EventLoopGroup group = new NioEventLoopGroup();
        Channel serverChannel = null;
        Channel clientChannel = null;
        try {
            final CountDownLatch dataLatch = new CountDownLatch(serverExpectedDataFrames);
            ServerBootstrap sb = new ServerBootstrap();
            sb.group(group);
            sb.channel(NioServerSocketChannel.class);
            sb.childHandler(new ChannelInitializer<Channel>() {
                @Override
                protected void initChannel(Channel ch) throws Exception {
                    SelfSignedCertificate cert = new SelfSignedCertificate();
                    ch.pipeline().addLast(SslContextBuilder.forServer(cert.certificate(), cert.privateKey())
                            .build()
                            .newHandler(ch.alloc()));
                    Http2ConnectionHandlerBuilder builder = new Http2ConnectionHandlerBuilder();
                    builder.server(true);
                    builder.frameListener(new Http2FrameAdapter() {
                        @Override
                        public int onDataRead(ChannelHandlerContext ctx, int streamId, ByteBuf data, int padding,
                                              boolean endOfStream) throws Http2Exception {
                            dataLatch.countDown();
                            return data.readableBytes() + padding;
                        }
                    });
                    builder.frameLogger(new Http2FrameLogger(LogLevel.INFO, "server"));
                    ch.pipeline().addLast(builder.build());
                }
            });
            serverChannel = sb.bind(new InetSocketAddress(0)).syncUninterruptibly().channel();

            Bootstrap bs = new Bootstrap();
            bs.group(group);
            bs.channel(NioSocketChannel.class);
            bs.handler(new ChannelInitializer<Channel>() {
                @Override
                protected void initChannel(Channel ch) throws Exception {
                    ch.pipeline().addLast(SslContextBuilder.forClient()
                            .trustManager(InsecureTrustManagerFactory.INSTANCE)
                            .build()
                            .newHandler(ch.alloc()));
                    Http2ConnectionHandlerBuilder builder = new Http2ConnectionHandlerBuilder();
                    builder.server(false);
                    builder.frameListener(new Http2FrameAdapter() {
                        @Override
                        public void onSettingsRead(ChannelHandlerContext ctx, Http2Settings settings)
                                throws Http2Exception {
                            Http2ConnectionHandler handler = ctx.pipeline().get(Http2ConnectionHandler.class);
                            writeHeadersAndData(ctx, handler, 3);
                        }
                    });
//                    builder.frameLogger(new Http2FrameLogger(LogLevel.INFO, "client"));
                    ch.pipeline().addLast(builder.build());
                    ch.pipeline().addLast(new ChannelInboundHandlerAdapter() {
                        @Override
                        public void userEventTriggered(final ChannelHandlerContext ctx, Object evt) throws Exception {
                            if (evt instanceof Http2ConnectionPrefaceWrittenEvent) {
                                // Send a WINDOW_UPDATE, but execute the job on the event loop to be sure we send after
                                // the SETTINGS frame has been sent.
                                ctx.channel().eventLoop().execute(new Runnable() {
                                    @Override
                                    public void run() {
                                        Http2ConnectionHandler handler =
                                                ctx.pipeline().get(Http2ConnectionHandler.class);
                                        Http2Connection connection = handler.connection();
                                        try {
                                            connection.local().flowController()
                                                    .incrementWindowSize(connection.stream(0), 10000000);
                                        } catch (Http2Exception e) {
                                            e.printStackTrace();
                                        }
                                    }
                                });
                            }
                        }
                    });
                }
            });
            bs.connect(serverChannel.localAddress()).syncUninterruptibly().channel();
            dataLatch.await();
        } finally {
            if (clientChannel != null) {
                clientChannel.close().syncUninterruptibly();
            }
            if (serverChannel != null) {
                serverChannel.close().syncUninterruptibly();
            }
            group.shutdownGracefully();
        }
    }

    private void writeHeadersAndData(final ChannelHandlerContext ctx,
                                     final Http2ConnectionHandler handler,
                                     final int streamId) {
        handler.encoder().writeHeaders(ctx, streamId,
                new DefaultHttp2Headers().method(HttpMethod.POST.asciiName()).path("/" + streamId),
                0, false, ctx.newPromise());
        handler.encoder().writeData(ctx, streamId,
                ctx.alloc().buffer(clientDataPayloadSize).writeZero(clientDataPayloadSize), 0, true, ctx.newPromise())
                    .addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture future) throws Exception {
                        if (streamId < maxClientStreamId) {
                            writeHeadersAndData(ctx, handler, streamId + 2);
                        }
                    }
                });
        ctx.channel().flush();
    }
}
```

**Comment by fsareshwala** [comment] 2017-04-07 19:58
@Scottmitch I am working on getting a reproducer up for you but I have some things I need to take care of first internally at Twitter. This is still an important task for me so I will get back to it as soon as I can. Just wanted to you let you know :).

**Comment by normanmaurer** [comment] 2017-04-18 11:40
@fsareshwala any update ?

@Scottmitch what you think about reverting for now and cut a release this week ? We should continue to investigate tho.

**Comment by fsareshwala** [comment] 2017-04-18 18:47
@normanmaurer I haven't had a chance to look at writing a reproducer. I'm backed up with some things internally here. I hope to get back to this soon but I think it's a good idea to revert for now and then try to address this.

**Comment by Scottmitch** [comment] 2017-04-19 17:37
I haven't had cycles to look into this either. I'm fine with reverting however I don't want to discourage producing a reproducer.

**Comment by normanmaurer** [comment] 2017-04-23 19:04
@fsareshwala @nhnFreespirit I will revert the commit in question for now but can you please continue working on a reproducer ?

**Comment by normanmaurer** [comment] 2017-04-23 19:12
Reverted via 4.1 (7f3b75a5091dcd6d882102fdb92daa6931e02c30) and 4.0 (a9ff2936c5cfa1481f98e562ee2291ec2248d136)

**Comment by fsareshwala** [comment] 2017-04-24 17:15
@normanmaurer Thank you! I plan to continue working on getting a reproducer together as soon as I can.

**Comment by normanmaurer** [comment] 2017-04-24 17:36
Thx

**Comment by Scottmitch** [comment] 2017-04-25 22:39
> Is a new version of Netty going to be released with this revert?

That is the plan. Please do provide a reproducer when you are able.

**Comment by Scottmitch** [comment] 2017-06-02 14:41
Note that https://github.com/netty/netty/pull/6803 may be released to this PR. After the next Netty release I would like to verify if we can now pull this optimization back in ... @fsareshwala would you run your original scenario again at this point to verify things still function as expected (I'll open a PR and ping you when ready)?

**Comment by Scottmitch** [comment] 2017-06-02 16:36
@fsareshwala @nhnFreespirit - Can you please evaluate PR https://github.com/netty/netty/pull/6806 and report back if this issue still occurs?

**Comment by normanmaurer** [comment] 2017-08-06 13:33
@fsareshwala @nhnFreespirit ping...

**Comment by Scottmitch** [comment] 2017-08-08 03:59
Let me close this for now. @nhnFreespirit will report back if there is an issue https://github.com/netty/netty/pull/6806#issuecomment-311515819.

**Closed by Scottmitch** 2017-08-08 03:59 UTC
Labels: defect
