### ISSUE TITLE
mvn compile error.

### ISSUE THREAD

**Issue by AlexanLee** [netty/netty#7462] opened 2017-12-01 12:18 UTC
### Expected behavior
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) on project netty-parent: Couldn't download artifact: Unable to get dependency information for org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.6: Failed to retrieve POM for org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.6: Could not transfer artifact org.mortbay.jetty.alpn:jetty-alpn-agent:pom:2.0.6 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
### JVM version (e.g. `java -version`)
java version "1.8.0_73"
### OS version (e.g. `uname -a`)
 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by AlexanLee** [comment] 2017-12-01 12:25
I fixed it by myself.

**Comment by AlexanLee** [comment] 2017-12-01 12:31
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-kqueue: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]  
I also get this .and fix it with this method:https://github.com/netty/netty/issues/7101

**Comment by normanmaurer** [comment] 2017-12-06 15:10
Ok then let me close this as duplicate of #7101

**Closed by normanmaurer** 2017-12-06 15:10 UTC
