### ISSUE TITLE
Unexpected pool behavior in parallel environment (OutOfMemoryError)

### ISSUE THREAD

**Issue by otrela-clgx** [netty/netty#14427] opened 2024-10-31 15:41 UTC
I encountered an `OutOfMemoryError` while using Redisson's `putAll()` method for large data packages concurrently. The issue appeared after upgrading Netty (4.1.74.Final -> 4.1.75.Final), where `defaultChunkSize` was changed from 16MiB to 4MiB. The JVM had 64MiB of direct memory set, so previously `DEFAULT_NUM_DIRECT_ARENA` was calculated to be 0, and now it's calculated to be 2. This change means that Netty created a pool of direct memory and started using it.

### Expected behavior
Direct memory is allocated to the pool after the first invocation of `putAll()`, and subsequent invocations of the same method with the same data reuse memory from the pool.

### Actual behavior
Direct memory is allocated to the pool after the first invocation of `putAll()`, but it appears that not all invocations of `putAll()` are reusing memory from the pool. After multiple `putAll()` calls, I receive an `OutOfMemoryError`. It wouldn't be unexpected if OOM occured on first calls, but problem starts after few iterations. Looks like leak, but it's probably my wrong usage. 

### Steps to reproduce
I prepared a repository to reproduce the issue. The application is configured so you can experiment with different values using an endpoint.  
The problem only occurs for large packages in a parallel environment.
 ```
curl --location --request POST 'http://localhost:8080/send-packages-to-redis?objectsInPackage=8000&numberOfPackages=200&batchSize=8000&poolSize=4'
```

### Solutions
- If we divide packages by using `batchSize` on the `putAll()` method (Redis then creates more, smaller ByteBuffers), the issue does not occur.
 ```
curl --location --request POST 'http://localhost:8080/send-packages-to-redis?objectsInPackage=8000&numberOfPackages=200&batchSize=1000&poolSize=4'
```
- Alternatively, if we use a thread pool of size 1 (making the environment non-parallel) but keep the same number of packages, the problem does not seem to occur.
 ```
curl --location --request POST 'http://localhost:8080/send-packages-to-redis?objectsInPackage=24000&numberOfPackages=200&batchSize=24000&poolSize=1'
```
- Increasing direct memory, e.g., to 512MB, also seems to prevent the problem.
```
-XX:MaxDirectMemorySize=512M
```

### Minimal yet complete reproducer code (or URL to code)
https://github.com/otrela-clgx/redisson-netty-direct-memory

### Question
Can you explain what is happening and why these solutions help?

### Netty version
4.1.113.Final - the version in the reproducer code and where the issue first occurred.

### JVM version (e.g. `java -version`)
Java 21.0.1 - the version in the reproducer code and where the issue first occurred.

### OS version (e.g. `uname -a`)
Doesn't matter; tested on Linux and Windows.

**Comment by Geker** [comment] 2024-11-01 17:57
I ran into a similar direct memory OOM issue, and I'm still investigating the cause

**Comment by normanmaurer** [comment] 2024-11-04 12:28
@franz1981 can you check ?

**Comment by franz1981** [comment] 2024-11-04 12:37
please @Geker , first, need to make sure no leaks are happening: can you enable leak detection first?
https://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks

add `-Dio.netty.leakDetectionLevel=paranoid` to make sure that all direct buffers are correctly released back.

**Comment by otrela-clgx** [comment] 2024-11-04 15:16
@franz1981, thanks for the reply. I ran the application with the given flag, but unfortunately, it does not seem to find any leaks. I'm attaching the logs from the execution of the linked application.
[20240411.log](https://github.com/user-attachments/files/17620106/20240411.log)

**Comment by otrela-clgx** [comment] 2024-11-04 15:22
@franz1981, that is basically what we did in our main application. We set -Dio.netty.allocator.numDirectArenas=0 so that the pooling mechanism is disabled. I just wanted to understand why it behaves like this, and I'm not saying that it behaves incorrectly.

**Comment by franz1981** [comment] 2024-11-04 15:26
> I just wanted to understand why it behaves like this

It is yet not clear to me why arenas off-heap memory keep on increasing - that's why I though was a leak.
But if your application retain the buffers (somewhere) or there's congestion of network (or queuing up of requests), is not considered a leak and the allocator just keep on increasing its capacity to accomodate the increased need of off-heap/direct memory.

**Comment by otrela-clgx** [comment] 2024-11-04 15:37
> Unless the requests are coming from non event loop threads or the event loop threads are a lot. Any clue about it?

Yes, the requests are coming from non-event loop threads. We simulated what we are doing in the main application. [This is](https://github.com/otrela-clgx/redisson-netty-direct-memory/blob/e8ad2c76bddfe03a0d7ca3fcf6d67244f94d30cd/src/main/java/com/corelogic/bis/tax/test/redisson_direct_memory/SendPackagesToRedisService.java#L43) where we are creating tasks (each task sends request to Redis) manually.

**Comment by franz1981** [comment] 2024-11-04 16:01
I think that 
```
Executors.newFixedThreadPool(poolSize)
```
while creating requests is not what you want - as the thread local cached buffers attached to each non-event loop threads will disappear as the GC decide to get rid of these freshly newly created threads.
Did you tried to assign the event executor in a `static final` field instead of creating a new one each time?
Basically the risk is that it keep on creating new threads (with their cached arenas) till GC decide it's time to clean them (which is unknown by definition)

**Comment by franz1981** [comment] 2024-11-05 10:46
If you feel happy enough with the explanation, let me know if we can close this @otrela-clgx (and @Geker )

**Comment by otrela-clgx** [comment] 2024-11-05 11:00
> Did you tried to assign the event executor in a `static final` field instead of creating a new one each time?

I've tested it with executor created on bean creation, so that we get similar result - same threads for each request execution, but got same results as previous.

> unless you add -Dio.netty.allocator.useCacheForAllThreads=false (in case is true?)

Actually it's `false` by default, I think. I switched it to `true` for tests and it needs even more memory, but it's expected. I wonder if maybe this is the cause, I will try another test to use same threads and also switch that flag to `true`, but I need to find smaller package that fits the first time.

**Comment by otrela-clgx** [comment] 2024-11-05 11:56
If you agree, then I am also happy with the explanation. Thanks for your help. :)
From my side, the issue can be closed.

**Comment by franz1981** [comment] 2024-11-05 12:20
I'm fine with your summary although I'm a bit surprised about `-Dio.netty.allocator.useCacheForAllThreads=true` being so effective to save memory - given that it still have to pick N buffers from an arena (based on the size class) and bind it to a specific thread (in it's so called thread local buffer): probably the fragmentation and contention over the shared arena(s) wasn't that effective for your allocation scheme!

**Closed by franz1981** 2024-11-05 12:20 UTC

**Comment by otrela-clgx** [comment] 2024-11-05 12:24
I wouldn't say that it's effective to save memory, because it consumes much more memory - that's why I needed to test it with smaller package. But it's more stable for a similar memory usage.

**Comment by franz1981** [comment] 2024-11-05 12:28
> But it's more stable for a similar memory usage.

Yep good point - that's expected because it doesn't "load balance" the memory usage in a way which can be reused by other threads - each threads got its own thread local buffers. But still, I would have expected the jemalloc algorithm we have implemented in Netty to be able to correctly release memory in a way to allow other threads to pick it right after, without keep on growing. The growth is a sort of sign of fragmentation, to me.

In case you're curious and if you're NOT using musl containers (so - use a glibc-based one) you can try attaching async-profiler with -e mprotect, and report what you see there.
