### ISSUE TITLE
Performance regression in buffer pool

### ISSUE THREAD

**Issue by martinfurmanski** [netty/netty#10805] opened 2020-11-17 15:42 UTC
### Expected behavior
Same performance as previous patch version 4.1.51 which on my machine was:
11,778 ± 1,185 ops/us

### Actual behavior
4,946 ± 0,143 ops/us

### Steps to reproduce
Run with JMH something like:

```
ByteBuf buf = PooledByteBufAllocator.DEFAULT.directBuffer( 32768 );
buf.release();
```

### Minimal yet complete reproducer code (or URL to code)
see above

### Netty version
4.1.52

### JVM version (e.g. `java -version`)
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

### OS version (e.g. `uname -a`)
Darwin E87 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
(macOS Mojave)

**Comment by martinfurmanski** [comment] 2020-11-17 15:43
I suspect this to be the cause: https://github.com/netty/netty/pull/10267

**Comment by normanmaurer** [comment] 2020-11-17 15:43
Can you please share a full benchmark ?

**Comment by martinfurmanski** [comment] 2020-11-17 15:55
@normanmaurer So above is basically the full thing, but it depends on how full you want it. I am working within a framework wrapping JMH itself, so I don't have like a clean project. This is the entire method though and the framework shouldn't be doing anything weird, but it attaches the async profiler and I can attach two flame graphs which I have gotten as output.

```
    @Benchmark
    @BenchmarkMode( Mode.Throughput )
    public void allocateAndFree()
    {
        ByteBuf buf = PooledByteBufAllocator.DEFAULT.directBuffer( 32768 );
        buf.release();
    }
```

This is just part of an even larger benchmark where I've zoomed in on this specifically and I cannot share that larger benchmark either, but it was showing the same thing in its flamegraphs and this is merely a simplification.

If this isn't helpful, let me know in more detail what you need!

**Comment by hyperxpro** [comment] 2020-11-17 19:39
Duplicate of #10362  #9930.

This issue will not be fixed in Netty 4.1.X. It's already scheduled for Netty 5.X in #8537.

**Comment by normanmaurer** [comment] 2020-11-19 07:07
@chrisvest @franz1981 can you have a look at this ?

**Comment by chrisvest** [comment] 2020-11-19 12:50
@martinfurmanski Please attach the flame graphs you have.

**Comment by franz1981** [comment] 2020-11-22 15:58
@martinfurmanski any news about the flamegraphs?

**Comment by franz1981** [comment] 2020-11-22 16:02
@martinfurmanski I strongly suggest to add a Black hole::consumeCpu(token) 
With a token params (0, 10, 20, 30) to mimic some usage of the buffer content (you can even cycle all buffer bytes collecting a sum int but is not that reproducible/tunable probably) and jaboid to ust hammer the atomic operations (that's unrealistic and not healthy, giving how cache coherency protocols works).

**Comment by martinfurmanski** [comment] 2020-11-23 13:04
Apologies for the delay. I've fallen ill, but I should be back in business in a couple of days.

> given how cache coherency protocols works
this is just a single thread though

**Comment by franz1981** [comment] 2020-11-23 14:24
@martinfurmanski 

> this is just a single thread though

And you think that atomic primitives knows that? :)

**Comment by martinfurmanski** [comment] 2020-11-23 16:37
@franz1981 You mentioned cache coherence which would imply that you are reasoning about some sort of effect between cores and that it would be relevant for the analysis here. Since this is a single thread on a single core there will be no effect to talk about.

**Comment by franz1981** [comment] 2020-11-23 16:48
@martinfurmanski 

> Since this is a single thread on a single core there will be no effect to talk about.

That's not correct. The atomic primitives of Java are being translated, depending on the primitive and the CPU architecture in memory barriers that cause some cache effects that cannot be ignored even on single threaded cases (please take a look at https://shipilev.net/blog/2014/nanotrusting-nanotime/ on the `incrVolatile` benchmark and how/why BlackHole::consumeCPU is being used there). Hope that help

**Comment by martinfurmanski** [comment] 2020-11-23 18:02
I'm afraid I will have to opt-out of engaging on that particular topic further.

**Comment by franz1981** [comment] 2020-11-23 18:09
It's fine, I reiterate https://github.com/netty/netty/issues/10805#issuecomment-730354776 and we can modify the bench to make it more similar to actual prod code by using consume CPU tokens as JMH parameters as suggested

**Comment by martinfurmanski** [comment] 2020-11-23 18:20
I've uploaded the flame graphs here:
https://raw.githubusercontent.com/martinfurmanski/netty-flame-graphs/master/alloc_free_32k/Netty-4.1.51-Final.svg
https://raw.githubusercontent.com/martinfurmanski/netty-flame-graphs/master/alloc_free_32k/Netty-4.1.52-Final.svg

I'd suggest to zoom in on alloc and free parts separately. For example if you look at PoolArena.allocate in separation you will find that:
- much more time is spent there now
- much of that time is spent in PoolChunk#removeAvailRun and PoolChunk#splitLargeRun, which doesn't resemble any behaviour seen in the previous version

**Comment by franz1981** [comment] 2020-11-23 19:18
Search `PoolThreadCache` on both flamegraph and it seems the spot to check...
`4.1.51`
![image](https://user-images.githubusercontent.com/13125299/100005287-fca03900-2dc8-11eb-9f7f-c67e6b0913f5.png)
`4.1.52`
![image](https://user-images.githubusercontent.com/13125299/100005331-117ccc80-2dc9-11eb-8a45-52e3900bd17f.png)

**Comment by franz1981** [comment] 2020-11-23 19:20
It's nice to see how ThreadLocal is stressed differently from both cases too :)

**Comment by franz1981** [comment] 2020-11-23 19:37
I see that the new version isn't using any `MemoryRegionCache` and that means that won't benefit from caching.

**Comment by franz1981** [comment] 2020-11-23 19:58
@yuanrw is it expected that 32K sized allocations won't benefit from normal sized caches? If not, we probably have a trivially fixable bug :)

**Comment by franz1981** [comment] 2020-11-23 20:32
@martinfurmanski If you set  a lower `io.netty.allocator.maxCachedBufferCapacity` value the 32K I'm sure the performance should be similar. Indexing on normal caches seems the key here

**Comment by normanmaurer** [comment] 2020-11-25 09:48
I will have a look.

**Comment by normanmaurer** [comment] 2020-11-25 11:37
I think I have a fix... Just running the testsuite and some benchmarks

**Comment by yuanrw** [comment] 2020-11-25 12:32
> @yuanrw is it expected that 32K sized allocations won't benefit from normal sized caches? If not, we probably have a trivially fixable bug :)
> 
> It seems to me that the computation that lookup for the normal-size caches has some bug

Sorry for late reply. It seems like we have a problem in PoolThreadCache.createNormalCaches().
`int arraySize = Math.max(1, log2(max / area.pageSize) + 1);` 
arraySize is unsuitable in the new version.

**Comment by normanmaurer** [comment] 2020-11-25 12:35
Yes + there is another issue . I will open a PR in the next hour

**Closed** 2020-11-25 14:05 UTC

**Comment by normanmaurer** [comment] 2020-11-25 14:08
Thanks again to everyone involved here...
