### ISSUE TITLE
Cannot build on SmartOS (Solaris variant)

### ISSUE THREAD

**Issue by timboudreau** [netty/netty#2668] opened 2014-07-18 19:53 UTC
For some time now, my Jenkins builds of Netty [have been failing](http://timboudreau.com/builds/job/Netty/873/console) as follows:

`Could not resolve dependencies for project io.netty:netty-handler:jar:5.0.0.Alpha2-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:sunos-x86_32:1.1.30.Fork2`

I added a build of the tcnative project to try to satisfy the missing dependency, which itself [fails on a missing dependency](http://timboudreau.com/builds/job/netty-tcnative/5/console):

`Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.10:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist. Could not find artifact io.netty:netty-tcnative:zip:native-src:1.1.30.Fork3-SNAPSHOT in sonatype-nexus-snapshots`

I understand that native epoll code is not going to compile on a non-Linux platform, but it would be good to make it at least possible to compile Netty (omitting the pieces that can't work) on other platforms.  Is there something I'm missing here?

**Comment by phemmer** [comment] 2016-05-12 17:00
Getting the same thing trying to build on FreeBSD:

```
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist. Could not find artifact io.netty:netty-tcnative:zip:native-src:1.1.33.Fork15 in central (https://repo.maven.apache.org/maven2)
```

I really just need boringssl-static, and attempting to build just it results in a similar error:

```
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative-boringssl-static: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist. Failure to find io.netty:netty-tcnative-boringssl-static:zip:native-src:1.1.33.Fork15 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

**Comment by dineshappavoo** [comment] 2017-08-24 00:49
@normanmaurer  I am getting the same error while building for Mac OSX 10.11.6.  Any update on this issue?

`[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)`

**Comment by normanmaurer** [comment] 2017-08-24 06:15
@dineshappavoo can you please show me the full error ?

**Comment by dineshappavoo** [comment] 2017-08-24 06:55
@normanmaurer here is the full error,

`[INFO] configure: error: the --with-apr parameter is incorrect. It must specify an install prefix, a build directory, or an apr-config file.
[INFO] checking for APR...
[INFO] rc: 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Netty/TomcatNative [Parent] ........................ SUCCESS [  4.239 s]
[INFO] Netty/TomcatNative [OpenSSL - Dynamic] ............. FAILURE [ 19.816 s]
[INFO] Netty/TomcatNative [OpenSSL - Static] .............. SKIPPED
[INFO] Netty/TomcatNative [BoringSSL - Static] ............ SKIPPED
[INFO] Netty/TomcatNative [LibreSSL - Static] ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.612 s
[INFO] Finished at: 2017-08-23T18:20:27-07:00
[INFO] Final Memory: 19M/295M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1
	at org.fusesource.hawtjni.maven.BuildMojo.execute(BuildMojo.java:254)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1
	at org.fusesource.hawtjni.maven.BuildMojo.configureBasedBuild(BuildMojo.java:370)
	at org.fusesource.hawtjni.maven.BuildMojo.execute(BuildMojo.java:245)
	... 22 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-tcnative`

**Comment by normanmaurer** [comment] 2017-08-24 06:57
@dineshappavoo never saw this one... Did you follow these steps:

http://netty.io/wiki/forked-tomcat-native.html#building-on-mac-os-x

**Comment by dineshappavoo** [comment] 2017-08-24 18:03
@normanmaurer I followed that wiki. I did the same steps. 

```
Building on Mac OS X
First of you need to install Xcode. After this make sure you install the command line tools as well:

xcode-select --install
Use Homebrew to install the required packages:

brew install autoconf automake libtool openssl perl ninja golang cmake apr
Build the package and install it into your local Maven repository:

git clone https://github.com/netty/netty-tcnative.git
cd netty-tcnative
// To build a specific version: (e.g. netty-tcnative-2.0.0.Final)
git checkout netty-tcnative-[version]
// To build a snapshot: (e.g. 2.0.0.Final)
git checkout [branch]
mvn clean install
```
To checkout the branch, I tried with master and netty-tcnative-parent-2.0.6.Final. I got the same error :(

**Comment by dineshappavoo** [comment] 2017-08-25 19:01
@normanmaurer I appreciate your help. I created a separate issue with netty-tcnative repo. It would be really helpful if you could give some lead on that one.

**Comment by johnou** [comment] 2018-04-18 06:51
@normanmaurer probably makes sense just to close this issue as it was opened against 5.0.0.Alpha2.

**Comment by timboudreau** [comment] 2018-04-18 09:03
The same problem exists in 4.x.  Please don't.

**Comment by normanmaurer** [comment] 2019-11-08 11:05
smartOS is not a "supported" build platform for us. So let me close this

**Closed by normanmaurer** 2019-11-08 11:05 UTC
Labels: defect
