### ISSUE TITLE
refCnt after retainedSlice and slice

### ISSUE THREAD

**Issue by lizhanhui** [netty/netty#10952] opened 2021-01-20 11:10 UTC
### Expected behavior
AbstractByteBuf has the following implementation
<code>
    public ByteBuf retainedSlice() {
        return this.slice().retain();
    }
</code>

refCnt of parent ByteBuf and the sliced one should keep consistency with ByteBuf.slice().retain()

### Actual behavior

They are inconsistent.

### Steps to reproduce

See the re-preroducer code

### Minimal yet complete reproducer code (or URL to code)

    @Test
    public void testRetainedSlice() {
        ByteBuf buf1 = PooledByteBufAllocator.DEFAULT.directBuffer();
        buf1.writeInt(1);

        ByteBuf slice1 = buf1.slice();
        slice1.retain();
        Assert.assertEquals(2, buf1.refCnt());
        Assert.assertEquals(2, slice1.refCnt());

        ByteBuf buf2 = PooledByteBufAllocator.DEFAULT.directBuffer();
        buf2.writeInt(1);

        ByteBuf slice2 = buf2.retainedSlice();
        Assert.assertEquals(2, buf2.refCnt());
        Assert.assertEquals(1, slice2.refCnt());
    }

### Netty version
         <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>4.1.58.Final</version>
            </dependency>

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 25.272-b10-jvmci-20.3-b06, mixed mode)
### OS version (e.g. `uname -a`)
Darwin ali-186590d602cd.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

**Comment by chrisvest** [comment] 2021-01-21 10:11
The javadocs do not say that they must have the same reference counts, so this behaviour is within spec. As long as you pair up retains and releases, they will behave the same.

**Comment by chrisvest** [comment] 2021-01-23 14:31
Duplicate of #10713

**Closed by chrisvest** 2021-01-23 14:31 UTC
