### ISSUE TITLE
IllegalReferenceCountException in HttpPostMultipartRequestDecoder.

### ISSUE THREAD

**Issue by ExIngus** [netty/netty#7814] opened 2018-03-28 11:00 UTC
### Netty version 
4.1.22.Final

### JVM version (e.g. `java -version`) 
1.8.0_162

### OS version (e.g. `uname -a`)
windows 10

The error is observed in versions 4.1.20-4.1.22

```
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(request);
try {
...
} finally {
	decoder.destroy();
}
```
When you call decoder.destroy () MixedAttribute.release () for objects is performed 2 times.

[PostTest.zip](https://github.com/netty/netty/files/1855660/PostTest.zip)

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
    	at io.netty.util.AbstractReferenceCounted.release0(AbstractReferenceCounted.java:87)
    	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:71)
    	at io.netty.handler.codec.http.multipart.MixedAttribute.release(MixedAttribute.java:320)
    	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.destroy(HttpPostMultipartRequestDecoder.java:947)
    	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.destroy(HttpPostRequestDecoder.java:247)
```

**Comment by doom369** [comment] 2018-03-28 11:09
https://github.com/netty/netty/pull/7696

**Comment by ExIngus** [comment] 2018-03-28 11:13
I do not call manually HttpData.release ().

**Comment by doom369** [comment] 2018-03-28 11:16
Are you sure? Please post the full sketch. Or minimal reproducer.

**Comment by ExIngus** [comment] 2018-03-28 11:18
Test in error in the attached archive to the first message. (PostTest.zip)

**Comment by fishjam** [comment] 2018-04-02 13:35
Maybe I found the reason, please confirm it.
- Reason:
   - same MixedAttribute instance saved both in DefaultHttpDataFactory.requestFileDeleteMap and HttpPostMultipartRequestDecoder.bodyListHttpData
   - when call HttpPostMultipartRequestDecoder.destroy,  it will release data in requestFileDeleteMap by cleanFiles(), and release data in bodyListHttpData.
   - call stack:
```
	at io.netty.handler.codec.http.multipart.DefaultHttpDataFactory.createAttribute(DefaultHttpDataFactory.java:141)   <== the Attribute will save in list
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:523)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDisposition(HttpPostMultipartRequestDecoder.java:783)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:490)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDelimiter(HttpPostMultipartRequestDecoder.java:642)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:477)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:448) <== call addHttpData(data) and save in bodyListHttpData  
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:411)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:336)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.<init>(HttpPostMultipartRequestDecoder.java:185)

```
  
  Code in HttpPostMultipartRequestDecoder.destroy 
```
  public void destroy() {
    checkDestroyed();
    cleanFiles();   <== release data in DefaultHttpDataFactory.requestFileDeleteMap
    destroyed = true;

    if (undecodedChunk != null && undecodedChunk.refCnt() > 0) {
      undecodedChunk.release();
      undecodedChunk = null;
    }

    // release all data which was not yet pulled
    for (int i = bodyListHttpDataRank; i < bodyListHttpData.size(); i++) {
      bodyListHttpData.get(i).release();   <== release same data stored in bodyListHttpData
    }
  }
```

- Fix: 
  - comment bodyListHttpData release code

**Comment by fishjam** [comment] 2018-04-02 14:15
It seems that there exist #7689

**Comment by fishjam** [comment] 2018-04-03 15:16
I have debugged the [upload demo](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/upload), after fix some bug, it seems that can fix the IllegalReferenceCountException or leak issue.
  - call factory.removeHttpDataFromClean(request, data); in HttpPostMultipartRequestDecoder.next and HttpPostStandardRequestDecoder.next. 
  - add following code in HttpPostStandardRequestDecoder.destroy
```
    // release all data which was not yet pulled
    for (int i = bodyListHttpDataRank; i < bodyListHttpData.size(); i++) {
      bodyListHttpData.get(i).release();
    }
```
After more test and confirmed, I will post the PR.

**Comment by danielflower** [comment] 2018-06-17 05:13
I'm also not calling `HttpData.release()` so for now I'm using this workaround:

    multipartRequestDecoder.getBodyHttpDatas().clear();
    multipartRequestDecoder.destroy();

Maybe this is related to the unusual way I'm creating the decoder, which is to construct it from a stream (because of reasons).

    multipartRequestDecoder = new HttpPostMultipartRequestDecoder(request);
    byte[] buffer = new byte[16 * 1024];
    int read;
    while ((read = inputStream.read(buffer)) > -1) {
        if (read > 0) {
            ByteBuf content = Unpooled.copiedBuffer(buffer, 0, read);
            multipartRequestDecoder.offer(new DefaultHttpContent(content));
        }
    }
    multipartRequestDecoder.offer(new DefaultLastHttpContent());

**Comment by chenshun00** [comment] 2018-09-19 14:09
@doom369 hi ,  i get exception when running netty's example about upload file ,as shown below.
```text
九月 19, 2018 9:58:20 下午 io.netty.example.http.upload.HttpUploadServerHandler exceptionCaught
警告: 
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.AbstractReferenceCounted.release0(AbstractReferenceCounted.java:87)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:71)
	at io.netty.handler.codec.http.multipart.MixedAttribute.release(MixedAttribute.java:320)
	at io.netty.handler.codec.http.multipart.DefaultHttpDataFactory.cleanRequestHttpData(DefaultHttpDataFactory.java:285)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.cleanFiles(HttpPostMultipartRequestDecoder.java:958)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.destroy(HttpPostMultipartRequestDecoder.java:937)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.destroy(HttpPostRequestDecoder.java:247)
	at io.netty.example.http.upload.HttpUploadServerHandler.reset(HttpUploadServerHandler.java:213)
	at io.netty.example.http.upload.HttpUploadServerHandler.channelRead0(HttpUploadServerHandler.java:201)
	at io.netty.example.http.upload.HttpUploadServerHandler.channelRead0(HttpUploadServerHandler.java:66)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

so i debug  and found some code like this

```java
@Override
    public void cleanRequestHttpData(HttpRequest request) {
        List<HttpData> list = requestFileDeleteMap.remove(request);
        if (list != null) {
            for (HttpData data : list) {
                //byteBuf is null , but release again also , so throw IllegalReferenceCountException
                data.release();
            }
        }
    }
```
[DefaultHttpDataFactory#cleanRequestHttpData](https://git.io/fA9rg)

**Comment by DATuan91** [comment] 2018-12-08 04:19
@ExIngus This issue seem same to this [Unexpected IllegalReferenceCountException on decode multipart request](https://github.com/netty/netty/issues/8575)

**Comment by normanmaurer** [comment] 2019-10-28 08:48
I think this should be fixed now... please reopen if you still see the issue once you upgraded to latest version

**Closed by normanmaurer** 2019-10-28 08:48 UTC
