### ISSUE TITLE
HTTP request should not be failed when UPGRADE_SUCCESSFUL is received

### ISSUE THREAD

**Issue by dpy1123** [netty/netty#14361] opened 2024-09-23 07:37 UTC
According to  https://github.com/netty/netty/issues/14339

In an async situation, for HttpClientUpgradeHandler, since we first fire the UPGRADE_SUCCESSFUL event and then call `removeThisHandler`, once we receive the event and send the request, we may still encounter the "trying to write the HTTP request that is being upgraded" situation.

Can we trigger this event at the very end
<img width="840" alt="image" src="https://github.com/user-attachments/assets/7d3a10fb-e16d-4b9d-a6d5-6db80a6f3828">

 or do we need to introduce another "final event" in HttpClientUpgradeHandler?

@normanmaurer what's your opinion?

**Comment by normanmaurer** [comment] 2024-09-23 07:49
I think I might have a better idea... gimme a few minutes

**Comment by normanmaurer** [comment] 2024-09-23 08:15
Check https://github.com/netty/netty/pull/14362

**Comment by linking12** [comment] 2024-09-23 08:40
> Check #14362

well done, buddy, we are waiting for 4.1.114.Final to go prod;

can you take a snapshot to oss-sonatype? We want to do a comprehensive test before the official version;

**Comment by normanmaurer** [comment] 2024-09-23 10:45
@linking12 will be deployed once merged

**Closed** 2024-09-23 11:56 UTC

**Comment by normanmaurer** [comment] 2024-09-23 12:08
@dpy1123 @linking12 snapshot should be deployed

**Comment by linking12** [comment] 2024-09-23 12:09
> @dpy1123 @linking12 snapshot should be deployed

👍， thanks

**Comment by normanmaurer** [comment] 2024-09-23 13:54
@linking12 let me know how it goes

**Comment by dpy1123** [comment] 2024-09-23 15:07
hi @normanmaurer this fix works well, and now we're taking a whole regression test. 
If all goes well, we'll update the results here.

**Comment by linking12** [comment] 2024-09-24 05:53
@normanmaurer  
our regression test has been completed. there are no Leak any more, everything is going as expected;

**using adaptive and asynchronous upgrade of h2c, our throughput has increased by 13%. Thank you very much for your support.**

Just wondering when 4.1.114.Final will be released?

**Comment by normanmaurer** [comment] 2024-09-24 07:07
@linking12 end of this week is the plan

**Comment by linking12** [comment] 2024-09-28 11:18
> @linking12 end of this week is the plan

@normanmaurer  Will plan change? 🤣

**Comment by franz1981** [comment] 2024-09-28 14:18
@linking12 I am fairly surprised about the performance increase here - is it a stack based on webflux or just some custom Netty alone, if I may ask? And is JVM mode or using native image?
Is it mostly event loop allocation heavy or via external executors?
It is very rare to meet allocation-limited scenarios (to me at least) - and happy that the job made by @normanmaurer and @chrisvest has paid off

**Comment by linking12** [comment] 2024-09-29 06:09
> @linking12 I am fairly surprised about the performance increase here - is it a stack based on webflux or just some custom Netty alone, if I may ask? And is JVM mode or using native image? Is it mostly event loop allocation heavy or via external executors? It is very rare to meet allocation-limited scenarios (to me at least) - and happy that the job made by @normanmaurer and @chrisvest has paid off

@franz1981  Thank you for your attention, we just use Netty alone, do not use webflux&native image;

Let me clarify some of the changes we made when upgrading to version 4.1.114.Final. Strictly speaking, they are some changes to the thread model and memory optimization:
First of all, we are a gateway application, just like zuul2, divided into 3 roles:
NettyServer, NettyClient, UpstreamService;

1: NettyServer receives the request
2: Get a NettyClient object from the UpstreamService Pool
3: If no connection is made, we will create a new connection and then do an H2C upgrade
4: Write the request to UpstreamService

Before this, our third step was synchronous, which means it would block the thread. Now we have changed it;
New connections and H2C upgrades are asynchronous and do not block threads. This change should solve the problem of IO thread stuck as you said;

In addition:
1: We also used adaptive because we have a Java Agent (pinpoint) uses gRPC to transmit data. We found that this change makes gRPC very optimized, with less memory allocation, basically half of the original, which is also a factor in performance improvement;
2: We also use caffeine for caching internally, but found that caffeine has a great impact on GC overhead, so we made a secondary cache, caffeine (heap cache)-> OHC (offheap cache)-> redis

The above are some of the changes we made this time, and the overall performance improvement is very significant;
