### ISSUE TITLE
HTTP/2 headers should not be flow controlled (outbound)

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4489] opened 2015-11-19 23:23 UTC
We've discussed this in the past for a variety of reasons. Trailers definitely have to go through the flow controller since they can't be sent until after the last DATA frame. However, there isn't a good reason that I'm aware of that we shouldn't just send HEADERS immediately.

Adding HEADERS to outbound flow control will add work to the new `UniformByteDistributor` (#4464) since it has to keep track of zero-length frames separately ... and HEADERS are zero-length frames. 

As part of resolving this issue, we should refactor the `RST_STREAM` fix in #4502. We need a better solution for dealing with delayed `HEADERS` frames.

/cc @Scottmitch @louiscryan

**Comment by nmittler** [comment] 2015-11-19 23:37
@normanmaurer I think this should go into the next release ... would you mind holding off on the release until next week? I'll cook up a PR shortly.

**Comment by normanmaurer** [comment] 2015-11-19 23:44
@nmittler deal

**Comment by nmittler** [comment] 2015-11-19 23:54
:+1:

**Comment by Scottmitch** [comment] 2015-11-20 01:21
Thanks for reporting @nmittler!

**Comment by nmittler** [comment] 2015-11-20 17:47
Just chatted with @louiscryan and @ejona86 about this offline.  We're thinking that keeping HEADERS in the flow controller as we do now lends itself to better goodput due to data locality.  If we send HEADERS for all streams way before data is actually sent, they're consuming bandwidth for those streams that are sending real data.

I think we should abandon this issue in favor of two changes:

1. We fix sending RST_STREAM for streams that we have not yet sent HEADERS for. (#4465).
2. We fix the `UniformByteDistributor` to enqueue empty frames into the same queue as the other frames.  If we don't send all empty frames, that's ok ... so long as we make sure that the head of the queue is never empty. By keeping empty frames separate, we were actually breaking data locality, which could potentially degrade goodput.

@Scottmitch @normanmaurer Make sense?

**Comment by nmittler** [comment] 2015-11-20 18:47
Closing this for now ... we can re-open as necessary.

**Comment by Scottmitch** [comment] 2015-11-20 20:27
@nmittler - A few thoughts/discussion points:

1. Sending empty frames may help to advise of a priority/weight change (priority change of headers, maybe less significant if both ends ignore priority) or alleviate resource constraints on the remote end (END_STREAM in empty data frame).
2. `they're consuming bandwidth for those streams that are sending real data.` -> it does not seem obvious that a zero length frame which does not impact flow control would be queued and sent at some later time. If the user is sending an empty frame, couldn't this be considered "real"/"important" data from the user's perspective?
3. Queuing empty frames (particularly headers) locally increases the work we do, and amount of resources we consume locally.

**Comment by nmittler** [comment] 2015-11-20 20:58
@Scottmitch 

> Sending empty frames may help to advise of a priority/weight change...

True, but the spec doesn't really require that both endpoints be all that in sync WRT priority. We're favoring goodput/throughput over correctness. The oddball here is that the PRIORTY frame is not flow controlled.  I think it should be consistent with whatever we're doing with HEADERS frames.

> it does not seem obvious that a zero length frame which does not impact flow control would be queued and sent at some later time. If the user is sending an empty frame, couldn't this be considered "real"/"important" data from the user's perspective

Empty frames are not special WRT the `UniformStreamByteDistributor`, as it's just focused on serving the next HEAD of the queue. If an application always wants to make progress on high-priority frames, it would have to use a priority-based distributor.

> Queuing empty frames (particularly headers) locally increases the work we do...

Yes, it's 1 extra object per stream for the headers frame. It's unclear without more investigation if this is adding significant memory pressure ... I suspect not.

**Comment by Scottmitch** [comment] 2015-11-20 23:37
@nmittler -
> True, but the spec doesn't really require that both endpoints be all that in sync WRT priority

Agreed. The focus here is not on what the other end does with the data, but how soon we get it to them (to allow them to potentially do something useful with it).

> The oddball here is that the PRIORTY frame is not flow controlled. I think it should be consistent with whatever we're doing with HEADERS frames.

Agreed...and we may need to consider other frame types. Seems like only queuing what we need will simplify things here.

>  If an application always wants to make progress on high-priority frames, it would have to use a priority-based distributor.

I guess the exception would be that 0 length frames don't consume flow control window and don't *have* to be prioritized.

> it's 1 extra object per stream for the headers frame

Also extra operations on the queue. Not a deal breaker, but just pointing out there is a bit of extra overhead.

Also with queuing header frames and the current queuing policy (prepend first time, then append after that) won't we be sending header frames in reverse order that they are created (for a given distribution cycle)?  Seems like this queuing policy was designed with just data frames in mind?

**Comment by Scottmitch** [comment] 2015-11-20 23:47
I will reopen to continue discussion

**Comment by nmittler** [comment] 2015-11-21 15:18
@louiscryan @ejona86 @Scottmitch @normanmaurer 

The idea of flow controlling `HEADERS` frames adds a reasonable amount of complexity to the HTTP/2 logic and is probably worthy of further discussion.

The first thing that comes to mind is that `HEADERS` frames **must** be sent in the same order in which they were created by the local side (e.g. 3 followed by 7). The current flow controller seems to work in this regard, but AFAIK it's not something that is specified in the API contract. Since the flow controller is frame agnostic, we would have to make the contract more general regarding the sending of initial frames on streams.

We also need to decide how to handle other frames that identify a stream, specifically `PRIORITY` and `PUSH_PROMISE`. I believe only way to guarantee that the two sides don't get out of sync would be to flow control those as well.

If we delay sending a `PRIORITY` frame, we could run into a couple of interesting situations.  First, priority changes sent for various streams could be sent out of order, resulting in an undesirable shaping of the priority tree on the remote side. This isn't a deal breaker, but would be unfortunate. Second, the dependent stream might have been closed (by either endpoint), which would likely result in the remote endpoint breaking the connection. This is much more severe. To get around this, our encoder would have to be modified so that when a stream is closed, it iterates over any unsent `PRIORITY` frames and changes the dependency (e.g. 0) if it references the closed stream.  Since `HEADERS` frames have a `PRIORITY` frame built-in, they would suffer from these same problems.

`PUSH_PROMISE` may also be a bit tricky. Generally they are sent by the server on a client-initiated stream, so I'm not quite sure if they would need to be flow controlled. If for some reason they do, then we have the problem of ensuring that no frames on the promised stream are sent until the headers on the original stream. This *may* be something that could be solved by priority, but it is not guaranteed.

We also have the case of custom frame types, but I think we can punt on that for now.

Did I miss any cases? What do you guys think?

**Comment by ejona86** [comment] 2015-11-23 07:37
Short-term (for the release), it seems we should focus on doing as few changes as possible, and just those changes necessary for correctness for major cases. It seems #4465 should be fixed because it _should_ cause the connection to be terminated and apparently is easy to hit if you are doing benchmarking.

Thus I propose we do one of these two options, based on whichever is most-obvious/smallest/least-risky:
 1. Fix RST_STREAM for queued HEADERS (#4502). #4502 seems rather small (~50 lines added/removed; mostly trivial), although the amount of changes necessary to tests is a bit daunting.
 2. Don't flow control initial headers.

I don't think we should hold up the release for the other issues described, since they won't prevent operation.

What to do in the long run is a longer discussion...

#### No strong issues with invalid wire protocol

Concerning PRIORITY frames:
> The PRIORITY frame can be sent for a stream in the "idle" or "closed" state.

So it is safe to send PRIORITY at any time. So the "only" problem for PRIORITY is reordering with respect to HEADERS, since HEADERS also specify PRIORITY information.

nmittler wrote:
> `PUSH_PROMISE` may also be a bit tricky. Generally they are sent by the server on a client-initiated stream

Actually, http/2 is more strict than that:

> PUSH_PROMISE frames MUST only be sent on a peer-initiated stream that is in either the "open" or "half-closed (remote)" state.

I think that means that you can send PUSH_PROMISE _before_ you send your initial HEADERS response for the client-initiated stream, because the client's request opened the stream. Which means PUSH_PROMISE is free to ignore flow control. If they went through the flow controller, then we would need some solution for stream id reordering.

I don't know what it would mean if we reorder a PRIORITY frame to before a PUSH_PROMISE for the same promised stream id. Maybe we can disallow this in our API (which I think client channels would do), but it might be useful to break the implicit dependency. The spec isn't too clear (which probably means "we shouldn't do that"):

> Pushed streams (Section 8.2) initially depend on their associated stream.

So all the above means that the _wire protocol_ portion is easy to deal with. We "just" need to figure out how to store and convey the information properly.

### Approaches to the problem

#### We have to solve it

The problems discussed here still apply even if we aren't flow controlling HEADERS directly, because of MAX_CONCURRENT_STREAMS (although I do understand that that limit is handled by `StreamBufferingEncoder` and not the normal flow controller). It seems these cases we are describing are broken if max concurrent streams is reached, even if HEADERS aren't flow controlled via the flow controller. Because they will be "flow controlled" by MAX_CONCURRENT_STREAMS.

So even if we don't flow control headers, we still have to solve the same problems.

I have a general preference to make any "large" frames go through the flow controller, because then we can have a central place to observe channel writeability and intelligently schedule frames. About a month after letting people use gRPC our users were creating 1000 streams immediately on the connection. Going through the flow controller observes writability which can prevent accumulating too much in the outbound queue, as well as allowing us to schedule small DATA frames along with the initial HEADERS. Responding with HEADERS alone is generally unhelpful; if we weren't going to complete the response soon after the HEADERS it would have been better to delay sending the HEADERS and use that bandwidth for another stream's DATA to let it complete.

#### How much wiggle room?

We can trivially allow HEADERS with priority to be reordered by sending a PRIORITY frame immediately before enqueuing the HEADERS without their priority. We could try to do the extra work only if exclusive bit is set, but that seems like a losing battle.

Delayed stream id allocation could solve some problems, but it doesn't seem like a solution that helps initial HEADERS to be flow controlled. PRIORITY between queued streams would be a problem.

Interesting protocol detail: client-specified MAX_CONCURRENT_STREAMS doesn't apply to reserved streams but it does to open streams; it doesn't prohibit sending PUSH_PROMISE on server-side, but it does prohibit sending the response.

#### Proposal

 1. PRIORITY ignores flow control. Exclusive priorities effectively require it. They are probably intended to take effect ASAP.
 2. PUSH_PROMISE ignores flow control. Reordering a PRIORITY before its PUSH_PROMISE would be too problematic. We don't expect many PUSH_PROMISES in general and the size of frame is likely not too large, since it wouldn't generally include cookies, auth, etc.
   a. With child channels, the PRIORITY issue may go away. If so, we maybe could revisit this.
 3. Initial HEADERS observes flow control. If a priority is specified, split it out to a separate PRIORITY frame. We would need to keep a separate queue for new streams or always add to the end of a combined queue to prevent reordering. We would also need to handle RST_STREAM racing with the initial headers.

**Comment by nmittler** [comment] 2015-11-23 16:19
@ejona86 thanks for the breakdown ... the proposal looks good!

One thought is that we might just *always* send a `PRIORITY` frame before sending our first `HEADERS` frame, even if no priority was specified. That way we ensure that the remote side knows about the stream in advance and the RST_STREAM/GO_AWAY effectively *goes away*.

**Comment by ejona86** [comment] 2015-11-23 16:29
PRIORITY _doesn't_ change the state, it simply can be sent at any time. If you send PRIORITY for an idle stream it is still idle.

> The PRIORITY frame can be sent on a stream in any state

And that means that a RST_STREAM before the headers would be a connection error:

> RST_STREAM frames MUST NOT be sent for a stream in the "idle" state. If a RST_STREAM frame identifying an idle stream is received, the recipient MUST treat this as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

**Comment by nmittler** [comment] 2015-11-23 16:49
Yup agreed.  I think the right thing to do here would be to always create streams in the `IDLE` state and not open them until we write the first `HEADERS` frame. In addition, we would never send `RST_STREAM for `IDLE` streams, we would simply close them (which would perform all necessary cleanup on the local side).  I think that would be much more aligned with the spec.

**Comment by Scottmitch** [comment] 2015-11-23 18:47
To summarize a discuss with @nmittler and @ejona86... We generally agreed to continue queuing the initial headers frames and proceed with @ejona86's proposal above. Here is some rational...

The current enforcement of `MAX_CONCURRENT_STREAMS` has a few issues:
1. We should not be enforcing this restrictions on IDLE streams, but instead when streams become "active". (this will be fixed in `DefaultHttp2Connection` by @nmittler's https://github.com/netty/netty/pull/4502)
2. The `StreamBufferingEncoder` currently does not account for all frame types which are specific to individual streams (priority, push promise, etc...). Even if we do fix this, we still may have the same ordering issues as discussed above.
3. `StreamBufferingEncoder` currently only works while in "client" mode.

In addition to the above issues there is an opportunity to consolidate the logic which attempts to enforce `MAX_CONCURRENT_STREAMS` and the flow control logic into a central place. This has the potential to simplify/unify the code base.

> Initial HEADERS observes flow control. If a priority is specified, split it out to a separate PRIORITY frame

Although we discussed that synthesizing frames is a bit "magical" and unexpected, we agree that this may be an acceptable compromise to accomplish our other goals.  This should be clearly documented at level which the user sends a headers frame.

**Comment by Scottmitch** [comment] 2016-02-04 11:55
Queuing the initial headers caused some practical issues and added additional complexity as discussed in https://github.com/netty/netty/issues/4758. For now initial headers are not being run through the flow controllers.

**Closed by Scottmitch** 2016-02-04 11:55 UTC
Labels: improvement
