### ISSUE TITLE
SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown #2

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6261] opened 2017-01-20 19:22 UTC
It appears the the `protocol is shutdown` Exception is still present in 4.1.8.Final-SNAPSHOT.

```
$ md5sum netty-all-4.1.8.Final-SNAPSHOT.jar 
9b729fc5155999e5ea46c3ef889844fc  netty-all-4.1.8.Final-SNAPSHOT.jar
```

```
netty-all-4.1.8.Final-20170120.120745-9.jar	Fri Jan 20 12:07:46 UTC 2017	3599129
```

```java
javax.net.ssl.SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:745) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:734) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:711) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:764) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:596) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:568) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:549) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:530) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:355) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
...
```

**Comment by normanmaurer** [comment] 2017-01-20 19:23
Duplicate of https://github.com/netty/netty/issues/6260 :) I was faster ;)

**Comment by rkapsi** [comment] 2017-01-20 19:24
Damn... Just as I was about tho hit the close button.

```
Dupe, see #6260
```

**Closed by normanmaurer** 2017-01-20 19:23 UTC
