### ISSUE TITLE
Handling TCP RST

### ISSUE THREAD

**Issue by zcourts** [netty/netty#3193] opened 2014-12-02 11:53 UTC
I have a Netty HTTP server behind HAproxy.
In 

![TCP](http://upload.wikimedia.org/wikipedia/commons/a/a2/Tcp_state_diagram_fixed.svg)

 HAproxy sends an RST when a timeout is reached and closes the connection from its end, but the socket remains in Netty. 
I'm not sure of what TCP state the socket is in exactly, possibly "Close Wait" since this happens after "Established". The end result is too many files open after a while.

lsof status says “can’t identify protocol”.  i.e.

```bash

$ lsof -Pnp 21709 | grep 34146
java    21709 csr  638r     IPv6          465676654      0t0       TCP ip1:9012->ip2:34146 (ESTABLISHED)
$ lsof -Pnp 21709 | grep 638r
java    21709 csr  638r     sock                0,6      0t0 465676654 can't identify protocol

```
What is the expected behaviour when Netty receives an RST? How is an application suppose to handle it?

Possibly related:
https://github.com/netty/netty/issues/581
https://github.com/netty/netty/issues/146

**Comment by Scottmitch** [comment] 2015-01-18 17:22
@zcourts @jroper Any updates?

**Comment by zcourts** [comment] 2015-01-19 12:51
No, the RST isn't a big deal I think it was just a red herring, the original issue reported still happens. For now I've added max timeout on fixed size requests then every 5 seconds that the channel is open after that I'm trying to close it . I haven't had the out of file handle issue since implementing that but if that is disabled the sockets still end up in the "can't identify protocol state" and never seem to get cleaned up.

**Comment by Scottmitch** [comment] 2015-01-19 14:15
@zcourts have you determined if auto_read is off at the time and if so have you called read?

**Comment by jroper** [comment] 2015-02-13 02:44
One small update, though I'm dubious as to whether it's the cause - these connections are actually SSL connections using the SslHandler (this is Netty 3.9.3, no openssl here), and there seems to be a number of `Failed to clean up SSLEngine.
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?` logged by the `SslHandler` when Netty attempts to close the inbound connection.  This is possibly related to the problem, and seems to be happening when the server closes the connection (in this case, Netty is the client).  From reading the code, it appears to me that these errors occur when the remote end closes the connection unexpectedly, without doing a proper ssl close.  I can't see anywhere in the code where ordinarily this would lead to a leak, but I wanted to confirm that here.

**Comment by zcourts** [comment] 2015-02-13 10:24
I missed the notification on this @Scottmitch - auto_read appears to be off. "appears" because the issue has been observed when the user's connection was rate limited.

**Comment by Scottmitch** [comment] 2015-02-13 18:40
@zcourts - Thanks for confirming auto_read is off (false).  What are your thoughts about https://github.com/netty/netty/issues/3193#issuecomment-67002103?  I'm not sure if you can programmatically detect when you are in this scenario, but what happens when you call `channel.read()`?  If the socket is closed up (exception may be thrown) then this is expected behavior.

@jroper - Thanks for the additional info! Would you be able to provide a reproducer which demonstrates the issue? I'm not too familiar with 3.9 branch... @normanmaurer / @trustin any thoughts?

**Comment by Scottmitch** [comment] 2015-02-13 18:42
@zcourts - Are you using an SslHandler when this issue is observed?  Have you updated your netty version?

**Comment by zcourts** [comment] 2015-02-15 13:13
@Scottmitch SSL isn't involved, SslHandler isn't in the pipeline.

In response to https://github.com/netty/netty/issues/3193#issuecomment-67002103 the app is automatically turning auto read on and off per connection.
Going over the code just now it actually doesn't account for that edge case.  I'll add that in and see if it makes a difference.

**Comment by jroper** [comment] 2015-02-18 05:25
Ok, I've managed to get a packet capture, and I think (though am yet to confirm) that the issue I'm having is identical to @zcourts.  The SslHandler issue seems irrelevant, though is likely caused by the same thing.

In most cases, connections are closed using FIN, but in some cases, an RST is sent, and then nothing is done after that.  I believe these cases are the ones that are leaking connections in the CLOSE_WAIT state.  From my reading, you can close a connection using RST, but other reading I've done suggests you can't.  Wireshark highlights it as an error.

So anyway, here are the possible problems:

* Netty is not handling RST closed connections properly.
* The JDK is not handling RST closed connections properly.
* Linux is not handling RST closed connections properly.

Now, from reading [this](http://stackoverflow.com/questions/17990689/behaviour-of-select-on-remote-socket-closedby-killing-process), it seems that the difference between a RST and FIN is that -1 or 0 should be returned by a read.

Now what does this mean for the JDK?  Well, a read should throw an exception if RST is received, and return -1 if FIN is received.  Does anything have to be done after that's received by either the JDK or the application?  Should the socket be closed?  I don't know, maybe you guys know more.

**Comment by jroper** [comment] 2015-02-18 06:40
I've tried to reproduce the issue, but so far have been unsuccessful.  What I have seen is connection reset by peer exceptions reported by Netty, which is what I expect to see.  I have only been testing on the loopback port, which may be special.

**Comment by jroper** [comment] 2015-02-18 23:11
Hi all,

Ignore everything I said about RST - I can now confirm that wasn't the issue, and I have now definitely captured some packet captures.

What I'm seeing is the client (Netty) making a connection, then not using it, then the remote end closing it after 10 minutes (presumably a timeout) with a FIN ACK, and then client responds with ACK.  See attached screenshot of the capture:

![capture_png](https://cloud.githubusercontent.com/assets/105833/6258760/718c79fc-b81f-11e4-97ec-6b1539a063ec.png)

I may need to do a bit more work to confirm whether this only happens for connections that have no data go across them, and whether this always happens for connections that have no data go across them - but I will try and reproduce this myself and let you know.  At this point, this feels like a Linux bug, not in the JDK and definitely not Netty.

**Comment by jroper** [comment] 2015-02-18 23:42
I haven't been able to reproduce it, but something interesting to note here - the client is using SSL, but never attempts to make an SSL handshake.  That's probably where the problem is - the client is never finding out that the connection is open.  So that could well mean that the bug is in the opening of connections.

**Comment by Scottmitch** [comment] 2015-02-18 23:51
@jroper - Thanks for all the hard work tracking this down!  Sound like your are narrowing in...I wonder is your connect future completing successfully on the client. If so is the `ChannelPipelineFactory.getPipeline()` being called and initializing your pipeline. If good so far is then what is happening in `SslContext` that prevents the ClientHello from going out?

**Comment by jroper** [comment] 2015-02-18 23:57
Note that the only place we've been able to reproduce this is on a high load production system - knowing whether getPipeline is being called is not simple (and the implementation of ChannelPipelineFactory is in async-http-client, so hard for us to put logging in there).

I do have a little more information here though - when these connections were created, there were many (5-15) connections connections created simultaneously (within 1 ms of each other).  So right now, I'm thinking maybe there's a race condition in the connection code.

I'm also wondering if I should raise a new issue somewhere, because it seems apparent that my issue is completely unrelated to the original reporters issue.

**Comment by slandelle** [comment] 2015-02-19 09:31
> and the implementation of ChannelPipelineFactory is in async-http-client, so hard for us to put logging in there

@jroper I know you can't upgrade easily and that @wsargent is investigating migration, but please note that [pipelines customization is available in AHC 1.9](https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/providers/netty/NettyAsyncHttpProviderConfig.java#L107-L110) ;)

**Comment by Scottmitch** [comment] 2015-02-19 16:57
@zcourts - Did the call to `read()` correct the behavior you were seeing (when `auto_read` was off)?

@jroper - Agreed.  I think we have enough info where we can open as a separate issue.  Not sure if it makes more sense to file with AHC and then we can jump in if necessary?  This may help ensure that the issue is fixed all the way through the stack. @slandelle - Does this sound appropriate?

**Comment by slandelle** [comment] 2015-02-19 17:45
Well, the problem is that Play uses the previous generation of AHC and the code base as completely changed in between. So I'm afraid I couldn't do much as long as the Play team doesn't provide a reproducer targeting 1.9... But I would of course gladly ship and release a new 1.8 if they were to provide a fix.

**Comment by jroper** [comment] 2015-02-19 23:45
For me, I just appreciate having a place to report my findings so that any experts that happen to be following along can spot anything obvious that I've missed or can provide pointers of where I might look next - I'm not expecting anyone other than myself to put any serious effort in, so I don't mind where this lives.  Perhaps the mailing list may be a better place?

**Comment by trustin** [comment] 2015-02-21 03:48
@jroper, @zcourts - I appreciate that you guys come here to provide more information hoping for future resolution on this issue, and I'm somewhat sad that we couldn't help a lot.  Please feel free to keep the relevant information coming. We are listening. :-)

**Comment by mgrandi** [comment] 2015-12-21 22:21
Has any work been done on fixing this? We are currently experiencing this exact issue and wondering if there are any workarounds

**Comment by Scottmitch** [comment] 2015-12-22 02:06
@mgrandi - Not that I'm aware of. Do you have a reproducer or any additional details you can share?

**Comment by mgrandi** [comment] 2015-12-22 19:18
@Scottmitch we might. We ran into a problem with our app that is using netty with running out of file handles, and when we ran lsof, we found that it had 3200+ connections in CLOSE_WAIT, and they were connections from our Varnish load balancer, and upon googling we found this issue, and were wondering if this could be the same thing

We have not confirmed that it isn't a fault of our own that this is happening, but we just fixed a bug that seems to of made our app more efficient, but at the same time it now creates connections faster then it can release them, or something we did to fix the bug somehow made it so the connections aren't getting released/closed.

We are using a older version of netty, 3.6, so we are going to try the typical steps (upgrading netty, etc, verifying our fixes didn't break anything) before we chalk it up to this bug

**Comment by Scottmitch** [comment] 2015-12-23 01:08
@mgrandi - Thanks for the details. Does your "upgrading netty" plan include going to a 4.x version?

**Comment by mgrandi** [comment] 2016-01-19 20:32
@Scottmitch sorry for the delay, no we don't plan to upgrade to 4.x (at least for this project) at the moment.

turns out it was our fault (as i was suspecting). We were waiting for the result of a NettyFuture on an IO thread, and even though the ChannelFuture class says "don't do this" in the class javadoc, it is not mentioned in any of the javadoc for the 'wait()' methods, which hindered our figuring out the problem.

also, unhelpfully, it seems that AsyncHttpClient used to disable the deadlock checker by default (https://github.com/AsyncHttpClient/async-http-client/commit/b4a6dbd103ec611f70879cfc78fc5cce5c63a4e6#diff-f86cd91228f3cde51e071f609d997d5bR205) which would of given us plenty warnings in the logs.

so sorry for adding to the spam of this bug report

**Comment by normanmaurer** [comment] 2016-04-07 19:16
Thanks for let us know... Closing now

**Closed by normanmaurer** 2016-04-07 19:16 UTC
Labels: needs info

**Comment by wikimore** [comment] 2016-11-28 09:36
hey, @jroper @zcourts  @Scottmitch
I reproduce this when writing a redis proxy use netty.

My redis client is [jedis](https://github.com/xetorthio/jedis), when I closing the connection from client like below

```
Jedis jedis = new Jedis("127.0.0.1", 16379, 0);
// do something..
jedis.close(); // closing and send RST
```
![wireshark](https://cloud.githubusercontent.com/assets/1697662/20662151/2aeb1482-b58d-11e6-92ff-1f9bfdcd289e.jpeg)


Netty server receive the RST packet and then throw exception

```
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:366)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:695)

```
At last I found jedis client set `socket.setSoLinger(true, 0);` to control socket close.

When I set `socket.setSoLinger(false, 0);` the client will send FIN to close connection.

@jroper You could not reproduce this maybe caused by not setting so_linger true.
