### ISSUE TITLE
Apparent memory leak when writing a TextWebSocketFrame on websocket connect.

### ISSUE THREAD

**Issue by jcohen** [netty/netty#9803] opened 2019-11-25 04:19 UTC
### Expected behavior

I'm trying to write a Netty based Web Socket server that expected to receive high load. The basic reproducible case involves simply opening a web socket connection and the server sending back a welcome message to the client.

### Actual behavior

While load testing during development, I'm seeing excessive memory utilization by the process that cannot be attributed to any identifiable source (at least, not identifiable by me, thus the issue). Under heavy load, the process eventually consumes all available memory on the host before it is killed by a separate oom-reaper process.

This memory utilization only occurs when the server starts writing new, non-empty,`TextWebSocketFrame`s.

### Steps to reproduce

Modify the example Web Socket server to send back any non-empty greeting on connect and send heavy load. (Note: the definition of heavy load will vary based on the available memory for the service).

### Minimal yet complete reproducer code (or URL to code)

Sample addition to `WebSocketFrameHandler`

```java
  @Override
  public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
    super.userEventTriggered(ctx, evt);
    if (evt instanceof HandshakeComplete) {
      websocketConnected(ctx);
    }
  }

  private void websocketConnected(ChannelHandlerContext ctx) {
    ctx.channel().writeAndFlush(new TextWebSocketFrame("{}"));
  }
```

For a fully functioning app that should exhibit the behavior in question, see this repo: https://github.com/jcohen/netty-ws-leak

### Netty version

4.1.43.Final

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

### OS version (e.g. `uname -a`)

`Linux a1d94bdbf936 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux`

**Comment by normanmaurer** [comment] 2019-11-25 08:14
I will have a look.

**Comment by normanmaurer** [comment] 2019-11-25 14:16
@jcohen I tried to use your reproducer but so far it did not end up running out of memory. Is this expected ?

**Comment by jcohen** [comment] 2019-11-25 15:48
@normanmaurer I was concerned that the problem would be harder to reproduce locally. For me when I run it I'm pretty reliably to get it to run out of memory on the way to 10k connections but it has occasionally been able to reach that peak. Here's a sample of a local run that died around ~8700 conns.

https://gist.github.com/jcohen/d9ae6bb86d8b362999194702efb952e8

**Comment by jcohen** [comment] 2019-11-25 15:51
I think in part it's difficult to reproduce locally because the service and the load generator are competing for resources. When this occurs in a more realistic scenario, the service is running with more resources and the load generation is coming from 10 separate load test generators.

Let me know if there's anything in particular I can do to capture more details under that scenario?

**Comment by normanmaurer** [comment] 2019-11-25 15:53
Could you try to see what happens when you remove the compression stuff ?

**Comment by jcohen** [comment] 2019-11-25 16:26
Well *that* was an easy fix! Memory utilization is *fine* with `WebSocketServerCompressionHandler` removed from the pipeline!

**Comment by normanmaurer** [comment] 2019-11-25 16:29
Ok thanks ... looking into it now

**Comment by normanmaurer** [comment] 2019-11-26 08:00
@jcohen alright I did spent some time to look into it and sadly there is not much we can do on our side in netty...

The problem is that with compression enabled it will use `permessage-deflate` with `server_no_context_takeover` not used. For more infos on what this actual means check:
See https://tools.ietf.org/html/rfc7692#section-7.1.1.1.

So with the configuration we need to create a new `Deflater` (which is part of the JDK: https://docs.oracle.com/javase/8/docs/api/java/util/zip/Deflater.html ) and keep it "alive" till the connection is closed. The problem here is that `Deflater` is implemented using `JNI` and so reserve native memory that will not be released until the connection is closed and so the `deflater.end()` method can be called by us.

So the only way to "guard" against such a problem is to limit the max number of concurrent connections which use the extension.

**Comment by normanmaurer** [comment] 2019-11-26 08:02
@jcohen also you should add some sort of timeout that will close connections after they are inactive for some amount of time.

**Comment by doom369** [comment] 2019-11-26 08:40
@normanmaurer hm... interesting.
@jcohen maybe you can plug in other compression codec into `WebSocketServerCompressionHandler`. From the code I see it should be possible.

**Comment by amizurov** [comment] 2019-11-26 09:42
Hi, @jcohen also you can try use selective compression approach https://github.com/netty/netty/pull/8910, (e.g. compress only message more than threshold) we use this feature on production. Or optimize extension configuration described on this old, but very interesting [post](https://www.igvita.com/2013/11/27/configuring-and-optimizing-websocket-compression/).

**Comment by jcohen** [comment] 2019-11-26 14:58
Thanks so much everyone for the investigation and the details. I'm so glad to know I wasn't going mad for the past week 😂. I'll have control over both clients and the server, so I think I can live without globally enabled compression and instead rely on compressing individual messages on an as-needed basis.

**Comment by normanmaurer** [comment] 2019-11-27 07:52
Ok let me close this then as there is nothing we can do

**Closed by normanmaurer** 2019-11-27 07:52 UTC

**Comment by silloy** [comment] 2020-10-20 07:57
@jcohen I hava the same question, and remove the WebSocketServerCompressionHandler is good, compressing individual messages on an as-needed basis,  I want to do how you realise it?

**Comment by jcohen** [comment] 2020-10-20 16:07
My messages are not particularly large, so I've just done without compressing them for the time being.

**Comment by sameerathangudu** [comment] 2020-12-08 20:29
> So the only way to "guard" against such a problem is to limit the max number of concurrent connections which use the extension.

Where is this configurable ? cc @normanmaurer

**Comment by novice88** [comment] 2022-10-27 05:17
> @jcohen alright I did spent some time to look into it and sadly there is not much we can do on our side in netty...
> 
> The problem is that with compression enabled it will use `permessage-deflate` with `server_no_context_takeover` not used. For more infos on what this actual means check: See https://tools.ietf.org/html/rfc7692#section-7.1.1.1.
> 
> So with the configuration we need to create a new `Deflater` (which is part of the JDK: https://docs.oracle.com/javase/8/docs/api/java/util/zip/Deflater.html ) and keep it "alive" till the connection is closed. The problem here is that `Deflater` is implemented using `JNI` and so reserve native memory that will not be released until the connection is closed and so the `deflater.end()` method can be called by us.
> 
> So the only way to "guard" against such a problem is to limit the max number of concurrent connections which use the extension.

Connection closed also not freeing memory，I create 40,000 connections, each connection sends a TextWebsocketFrame when it is established, and these memory are not released when it is closed

**Comment by novice88** [comment] 2022-11-08 07:52
same problem

**Comment by welkinxu** [comment] 2023-08-15 08:21
@normanmaurer Will WebSocketServerCompressionHandler cause any problems if set to @Shareable?
