### ISSUE TITLE
Performance Issue Report: Performance problem with PooledUnsafeDirectByteBuf#writeZero() method when writing little data

### ISSUE THREAD

**Issue by imangry** [netty/netty#13692] opened 2023-11-08 08:50 UTC
### Expected behavior
I expected to achieve good performance even when writing little data.

### Actual behavior
However, I noticed a significant decrease in performance when writing little data.
Upon further investigation, I suspect that the root cause of this issue may be related to the suboptimal performance of the jdk/internal/misc/Unsafe.setMemory0 method.

### Minimal yet complete reproducer code (or URL to code)
```java 
package com.xiaohongshu.infra.benchmark;

import java.util.concurrent.TimeUnit;

import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.TearDown;
import org.openjdk.jmh.infra.Blackhole;
import org.openjdk.jmh.profile.AsyncProfiler;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.RunnerException;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;
import org.openjdk.jmh.runner.options.TimeValue;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.PooledByteBufAllocator;

/**
 * @author lvshichang
 * Created on 2023-11-08.
 */

@State(Scope.Benchmark)
public class WriteZeroBenchmark {

    private ByteBufAllocator allocator;

    private ByteBuf byteBuf;

    @Setup
    public void setup() {
        allocator = new PooledByteBufAllocator(true);
        byteBuf = allocator.directBuffer(8192);
    }

    @TearDown
    public void release() {
        byteBuf.release();
    }

    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @OutputTimeUnit(TimeUnit.MILLISECONDS)
    public void writeManual(Blackhole blackhole) {
        byteBuf.markWriterIndex();
        try {
            for (int i = 0; i < 8; i++) {
                byteBuf.ensureWritable(i);
                for (int j = 0; j < i; j++) {
                    byteBuf.writeByte(0);
                }
            }
            blackhole.consume(byteBuf);
        } finally {
            byteBuf.resetWriterIndex();
        }
    }

    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @OutputTimeUnit(TimeUnit.MILLISECONDS)
    public void writeUnsafe(Blackhole blackhole) {
        byteBuf.markWriterIndex();
        try {
            for (int i = 0; i < 8; i++) {
                byteBuf.writeZero(i);
            }
            blackhole.consume(byteBuf);
        } finally {
            byteBuf.resetWriterIndex();
        }
    }


    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @OutputTimeUnit(TimeUnit.MILLISECONDS)
    public void writeManualBig(Blackhole blackhole) {
        byteBuf.markWriterIndex();
        try {
            for (int i = 64; i < 128; i++) {
                byteBuf.ensureWritable(i);
                for (int j = 0; j < i; j++) {
                    byteBuf.writeByte(0);
                }
            }
            blackhole.consume(byteBuf);
        } finally {
            byteBuf.resetWriterIndex();
        }
    }

    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @OutputTimeUnit(TimeUnit.MILLISECONDS)
    public void writeUnsafeBig(Blackhole blackhole) {
        byteBuf.markWriterIndex();
        try {
            for (int i = 64; i < 128; i++) {
                byteBuf.writeZero(i);
            }
            blackhole.consume(byteBuf);
        } finally {
            byteBuf.resetWriterIndex();
        }
    }

    public static void main(String[] args) throws RunnerException {

        Options opt = new OptionsBuilder()//
                .include(WriteZeroBenchmark.class.getSimpleName())//
                .warmupIterations(3)//
                .warmupTime(TimeValue.seconds(10))//
                .measurementIterations(3)//
                .measurementTime(TimeValue.seconds(10))//
                .threads(1)//
                .jvmArgsAppend("-Dio.netty.buffer.checkBounds=false", "-Dio.netty.buffer.checkAccessible=false")

                .addProfiler(AsyncProfiler.class,
                        "libPath=/home/admin/async-profiler-2.9-linux-x64/build/libasyncProfiler.so;output=flamegraph;verbose=true;event=cpu")
                .forks(1)//
                .build();

        new Runner(opt).run();
    }
}

```
Benchmark Result:
```
Benchmark                                  Mode  Cnt      Score     Error   Units
WriteZeroBenchmark.writeManual            thrpt    3  14255.164 ± 475.204  ops/ms
WriteZeroBenchmark.writeManual:·async     thrpt             NaN               ---
WriteZeroBenchmark.writeManualBig         thrpt    3     77.641 ±   1.365  ops/ms
WriteZeroBenchmark.writeManualBig:·async  thrpt             NaN               ---
WriteZeroBenchmark.writeUnsafe            thrpt    3   3353.325 ±  64.074  ops/ms
WriteZeroBenchmark.writeUnsafe:·async     thrpt             NaN               ---
WriteZeroBenchmark.writeUnsafeBig         thrpt    3    326.171 ±   5.618  ops/ms
WriteZeroBenchmark.writeUnsafeBig:·async  thrpt             NaN               ---
```
<img width="2553" alt="Snipaste_2023-11-08_19-33-53" src="https://github.com/netty/netty/assets/17894679/9ba936b7-4f5e-4a83-9888-3a70542a16df">

### Netty version
4.1.100.Final

### JVM version (e.g. `java -version`)
JDK 11.0.20, OpenJDK 64-Bit Server VM, 11.0.20+8-LTS

### OS version (e.g. `uname -a`)
3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment] 2023-11-08 09:29
There are a few issues in your benchmark that I think need to be fixed first to ensure the benchmark is meaningful:
- Your methods should either use a `BlackHole` or return something so it might not get optimised away.
- You should create a new ByteBufAllocator in a `@Setup` method to ensure that you not benefit from already cached buffers in one case.

**Comment by normanmaurer** [comment] 2023-11-08 09:43
Even better would be to just allocate the buffer once and reuse it.

**Comment by imangry** [comment] 2023-11-08 11:46
It seems that despite making modifications based on the suggestions , the JMH test results remain consistent.

**Comment by imangry** [comment] 2023-11-08 11:57
#5315 I don't think this pull request has enough evidence of improved performance.

**Comment by franz1981** [comment] 2023-11-08 12:46
Please try with a most recent version and...I see that the methods up there aren't inclined, which is weird. Please attach the perfasm data or the compiler logs to be sure of it OR just do not inline (there's a compiler control annotation for that) the benchmark method, to grant  inclining depth to be just enough to have while chain of methods fully inlinied.

Secondary, add a test which force a blackhole consume on each write op or we risk to measure how good autovectorization is, I'd kick in (which isn't likely not implemented for setMemory iirc).
Last but not least, clarify yourself first what is what you want to measure and what the real code will look like (and if it can even be reproduced) ie are you using setZero for some reason like that? What is the context of it? Is it slowing down the surrounding code?

**Comment by imangry** [comment] 2023-11-09 03:31
I am a developer of Thrift's RPC framework, and the [THeader protocol](https://github.com/apache/thrift/blob/master/doc/specs/HeaderFormat.md) needs to add 0-4 bytes of padding. I used the writeZero method to add padding. But in the production environment, the flame graph shows that the padding accounts for a significant width. Compared with the serialization of the actual fields, the padding should be very small. This phenomenon aroused my suspicion, so I did the above JMH test.

**Comment by franz1981** [comment] 2023-11-09 04:49
Thanks for the clarification, if you have a proper prod code, I stil believe is not what you would exactly would do for maximum speed
eg
writeManual is writing 8 zeros, while writeUnsafe is writing 1 + 2 + 3 + ... + 8 = n * (n + 1)/2  = 72 bytes according to https://netty.io/4.1/api/io/netty/buffer/ByteBuf.html#writeZero-int- API, where the parameter length determine how many zeros are placed.
This should be fixed by replacing the loop with a single writeZero call.

Assuming the actual code in Thrift is instead using the buffer API correctly, there are still inherent inefficiencies of Unsafe's setMemory implementation for very small lengths (smaller than the word's size and more, given that the underlying JDK impl could rely on the platform one, which in turn has some bootstrap cost, if vectorized, see https://github.com/real-logic/agrona/blob/5acc4a8e0cbc3a740ac15b0421b900a03bb6565a/agrona/src/main/java/org/agrona/AbstractMutableDirectBuffer.java#L77 and https://github.com/real-logic/agrona/blob/5acc4a8e0cbc3a740ac15b0421b900a03bb6565a/agrona-benchmarks/src/main/java/org/agrona/concurrent/SetMemoryBenchmark.java#L38)  AND that writeXYZ has to move forward writers index each time too, which means performing one tiny more operation for each tiny operations, doubling the work (I suggest instead, for Thrift to use the setXYZ variants in Netty, and just move the writer index manually at the end, while done).
I can both check to open a JDK issue and send a Netty change to do something similar to what Agrona does, but given that there things are usually done using "magic" thresholds which not always hold for every possible architecture and operating system, I strongly encourage you to consider my point related writer indexes AND try in your specific case yourself (replacing the variable single zero write with a mix of setByte/setShort/setInt based on length of the padding)

**Comment by franz1981** [comment] 2023-11-09 14:33
But before sending a PR, to improve it: @normanmaurer wdyt? if you are against adding paths to improve it, which is, IMO (yet to measure), with 2 different mindsets:
- *option 1*: trying to do better then the JDK (ie by making memset to happen more often) AND tiny writes to avoid the thread-state barriers due to `Unsafe::setMemory0`
- *option 2*: just makes tiny writes to work better (adding a special code path for <= 8 bytes - or slightly more)

lmk

**Comment by normanmaurer** [comment] 2023-11-09 14:55
@franz1981 I think option 2 might be something we could consider.

**Comment by franz1981** [comment] 2023-11-09 15:28
Sending a PR now, @imangry can give it a shot

**Closed** 2023-11-13 08:13 UTC
