### ISSUE TITLE
AsciiString.of("/foo).lastIndexOf("/") returns -1

### ISSUE THREAD

**Issue by mtuchkov** [netty/netty#9225] opened 2019-06-06 01:03 UTC
### Expected behavior
AsciiString.of("/foo").lastIndexOf("/") = 0

### Actual behavior
AsciiString.of("/foo").lastIndexOf("/") = -1

### Netty version
4.1.36.Final

### JVM version (e.g. `java -version`)
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

### OS version (e.g. `uname -a`)
4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by qeesung** [comment] 2019-06-06 01:22
Duplicate of #9099

**Comment by njhill** [comment] 2019-06-06 01:25
@mtuchkov @qeesung is right, already fixed in 4.1.37.Final (yet to be released).

**Closed by njhill** 2019-06-06 01:25 UTC
