### ISSUE TITLE
NioEvengLoopGroup constructor throws NoSuchMethodException on Android

### ISSUE THREAD

**Issue by opendof** [netty/netty#7771] opened 2018-03-06 21:51 UTC
NioEventLoopGroup constructor fails fatally throwing NoSuchMethodException:

this.eventLoopGroup = new NioEventLoopGroup(0, factory);

sun.misc.Unsafe.copyMemory: unavailable
java.lang.NoSuchMethodException: copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]
 at java.lang.Class.getMethod(Class.java:624)
 at java.lang.Class.getDeclaredMethod(Class.java:586)
 at io.netty.util.internal.PlatformDependent0$2.run(PlatformDependent0.java:132)
 at java.security.AccessController.doPrivileged(AccessController.java:45)
 at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:128)
 at io.netty.util.internal.PlatformDependent0.isAndroid(PlatformDependent0.java:785)
 at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
 at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
 at io.netty.util.internal.PlatformDependent.newMpscQueue(PlatformDependent.java:874)
 at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:259)
 at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
 at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
 at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
 at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
 at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
 at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
 at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
 at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
 at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
 at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
 at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
 at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)

Netty version 4.1.22

Android 6.0 (and tested on 8.0)

**Comment by normanmaurer** [comment] 2018-03-06 21:55
@carl-mastrangelo can you check... seems like your android detection code changes does not work on (all) android versions ?

**Comment by normanmaurer** [comment] 2018-03-06 21:57
@opendof as a workaround you should be able to force disabling of android:

`-Dio.netty.noUnsafe=true`

**Comment by carl-mastrangelo** [comment] 2018-03-06 22:23
@opendof can you print out `System.getProperty("java.vm.name")`   ?

**Comment by opendof** [comment] 2018-03-06 22:26
java.vm.name: Dalvik

**Comment by carl-mastrangelo** [comment] 2018-03-06 22:30
That means that somehow you are not able to rad this property on classload.   

Let me think about this.    It should always be set.

**Comment by carl-mastrangelo** [comment] 2018-03-07 02:27
I didn't notice at first glance, but the problem is:

```at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)```

In the process of checked if something is android, it tries to init the class.  That said, It looks like you just noticed the log statement, not an exception.   The code should still work despite being noisy right?

**Comment by opendof** [comment] 2018-03-07 17:20
Through the debug log, I can see that PlatformDependent0.isAndorid0() is returning true

**Comment by opendof** [comment] 2018-03-07 17:46
I believe you are correct. The could should still work despite being noisy (my code isn't working, but this doesn't appear to be the cause).

**Comment by carl-mastrangelo** [comment] 2018-03-07 17:49
@opendof In Android 7.0 and higher, the JDK used is the same one from OpenJDK, so the Unsafe class would actually work.   It would be nice if later android versions could use it.

**Comment by normanmaurer** [comment] 2018-03-14 15:05
@carl-mastrangelo let me know once you have an idea how to "fix it".

**Comment by carl-mastrangelo** [comment] 2018-03-14 20:41
If I am not mistaken, this is only printed out if debug logging is turned on.   I think the solution is to turn off debug logging.

**Comment by normanmaurer** [comment] 2018-03-19 08:23
@opendof ^^ thoughts ?

**Comment by normanmaurer** [comment] 2018-05-06 18:15
Let me close this as I think its just logging as @carl-mastrangelo pointed out. Please re-open if you think there is anything we need to do tho.

**Closed by normanmaurer** 2018-05-06 18:15 UTC
