### ISSUE TITLE
Consider using code-generation for header-map implementations

### ISSUE THREAD

**Issue by trustin** [netty/netty#4018] opened 2015-07-22 10:54 UTC
As shown in #3962 and #3681, our attempts to generalize textual multi-value map have caused troubles such as memory consumption and performance regression.

The thing is, the `*Headers` implementations don't really need to share the type hierarchy nor have to be compatible with each other. i.e. `StompHeaders` is not an `HttpHeaders`. `HttpHeaders` is not an `Http2Headers`. (Well, we sometimes convert `HttpHeaders` to `Http2Headers` and vice versa, but it can be done without shared supertype.)

Then, why are we putting so much effort on designing proper type hierarchy or keeping the current type hierarchy?  Why don't we just write some template and generate highly optimized `*Headers` implementation and a few generic implementations (something like `DefaultTextHeaders` today)?  That should let JVM optimize the header access a lot better than what we have today.

Opinions?

**Comment by buchgr** [comment] 2015-07-22 17:46
My understanding is that the performance regression is not inherent to generalizing the map implementation - that is to my knowledge the class hierarchy doesn't introduce noticeable overhead. The problem is that the implementation as is merged right now in 4.1 and master is just not good. However, I also think that the the whole headers are still very much over engineered and overly abstract and that  there is some cleaning up to do in the class hierarchy (see #3655) i.e. I think we should get rid of `DefaultConvertibleHeaders`, `DefaultTextHeaders` and `DefaultBinaryHeaders` i.e `DefaultHttpHeaders` , `DefaultStompHeaders`, etc. should just directly extend `DefaultHeaders`.

If after those changes we can measure an overhead then we could turn to code generation. However, I think we should only do that if really necessary.

**Comment by trustin** [comment] 2015-07-22 22:57
@buchgr No worries. This is just an exploratory discussion issue to understand what people think about it. We will have to try this option if we can't fix #3962 with our current design.

I'm very fine with your PR. My (and @normanmaurer's) concern is to make sure we get rid of the regressions in #3962. If we can achieve that without losing all the nice stuff, then it would be amazing. So, let's get your PR reviewed and wait for @normanmaurer's perf numbers on your PR.

**Comment by buchgr** [comment] 2015-07-22 23:53
@trustin this are the perf numbers with my PR https://github.com/netty/netty/issues/3962#issuecomment-120058035 . It's ~15% slower than 4.0. Looking at the profiler snapshot, shows the `TreeMap` to account for most of the time spend in the headers. So I think moving forward, the question will be whether we can just plug in the 4.0 implementation as a `Map` into my PR and get the same performance or if maybe wrapping everything in a `Map` introduces too much overhead. Then we could just replace `DefaultHeaders` with the 4.0 implementation and see if that works out.

**Comment by Scottmitch** [comment] 2015-07-25 02:55
@trustin @buchgr - See https://github.com/netty/netty/issues/3962#issuecomment-124791458 as it relates to this discussion.  Not to say we couldn't get better performance with a code-generation approach but I also don't think the performance problems are caused by the shared interface / implementation.  Lets re-evaluate this issue if other attempts fail to rectify performance....or if after that we want to attempt to get even greater performance :)

**Comment by Scottmitch** [comment] 2015-08-21 17:51
@trustin @buchgr - I think the performance issue has been addressed. Is there still interest in this, or should we close it?

/cc @normanmaurer

**Comment by normanmaurer** [comment] 2015-08-21 17:54
I think we can close

**Comment by buchgr** [comment] 2015-08-21 18:02
no interest into looking into this :smile: . I vote for closing ;-).

**Comment by Scottmitch** [comment] 2015-08-21 18:03
Me too. that seems like a majority. Feel free to re-open if you want to take this on @trustin :)

**Closed by Scottmitch** 2015-08-21 18:03 UTC
Labels: discussion

**Comment by trustin** [comment] 2015-08-22 01:01
Same here. Great that it turned ou we didn't have to go this route!
