### ISSUE TITLE
HttpPostRequestDecoder$ErrorDataDecoderException  Caused by: java.io.IOException: Unable to create temporary file

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#10328] opened 2020-05-29 06:48 UTC
### Actual behavior
new DefaultHttpDataFactory(true);

When the mode is true, it will write to the disk, and when the data is "requetTpl":\"id=2c928bb062c41aad", it will report an error. At present, it seems to be an internal string interception problem. Hope the official website can fix it

http raw request data   Test Data "requetTpl":\"id=2c928bb062c41aad"

### Minimal yet complete reproducer code (or URL to code)
```
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.io.IOException: Unable to create temporary file, C:\Users\hxm\App
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:615)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:366)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:295)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:47)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
	at top.hserver.core.server.handlers.DispatcherHandler.buildWebContext(DispatcherHandler.java:70)
	at top.hserver.core.server.handlers.ActionHandler.lambda$channelRead0$0(ActionHandler.java:22)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to create temporary file, C:\Users\hxm\AppData\Local\Temp\Attr_7403181982031682126_{  "pid": "CDAA2BD5-8BED-478
	at java.io.File$TempDirectory.generateFile(File.java:1921)
	at java.io.File.createTempFile(File.java:2010)
	at java.io.File.createTempFile(File.java:2070)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:162)
	at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:133)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.setFinalBuffer(HttpPostStandardRequestDecoder.java:624)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:549)
	... 15 more

### Netty version
     4.1.49.Final
### JVM version (e.g. `java -version`)
   java8
### OS version (e.g. `uname -a`)
   Win10

**Comment by zhenjunMa** [comment] 2020-05-30 23:37
how to reproduce this exception? i can't get....

**Comment by heixiaoma** [comment] 2020-05-31 02:07
private static final HttpDataFactory HTTP_DATA_FACTORY = new DefaultHttpDataFactory(true); 
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(HTTP_DATA_FACTORY, req);

HTTP raw post request mode  Test Data "requetTpl":"id=2c928bb062c41aad"

**Comment by fredericBregier** [comment] 2020-05-31 09:35
Maybe a dumb question: is your POST a form value format?

      Content-Disposition: form-data; name="{NOM}"[CRLF]
     [CRLF]
     {VALEUR}

Because if not, HttpPostxxxRequestDecoder is not intend for something else than standard form mode... ?

**Comment by heixiaoma** [comment] 2020-05-31 10:28
Not form key value mode

**Comment by heixiaoma** [comment] 2020-05-31 15:34
Error is caused by temporary file name interception during disk caching

**Comment by heixiaoma** [comment] 2020-05-31 15:36
C:\Users\hxm\AppData\Local\Temp\Attr_7403181982031682126_{  "pid": "CDAA2BD5-8BED-478

It can be found in the log that there is a problem in the name truncation of this temporary file

**Comment by fredericBregier** [comment] 2020-06-01 14:29
As I wrote, HttpPostRequestDecoder is intended to decode form post, not regular content out of content-disposition form.
So it is quite normal that it messed up the name since it cannot find it...
You probably want to write some special handling for that, directly using ByteBuf writing to a file...

**Comment by normanmaurer** [comment] 2020-06-08 08:31
@fredericBregier so can we close this ?

**Closed** 2020-06-08 08:33 UTC
