### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred with Minecraft

### ISSUE THREAD

**Issue by Computero** [netty/netty#7442] opened 2017-11-26 20:30 UTC
### Expected behavior
No errors or warnings

### Actual behavior
Warnings when running Minecraft Server with Oracle Java 9

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/minecraft/minecraft_server.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Steps to reproduce
Start minecraft_server.1.12.2.jar

### Netty version
No sure how to check version

### JVM version (e.g. `java -version`)
```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

### OS version (e.g. `uname -a`)
```
Linux minecraft 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Not sure what to do to fix this, I've seen notes on how to hide the errors but I'd prefer to get it resolved instead of masking. Is this a Minecraft thing that they need to fix to not use old classes in their software or is there something I can do on my end to correct it?

If anything else is needed, please feel free to let me know.

**Comment by Computero** [comment] 2017-11-26 20:35
Removed Minimal yet complete reproducer code (or URL to code) line

**Comment by coelho** [comment] 2017-11-26 22:41
Minecraft is made for Java 8 and it uses an old version of Netty IIRC.

**Comment by normanmaurer** [comment] 2017-11-27 08:48
@Computero this is a duplicate of https://github.com/netty/netty/issues/7254...

That said it will still just work. Its a warning

**Closed by normanmaurer** 2017-11-27 08:48 UTC
