### ISSUE TITLE
Throwing an exception in case glibc is missing instead of segfaulting the JVM

### ISSUE THREAD

**Issue by jonatan-ivanov** [netty/netty#11701] opened 2021-09-22 02:15 UTC
It seems Netty's native support depends on glibc (btw is this documented?).
When glibc is missing (for example using vanilla Alpine), the JVM could end up with a crash (`SIGSEGV`), see details in this issue: https://github.com/micrometer-metrics/micrometer/issues/2776

It also seems that `Epoll.isAvailable()` returns `true` even if glibc is missing.

### Expected behavior
Throwing an exception

### Actual behavior
JVM crash

### Steps to reproduce
Using Netty native with an environment that does not have glibc, e.g.: vanilla Alpine

### Minimal yet complete reproducer code (or URL to code)
This seems to be a known issue, please let me know if you really need a reproducer.

### Netty version
`4.1.68` (latest)

### JVM version (e.g. `java -version`)
Latest 11:
```bash
 ❯ docker run --rm 'azul/zulu-openjdk-alpine:11-jre' 'sh' '-c' 'java --version'
openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)
```
Or also latest 17:
```bash
 ❯ docker run --rm 'bellsoft/liberica-openjdk-alpine-musl:17' 'sh' '-c' 'java --version'
openjdk 17 2021-09-14 LTS
OpenJDK Runtime Environment (build 17+35-LTS)
OpenJDK 64-Bit Server VM (build 17+35-LTS, mixed mode)
```
I assume this is an issue in every JRE that is currently supported.

### OS version (e.g. `uname -a`)
Both images above have the same output:
```bash
 ❯ docker run --rm 'azul/zulu-openjdk-alpine:11-jre' 'sh' '-c' 'uname -a'
Linux 1ee8d1090f14 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 Linux
```
I assume this is an issue in every OS where glibc is missing.

**Comment by chrisvest** [comment] 2021-09-23 12:03
The binary compatibility baseline for our native code is the GLIBC version that's used on CentOS 6. The work-around is to use the Nio transport.

It's not clear from the error reports how this is really showing up. If it's an ABI problem, then I'm not sure what we can do to mitigate it. If we are calling glibc specific functions, then I wonder if we can somehow check what libc we are using at runtime.

**Comment by jonatan-ivanov** [comment] 2021-09-23 18:18
>It's not clear from the error reports how this is really showing up.
I'm not sure what your question is. The error happens when Netty native is used without having glibc.

>If it's an ABI problem...
I don't think it is an ABI problem since glibc is missing in Alpine, there is nothing to be compatible with (and based on [this comment ](https://github.com/netty/netty/issues/6841#issuecomment-307716433), other libc implementations are out of question).

I think checking if glibc is available or not and/or fixing `Epoll.isAvailable()` would fix the issue (it seems it returns true even if glibc is missing).

**Comment by jonatan-ivanov** [comment] 2021-09-24 00:14
I put together a little test for this: https://github.com/jonatan-ivanov/netty-gh-11701

I called `Epoll.isAvailable()` and `Epoll.ensureAvailability()` on different distros to see if they return false/fail in case glibc is missing. It seems `isAvailable` does not return false and `ensureAvailability` does not fail even if glibc is missing.

Image | `isAvailable` | `ensureAvailability` | Comment
------ | ------------------- |  --------------------------- | -------------
bellsoft_liberica-openjre-debian:17 | `true` | `OK` | works
bellsoft_liberica-openjre-alpine:17  | `true` | `OK` | works since it contains glibc
**bellsoft_liberica-openjre-alpine-musl:17**  | `true` | `OK` | **does not work as expected**
azul_zulu-openjdk:17 | `true` | `OK` | works as expected
**azul_zulu-openjdk-alpine:17-jre**  | `true` | `OK` | **does not work as expected**

**Comment by chrisvest** [comment] 2021-09-24 11:37
There's no way to detect the libc vendor from within a process, as far as I can see. And calling out to `lld`, or something like that, is quite awkward and can be a security liability. I think the best we can do for the moment is to document that only the Nio transport is supported on musl.

What do you think, @normanmaurer ?

**Comment by normanmaurer** [comment] 2021-09-24 11:59
I agree with @chrisvest here

**Comment by jonatan-ivanov** [comment] 2021-09-29 04:49
I'm not very familiar with this domain but do you think is it at least possible to throw an exception instead of crashing a JVM if such a thing occur?

**Comment by chrisvest** [comment] 2021-09-29 07:23
@jonatan-ivanov That's only at compile time. At runtime you can feature detect by inspecting linked symbols, except you cant do that without calling into libc which in this case would cause a crash. Alternatively we shell out to a program to inspect libc, but that is also bad for multiple reasons, and we don't want to do that.

**Comment by chrisvest** [comment] 2021-09-29 10:17
I have updated the documentation on the native transports to note that musl is not officially supported: https://github.com/netty/netty/wiki/Native-transports

I think that's the best we can do for now.

**Comment by Hello71** [comment] 2021-09-29 13:15
musl generally tries to support glibc-linked binaries invoking POSIX and some BSD extensions. errors related to GNU-specific extensions (and glibc header bastardizations) should be caught at load time, as in #6841 "__strndup: symbol not found". that particular issue can be fixed by installing gcompat package in alpine linux. segfaults are, as you say, caused by some ABI incompatibility.

i briefly glanced through netty c code and found some suspicious items: https://github.com/netty/netty/blob/6b3ec62e6e4e19a85304aecd8cb5331a3fcc70be/transport-native-unix-common/src/main/c/netty_unix_errors.c#L41 is suspicious: application code should never check feature test macros, because it should be defining it themselves. https://github.com/netty/netty/blob/51ebcbd9aba7eac854716e45f07765744f8dcdaf/transport-native-epoll/src/main/c/netty_epoll_native.c#L140 is suspicious: sysctl values should always be accessed using `read`/`write`, never stdio. some sysctls will not be read correctly if using stdio. neither of these should cause segfault at run time though.

**Comment by chrisvest** [comment] 2021-09-29 19:13
@Hello71 The netty_unit_errors code is because we wish to use a thread-safe strerror variant, which is not immediately portable. (I'm not familiar with the other one you point out)
If you know of a way to improve it, we'd love to review a PR!

**Comment by chrisvest** [comment] 2021-10-07 09:49
Fix reverted because it negatively impacts musl-based systems that also use the glibc compatibility layer.

**Comment by normanmaurer** [comment] 2021-10-11 08:00
reopened

**Comment by chrisvest** [comment] 2021-10-12 12:25
@Hello71 The JVM itself might rely on signals and tie them to internal semantics, i.e. rare NullPointerExceptions sometimes rely on segfaults to optimise a non-null fast path. So I wouldn't feel very confident trying to trap signals in JNI library code.

**Comment by normanmaurer** [comment] 2022-04-19 12:38
I think this would be fixed by https://github.com/netty/netty/pull/12272 ...

**Closed** 2022-04-20 20:24 UTC
