### ISSUE TITLE
Sporadic exception on DnsNameResolver

### ISSUE THREAD

**Issue by lechiefe** [netty/netty#9193] opened 2019-05-29 03:19 UTC
### Periodically throws the following exception: 
```
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(512) + length(2) exceeds writerIndex(512): PooledUnsafeDirectByteBuf(ridx: 512, widx: 512, cap: 4096)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(512) + length(2) exceeds writerIndex(512): PooledUnsafeDirectByteBuf(ridx: 512, widx: 512, cap: 4096)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:742) ~[netty-buffer-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.buffer.AbstractByteBuf.readUnsignedShort(AbstractByteBuf.java:758) ~[netty-buffer-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:61) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decodeRecords(DatagramDnsResponseDecoder.java:110) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:68) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:33) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	... 16 common frames omitted
```
### Minimal yet complete reproducer code (or URL to code)
```
public class DnsClient{

	private static EventLoopGroup eventLoop = new NioEventLoopGroup(1);
	private CompletableFuture<String> completableFuture;
	private DnsNameResolver resolver;
	private static DefaultDnsCache cache = new DefaultDnsCache();
	public DnsClient() {
//		eventLoop = new NioEventLoopGroup();
	}

	public CompletableFuture<String> call() throws Exception {
		completableFuture = new CompletableFuture<String>();
		try {
			resolver = new DnsNameResolverBuilder(eventLoop.next()).queryTimeoutMillis(10000).resolveCache(cache).maxQueriesPerResolve(5).channelType(NioDatagramChannel.class).build();
			DefaultDnsQuestion defaultDnsQuestion = new DefaultDnsQuestion("gmail.com", DnsRecordType.MX);
			Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> future = resolver.query(defaultDnsQuestion);
//			AddressEnvelopeListener listener = new AddressEnvelopeListener();
			future.addListener(new GenericFutureListener<Future<AddressedEnvelope<DnsResponse, InetSocketAddress>>>() {

				@Override
				public void operationComplete(Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> future)
						throws Exception {
					handleOperationComplete(future);
				}
			});
		} catch (Exception e) {
			System.out.println(e);
		}
		return completableFuture;
	}

	protected synchronized void handleOperationComplete(
			Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> future) {
		System.out.println("operation complete");
		List<MxDnsRecord> dnsRecords;
		if (future.isSuccess()) {
			try {
				dnsRecords = new ArrayList<>();
				AddressedEnvelope<DnsResponse, InetSocketAddress> answer = future.get();
				
				DnsResponse content = answer.content();
				final int count = content.count(DnsSection.ANSWER);
				final List<MxDnsRecord> mxList = new ArrayList(count);
				for (int i = 0; i < count; i++) {
					final DnsRecord record = content.recordAt(DnsSection.ANSWER, i);
					if (record.type() == DnsRecordType.MX) {
						mxList.add(new MxDnsRecord(record));
					}
				}
				answer.release();
				sortRecordsByPriority(mxList);
				StringBuilder stringBuilder = new StringBuilder();
				mxList.forEach(m -> stringBuilder.append(m.toString()));
				completableFuture.complete(stringBuilder.toString());
				
			} catch (InterruptedException e) {
				e.printStackTrace();
			} catch (ExecutionException e) {
				e.printStackTrace();
			}
		}
		else {
			try {
				AddressedEnvelope<DnsResponse, InetSocketAddress> answer = future.get();
			} catch (InterruptedException | ExecutionException e1) {
				e1.printStackTrace();
			}
		}
		resolver.close();
	}

	private List<MxDnsRecord> sortRecordsByPriority(List<MxDnsRecord> dnsRecords) {
		if (dnsRecords != null) {
			Collections.sort(dnsRecords, new Comparator<MxDnsRecord>() {
				@Override
				public int compare(MxDnsRecord o1, MxDnsRecord o2) {
					return ((Integer) o1.getPriority()).compareTo(o2.getPriority());
				}
			});
		}
		return dnsRecords;
	}
}
```

### And here is the MxDnsRecordClass:
```
public class MxDnsRecord implements DnsRecord {

	private String name;
	private DnsRecordType recordType;
	private int dnsClass;
	private long timeToLive;
	private int priority;
	private String inetHost;

	public MxDnsRecord(DnsRecord dnsRecord) {
		this.name = dnsRecord.name();
		this.recordType = dnsRecord.type();
		this.dnsClass = dnsRecord.dnsClass();
		this.timeToLive = dnsRecord.timeToLive();
		ByteBuf recordContent = ((ByteBufHolder) dnsRecord).content();
		this.priority = recordContent.readUnsignedShort();
		this.inetHost = DefaultDnsRecordDecoder.decodeName(recordContent);
	}

	@Override
	public String name() {
		return name;
	}

	@Override
	public DnsRecordType type() {
		return recordType;
	}

	@Override
	public int dnsClass() {
		return dnsClass;
	}

	@Override
	public long timeToLive() {
		return timeToLive;
	}

	public int getPriority() {
		return priority;
	}

	public String getInetHost() {
		return inetHost;
	}

	public String toString() {
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append(StringUtil.NEWLINE);
		stringBuilder.append('\t');
		stringBuilder.append(getName());
		stringBuilder.append(' ');
		stringBuilder.append(getRecordType().name());
		stringBuilder.append(' ');
		stringBuilder.append(getPriority());
		stringBuilder.append(' ');
		stringBuilder.append(getInetHost());
		return inetHost;
	}
}
```
### Netty version
4.1.36
### JVM version (e.g. `java -version`)
11
### OS version (e.g. `uname -a`)
Windows 10

**Comment by lechiefe** [comment] 2019-05-29 04:45
I was able to reproduce this with simpler code as well: 
```
EventLoopGroup eventLoop = new NioEventLoopGroup();
			DnsNameResolver resolver = null;
			DnsResponse content = null;
			AddressedEnvelope<DnsResponse, InetSocketAddress> answer = null;
			String result = "nothing to show";
			try {
				resolver = new DnsNameResolverBuilder(eventLoop.next()).channelType(NioDatagramChannel.class).build();
				DefaultDnsQuestion defaultDnsQuestion = new DefaultDnsQuestion("gmail.com", DnsRecordType.MX);
				Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> future = resolver.query(defaultDnsQuestion);

				answer = future.syncUninterruptibly().getNow();
				content = answer.content();
	            final int count = content.count(DnsSection.ANSWER);
	            final List<DnsRecord> mxList = new ArrayList(count);
	            for (int i = 0; i < count; i ++) {
                    final DnsRecord r = content.recordAt(DnsSection.ANSWER, i);
                    if (r.type() == DnsRecordType.MX) {
                        mxList.add(r);
                    }
                }
	            StringBuilder buf = new StringBuilder();
                for (DnsRecord r: mxList) {
                    ByteBuf recordContent = ((ByteBufHolder) r).content();

                    buf.append(StringUtil.NEWLINE);
                    buf.append('\t');
                    buf.append(r.name());
                    buf.append(' ');
                    buf.append(r.type().name());
                    buf.append(' ');
                    buf.append(recordContent.readUnsignedShort());
                    buf.append(' ');
                    buf.append(DefaultDnsRecordDecoder.decodeName(recordContent));
                }
                System.out.println(buf.toString());
	            result = buf.toString();
			}
			catch (Exception e) {
				System.out.println(e);
			}
			finally {
				if (resolver != null) {
					resolver.close();
					answer.release();
				}
				eventLoop.shutdownGracefully();
			}
			System.out.println(result);
			return result;
```

**Comment by normanmaurer** [comment] 2019-05-30 05:45
Will have a look over the next days.

**Comment by lechiefe** [comment] 2019-05-31 05:06
I wanted to give a bit more information. This has been very difficult to debug, since it is completely unpredictable; however, for what its worth, I have not been able to replicate it since setting the following 2 settings: 
```
.optResourceEnabled(false)
.resolvedAddressTypes(ResolvedAddressTypes.IPV4_PREFERRED)
```
This does not mean that it is decisively fixed yet, since the issue does not manifest itself all the time, but it is a good sign.

**Comment by qeesung** [comment] 2019-05-31 16:45
@lechiefe I tried many times locally, but I couldn't reproduce the problem.

**Comment by lechiefe** [comment] 2019-06-01 00:58
> @lechiefe I tried many times locally, but I couldn't reproduce the problem.

I believe it, that is why I pointed out that the issue is sporadic and is hard to reproduce. Because of its nature, I believe that it is cause by a certain response from a remote dns server. Like I mentioned above, it seems to go away if I apply those settings, the first one specifically mentions that setting it to true might cause some dns providers to send a broken response. If that is correct, and that is the case(I cannot decisively confirm that) then perhaps there should be better handling of such an error, for example, if the retry setting was set on the resolver, perhaps it could retry with the setting set to false. As of right now its just a mysterious, cryptic error.

**Comment by qeesung** [comment] 2019-06-01 05:22
Would you please tell me what DNS server address you are using? I tried `@8.8.8.8` and `@ns1.google.com`, `@114.114.114.114`, I can't reproduce this problem.  By the way, the code I tested is here : https://gist.github.com/qeesung/7b5d5a42e7d8b97597d2baf55a83b43b

**Comment by normanmaurer** [comment] 2019-06-03 09:35
@lechiefe I suspect your problem is that you use use the "opt record" which tells the remote peer that you support datagram packets up to 4096 bytes (by default) and you sometimes get truncated datagrams. You can try to use a different `maxPayloadSize` to set a smaller limit if you encounter problems.

**Comment by lechiefe** [comment] 2019-06-06 17:34
@normanmaurer My apologies for the delay, it may be the case, you obviously understand the infrastructure better than myself. I also suspected that that was the case, however while stepping though the code, on a rare occasion that I was able to catch an erroneous request in execution, the isTruncated flag was not set. Is my understanding correct that the current release does not support truncated packets?

**Comment by lechiefe** [comment] 2019-06-06 17:35
@qeesung Yes, I can, I will have some time to look at the issue again this weekend, I will update this when I have the info. Thank you for looking into this, you guys do amazing work!

**Comment by normanmaurer** [comment] 2019-06-07 23:53
@lechiefe no it will have no truncated flag set as you told it via the OPT record that you can read 4096 bytes. It will set the truncated flag if the response would be bigger then 4096 bytes in this case

**Comment by normanmaurer** [comment] 2019-08-16 07:41
This will be fixed by https://github.com/netty/netty/pull/9468

**Closed** 2019-08-17 07:59 UTC
